// Package regional implements the server-to-server API between the auth plane and
// the regional data planes: provisioning a user's profile in their chosen region at
// signup, and deleting the identity record when an account is erased.
//
// Calls are authenticated with Google-signed ID tokens (the caller's Cloud Run
// service account), verified against an allowlist of service account emails.
package regional

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/rumi/rumi-be/config"
	"github.com/rumi/rumi-be/database"
	"github.com/rumi/rumi-be/internal/models"
	"golang.org/x/oauth2"
	"google.golang.org/api/idtoken"
	"gorm.io/gorm"
)

// UserProvision is the profile payload the auth plane sends to a data plane when a
// user signs up with residency in that region. The ID is generated by the auth plane
// so identity and profile share the same key.
type UserProvision struct {
	ID                           string     `json:"id"`
	Email                        *string    `json:"email,omitempty"`
	PhoneNumber                  *string    `json:"phoneNumber,omitempty"`
	Name                         *string    `json:"name,omitempty"`
	DateOfBirth                  *time.Time `json:"dateOfBirth,omitempty"`
	Gender                       *string    `json:"gender,omitempty"`
	Country                      *string    `json:"country,omitempty"`
	Region                       *string    `json:"region,omitempty"`
	PreferredLanguage            *string    `json:"preferredLanguage,omitempty"`
	DataRegion                   string     `json:"dataRegion"`
	IsActive                     bool       `json:"isActive"`
	TermsAndConditionsAcceptedAt *time.Time `json:"termsAndConditionsAcceptedAt,omitempty"`
	MarketingAcceptedAt          *time.Time `json:"marketingAcceptedAt,omitempty"`
	AIAcceptedAt                 *time.Time `json:"aiAcceptedAt,omitempty"`
}

// UserContactUpdate is the payload for updating user contact information across planes.
type UserContactUpdate struct {
	ID          string  `json:"id"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// Client makes authenticated calls to other planes.
type Client struct {
	httpClient *http.Client

	mu      sync.Mutex
	sources map[string]oauth2.TokenSource // audience → cached ID-token source
}

func NewClient() *Client {
	return &Client{
		httpClient: &http.Client{Timeout: 15 * time.Second},
		sources:    map[string]oauth2.TokenSource{},
	}
}

// ProvisionUser creates the user's profile on the data plane at baseURL.
func (c *Client) ProvisionUser(ctx context.Context, baseURL string, p UserProvision) error {
	body, err := json.Marshal(p)
	if err != nil {
		return err
	}
	return c.do(ctx, http.MethodPost, baseURL, "/internal/users", bytes.NewReader(body))
}

// ProvisionInRegion creates the profile row in the user's home region: directly in
// the local database when the region is served by this deployment (the auth plane
// shares the EU data plane, and local development has no remote planes), otherwise
// via the internal API of the remote data plane. Idempotent on both paths, so a
// failed activation can simply be retried.
func (c *Client) ProvisionInRegion(ctx context.Context, dataRegion string, p UserProvision) error {
	if dataRegion == "eu" || (config.AppConfig.DataPlaneURL(dataRegion) == "" && config.AppConfig.Environment == "development") {
		return CreateLocalProfile(p)
	}
	return c.ProvisionUser(ctx, config.AppConfig.DataPlaneURL(dataRegion), p)
}

// UpdateUserContact sends a request to the data plane to update the user contact information.
func (c *Client) UpdateUserContact(ctx context.Context, baseURL string, p UserContactUpdate) error {
	body, err := json.Marshal(p)
	if err != nil {
		return err
	}
	return c.do(ctx, http.MethodPut, baseURL, "/internal/users/"+p.ID+"/contact", bytes.NewReader(body))
}

// UpdateContact coordinates updating the contact information (Email/PhoneNumber)
// in the user's data plane, whether local or remote.
func (c *Client) UpdateContact(ctx context.Context, dataRegion string, p UserContactUpdate) error {
	if dataRegion == "eu" || (config.AppConfig.DataPlaneURL(dataRegion) == "" && config.AppConfig.Environment == "development") {
		return UpdateLocalUserContact(p)
	}
	return c.UpdateUserContact(ctx, config.AppConfig.DataPlaneURL(dataRegion), p)
}

// CreateLocalProfile writes the regional profile row for a provision payload into
// this plane's own database. Idempotent: an already-provisioned ID is a no-op.
func CreateLocalProfile(p UserProvision) error {
	var existing models.User
	err := database.DB.Where("id = ?", p.ID).First(&existing).Error
	if err == nil {
		return nil
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}

	dataRegion := p.DataRegion
	user := models.User{
		ID:                           p.ID,
		Email:                        p.Email,
		PhoneNumber:                  p.PhoneNumber,
		Name:                         p.Name,
		DateOfBirth:                  p.DateOfBirth,
		Gender:                       p.Gender,
		Country:                      p.Country,
		Region:                       p.Region,
		PreferredLanguage:            p.PreferredLanguage,
		DataRegion:                   &dataRegion,
		IsActive:                     p.IsActive,
		TermsAndConditionsAcceptedAt: p.TermsAndConditionsAcceptedAt,
		MarketingAcceptedAt:          p.MarketingAcceptedAt,
		AIAcceptedAt:                 p.AIAcceptedAt,
	}
	return database.DB.Create(&user).Error
}

// UpdateLocalUserContact updates the regional profile row for a contact payload.
func UpdateLocalUserContact(p UserContactUpdate) error {
	updates := map[string]interface{}{}
	if p.Email != nil {
		updates["email"] = *p.Email
	}
	if p.PhoneNumber != nil {
		updates["phone_number"] = *p.PhoneNumber
	}

	if len(updates) == 0 {
		return nil
	}

	return database.DB.Model(&models.User{}).Where("id = ?", p.ID).Updates(updates).Error
}

// DeleteIdentity asks the auth plane at baseURL to erase a user's identity record.
// Data planes call this as the second step of account deletion.
func (c *Client) DeleteIdentity(ctx context.Context, baseURL, userID string) error {
	return c.do(ctx, http.MethodDelete, baseURL, "/internal/identities/"+userID, nil)
}

func (c *Client) do(ctx context.Context, method, baseURL, path string, body io.Reader) error {
	if baseURL == "" {
		return fmt.Errorf("no base URL configured for internal call to %s", path)
	}
	req, err := http.NewRequestWithContext(ctx, method, strings.TrimSuffix(baseURL, "/")+path, body)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	if token, err := c.identityToken(ctx, baseURL); err == nil {
		req.Header.Set("Authorization", "Bearer "+token)
	} else if config.AppConfig.Environment != "development" {
		return fmt.Errorf("mint service identity token: %w", err)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		msg, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return fmt.Errorf("internal call %s %s: status %d: %s", method, path, resp.StatusCode, msg)
	}
	return nil
}

// identityToken mints a Google-signed ID token for the target audience using this
// service's Cloud Run service account.
func (c *Client) identityToken(ctx context.Context, audience string) (string, error) {
	c.mu.Lock()
	src, ok := c.sources[audience]
	c.mu.Unlock()

	if !ok {
		var err error
		src, err = idtoken.NewTokenSource(ctx, audience)
		if err != nil {
			return "", err
		}
		c.mu.Lock()
		c.sources[audience] = src
		c.mu.Unlock()
	}

	token, err := src.Token()
	if err != nil {
		return "", err
	}
	return token.AccessToken, nil
}

// AuthMiddleware protects /internal endpoints: the caller must present a
// Google-signed ID token for this plane's own URL as audience, issued to a service
// account on the INTERNAL_ALLOWED_SAS allowlist. In development with no allowlist
// configured, calls are accepted to keep local single-process setups working.
func AuthMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cfg := config.AppConfig
		allowed := strings.Split(cfg.InternalAllowedSAs, ",")

		if cfg.InternalAllowedSAs == "" {
			if cfg.Environment == "development" {
				next.ServeHTTP(w, r)
				return
			}
			http.Error(w, `{"error": "internal API disabled"}`, http.StatusForbidden)
			return
		}

		authHeader := r.Header.Get("Authorization")
		if !strings.HasPrefix(authHeader, "Bearer ") {
			http.Error(w, `{"error": "missing service credentials"}`, http.StatusUnauthorized)
			return
		}

		audience := cfg.DataPlaneURL(cfg.RegionCode)
		payload, err := idtoken.Validate(r.Context(), strings.TrimPrefix(authHeader, "Bearer "), audience)
		if err != nil {
			http.Error(w, `{"error": "invalid service credentials"}`, http.StatusUnauthorized)
			return
		}

		email, _ := payload.Claims["email"].(string)
		emailVerified, _ := payload.Claims["email_verified"].(bool)
		for _, sa := range allowed {
			if emailVerified && email != "" && strings.EqualFold(strings.TrimSpace(sa), email) {
				next.ServeHTTP(w, r)
				return
			}
		}
		http.Error(w, `{"error": "caller not allowed"}`, http.StatusForbidden)
	})
}
