// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Aggregate dashboard over users and communication sessions
	// (GET /admin/dashboard)
	GetAdminDashboard(w http.ResponseWriter, r *http.Request, params GetAdminDashboardParams)
	// List business leads
	// (GET /admin/leads)
	AdminListLeads(w http.ResponseWriter, r *http.Request, params AdminListLeadsParams)
	// Update a lead
	// (PATCH /admin/leads/{id})
	AdminUpdateLead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Reset the calling admin's own account to a freshly created one (test only)
	// (POST /admin/reset-account)
	ResetAccount(w http.ResponseWriter, r *http.Request)
	// List communication sessions for admin
	// (GET /admin/sessions)
	GetAdminSessions(w http.ResponseWriter, r *http.Request, params GetAdminSessionsParams)
	// Set up database for testing using a persona
	// (POST /admin/test-setup)
	SetupTestData(w http.ResponseWriter, r *http.Request)
	// List users for admin
	// (GET /admin/users)
	GetAdminUsers(w http.ResponseWriter, r *http.Request, params GetAdminUsersParams)
	// Get user details for admin
	// (GET /admin/users/{id})
	GetAdminUsersId(w http.ResponseWriter, r *http.Request, id string)
	// Update user details or status (e.g. isActive) for admin
	// (PATCH /admin/users/{id})
	PatchAdminUsersId(w http.ResponseWriter, r *http.Request, id string)
	// Credit session minutes to a user (manual, until a payment provider exists)
	// (POST /admin/users/{id}/credits)
	PostAdminUsersIdCredits(w http.ResponseWriter, r *http.Request, id string)
	// Login via Apple identity token (Sign in with Apple, iOS only)
	// (POST /auth/apple)
	AppleLogin(w http.ResponseWriter, r *http.Request)
	// Login via Google IdToken
	// (POST /auth/google)
	GoogleLogin(w http.ResponseWriter, r *http.Request)
	// Login via verification code
	// (POST /auth/login/code)
	LoginWithCode(w http.ResponseWriter, r *http.Request)
	// Update email or phone number for current user
	// (PUT /auth/me/identifier)
	UpdateIdentifier(w http.ResponseWriter, r *http.Request)
	// Link a Sign in with Apple credential to the current account
	// (POST /auth/me/link/apple)
	LinkAppleAccount(w http.ResponseWriter, r *http.Request)
	// Refresh JWT Access Token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Register a new active user account
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Request verification code (email or SMS)
	// (POST /auth/verifications/request)
	RequestVerification(w http.ResponseWriter, r *http.Request)
	// Verify SSO Token (e.g. Google) and check user existence
	// (POST /auth/verifications/sso)
	VerifySSO(w http.ResponseWriter, r *http.Request)
	// Verify the requested code
	// (POST /auth/verifications/verify)
	VerifyCode(w http.ResponseWriter, r *http.Request)
	// Submit user feedback for a completed coaching session
	// (POST /chat/sessions/{sessionID}/feedback)
	SubmitSessionFeedback(w http.ResponseWriter, r *http.Request, sessionID string)
	// List the user's present and future commitments
	// (GET /commitments)
	GetCommitments(w http.ResponseWriter, r *http.Request, params GetCommitmentsParams)
	// Create a manual commitment
	// (POST /commitments)
	CreateCommitment(w http.ResponseWriter, r *http.Request)
	// Delete a commitment
	// (DELETE /commitments/{commitmentId})
	DeleteCommitment(w http.ResponseWriter, r *http.Request, commitmentId string)
	// Update a commitment (edit fields and/or toggle completion)
	// (PATCH /commitments/{commitmentId})
	UpdateCommitment(w http.ResponseWriter, r *http.Request, commitmentId string)
	// Get user Eisenhower Matrix exercises history
	// (GET /eisenhower-matrix)
	GetEisenhowerMatrix(w http.ResponseWriter, r *http.Request, params GetEisenhowerMatrixParams)
	// Get a specific Eisenhower Matrix exercise by ID
	// (GET /eisenhower-matrix/{id})
	GetEisenhowerMatrixId(w http.ResponseWriter, r *http.Request, id string)
	// Send feedback, a bug report, or a feature request
	// (POST /feedback)
	SubmitFeedback(w http.ResponseWriter, r *http.Request)
	// Get today's proposed growth session
	// (GET /journey)
	GetDailyJourney(w http.ResponseWriter, r *http.Request)
	// Submit a new lead
	// (POST /leads)
	PostLeads(w http.ResponseWriter, r *http.Request)
	// Delete current user (anonymize account)
	// (DELETE /me)
	DeleteCurrentUser(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Update current user
	// (PATCH /me)
	UpdateCurrentUser(w http.ResponseWriter, r *http.Request)
	// Delete user data, all of it or by category
	// (DELETE /me/data)
	DeleteCurrentUserData(w http.ResponseWriter, r *http.Request, params DeleteCurrentUserDataParams)
	// Export all personal data for GDPR compliance
	// (GET /me/data)
	ExportCurrentUserData(w http.ResponseWriter, r *http.Request)
	// Email the user a copy of their data
	// (POST /me/data/export)
	RequestUserDataExport(w http.ResponseWriter, r *http.Request)
	// Register a new device FCM token for push notifications
	// (POST /me/fcm-token)
	RegisterFCMToken(w http.ResponseWriter, r *http.Request)
	// List the user's integrations (WhatsApp, ...)
	// (GET /me/integrations)
	GetIntegrations(w http.ResponseWriter, r *http.Request)
	// Start linking the user's Telegram account (returns a one-time code and t.me link)
	// (POST /me/integrations/telegram/link)
	LinkTelegramIntegration(w http.ResponseWriter, r *http.Request)
	// Start linking the user's WhatsApp number (returns a one-time code and wa.me link)
	// (POST /me/integrations/whatsapp/link)
	LinkWhatsAppIntegration(w http.ResponseWriter, r *http.Request)
	// Unlink an integration
	// (DELETE /me/integrations/{integrationId})
	DeleteIntegration(w http.ResponseWriter, r *http.Request, integrationId string)
	// Get details of an integration by ID or provider name (e.g., whatsapp)
	// (GET /me/integrations/{integrationId})
	GetIntegration(w http.ResponseWriter, r *http.Request, integrationId string)
	// Update an integration (e.g. reply mode)
	// (PATCH /me/integrations/{integrationId})
	UpdateIntegration(w http.ResponseWriter, r *http.Request, integrationId string)
	// Get user profile and progress statistics
	// (GET /me/profile)
	GetMeProfile(w http.ResponseWriter, r *http.Request)
	// Get the user's balance transaction history (newest first)
	// (GET /me/transactions)
	GetTransactions(w http.ResponseWriter, r *http.Request, params GetTransactionsParams)
	// Get the user's usage history (billable sessions and companion messages, newest first)
	// (GET /me/usage)
	GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams)
	// Get user memories
	// (GET /memories)
	GetMemories(w http.ResponseWriter, r *http.Request, params GetMemoriesParams)
	// Delete a specific memory
	// (DELETE /memories/{memoryId})
	DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId string)
	// Get a random personal development quote
	// (GET /quotes/random)
	GetRandomQuote(w http.ResponseWriter, r *http.Request, params GetRandomQuoteParams)
	// Get user recommendations
	// (GET /recommendations)
	GetRecommendations(w http.ResponseWriter, r *http.Request, params GetRecommendationsParams)
	// List user's sessions
	// (GET /sessions)
	GetSessions(w http.ResponseWriter, r *http.Request, params GetSessionsParams)
	// Get user streak information
	// (GET /streak)
	GetStreak(w http.ResponseWriter, r *http.Request)
	// Get test setup documentation
	// (GET /test-data)
	GetTestDataDocs(w http.ResponseWriter, r *http.Request)
	// Get usage calendar statistics for a given month
	// (GET /usage-calendar)
	GetUsageCalendar(w http.ResponseWriter, r *http.Request, params GetUsageCalendarParams)
	// Join the waitlist
	// (POST /waitlist)
	JoinWaitlist(w http.ResponseWriter, r *http.Request)
	// RevenueCat purchase events webhook (credits the minutes balance)
	// (POST /webhooks/revenuecat)
	PostWebhooksRevenuecat(w http.ResponseWriter, r *http.Request)
	// Telegram incoming updates webhook
	// (POST /webhooks/telegram/{secret})
	PostWebhooksTelegramSecret(w http.ResponseWriter, r *http.Request, secret string)
	// Twilio incoming SMS webhook
	// (POST /webhooks/twilio/sms)
	PostWebhooksTwilioSms(w http.ResponseWriter, r *http.Request)
	// Meta WhatsApp verification webhook
	// (GET /webhooks/whatsapp)
	GetWebhooksWhatsapp(w http.ResponseWriter, r *http.Request)
	// Meta WhatsApp incoming messages webhook
	// (POST /webhooks/whatsapp)
	PostWebhooksWhatsapp(w http.ResponseWriter, r *http.Request)
	// Get user Wheel of Life exercises history
	// (GET /wheel-of-life)
	GetWheelOfLife(w http.ResponseWriter, r *http.Request, params GetWheelOfLifeParams)
	// Get a specific Wheel of Life exercise by ID
	// (GET /wheel-of-life/{id})
	GetWheelOfLifeId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Aggregate dashboard over users and communication sessions
// (GET /admin/dashboard)
func (_ Unimplemented) GetAdminDashboard(w http.ResponseWriter, r *http.Request, params GetAdminDashboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List business leads
// (GET /admin/leads)
func (_ Unimplemented) AdminListLeads(w http.ResponseWriter, r *http.Request, params AdminListLeadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a lead
// (PATCH /admin/leads/{id})
func (_ Unimplemented) AdminUpdateLead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset the calling admin's own account to a freshly created one (test only)
// (POST /admin/reset-account)
func (_ Unimplemented) ResetAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List communication sessions for admin
// (GET /admin/sessions)
func (_ Unimplemented) GetAdminSessions(w http.ResponseWriter, r *http.Request, params GetAdminSessionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set up database for testing using a persona
// (POST /admin/test-setup)
func (_ Unimplemented) SetupTestData(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users for admin
// (GET /admin/users)
func (_ Unimplemented) GetAdminUsers(w http.ResponseWriter, r *http.Request, params GetAdminUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user details for admin
// (GET /admin/users/{id})
func (_ Unimplemented) GetAdminUsersId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user details or status (e.g. isActive) for admin
// (PATCH /admin/users/{id})
func (_ Unimplemented) PatchAdminUsersId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Credit session minutes to a user (manual, until a payment provider exists)
// (POST /admin/users/{id}/credits)
func (_ Unimplemented) PostAdminUsersIdCredits(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login via Apple identity token (Sign in with Apple, iOS only)
// (POST /auth/apple)
func (_ Unimplemented) AppleLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login via Google IdToken
// (POST /auth/google)
func (_ Unimplemented) GoogleLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login via verification code
// (POST /auth/login/code)
func (_ Unimplemented) LoginWithCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update email or phone number for current user
// (PUT /auth/me/identifier)
func (_ Unimplemented) UpdateIdentifier(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Link a Sign in with Apple credential to the current account
// (POST /auth/me/link/apple)
func (_ Unimplemented) LinkAppleAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh JWT Access Token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new active user account
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request verification code (email or SMS)
// (POST /auth/verifications/request)
func (_ Unimplemented) RequestVerification(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify SSO Token (e.g. Google) and check user existence
// (POST /auth/verifications/sso)
func (_ Unimplemented) VerifySSO(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify the requested code
// (POST /auth/verifications/verify)
func (_ Unimplemented) VerifyCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit user feedback for a completed coaching session
// (POST /chat/sessions/{sessionID}/feedback)
func (_ Unimplemented) SubmitSessionFeedback(w http.ResponseWriter, r *http.Request, sessionID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the user's present and future commitments
// (GET /commitments)
func (_ Unimplemented) GetCommitments(w http.ResponseWriter, r *http.Request, params GetCommitmentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a manual commitment
// (POST /commitments)
func (_ Unimplemented) CreateCommitment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a commitment
// (DELETE /commitments/{commitmentId})
func (_ Unimplemented) DeleteCommitment(w http.ResponseWriter, r *http.Request, commitmentId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a commitment (edit fields and/or toggle completion)
// (PATCH /commitments/{commitmentId})
func (_ Unimplemented) UpdateCommitment(w http.ResponseWriter, r *http.Request, commitmentId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user Eisenhower Matrix exercises history
// (GET /eisenhower-matrix)
func (_ Unimplemented) GetEisenhowerMatrix(w http.ResponseWriter, r *http.Request, params GetEisenhowerMatrixParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific Eisenhower Matrix exercise by ID
// (GET /eisenhower-matrix/{id})
func (_ Unimplemented) GetEisenhowerMatrixId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send feedback, a bug report, or a feature request
// (POST /feedback)
func (_ Unimplemented) SubmitFeedback(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get today's proposed growth session
// (GET /journey)
func (_ Unimplemented) GetDailyJourney(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a new lead
// (POST /leads)
func (_ Unimplemented) PostLeads(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete current user (anonymize account)
// (DELETE /me)
func (_ Unimplemented) DeleteCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update current user
// (PATCH /me)
func (_ Unimplemented) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user data, all of it or by category
// (DELETE /me/data)
func (_ Unimplemented) DeleteCurrentUserData(w http.ResponseWriter, r *http.Request, params DeleteCurrentUserDataParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export all personal data for GDPR compliance
// (GET /me/data)
func (_ Unimplemented) ExportCurrentUserData(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Email the user a copy of their data
// (POST /me/data/export)
func (_ Unimplemented) RequestUserDataExport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new device FCM token for push notifications
// (POST /me/fcm-token)
func (_ Unimplemented) RegisterFCMToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the user's integrations (WhatsApp, ...)
// (GET /me/integrations)
func (_ Unimplemented) GetIntegrations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start linking the user's Telegram account (returns a one-time code and t.me link)
// (POST /me/integrations/telegram/link)
func (_ Unimplemented) LinkTelegramIntegration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start linking the user's WhatsApp number (returns a one-time code and wa.me link)
// (POST /me/integrations/whatsapp/link)
func (_ Unimplemented) LinkWhatsAppIntegration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unlink an integration
// (DELETE /me/integrations/{integrationId})
func (_ Unimplemented) DeleteIntegration(w http.ResponseWriter, r *http.Request, integrationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get details of an integration by ID or provider name (e.g., whatsapp)
// (GET /me/integrations/{integrationId})
func (_ Unimplemented) GetIntegration(w http.ResponseWriter, r *http.Request, integrationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an integration (e.g. reply mode)
// (PATCH /me/integrations/{integrationId})
func (_ Unimplemented) UpdateIntegration(w http.ResponseWriter, r *http.Request, integrationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user profile and progress statistics
// (GET /me/profile)
func (_ Unimplemented) GetMeProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the user's balance transaction history (newest first)
// (GET /me/transactions)
func (_ Unimplemented) GetTransactions(w http.ResponseWriter, r *http.Request, params GetTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the user's usage history (billable sessions and companion messages, newest first)
// (GET /me/usage)
func (_ Unimplemented) GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user memories
// (GET /memories)
func (_ Unimplemented) GetMemories(w http.ResponseWriter, r *http.Request, params GetMemoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a specific memory
// (DELETE /memories/{memoryId})
func (_ Unimplemented) DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a random personal development quote
// (GET /quotes/random)
func (_ Unimplemented) GetRandomQuote(w http.ResponseWriter, r *http.Request, params GetRandomQuoteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user recommendations
// (GET /recommendations)
func (_ Unimplemented) GetRecommendations(w http.ResponseWriter, r *http.Request, params GetRecommendationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user's sessions
// (GET /sessions)
func (_ Unimplemented) GetSessions(w http.ResponseWriter, r *http.Request, params GetSessionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user streak information
// (GET /streak)
func (_ Unimplemented) GetStreak(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get test setup documentation
// (GET /test-data)
func (_ Unimplemented) GetTestDataDocs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get usage calendar statistics for a given month
// (GET /usage-calendar)
func (_ Unimplemented) GetUsageCalendar(w http.ResponseWriter, r *http.Request, params GetUsageCalendarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join the waitlist
// (POST /waitlist)
func (_ Unimplemented) JoinWaitlist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevenueCat purchase events webhook (credits the minutes balance)
// (POST /webhooks/revenuecat)
func (_ Unimplemented) PostWebhooksRevenuecat(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Telegram incoming updates webhook
// (POST /webhooks/telegram/{secret})
func (_ Unimplemented) PostWebhooksTelegramSecret(w http.ResponseWriter, r *http.Request, secret string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Twilio incoming SMS webhook
// (POST /webhooks/twilio/sms)
func (_ Unimplemented) PostWebhooksTwilioSms(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Meta WhatsApp verification webhook
// (GET /webhooks/whatsapp)
func (_ Unimplemented) GetWebhooksWhatsapp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Meta WhatsApp incoming messages webhook
// (POST /webhooks/whatsapp)
func (_ Unimplemented) PostWebhooksWhatsapp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user Wheel of Life exercises history
// (GET /wheel-of-life)
func (_ Unimplemented) GetWheelOfLife(w http.ResponseWriter, r *http.Request, params GetWheelOfLifeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific Wheel of Life exercise by ID
// (GET /wheel-of-life/{id})
func (_ Unimplemented) GetWheelOfLifeId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetAdminDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminDashboardParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListLeads operation middleware
func (siw *ServerInterfaceWrapper) AdminListLeads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminListLeadsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListLeads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateLead operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateLead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateLead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetAccount operation middleware
func (siw *ServerInterfaceWrapper) ResetAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminSessions operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminSessionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userId", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "userName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userName", r.URL.Query(), &params.UserName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userName"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "userCountry" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userCountry", r.URL.Query(), &params.UserCountry, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userCountry"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userCountry", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "userLanguage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userLanguage", r.URL.Query(), &params.UserLanguage, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userLanguage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userLanguage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetupTestData operation middleware
func (siw *ServerInterfaceWrapper) SetupTestData(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetupTestData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "preferredLanguage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "preferredLanguage", r.URL.Query(), &params.PreferredLanguage, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "preferredLanguage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preferredLanguage", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "isActive"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdAt" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdAt", r.URL.Query(), &params.CreatedAt, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdAt"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdAt", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "waitlisted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "waitlisted", r.URL.Query(), &params.Waitlisted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "waitlisted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "waitlisted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsersId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAdminUsersId operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminUsersId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAdminUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminUsersIdCredits operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUsersIdCredits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminUsersIdCredits(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppleLogin operation middleware
func (siw *ServerInterfaceWrapper) AppleLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppleLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GoogleLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginWithCode operation middleware
func (siw *ServerInterfaceWrapper) LoginWithCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginWithCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIdentifier operation middleware
func (siw *ServerInterfaceWrapper) UpdateIdentifier(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIdentifier(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkAppleAccount operation middleware
func (siw *ServerInterfaceWrapper) LinkAppleAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkAppleAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestVerification operation middleware
func (siw *ServerInterfaceWrapper) RequestVerification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestVerification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifySSO operation middleware
func (siw *ServerInterfaceWrapper) VerifySSO(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifySSO(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitSessionFeedback operation middleware
func (siw *ServerInterfaceWrapper) SubmitSessionFeedback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionID" -------------
	var sessionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionID", chi.URLParam(r, "sessionID"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitSessionFeedback(w, r, sessionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCommitments operation middleware
func (siw *ServerInterfaceWrapper) GetCommitments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCommitmentsParams

	// ------------- Optional query parameter "history" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "history", r.URL.Query(), &params.History, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "history"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "history", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCommitments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCommitment operation middleware
func (siw *ServerInterfaceWrapper) CreateCommitment(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCommitment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCommitment operation middleware
func (siw *ServerInterfaceWrapper) DeleteCommitment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "commitmentId" -------------
	var commitmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "commitmentId", chi.URLParam(r, "commitmentId"), &commitmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commitmentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCommitment(w, r, commitmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCommitment operation middleware
func (siw *ServerInterfaceWrapper) UpdateCommitment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "commitmentId" -------------
	var commitmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "commitmentId", chi.URLParam(r, "commitmentId"), &commitmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commitmentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCommitment(w, r, commitmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEisenhowerMatrix operation middleware
func (siw *ServerInterfaceWrapper) GetEisenhowerMatrix(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEisenhowerMatrixParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEisenhowerMatrix(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEisenhowerMatrixId operation middleware
func (siw *ServerInterfaceWrapper) GetEisenhowerMatrixId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEisenhowerMatrixId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitFeedback operation middleware
func (siw *ServerInterfaceWrapper) SubmitFeedback(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitFeedback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyJourney operation middleware
func (siw *ServerInterfaceWrapper) GetDailyJourney(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyJourney(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLeads operation middleware
func (siw *ServerInterfaceWrapper) PostLeads(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLeads(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCurrentUserData operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrentUserData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteCurrentUserDataParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", r.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCurrentUserData(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportCurrentUserData operation middleware
func (siw *ServerInterfaceWrapper) ExportCurrentUserData(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportCurrentUserData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestUserDataExport operation middleware
func (siw *ServerInterfaceWrapper) RequestUserDataExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestUserDataExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterFCMToken operation middleware
func (siw *ServerInterfaceWrapper) RegisterFCMToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterFCMToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIntegrations operation middleware
func (siw *ServerInterfaceWrapper) GetIntegrations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIntegrations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkTelegramIntegration operation middleware
func (siw *ServerInterfaceWrapper) LinkTelegramIntegration(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkTelegramIntegration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkWhatsAppIntegration operation middleware
func (siw *ServerInterfaceWrapper) LinkWhatsAppIntegration(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkWhatsAppIntegration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIntegration operation middleware
func (siw *ServerInterfaceWrapper) DeleteIntegration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "integrationId" -------------
	var integrationId string

	err = runtime.BindStyledParameterWithOptions("simple", "integrationId", chi.URLParam(r, "integrationId"), &integrationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "integrationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIntegration(w, r, integrationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIntegration operation middleware
func (siw *ServerInterfaceWrapper) GetIntegration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "integrationId" -------------
	var integrationId string

	err = runtime.BindStyledParameterWithOptions("simple", "integrationId", chi.URLParam(r, "integrationId"), &integrationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "integrationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIntegration(w, r, integrationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIntegration operation middleware
func (siw *ServerInterfaceWrapper) UpdateIntegration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "integrationId" -------------
	var integrationId string

	err = runtime.BindStyledParameterWithOptions("simple", "integrationId", chi.URLParam(r, "integrationId"), &integrationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "integrationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIntegration(w, r, integrationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMeProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "grouped" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "grouped", r.URL.Query(), &params.Grouped, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "grouped"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "grouped", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMemories operation middleware
func (siw *ServerInterfaceWrapper) GetMemories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMemoriesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "text" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "text", r.URL.Query(), &params.Text, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "text"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "text", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMemory operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", chi.URLParam(r, "memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRandomQuote operation middleware
func (siw *ServerInterfaceWrapper) GetRandomQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRandomQuoteParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRandomQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecommendations operation middleware
func (siw *ServerInterfaceWrapper) GetRecommendations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecommendationsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecommendations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessions operation middleware
func (siw *ServerInterfaceWrapper) GetSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSessionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStreak operation middleware
func (siw *ServerInterfaceWrapper) GetStreak(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStreak(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTestDataDocs operation middleware
func (siw *ServerInterfaceWrapper) GetTestDataDocs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTestDataDocs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsageCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetUsageCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageCalendarParams

	// ------------- Required query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsageCalendar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinWaitlist operation middleware
func (siw *ServerInterfaceWrapper) JoinWaitlist(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinWaitlist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWebhooksRevenuecat operation middleware
func (siw *ServerInterfaceWrapper) PostWebhooksRevenuecat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWebhooksRevenuecat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWebhooksTelegramSecret operation middleware
func (siw *ServerInterfaceWrapper) PostWebhooksTelegramSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "secret" -------------
	var secret string

	err = runtime.BindStyledParameterWithOptions("simple", "secret", chi.URLParam(r, "secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWebhooksTelegramSecret(w, r, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWebhooksTwilioSms operation middleware
func (siw *ServerInterfaceWrapper) PostWebhooksTwilioSms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWebhooksTwilioSms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebhooksWhatsapp operation middleware
func (siw *ServerInterfaceWrapper) GetWebhooksWhatsapp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebhooksWhatsapp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWebhooksWhatsapp operation middleware
func (siw *ServerInterfaceWrapper) PostWebhooksWhatsapp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWebhooksWhatsapp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWheelOfLife operation middleware
func (siw *ServerInterfaceWrapper) GetWheelOfLife(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWheelOfLifeParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWheelOfLife(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWheelOfLifeId operation middleware
func (siw *ServerInterfaceWrapper) GetWheelOfLifeId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWheelOfLifeId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/dashboard", wrapper.GetAdminDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/leads", wrapper.AdminListLeads)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/leads/{id}", wrapper.AdminUpdateLead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/reset-account", wrapper.ResetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/sessions", wrapper.GetAdminSessions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/test-setup", wrapper.SetupTestData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users", wrapper.GetAdminUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users/{id}", wrapper.GetAdminUsersId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/users/{id}", wrapper.PatchAdminUsersId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users/{id}/credits", wrapper.PostAdminUsersIdCredits)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/apple", wrapper.AppleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/google", wrapper.GoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login/code", wrapper.LoginWithCode)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/me/identifier", wrapper.UpdateIdentifier)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/me/link/apple", wrapper.LinkAppleAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verifications/request", wrapper.RequestVerification)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verifications/sso", wrapper.VerifySSO)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verifications/verify", wrapper.VerifyCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/chat/sessions/{sessionID}/feedback", wrapper.SubmitSessionFeedback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/commitments", wrapper.GetCommitments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/commitments", wrapper.CreateCommitment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/commitments/{commitmentId}", wrapper.DeleteCommitment)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/commitments/{commitmentId}", wrapper.UpdateCommitment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/eisenhower-matrix", wrapper.GetEisenhowerMatrix)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/eisenhower-matrix/{id}", wrapper.GetEisenhowerMatrixId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/feedback", wrapper.SubmitFeedback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/journey", wrapper.GetDailyJourney)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leads", wrapper.PostLeads)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me", wrapper.DeleteCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me/data", wrapper.DeleteCurrentUserData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/data", wrapper.ExportCurrentUserData)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/data/export", wrapper.RequestUserDataExport)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/fcm-token", wrapper.RegisterFCMToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/integrations", wrapper.GetIntegrations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/integrations/telegram/link", wrapper.LinkTelegramIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/integrations/whatsapp/link", wrapper.LinkWhatsAppIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me/integrations/{integrationId}", wrapper.DeleteIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/integrations/{integrationId}", wrapper.GetIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me/integrations/{integrationId}", wrapper.UpdateIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/profile", wrapper.GetMeProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/transactions", wrapper.GetTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/usage", wrapper.GetUsage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/memories", wrapper.GetMemories)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/memories/{memoryId}", wrapper.DeleteMemory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/quotes/random", wrapper.GetRandomQuote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recommendations", wrapper.GetRecommendations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions", wrapper.GetSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/streak", wrapper.GetStreak)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-data", wrapper.GetTestDataDocs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/usage-calendar", wrapper.GetUsageCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/waitlist", wrapper.JoinWaitlist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/revenuecat", wrapper.PostWebhooksRevenuecat)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/telegram/{secret}", wrapper.PostWebhooksTelegramSecret)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/twilio/sms", wrapper.PostWebhooksTwilioSms)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/webhooks/whatsapp", wrapper.GetWebhooksWhatsapp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/whatsapp", wrapper.PostWebhooksWhatsapp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wheel-of-life", wrapper.GetWheelOfLife)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wheel-of-life/{id}", wrapper.GetWheelOfLifeId)
	})

	return r
}
