// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for AdminCreditRequestType.
const (
	AdminCreditRequestTypeSubscription AdminCreditRequestType = "subscription"
	AdminCreditRequestTypeTopUp        AdminCreditRequestType = "top_up"
)

// Valid indicates whether the value is a known member of the AdminCreditRequestType enum.
func (e AdminCreditRequestType) Valid() bool {
	switch e {
	case AdminCreditRequestTypeSubscription:
		return true
	case AdminCreditRequestTypeTopUp:
		return true
	default:
		return false
	}
}

// Defines values for BadgeType.
const (
	AllThemesExplored     BadgeType = "allThemesExplored"
	AlwaysWithYou         BadgeType = "alwaysWithYou"
	AreaImproved          BadgeType = "areaImproved"
	FirstCommitment       BadgeType = "firstCommitment"
	FirstDeepSession      BadgeType = "firstDeepSession"
	FirstSession          BadgeType = "firstSession"
	HundredSessions       BadgeType = "hundredSessions"
	SevenDayStreak        BadgeType = "sevenDayStreak"
	TenInsights           BadgeType = "tenInsights"
	ThirtyDayStreak       BadgeType = "thirtyDayStreak"
	ThreeDayStreak        BadgeType = "threeDayStreak"
	TwentyFiveCommitments BadgeType = "twentyFiveCommitments"
	TwentySessions        BadgeType = "twentySessions"
	VisionSet             BadgeType = "visionSet"
	WheelRemapped         BadgeType = "wheelRemapped"
)

// Valid indicates whether the value is a known member of the BadgeType enum.
func (e BadgeType) Valid() bool {
	switch e {
	case AllThemesExplored:
		return true
	case AlwaysWithYou:
		return true
	case AreaImproved:
		return true
	case FirstCommitment:
		return true
	case FirstDeepSession:
		return true
	case FirstSession:
		return true
	case HundredSessions:
		return true
	case SevenDayStreak:
		return true
	case TenInsights:
		return true
	case ThirtyDayStreak:
		return true
	case ThreeDayStreak:
		return true
	case TwentyFiveCommitments:
		return true
	case TwentySessions:
		return true
	case VisionSet:
		return true
	case WheelRemapped:
		return true
	default:
		return false
	}
}

// Defines values for BalanceTransactionPlan.
const (
	Annual  BalanceTransactionPlan = "annual"
	Monthly BalanceTransactionPlan = "monthly"
)

// Valid indicates whether the value is a known member of the BalanceTransactionPlan enum.
func (e BalanceTransactionPlan) Valid() bool {
	switch e {
	case Annual:
		return true
	case Monthly:
		return true
	default:
		return false
	}
}

// Defines values for BalanceTransactionType.
const (
	BalanceTransactionTypeMessageUsage BalanceTransactionType = "message_usage"
	BalanceTransactionTypeRefund       BalanceTransactionType = "refund"
	BalanceTransactionTypeSessionFree  BalanceTransactionType = "session_free"
	BalanceTransactionTypeSessionUsage BalanceTransactionType = "session_usage"
	BalanceTransactionTypeSubscription BalanceTransactionType = "subscription"
	BalanceTransactionTypeTopUp        BalanceTransactionType = "top_up"
)

// Valid indicates whether the value is a known member of the BalanceTransactionType enum.
func (e BalanceTransactionType) Valid() bool {
	switch e {
	case BalanceTransactionTypeMessageUsage:
		return true
	case BalanceTransactionTypeRefund:
		return true
	case BalanceTransactionTypeSessionFree:
		return true
	case BalanceTransactionTypeSessionUsage:
		return true
	case BalanceTransactionTypeSubscription:
		return true
	case BalanceTransactionTypeTopUp:
		return true
	default:
		return false
	}
}

// Defines values for ChannelUpdateRequestReplyMode.
const (
	ChannelUpdateRequestReplyModeAudio ChannelUpdateRequestReplyMode = "audio"
	ChannelUpdateRequestReplyModeAuto  ChannelUpdateRequestReplyMode = "auto"
	ChannelUpdateRequestReplyModeText  ChannelUpdateRequestReplyMode = "text"
)

// Valid indicates whether the value is a known member of the ChannelUpdateRequestReplyMode enum.
func (e ChannelUpdateRequestReplyMode) Valid() bool {
	switch e {
	case ChannelUpdateRequestReplyModeAudio:
		return true
	case ChannelUpdateRequestReplyModeAuto:
		return true
	case ChannelUpdateRequestReplyModeText:
		return true
	default:
		return false
	}
}

// Defines values for CommitmentOrigin.
const (
	Behavior CommitmentOrigin = "behavior"
	Manual   CommitmentOrigin = "manual"
	Plan     CommitmentOrigin = "plan"
)

// Valid indicates whether the value is a known member of the CommitmentOrigin enum.
func (e CommitmentOrigin) Valid() bool {
	switch e {
	case Behavior:
		return true
	case Manual:
		return true
	case Plan:
		return true
	default:
		return false
	}
}

// Defines values for CommitmentStatus.
const (
	Completed CommitmentStatus = "completed"
	Missed    CommitmentStatus = "missed"
	Overdue   CommitmentStatus = "overdue"
	Pending   CommitmentStatus = "pending"
)

// Valid indicates whether the value is a known member of the CommitmentStatus enum.
func (e CommitmentStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Missed:
		return true
	case Overdue:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for CommitmentType.
const (
	CommitmentTypeOneTime   CommitmentType = "one_time"
	CommitmentTypeRecurring CommitmentType = "recurring"
)

// Valid indicates whether the value is a known member of the CommitmentType enum.
func (e CommitmentType) Valid() bool {
	switch e {
	case CommitmentTypeOneTime:
		return true
	case CommitmentTypeRecurring:
		return true
	default:
		return false
	}
}

// Defines values for CreateCommitmentRequestType.
const (
	CreateCommitmentRequestTypeOneTime   CreateCommitmentRequestType = "one_time"
	CreateCommitmentRequestTypeRecurring CreateCommitmentRequestType = "recurring"
)

// Valid indicates whether the value is a known member of the CreateCommitmentRequestType enum.
func (e CreateCommitmentRequestType) Valid() bool {
	switch e {
	case CreateCommitmentRequestTypeOneTime:
		return true
	case CreateCommitmentRequestTypeRecurring:
		return true
	default:
		return false
	}
}

// Defines values for FeedbackRequestCategory.
const (
	Bug      FeedbackRequestCategory = "bug"
	Feature  FeedbackRequestCategory = "feature"
	Feedback FeedbackRequestCategory = "feedback"
)

// Valid indicates whether the value is a known member of the FeedbackRequestCategory enum.
func (e FeedbackRequestCategory) Valid() bool {
	switch e {
	case Bug:
		return true
	case Feature:
		return true
	case Feedback:
		return true
	default:
		return false
	}
}

// Defines values for IntegrationReplyMode.
const (
	IntegrationReplyModeAudio IntegrationReplyMode = "audio"
	IntegrationReplyModeAuto  IntegrationReplyMode = "auto"
	IntegrationReplyModeText  IntegrationReplyMode = "text"
)

// Valid indicates whether the value is a known member of the IntegrationReplyMode enum.
func (e IntegrationReplyMode) Valid() bool {
	switch e {
	case IntegrationReplyModeAudio:
		return true
	case IntegrationReplyModeAuto:
		return true
	case IntegrationReplyModeText:
		return true
	default:
		return false
	}
}

// Defines values for JourneySessionResponseMode.
const (
	Resume JourneySessionResponseMode = "resume"
	Start  JourneySessionResponseMode = "start"
)

// Valid indicates whether the value is a known member of the JourneySessionResponseMode enum.
func (e JourneySessionResponseMode) Valid() bool {
	switch e {
	case Resume:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Defines values for LoginWithCodeRequestType.
const (
	LoginWithCodeRequestTypeEmail LoginWithCodeRequestType = "email"
	LoginWithCodeRequestTypePhone LoginWithCodeRequestType = "phone"
)

// Valid indicates whether the value is a known member of the LoginWithCodeRequestType enum.
func (e LoginWithCodeRequestType) Valid() bool {
	switch e {
	case LoginWithCodeRequestTypeEmail:
		return true
	case LoginWithCodeRequestTypePhone:
		return true
	default:
		return false
	}
}

// Defines values for MemoryCategory.
const (
	Context   MemoryCategory = "context"
	Identity  MemoryCategory = "identity"
	Insight   MemoryCategory = "insight"
	Needs     MemoryCategory = "needs"
	Obstacles MemoryCategory = "obstacles"
	Values    MemoryCategory = "values"
)

// Valid indicates whether the value is a known member of the MemoryCategory enum.
func (e MemoryCategory) Valid() bool {
	switch e {
	case Context:
		return true
	case Identity:
		return true
	case Insight:
		return true
	case Needs:
		return true
	case Obstacles:
		return true
	case Values:
		return true
	default:
		return false
	}
}

// Defines values for QuoteCategory.
const (
	Action     QuoteCategory = "action"
	Growth     QuoteCategory = "growth"
	Mindset    QuoteCategory = "mindset"
	Purpose    QuoteCategory = "purpose"
	Resilience QuoteCategory = "resilience"
	Wisdom     QuoteCategory = "wisdom"
)

// Valid indicates whether the value is a known member of the QuoteCategory enum.
func (e QuoteCategory) Valid() bool {
	switch e {
	case Action:
		return true
	case Growth:
		return true
	case Mindset:
		return true
	case Purpose:
		return true
	case Resilience:
		return true
	case Wisdom:
		return true
	default:
		return false
	}
}

// Defines values for RecommendationType.
const (
	RecommendationTypeArticle RecommendationType = "article"
	RecommendationTypeBook    RecommendationType = "book"
	RecommendationTypeOther   RecommendationType = "other"
	RecommendationTypePodcast RecommendationType = "podcast"
	RecommendationTypeVideo   RecommendationType = "video"
)

// Valid indicates whether the value is a known member of the RecommendationType enum.
func (e RecommendationType) Valid() bool {
	switch e {
	case RecommendationTypeArticle:
		return true
	case RecommendationTypeBook:
		return true
	case RecommendationTypeOther:
		return true
	case RecommendationTypePodcast:
		return true
	case RecommendationTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for SSOVerificationRequestType.
const (
	Apple  SSOVerificationRequestType = "apple"
	Google SSOVerificationRequestType = "google"
)

// Valid indicates whether the value is a known member of the SSOVerificationRequestType enum.
func (e SSOVerificationRequestType) Valid() bool {
	switch e {
	case Apple:
		return true
	case Google:
		return true
	default:
		return false
	}
}

// Defines values for SessionType.
const (
	SessionTypeCheckin           SessionType = "checkin"
	SessionTypeOnboarding        SessionType = "onboarding"
	SessionTypeSessionAcceptance SessionType = "session_acceptance"
	SessionTypeSessionBeliefs    SessionType = "session_beliefs"
	SessionTypeSessionDecisions  SessionType = "session_decisions"
	SessionTypeSessionEnergy     SessionType = "session_energy"
	SessionTypeSessionIdentity   SessionType = "session_identity"
	SessionTypeSessionMovement   SessionType = "session_movement"
	SessionTypeSessionPriorities SessionType = "session_priorities"
	SessionTypeSessionValues     SessionType = "session_values"
	SessionTypeSessionVision     SessionType = "session_vision"
)

// Valid indicates whether the value is a known member of the SessionType enum.
func (e SessionType) Valid() bool {
	switch e {
	case SessionTypeCheckin:
		return true
	case SessionTypeOnboarding:
		return true
	case SessionTypeSessionAcceptance:
		return true
	case SessionTypeSessionBeliefs:
		return true
	case SessionTypeSessionDecisions:
		return true
	case SessionTypeSessionEnergy:
		return true
	case SessionTypeSessionIdentity:
		return true
	case SessionTypeSessionMovement:
		return true
	case SessionTypeSessionPriorities:
		return true
	case SessionTypeSessionValues:
		return true
	case SessionTypeSessionVision:
		return true
	default:
		return false
	}
}

// Defines values for SetupTestDataRequestSessionType.
const (
	CheckinDailyAfterDays   SetupTestDataRequestSessionType = "checkin_daily_after_days"
	CheckinDailyAfterLong   SetupTestDataRequestSessionType = "checkin_daily_after_long"
	CheckinDailyAfterWeeks  SetupTestDataRequestSessionType = "checkin_daily_after_weeks"
	CheckinDailyConsecutive SetupTestDataRequestSessionType = "checkin_daily_consecutive"
	CheckinDailyFirst       SetupTestDataRequestSessionType = "checkin_daily_first"
	CheckinDailySameDay     SetupTestDataRequestSessionType = "checkin_daily_same_day"
	CoachingSessionReady    SetupTestDataRequestSessionType = "coaching_session_ready"
	NewUser                 SetupTestDataRequestSessionType = "new_user"
	OnboardingEnding        SetupTestDataRequestSessionType = "onboarding_ending"
	OnboardingIdealVision   SetupTestDataRequestSessionType = "onboarding_ideal_vision"
	OnboardingMetaphor      SetupTestDataRequestSessionType = "onboarding_metaphor"
	OnboardingWheel         SetupTestDataRequestSessionType = "onboarding_wheel"
	Stressed                SetupTestDataRequestSessionType = "stressed"
)

// Valid indicates whether the value is a known member of the SetupTestDataRequestSessionType enum.
func (e SetupTestDataRequestSessionType) Valid() bool {
	switch e {
	case CheckinDailyAfterDays:
		return true
	case CheckinDailyAfterLong:
		return true
	case CheckinDailyAfterWeeks:
		return true
	case CheckinDailyConsecutive:
		return true
	case CheckinDailyFirst:
		return true
	case CheckinDailySameDay:
		return true
	case CoachingSessionReady:
		return true
	case NewUser:
		return true
	case OnboardingEnding:
		return true
	case OnboardingIdealVision:
		return true
	case OnboardingMetaphor:
		return true
	case OnboardingWheel:
		return true
	case Stressed:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseDataRegion.
const (
	TokenResponseDataRegionEu TokenResponseDataRegion = "eu"
	TokenResponseDataRegionUs TokenResponseDataRegion = "us"
)

// Valid indicates whether the value is a known member of the TokenResponseDataRegion enum.
func (e TokenResponseDataRegion) Valid() bool {
	switch e {
	case TokenResponseDataRegionEu:
		return true
	case TokenResponseDataRegionUs:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCommitmentRequestType.
const (
	OneTime   UpdateCommitmentRequestType = "one_time"
	Recurring UpdateCommitmentRequestType = "recurring"
)

// Valid indicates whether the value is a known member of the UpdateCommitmentRequestType enum.
func (e UpdateCommitmentRequestType) Valid() bool {
	switch e {
	case OneTime:
		return true
	case Recurring:
		return true
	default:
		return false
	}
}

// Defines values for UpdateIdentifierRequestType.
const (
	UpdateIdentifierRequestTypeEmail UpdateIdentifierRequestType = "email"
	UpdateIdentifierRequestTypePhone UpdateIdentifierRequestType = "phone"
)

// Valid indicates whether the value is a known member of the UpdateIdentifierRequestType enum.
func (e UpdateIdentifierRequestType) Valid() bool {
	switch e {
	case UpdateIdentifierRequestTypeEmail:
		return true
	case UpdateIdentifierRequestTypePhone:
		return true
	default:
		return false
	}
}

// Defines values for UsageCalendarResponseDaysKind.
const (
	UsageCalendarResponseDaysKindCheckin UsageCalendarResponseDaysKind = "checkin"
	UsageCalendarResponseDaysKindNone    UsageCalendarResponseDaysKind = "none"
	UsageCalendarResponseDaysKindSession UsageCalendarResponseDaysKind = "session"
)

// Valid indicates whether the value is a known member of the UsageCalendarResponseDaysKind enum.
func (e UsageCalendarResponseDaysKind) Valid() bool {
	switch e {
	case UsageCalendarResponseDaysKindCheckin:
		return true
	case UsageCalendarResponseDaysKindNone:
		return true
	case UsageCalendarResponseDaysKindSession:
		return true
	default:
		return false
	}
}

// Defines values for UsageEntryKind.
const (
	Messages UsageEntryKind = "messages"
	Session  UsageEntryKind = "session"
)

// Valid indicates whether the value is a known member of the UsageEntryKind enum.
func (e UsageEntryKind) Valid() bool {
	switch e {
	case Messages:
		return true
	case Session:
		return true
	default:
		return false
	}
}

// Defines values for UserCoachVoice.
const (
	UserCoachVoiceAlgieba      UserCoachVoice = "algieba"
	UserCoachVoiceCharon       UserCoachVoice = "charon"
	UserCoachVoiceDespina      UserCoachVoice = "despina"
	UserCoachVoiceEnceladus    UserCoachVoice = "enceladus"
	UserCoachVoiceGacrux       UserCoachVoice = "gacrux"
	UserCoachVoiceOrus         UserCoachVoice = "orus"
	UserCoachVoiceVindemiatrix UserCoachVoice = "vindemiatrix"
)

// Valid indicates whether the value is a known member of the UserCoachVoice enum.
func (e UserCoachVoice) Valid() bool {
	switch e {
	case UserCoachVoiceAlgieba:
		return true
	case UserCoachVoiceCharon:
		return true
	case UserCoachVoiceDespina:
		return true
	case UserCoachVoiceEnceladus:
		return true
	case UserCoachVoiceGacrux:
		return true
	case UserCoachVoiceOrus:
		return true
	case UserCoachVoiceVindemiatrix:
		return true
	default:
		return false
	}
}

// Defines values for UserDataRegion.
const (
	UserDataRegionEu UserDataRegion = "eu"
	UserDataRegionUs UserDataRegion = "us"
)

// Valid indicates whether the value is a known member of the UserDataRegion enum.
func (e UserDataRegion) Valid() bool {
	switch e {
	case UserDataRegionEu:
		return true
	case UserDataRegionUs:
		return true
	default:
		return false
	}
}

// Defines values for UserUpdateRequestChatHistoryRetentionDays.
const (
	N0  UserUpdateRequestChatHistoryRetentionDays = 0
	N3  UserUpdateRequestChatHistoryRetentionDays = 3
	N30 UserUpdateRequestChatHistoryRetentionDays = 30
	N7  UserUpdateRequestChatHistoryRetentionDays = 7
)

// Valid indicates whether the value is a known member of the UserUpdateRequestChatHistoryRetentionDays enum.
func (e UserUpdateRequestChatHistoryRetentionDays) Valid() bool {
	switch e {
	case N0:
		return true
	case N3:
		return true
	case N30:
		return true
	case N7:
		return true
	default:
		return false
	}
}

// Defines values for UserUpdateRequestCoachVoice.
const (
	UserUpdateRequestCoachVoiceAlgieba      UserUpdateRequestCoachVoice = "algieba"
	UserUpdateRequestCoachVoiceCharon       UserUpdateRequestCoachVoice = "charon"
	UserUpdateRequestCoachVoiceDespina      UserUpdateRequestCoachVoice = "despina"
	UserUpdateRequestCoachVoiceEnceladus    UserUpdateRequestCoachVoice = "enceladus"
	UserUpdateRequestCoachVoiceGacrux       UserUpdateRequestCoachVoice = "gacrux"
	UserUpdateRequestCoachVoiceOrus         UserUpdateRequestCoachVoice = "orus"
	UserUpdateRequestCoachVoiceVindemiatrix UserUpdateRequestCoachVoice = "vindemiatrix"
)

// Valid indicates whether the value is a known member of the UserUpdateRequestCoachVoice enum.
func (e UserUpdateRequestCoachVoice) Valid() bool {
	switch e {
	case UserUpdateRequestCoachVoiceAlgieba:
		return true
	case UserUpdateRequestCoachVoiceCharon:
		return true
	case UserUpdateRequestCoachVoiceDespina:
		return true
	case UserUpdateRequestCoachVoiceEnceladus:
		return true
	case UserUpdateRequestCoachVoiceGacrux:
		return true
	case UserUpdateRequestCoachVoiceOrus:
		return true
	case UserUpdateRequestCoachVoiceVindemiatrix:
		return true
	default:
		return false
	}
}

// Defines values for VerificationCheckType.
const (
	VerificationCheckTypeEmail VerificationCheckType = "email"
	VerificationCheckTypePhone VerificationCheckType = "phone"
)

// Valid indicates whether the value is a known member of the VerificationCheckType enum.
func (e VerificationCheckType) Valid() bool {
	switch e {
	case VerificationCheckTypeEmail:
		return true
	case VerificationCheckTypePhone:
		return true
	default:
		return false
	}
}

// Defines values for VerificationRequestType.
const (
	VerificationRequestTypeEmail VerificationRequestType = "email"
	VerificationRequestTypePhone VerificationRequestType = "phone"
)

// Valid indicates whether the value is a known member of the VerificationRequestType enum.
func (e VerificationRequestType) Valid() bool {
	switch e {
	case VerificationRequestTypeEmail:
		return true
	case VerificationRequestTypePhone:
		return true
	default:
		return false
	}
}

// Defines values for WaitlistRequestDataRegion.
const (
	Eu WaitlistRequestDataRegion = "eu"
	Us WaitlistRequestDataRegion = "us"
)

// Valid indicates whether the value is a known member of the WaitlistRequestDataRegion enum.
func (e WaitlistRequestDataRegion) Valid() bool {
	switch e {
	case Eu:
		return true
	case Us:
		return true
	default:
		return false
	}
}

// Defines values for GetRecommendationsParamsType.
const (
	GetRecommendationsParamsTypeArticle GetRecommendationsParamsType = "article"
	GetRecommendationsParamsTypeBook    GetRecommendationsParamsType = "book"
	GetRecommendationsParamsTypeOther   GetRecommendationsParamsType = "other"
	GetRecommendationsParamsTypePodcast GetRecommendationsParamsType = "podcast"
	GetRecommendationsParamsTypeVideo   GetRecommendationsParamsType = "video"
)

// Valid indicates whether the value is a known member of the GetRecommendationsParamsType enum.
func (e GetRecommendationsParamsType) Valid() bool {
	switch e {
	case GetRecommendationsParamsTypeArticle:
		return true
	case GetRecommendationsParamsTypeBook:
		return true
	case GetRecommendationsParamsTypeOther:
		return true
	case GetRecommendationsParamsTypePodcast:
		return true
	case GetRecommendationsParamsTypeVideo:
		return true
	default:
		return false
	}
}

// AdminCreditRequest defines model for AdminCreditRequest.
type AdminCreditRequest struct {
	// AmountMinutes Convenience alternative to amountSeconds (credited as minutes × 60)
	AmountMinutes *int `json:"amountMinutes,omitempty"`

	// AmountSeconds Exactly one of amountSeconds/amountMinutes must be set and positive
	AmountSeconds *int64  `json:"amountSeconds,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Product Plan/package label (e.g. "monthly_120", "topup_60")
	Product *string                `json:"product,omitempty"`
	Type    AdminCreditRequestType `json:"type"`
}

// AdminCreditRequestType defines model for AdminCreditRequest.Type.
type AdminCreditRequestType string

// AdminDashboard defines model for AdminDashboard.
type AdminDashboard struct {
	Cost       *AdminDashboardCost     `json:"cost,omitempty"`
	PeriodFrom *time.Time              `json:"periodFrom,omitempty"`
	PeriodTo   *time.Time              `json:"periodTo,omitempty"`
	Quality    *AdminDashboardQuality  `json:"quality,omitempty"`
	Sessions   *AdminDashboardSessions `json:"sessions,omitempty"`
	Users      *AdminDashboardUsers    `json:"users,omitempty"`
}

// AdminDashboardCost defines model for AdminDashboardCost.
type AdminDashboardCost struct {
	AvgCostPerMinuteUsd  *float32 `json:"avgCostPerMinuteUsd,omitempty"`
	AvgCostPerSessionUsd *float32 `json:"avgCostPerSessionUsd,omitempty"`
	AvgCostPerUserUsd    *float32 `json:"avgCostPerUserUsd,omitempty"`
	TotalCostUsd         *float32 `json:"totalCostUsd,omitempty"`
}

// AdminDashboardQuality defines model for AdminDashboardQuality.
type AdminDashboardQuality struct {
	AvgAiEvaluation   *float32 `json:"avgAiEvaluation,omitempty"`
	AvgUserEvaluation *float32 `json:"avgUserEvaluation,omitempty"`

	// RatedSessions Sessions with a user-submitted evaluation.
	RatedSessions *int `json:"ratedSessions,omitempty"`

	// ReviewedSessions Sessions with an AI evaluation.
	ReviewedSessions *int `json:"reviewedSessions,omitempty"`
}

// AdminDashboardSessions defines model for AdminDashboardSessions.
type AdminDashboardSessions struct {
	AvgSessionDurationMinutes *float32                `json:"avgSessionDurationMinutes,omitempty"`
	BySessionType             *[]AdminSessionTypeStat `json:"bySessionType,omitempty"`
	TotalDurationMinutes      *float32                `json:"totalDurationMinutes,omitempty"`
	TotalSessions             *int                    `json:"totalSessions,omitempty"`
}

// AdminDashboardUsers defines model for AdminDashboardUsers.
type AdminDashboardUsers struct {
	// ActiveUsers Distinct users with at least one session in the window.
	ActiveUsers              *int                   `json:"activeUsers,omitempty"`
	AvgSessionsPerActiveUser *float32               `json:"avgSessionsPerActiveUser,omitempty"`
	Demographics             *AdminUserDemographics `json:"demographics,omitempty"`

	// NewUsers Users created within [from,to] when a window is given, otherwise within the last 30 days.
	NewUsers *int `json:"newUsers,omitempty"`

	// OnboardingCompleted Users whose state has advanced past onboarding (current snapshot, not windowed).
	OnboardingCompleted  *int `json:"onboardingCompleted,omitempty"`
	OnboardingInProgress *int `json:"onboardingInProgress,omitempty"`

	// ReturningUsers Distinct users with two or more sessions in the window.
	ReturningUsers *int `json:"returningUsers,omitempty"`
	TotalUsers     *int `json:"totalUsers,omitempty"`
}

// AdminDemographicStat defines model for AdminDemographicStat.
type AdminDemographicStat struct {
	Key       *string `json:"key,omitempty"`
	UserCount *int    `json:"userCount,omitempty"`
}

// AdminSessionTypeStat defines model for AdminSessionTypeStat.
type AdminSessionTypeStat struct {
	AvgCostUsd         *float32 `json:"avgCostUsd,omitempty"`
	AvgDurationMinutes *float32 `json:"avgDurationMinutes,omitempty"`
	SessionCount       *int     `json:"sessionCount,omitempty"`
	SessionType        *string  `json:"sessionType,omitempty"`
	TotalCostUsd       *float32 `json:"totalCostUsd,omitempty"`
}

// AdminUserDemographics defines model for AdminUserDemographics.
type AdminUserDemographics struct {
	ByAgeBucket *[]AdminDemographicStat `json:"byAgeBucket,omitempty"`
	ByCountry   *[]AdminDemographicStat `json:"byCountry,omitempty"`
	ByGender    *[]AdminDemographicStat `json:"byGender,omitempty"`
	ByLanguage  *[]AdminDemographicStat `json:"byLanguage,omitempty"`
}

// AdminUserPatchRequest defines model for AdminUserPatchRequest.
type AdminUserPatchRequest struct {
	IsActive *bool `json:"isActive,omitempty"`
}

// AppleLoginRequest defines model for AppleLoginRequest.
type AppleLoginRequest struct {
	// Email Email as reported by the client on first authorization. Informational only — the server trusts the verified email inside the identity token.
	Email *string `json:"email,omitempty"`

	// IdentityToken JWT identity token from ASAuthorizationAppleIDCredential.
	IdentityToken string `json:"identityToken"`

	// Name Full name from the first authorization (Apple never provides it again). Informational only; login never creates accounts.
	Name *string `json:"name,omitempty"`
}

// BadgeType Profile badges v2. The app renders these in this order as a 3x5 grid. Rows in user_badges may still carry the retired goalReached type (granted on behaviour-plan graduation) — kept for analytics; the app ignores types it does not recognize.
type BadgeType string

// BalanceTransaction defines model for BalanceTransaction.
type BalanceTransaction struct {
	// AmountSeconds Signed: positive = credit, negative = debit. Always 0 for session_free — the row exists so the history accounts for the session, not to move money. For a grouped message row, the run's debits summed.
	AmountSeconds *int64 `json:"amountSeconds,omitempty"`

	// BalanceAfter The balance after this row applied (after the newest debit, for a grouped message row).
	BalanceAfter *int64 `json:"balanceAfter,omitempty"`

	// CreatedAt When this row applied (the newest debit's time, for a grouped message row).
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Day Grouped message rows only: the calendar day of the run, YYYY-MM-DD in the request's X-Timezone.
	Day         *string `json:"day,omitempty"`
	Description *string `json:"description,omitempty"`

	// Id For a grouped message row, the id of the newest debit in the run.
	Id *string `json:"id,omitempty"`

	// MessageCount Grouped message rows only: how many charged replies the run collapses.
	MessageCount *int `json:"messageCount,omitempty"`

	// Plan Billing cadence of a subscription credit, derived server-side from the product id so clients translate an enum instead of parsing store slugs. Subscription rows only, and absent when the product names neither cadence.
	Plan *BalanceTransactionPlan `json:"plan,omitempty"`

	// Product Plan/package label for purchase credits and refunds
	Product *string `json:"product,omitempty"`

	// SessionId Communication session charged by a session_usage debit (or recorded by a session_free row)
	SessionId *string `json:"sessionId,omitempty"`

	// SessionType Type of the session (if applicable)
	SessionType *string                 `json:"sessionType,omitempty"`
	Type        *BalanceTransactionType `json:"type,omitempty"`
}

// BalanceTransactionPlan Billing cadence of a subscription credit, derived server-side from the product id so clients translate an enum instead of parsing store slugs. Subscription rows only, and absent when the product names neither cadence.
type BalanceTransactionPlan string

// BalanceTransactionType defines model for BalanceTransaction.Type.
type BalanceTransactionType string

// BalanceTransactionPaginatedResponse defines model for BalanceTransactionPaginatedResponse.
type BalanceTransactionPaginatedResponse struct {
	Items      *[]BalanceTransaction `json:"items,omitempty"`
	Pagination *PaginationInfo       `json:"pagination,omitempty"`
}

// ChannelLinkResponse defines model for ChannelLinkResponse.
type ChannelLinkResponse struct {
	// Code One-time link code (e.g. "RUMI-7K3M2X")
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`

	// WaLink wa.me deep link that pre-fills the code
	WaLink string `json:"waLink"`
}

// ChannelUpdateRequest defines model for ChannelUpdateRequest.
type ChannelUpdateRequest struct {
	// ReplyMode How Rumi answers ("text", "audio", or "auto")
	ReplyMode *ChannelUpdateRequestReplyMode `json:"replyMode,omitempty"`
}

// ChannelUpdateRequestReplyMode How Rumi answers ("text", "audio", or "auto")
type ChannelUpdateRequestReplyMode string

// Commitment defines model for Commitment.
type Commitment struct {
	// Date Specific date for one-time commitments (YYYY-MM-DD)
	Date *string `json:"date,omitempty"`

	// Days Days of the week for recurring commitments (1 = Monday, 2 = Tuesday, ..., 7 = Sunday)
	Days *[]int `json:"days,omitempty"`

	// EndedAt When a recurring commitment was ended by the user. It stops generating occurrences from then on, but past ones remain in history. Null while it is still running.
	EndedAt *time.Time `json:"endedAt,omitempty"`
	Id      string     `json:"id"`

	// NextDate Next occurrence of this commitment (YYYY-MM-DD, user's timezone): the next matching weekday for recurring, the date for one-time (past when overdue). Present on the /commitments list, absent in history mode.
	NextDate *string `json:"nextDate,omitempty"`

	// OccurrenceDate The day this entry refers to (YYYY-MM-DD, user's timezone). Only present with history=true, where each entry is ONE past occurrence rather than the commitment as a whole — a recurring commitment yields one entry per scheduled day. Together with id it uniquely keys a history row.
	OccurrenceDate *string `json:"occurrenceDate,omitempty"`

	// Origin Where the commitment came from: 'plan' (created by a coaching session as part of the commitment plan), 'manual' (added by the user), or 'behavior' (projected from a behavior plan).
	Origin CommitmentOrigin `json:"origin"`

	// Status In the normal list: pending, completed or overdue for the commitment as a whole. In history mode it describes that single past occurrence — 'completed' if it was done that day, 'missed' if it was not.
	Status CommitmentStatus `json:"status"`
	Title  string           `json:"title"`
	Type   CommitmentType   `json:"type"`
}

// CommitmentOrigin Where the commitment came from: 'plan' (created by a coaching session as part of the commitment plan), 'manual' (added by the user), or 'behavior' (projected from a behavior plan).
type CommitmentOrigin string

// CommitmentStatus In the normal list: pending, completed or overdue for the commitment as a whole. In history mode it describes that single past occurrence — 'completed' if it was done that day, 'missed' if it was not.
type CommitmentStatus string

// CommitmentType defines model for Commitment.Type.
type CommitmentType string

// CommunicationSession defines model for CommunicationSession.
type CommunicationSession struct {
	Duration *int    `json:"duration,omitempty"`
	Id       *string `json:"id,omitempty"`

	// Recap Short user-facing summary (2-3 sentences) of what the session covered and what the user took from it, in their language. Generated after the session ends, so it is absent for sessions still in progress, for very short ones, and always for the onboarding intro.
	Recap *string `json:"recap,omitempty"`

	// RecapTitle A few words naming what the session was about, in the user's language. Use it as the row heading in the sessions list; fall back to the session-type label when absent.
	RecapTitle         *string    `json:"recapTitle,omitempty"`
	SessionType        *string    `json:"sessionType,omitempty"`
	StartTime          *time.Time `json:"startTime,omitempty"`
	UserEvaluation     *float32   `json:"userEvaluation,omitempty"`
	UserFeedback       *string    `json:"userFeedback,omitempty"`
	UserSessionInsight *string    `json:"userSessionInsight,omitempty"`
}

// CommunicationSessionAdmin defines model for CommunicationSessionAdmin.
type CommunicationSessionAdmin struct {
	AiEvaluation       *float32   `json:"aiEvaluation,omitempty"`
	AiNotes            *string    `json:"aiNotes,omitempty"`
	EndTime            *time.Time `json:"endTime,omitempty"`
	Id                 *string    `json:"id,omitempty"`
	InputAudioTokens   *int       `json:"inputAudioTokens,omitempty"`
	InputTextTokens    *int       `json:"inputTextTokens,omitempty"`
	Language           *string    `json:"language,omitempty"`
	OutputAudioTokens  *int       `json:"outputAudioTokens,omitempty"`
	OutputTextTokens   *int       `json:"outputTextTokens,omitempty"`
	SessionType        *string    `json:"sessionType,omitempty"`
	StartTime          *time.Time `json:"startTime,omitempty"`
	TotalCostUsd       *float32   `json:"totalCostUsd,omitempty"`
	UserCountry        *string    `json:"userCountry,omitempty"`
	UserEvaluation     *float32   `json:"userEvaluation,omitempty"`
	UserFeedback       *string    `json:"userFeedback,omitempty"`
	UserId             *string    `json:"userId,omitempty"`
	UserLanguage       *string    `json:"userLanguage,omitempty"`
	UserName           *string    `json:"userName,omitempty"`
	UserSessionInsight *string    `json:"userSessionInsight,omitempty"`
}

// CommunicationSessionPaginatedResponse defines model for CommunicationSessionPaginatedResponse.
type CommunicationSessionPaginatedResponse struct {
	Items      *[]CommunicationSessionAdmin `json:"items,omitempty"`
	Pagination *PaginationInfo              `json:"pagination,omitempty"`
}

// CreateCommitmentRequest defines model for CreateCommitmentRequest.
type CreateCommitmentRequest struct {
	// Date Specific date for one-time commitments (YYYY-MM-DD)
	Date *string `json:"date,omitempty"`

	// Days Days of the week for recurring commitments (1 = Monday, ..., 7 = Sunday)
	Days *[]int `json:"days,omitempty"`

	// EndDate The day a recurring commitment stops (YYYY-MM-DD, user's timezone). Coaching sessions set this when the habit is agreed, so it has a horizon to complete rather than running forever. Ignored for one-time commitments — their own date is their end.
	EndDate *string                     `json:"endDate,omitempty"`
	Title   string                      `json:"title"`
	Type    CreateCommitmentRequestType `json:"type"`
}

// CreateCommitmentRequestType defines model for CreateCommitmentRequest.Type.
type CreateCommitmentRequestType string

// EisenhowerMatrixData defines model for EisenhowerMatrixData.
type EisenhowerMatrixData struct {
	NotUrgentImportant    *[]EisenhowerMatrixTask `json:"not_urgent_important,omitempty"`
	NotUrgentNotImportant *[]EisenhowerMatrixTask `json:"not_urgent_not_important,omitempty"`
	UrgentImportant       *[]EisenhowerMatrixTask `json:"urgent_important,omitempty"`
	UrgentNotImportant    *[]EisenhowerMatrixTask `json:"urgent_not_important,omitempty"`
}

// EisenhowerMatrixExercise defines model for EisenhowerMatrixExercise.
type EisenhowerMatrixExercise struct {
	CreatedAt *time.Time            `json:"createdAt,omitempty"`
	Data      *EisenhowerMatrixData `json:"data,omitempty"`
	Id        *string               `json:"id,omitempty"`
	SessionId *string               `json:"sessionId,omitempty"`
	UserId    *string               `json:"userId,omitempty"`
}

// EisenhowerMatrixPaginatedResponse defines model for EisenhowerMatrixPaginatedResponse.
type EisenhowerMatrixPaginatedResponse struct {
	Items      *[]EisenhowerMatrixExercise `json:"items,omitempty"`
	Pagination *PaginationInfo             `json:"pagination,omitempty"`
}

// EisenhowerMatrixTask defines model for EisenhowerMatrixTask.
type EisenhowerMatrixTask struct {
	Quadrant  *string `json:"quadrant,omitempty"`
	Reasoning *string `json:"reasoning,omitempty"`
	Task      *string `json:"task,omitempty"`
}

// FCMTokenRequest defines model for FCMTokenRequest.
type FCMTokenRequest struct {
	Platform *string `json:"platform,omitempty"`
	Token    string  `json:"token"`
}

// FeedbackContext Diagnostics gathered by the client. Every field is optional — send whatever the platform can tell you. A bug report without a version and a screen name costs a round trip to the user before anyone can act on it, which is usually a report lost.
type FeedbackContext struct {
	// AppVersion e.g. "1.4.2"
	AppVersion  *string `json:"appVersion,omitempty"`
	BuildNumber *string `json:"buildNumber,omitempty"`

	// DeviceModel e.g. "iPhone15,3". Mobile only.
	DeviceModel *string `json:"deviceModel,omitempty"`

	// Locale The app's active language, which is not always the device's.
	Locale *string `json:"locale,omitempty"`

	// OsVersion e.g. "iOS 17.2", "Android 14", or the browser and version on web.
	OsVersion *string `json:"osVersion,omitempty"`

	// Screen Where the user was when they opened the form, e.g. "(tabs)/growth".
	Screen *string `json:"screen,omitempty"`

	// ScreenSize e.g. "393x852". Layout bugs are unreproducible without it.
	ScreenSize *string `json:"screenSize,omitempty"`

	// Timezone IANA name, so timestamps in the report can be read in the user's own day.
	Timezone *string `json:"timezone,omitempty"`

	// UserAgent Web only.
	UserAgent *string `json:"userAgent,omitempty"`
}

// FeedbackRequest defines model for FeedbackRequest.
type FeedbackRequest struct {
	Category FeedbackRequestCategory `json:"category"`

	// Context Diagnostics gathered by the client. Every field is optional — send whatever the platform can tell you. A bug report without a version and a screen name costs a round trip to the user before anyone can act on it, which is usually a report lost.
	Context *FeedbackContext `json:"context,omitempty"`

	// Description The user's own words. Truncated past 8000 characters rather than rejected.
	Description string    `json:"description"`
	Images      *[]string `json:"images,omitempty"`
}

// FeedbackRequestCategory defines model for FeedbackRequest.Category.
type FeedbackRequestCategory string

// FeedbackResponse defines model for FeedbackResponse.
type FeedbackResponse struct {
	Id *string `json:"id,omitempty"`
}

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	AccessToken *string `json:"accessToken,omitempty"`
	IdToken     *string `json:"idToken,omitempty"`
}

// Integration defines model for Integration.
type Integration struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// MaskedExternalId Masked phone/chat id (e.g. "+3519•••••78"), only set when linked
	MaskedExternalId *string `json:"maskedExternalId,omitempty"`

	// Provider Channel provider ("whatsapp")
	Provider string `json:"provider"`

	// ReplyMode How Rumi answers ("text", "audio", or "auto")
	ReplyMode IntegrationReplyMode `json:"replyMode"`

	// Status Binding status ("pending", "active", "revoked")
	Status string `json:"status"`
}

// IntegrationReplyMode How Rumi answers ("text", "audio", or "auto")
type IntegrationReplyMode string

// JourneySessionResponse defines model for JourneySessionResponse.
type JourneySessionResponse struct {
	// FocusArea The user's Current Focus — the Wheel of Life area being prioritized (chosen during onboarding), in the user's language.
	FocusArea *string                     `json:"focusArea,omitempty"`
	Mode      *JourneySessionResponseMode `json:"mode,omitempty"`

	// NextSession The next deep session on the user's growth journey and when it becomes available, so the app can preview the upcoming chapter.
	NextSession *SessionInfo `json:"nextSession,omitempty"`
	Quote       *Quote       `json:"quote,omitempty"`
	Session     *SessionType `json:"session,omitempty"`

	// Sessions List of upcoming deep sessions on the user's growth journey and their estimated availability dates.
	Sessions *[]SessionInfo `json:"sessions,omitempty"`

	// Theme Visual theme override picked by the AI at the end of the last session. Only present while that override is active — absent when the user's own theme choice (on /me, PATCH /me clears the override) should stand. Clients must not change the theme when this is absent.
	Theme *string `json:"theme,omitempty"`
}

// JourneySessionResponseMode defines model for JourneySessionResponse.Mode.
type JourneySessionResponseMode string

// LeadAdmin defines model for LeadAdmin.
type LeadAdmin struct {
	Company   *string    `json:"company,omitempty"`
	Country   *string    `json:"country,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Language  *string    `json:"language,omitempty"`
	Message   *string    `json:"message,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Origin    *string    `json:"origin,omitempty"`
	Phone     *string    `json:"phone,omitempty"`
	Size      *string    `json:"size,omitempty"`
	State     *string    `json:"state,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// LeadListResponse defines model for LeadListResponse.
type LeadListResponse struct {
	Items      *[]LeadAdmin    `json:"items,omitempty"`
	Pagination *PaginationInfo `json:"pagination,omitempty"`
}

// LeadRequest defines model for LeadRequest.
type LeadRequest struct {
	Company  string  `json:"company"`
	Country  string  `json:"country"`
	Email    string  `json:"email"`
	Language *string `json:"language,omitempty"`
	Message  *string `json:"message,omitempty"`
	Name     string  `json:"name"`
	Origin   *string `json:"origin,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Size     string  `json:"size"`
}

// LinkAppleRequest defines model for LinkAppleRequest.
type LinkAppleRequest struct {
	// IdentityToken JWT identity token from ASAuthorizationAppleIDCredential.
	IdentityToken string `json:"identityToken"`
}

// LoginWithCodeRequest defines model for LoginWithCodeRequest.
type LoginWithCodeRequest struct {
	Code       string                   `json:"code"`
	Identifier string                   `json:"identifier"`
	Type       LoginWithCodeRequestType `json:"type"`
}

// LoginWithCodeRequestType defines model for LoginWithCodeRequest.Type.
type LoginWithCodeRequestType string

// Memory defines model for Memory.
type Memory struct {
	Category  *MemoryCategory `json:"category,omitempty"`
	Content   *string         `json:"content,omitempty"`
	CreatedAt *time.Time      `json:"createdAt,omitempty"`
	Id        *string         `json:"id,omitempty"`
	UserId    *string         `json:"userId,omitempty"`
}

// MemoryCategory defines model for MemoryCategory.
type MemoryCategory string

// MemoryPaginatedResponse defines model for MemoryPaginatedResponse.
type MemoryPaginatedResponse struct {
	Items      *[]Memory       `json:"items,omitempty"`
	Pagination *PaginationInfo `json:"pagination,omitempty"`
}

// PaginationInfo defines model for PaginationInfo.
type PaginationInfo struct {
	CurrentPage  *int `json:"currentPage,omitempty"`
	ItemsPerPage *int `json:"itemsPerPage,omitempty"`
	TotalItems   *int `json:"totalItems,omitempty"`
	TotalPages   *int `json:"totalPages,omitempty"`
}

// ProfileBadge defines model for ProfileBadge.
type ProfileBadge struct {
	EarnedAt *time.Time `json:"earnedAt,omitempty"`

	// Type Profile badges v2. The app renders these in this order as a 3x5 grid. Rows in user_badges may still carry the retired goalReached type (granted on behaviour-plan graduation) — kept for analytics; the app ignores types it does not recognize.
	Type *BadgeType `json:"type,omitempty"`
}

// ProfileBalance defines model for ProfileBalance.
type ProfileBalance struct {
	CompletedAt *openapi_types.Date `json:"completedAt,omitempty"`

	// Data JSON array of WheelOfLifeItem
	Data *string `json:"data,omitempty"`
}

// ProfileProgress defines model for ProfileProgress.
type ProfileProgress struct {
	BestStreak         *int     `json:"bestStreak,omitempty"`
	CommitmentsKept    *int     `json:"commitmentsKept,omitempty"`
	CurrentStreak      *int     `json:"currentStreak,omitempty"`
	HoursWithRumi      *float32 `json:"hoursWithRumi,omitempty"`
	InsightsDiscovered *int     `json:"insightsDiscovered,omitempty"`
	TotalSessions      *int     `json:"totalSessions,omitempty"`
}

// ProfileVision defines model for ProfileVision.
type ProfileVision struct {
	CraftedAt *time.Time `json:"craftedAt,omitempty"`
	Text      *string    `json:"text,omitempty"`
}

// Quote defines model for Quote.
type Quote struct {
	Author   *string        `json:"author,omitempty"`
	Category *QuoteCategory `json:"category,omitempty"`
	Id       *string        `json:"id,omitempty"`
	Quote    *string        `json:"quote,omitempty"`
}

// QuoteCategory defines model for QuoteCategory.
type QuoteCategory string

// Recommendation defines model for Recommendation.
type Recommendation struct {
	Author      *string             `json:"author,omitempty"`
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *string             `json:"id,omitempty"`
	SessionId   *string             `json:"sessionId,omitempty"`
	Title       *string             `json:"title,omitempty"`
	Type        *RecommendationType `json:"type,omitempty"`
	Url         *string             `json:"url,omitempty"`
	UserId      *string             `json:"userId,omitempty"`
}

// RecommendationType defines model for Recommendation.Type.
type RecommendationType string

// RecommendationPaginatedResponse defines model for RecommendationPaginatedResponse.
type RecommendationPaginatedResponse struct {
	Items      *[]Recommendation `json:"items,omitempty"`
	Pagination *PaginationInfo   `json:"pagination,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// SSOVerificationRequest defines model for SSOVerificationRequest.
type SSOVerificationRequest struct {
	AccessToken *string                    `json:"accessToken,omitempty"`
	IdToken     *string                    `json:"idToken,omitempty"`
	Type        SSOVerificationRequestType `json:"type"`
}

// SSOVerificationRequestType defines model for SSOVerificationRequest.Type.
type SSOVerificationRequestType string

// SessionInfo The next deep session on the user's growth journey and when it becomes available, so the app can preview the upcoming chapter.
type SessionInfo struct {
	// AvailableAt When the session unlocks. May be in the past, meaning it is available now.
	AvailableAt time.Time   `json:"availableAt"`
	Session     SessionType `json:"session"`
}

// SessionType defines model for SessionType.
type SessionType string

// SetupTestDataRequest defines model for SetupTestDataRequest.
type SetupTestDataRequest struct {
	SessionType SetupTestDataRequestSessionType `json:"sessionType"`
}

// SetupTestDataRequestSessionType defines model for SetupTestDataRequest.SessionType.
type SetupTestDataRequestSessionType string

// StreakResponse defines model for StreakResponse.
type StreakResponse struct {
	Calendar      *[]openapi_types.Date `json:"calendar,omitempty"`
	CurrentStreak *int                  `json:"currentStreak,omitempty"`
	LongestStreak *int                  `json:"longestStreak,omitempty"`
	TotalDays     *int                  `json:"totalDays,omitempty"`
}

// SubmitFeedbackRequest defines model for SubmitFeedbackRequest.
type SubmitFeedbackRequest struct {
	// Evaluation Numeric evaluation rating (decimal, 0 to 10)
	Evaluation float64 `json:"evaluation"`

	// Feedback Written feedback text notes
	Feedback *string `json:"feedback,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`

	// ApiBaseUrl Base URL of the regional API the client must use for all non-auth calls.
	ApiBaseUrl *string `json:"apiBaseUrl,omitempty"`

	// DataRegion The region where this user's data is stored.
	DataRegion   *TokenResponseDataRegion `json:"dataRegion,omitempty"`
	RefreshToken *string                  `json:"refreshToken,omitempty"`
	TokenType    *string                  `json:"tokenType,omitempty"`
}

// TokenResponseDataRegion The region where this user's data is stored.
type TokenResponseDataRegion string

// UpdateCommitmentRequest Partial update. Any provided field is applied; omitted fields are unchanged.
type UpdateCommitmentRequest struct {
	Date *string `json:"date,omitempty"`
	Days *[]int  `json:"days,omitempty"`
	Done *bool   `json:"done,omitempty"`

	// EndDate Set the day a recurring commitment stops (YYYY-MM-DD). Send null to remove the horizon and let it run on.
	EndDate *string                      `json:"endDate,omitempty"`
	Title   *string                      `json:"title,omitempty"`
	Type    *UpdateCommitmentRequestType `json:"type,omitempty"`
}

// UpdateCommitmentRequestType defines model for UpdateCommitmentRequest.Type.
type UpdateCommitmentRequestType string

// UpdateIdentifierRequest defines model for UpdateIdentifierRequest.
type UpdateIdentifierRequest struct {
	Identifier     string                      `json:"identifier"`
	Type           UpdateIdentifierRequestType `json:"type"`
	VerificationId string                      `json:"verificationId"`
}

// UpdateIdentifierRequestType defines model for UpdateIdentifierRequest.Type.
type UpdateIdentifierRequestType string

// UpdateLeadRequest defines model for UpdateLeadRequest.
type UpdateLeadRequest struct {
	State string `json:"state"`
}

// UsageCalendarResponse defines model for UsageCalendarResponse.
type UsageCalendarResponse struct {
	DayStreak *int `json:"dayStreak,omitempty"`
	Days      *map[string]struct {
		Date     *openapi_types.Date            `json:"date,omitempty"`
		Kind     *UsageCalendarResponseDaysKind `json:"kind,omitempty"`
		Sessions *[]CommunicationSession        `json:"sessions,omitempty"`
	} `json:"days,omitempty"`
	Hours         *float32 `json:"hours,omitempty"`
	SessionsCount *int     `json:"sessionsCount,omitempty"`
}

// UsageCalendarResponseDaysKind defines model for UsageCalendarResponse.Days.Kind.
type UsageCalendarResponseDaysKind string

// UsageEntry defines model for UsageEntry.
type UsageEntry struct {
	// Date Day the messages were sent (YYYY-MM-DD in the request timezone) — message entries only
	Date *string `json:"date,omitempty"`

	// Free True when this session was one of the free introductory ones and cost the user nothing. Session entries only. Free sessions are shown rather than hidden so the history accounts for every session the user actually had; they contribute to sessionCount and freeSessionSeconds, never to sessionSeconds.
	Free *bool          `json:"free,omitempty"`
	Kind UsageEntryKind `json:"kind"`

	// MessageCount Charged replies in this day group (message entries only). Proactive nudges, templates and system notices cost the user nothing and are not listed.
	MessageCount *int `json:"messageCount,omitempty"`

	// OccurredAt Session end for sessions; the day's latest message for message groups. Sort key of the feed.
	OccurredAt time.Time `json:"occurredAt"`

	// Seconds How long this entry ran, in seconds (always positive). For a free session this is the real duration even though nothing was charged — see `free`, and note it is therefore NOT always what came off the balance.
	Seconds int64 `json:"seconds"`

	// SessionId Communication session this entry billed (session entries only)
	SessionId *string `json:"sessionId,omitempty"`

	// SessionType Type of the billed session (session entries only)
	SessionType *string `json:"sessionType,omitempty"`
}

// UsageEntryKind defines model for UsageEntry.Kind.
type UsageEntryKind string

// UsageHistoryResponse defines model for UsageHistoryResponse.
type UsageHistoryResponse struct {
	Items      *[]UsageEntry   `json:"items,omitempty"`
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Totals     *UsageTotals    `json:"totals,omitempty"`
}

// UsageTotals defines model for UsageTotals.
type UsageTotals struct {
	// FreeSessionSeconds Seconds spent in free introductory sessions, charged to nobody.
	FreeSessionSeconds *int64 `json:"freeSessionSeconds,omitempty"`

	// MessageCount Total charged replies (not day groups); excludes anything sent unprompted.
	MessageCount   *int   `json:"messageCount,omitempty"`
	MessageSeconds *int64 `json:"messageSeconds,omitempty"`

	// SessionCount Every session in the feed, free ones included.
	SessionCount *int `json:"sessionCount,omitempty"`

	// SessionSeconds Seconds actually charged to the balance; excludes free sessions.
	SessionSeconds *int64 `json:"sessionSeconds,omitempty"`

	// TotalSeconds sessionSeconds + messageSeconds
	TotalSeconds *int64 `json:"totalSeconds,omitempty"`
}

// User defines model for User.
type User struct {
	AiAcceptedAt *time.Time `json:"aiAcceptedAt,omitempty"`

	// BalanceSeconds Remaining voice-session balance in seconds (may be negative). Starting a billable session requires at least 60 seconds — anything below that is refused on the session WebSocket, which sends an INSUFFICIENT_BALANCE error frame and then closes with code 4402.
	BalanceSeconds *int64 `json:"balanceSeconds,omitempty"`

	// ChatHistoryRetentionDays How long the WhatsApp/Telegram conversation is kept, in days; 0 keeps it indefinitely.
	ChatHistoryRetentionDays *int            `json:"chatHistoryRetentionDays,omitempty"`
	CoachGender              *string         `json:"coachGender,omitempty"`
	CoachVoice               *UserCoachVoice `json:"coachVoice,omitempty"`
	Country                  *string         `json:"country,omitempty"`

	// CreatedAt Signup time (for waitlisted users, when they joined the waitlist).
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	DataRegion  *UserDataRegion     `json:"dataRegion,omitempty"`
	DateOfBirth *openapi_types.Date `json:"dateOfBirth,omitempty"`
	Email       *string             `json:"email,omitempty"`

	// FocusArea The Wheel of Life area the user committed to work on (chosen during onboarding), in the user's language.
	FocusArea *string `json:"focusArea,omitempty"`
	Gender    *string `json:"gender,omitempty"`
	Id        *string `json:"id,omitempty"`

	// InFirstJourney True while the user still has free introductory sessions left — the onboarding intro and the Vision session it hands over to — and is therefore exempt from the balance gate. Derived from what those sessions produce: the profile details the intro collects (country, date of birth, gender) and the ideal-life vision the Vision session writes. It stays true while either is still missing, so a session the user abandoned after a few seconds costs them nothing.
	// Informational only. Clients must NOT gate on it: the WebSocket is the enforcement and it now refuses in a form a client can read, so an app that pre-empts the call is keeping a second copy of a billing rule that will drift from this one. The name predates the change of rule and is kept because shipped app builds read it.
	InFirstJourney               *bool      `json:"inFirstJourney,omitempty"`
	IsActive                     *bool      `json:"isActive,omitempty"`
	LastOnlineAt                 *time.Time `json:"lastOnlineAt,omitempty"`
	LastPlatform                 *string    `json:"lastPlatform,omitempty"`
	MarketingAcceptedAt          *time.Time `json:"marketingAcceptedAt,omitempty"`
	Name                         *string    `json:"name,omitempty"`
	PhoneNumber                  *string    `json:"phoneNumber,omitempty"`
	PreferredLanguage            *string    `json:"preferredLanguage,omitempty"`
	Region                       *string    `json:"region,omitempty"`
	TermsAndConditionsAcceptedAt *time.Time `json:"termsAndConditionsAcceptedAt,omitempty"`
	Theme                        *string    `json:"theme,omitempty"`

	// Waitlisted True for a waitlist signup whose regional profile has not been provisioned yet; activating the user provisions it.
	Waitlisted *bool `json:"waitlisted,omitempty"`
}

// UserCoachVoice defines model for User.CoachVoice.
type UserCoachVoice string

// UserDataRegion defines model for User.DataRegion.
type UserDataRegion string

// UserDataExport A full export of all the user's data.
type UserDataExport map[string]interface{}

// UserPaginatedResponse defines model for UserPaginatedResponse.
type UserPaginatedResponse struct {
	Items      *[]User         `json:"items,omitempty"`
	Pagination *PaginationInfo `json:"pagination,omitempty"`
}

// UserProfileResponse defines model for UserProfileResponse.
type UserProfileResponse struct {
	Badges *[]ProfileBadge `json:"badges,omitempty"`

	// FocusArea The user's chosen Focus Area for their coaching journey.
	FocusArea   *string          `json:"focusArea,omitempty"`
	LifeBalance *ProfileBalance  `json:"lifeBalance,omitempty"`
	Progress    *ProfileProgress `json:"progress,omitempty"`
	Vision      *ProfileVision   `json:"vision,omitempty"`
}

// UserSessionPaginatedResponse defines model for UserSessionPaginatedResponse.
type UserSessionPaginatedResponse struct {
	Items      *[]CommunicationSession `json:"items,omitempty"`
	Pagination *PaginationInfo         `json:"pagination,omitempty"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	// AiAccepted Consent to the user's voice being processed by Google's AI. Required to use the app: sessions are the product and they cannot run without it.
	// These three are collected at registration, but not everyone arrives that way. "Continue with Apple" (or Google) on the sign-in screen creates an account without passing through the signup steps, so such a user holds none of them — not even the Terms — and neither do accounts predating a given consent. Those users are asked in the app before their first session and the answers land here, which is why all three are writable and not just the AI one.
	// Write-only and one-way, all three. Only `true` is meaningful: it stamps the matching `*AcceptedAt` with the server's clock, and does so once — a second `true` leaves the original moment intact, because when consent was first given is the auditable fact. `false` is ignored rather than treated as a withdrawal; revoking the required ones means deleting the account, not editing a profile field. The timestamps are returned on the User schema as `termsAndConditionsAcceptedAt`, `marketingAcceptedAt` and `aiAcceptedAt`.
	AiAccepted *bool `json:"aiAccepted,omitempty"`

	// ChatHistoryRetentionDays How long the WhatsApp/Telegram conversation is kept, in days. 0 keeps it indefinitely and is the only value that gives up the guarantee, so the app should say so rather than list it plainly. Changing this rewrites the expiry of the existing conversation, so lowering it takes effect immediately and retroactively. Nothing below 3 days is offered: the coach replays the last 72 hours, and a shorter retention would have it losing the thread mid-exchange.
	ChatHistoryRetentionDays *UserUpdateRequestChatHistoryRetentionDays `json:"chatHistoryRetentionDays,omitempty"`
	CoachGender              *string                                    `json:"coachGender,omitempty"`
	CoachVoice               *UserUpdateRequestCoachVoice               `json:"coachVoice,omitempty"`
	Country                  *string                                    `json:"country,omitempty"`
	DateOfBirth              *openapi_types.Date                        `json:"dateOfBirth,omitempty"`
	Gender                   *string                                    `json:"gender,omitempty"`

	// MarketingAccepted Consent — see aiAccepted for how all three behave. The one optional consent.
	MarketingAccepted *bool   `json:"marketingAccepted,omitempty"`
	Name              *string `json:"name,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
	Region            *string `json:"region,omitempty"`

	// TermsAndConditionsAccepted Consent — see aiAccepted for how all three behave. Required to use the app.
	TermsAndConditionsAccepted *bool   `json:"termsAndConditionsAccepted,omitempty"`
	Theme                      *string `json:"theme,omitempty"`
}

// UserUpdateRequestChatHistoryRetentionDays How long the WhatsApp/Telegram conversation is kept, in days. 0 keeps it indefinitely and is the only value that gives up the guarantee, so the app should say so rather than list it plainly. Changing this rewrites the expiry of the existing conversation, so lowering it takes effect immediately and retroactively. Nothing below 3 days is offered: the coach replays the last 72 hours, and a shorter retention would have it losing the thread mid-exchange.
type UserUpdateRequestChatHistoryRetentionDays int

// UserUpdateRequestCoachVoice defines model for UserUpdateRequest.CoachVoice.
type UserUpdateRequestCoachVoice string

// VerificationCheck defines model for VerificationCheck.
type VerificationCheck struct {
	Code        string                `json:"code"`
	Email       *string               `json:"email,omitempty"`
	PhoneNumber *string               `json:"phoneNumber,omitempty"`
	Type        VerificationCheckType `json:"type"`
}

// VerificationCheckType defines model for VerificationCheck.Type.
type VerificationCheckType string

// VerificationRequest defines model for VerificationRequest.
type VerificationRequest struct {
	Email       *string                 `json:"email,omitempty"`
	Event       *string                 `json:"event,omitempty"`
	PhoneNumber *string                 `json:"phoneNumber,omitempty"`
	Type        VerificationRequestType `json:"type"`
}

// VerificationRequestType defines model for VerificationRequest.Type.
type VerificationRequestType string

// VerificationResponse defines model for VerificationResponse.
type VerificationResponse struct {
	Message        *string `json:"message,omitempty"`
	VerificationId *string `json:"verificationId,omitempty"`
	Verified       *bool   `json:"verified,omitempty"`
}

// WaitlistRequest defines model for WaitlistRequest.
type WaitlistRequest struct {
	AiAccepted *bool `json:"aiAccepted,omitempty"`

	// AppleIdentityToken Sign in with Apple identity token (iOS). Replaces OTP verification.
	AppleIdentityToken *string `json:"appleIdentityToken,omitempty"`
	Country            *string `json:"country,omitempty"`

	// DataRegion Where the user's data will be stored. Chosen by the user at signup.
	DataRegion                 *WaitlistRequestDataRegion `json:"dataRegion,omitempty"`
	DateOfBirth                *openapi_types.Date        `json:"dateOfBirth,omitempty"`
	Email                      *string                    `json:"email,omitempty"`
	EmailVerificationId        *string                    `json:"emailVerificationId,omitempty"`
	Gender                     *string                    `json:"gender,omitempty"`
	GoogleAccessToken          *string                    `json:"googleAccessToken,omitempty"`
	GoogleIdToken              *string                    `json:"googleIdToken,omitempty"`
	MarketingAccepted          *bool                      `json:"marketingAccepted,omitempty"`
	Name                       string                     `json:"name"`
	PhoneNumber                *string                    `json:"phoneNumber,omitempty"`
	PhoneVerificationId        *string                    `json:"phoneVerificationId,omitempty"`
	PreferredLanguage          *string                    `json:"preferredLanguage,omitempty"`
	Region                     *string                    `json:"region,omitempty"`
	TermsAndConditionsAccepted *bool                      `json:"termsAndConditionsAccepted,omitempty"`
}

// WaitlistRequestDataRegion Where the user's data will be stored. Chosen by the user at signup.
type WaitlistRequestDataRegion string

// WheelOfLifeExercise defines model for WheelOfLifeExercise.
type WheelOfLifeExercise struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Data      *[]WheelOfLifeItem `json:"data,omitempty"`
	Id        *string            `json:"id,omitempty"`
	SessionId *string            `json:"sessionId,omitempty"`
	UpdatedAt *time.Time         `json:"updatedAt,omitempty"`
	UserId    *string            `json:"userId,omitempty"`
}

// WheelOfLifeItem defines model for WheelOfLifeItem.
type WheelOfLifeItem struct {
	CurrentScore *float32 `json:"currentScore,omitempty"`
	Name         *string  `json:"name,omitempty"`
	Reasoning    *string  `json:"reasoning,omitempty"`
}

// WheelOfLifePaginatedResponse defines model for WheelOfLifePaginatedResponse.
type WheelOfLifePaginatedResponse struct {
	Items      *[]WheelOfLifeExercise `json:"items,omitempty"`
	Pagination *PaginationInfo        `json:"pagination,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetAdminDashboardParams defines parameters for GetAdminDashboard.
type GetAdminDashboardParams struct {
	// From Scope session-based metrics to sessions started at or after this time (RFC3339).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Scope session-based metrics to sessions started at or before this time (RFC3339).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// AdminListLeadsParams defines parameters for AdminListLeads.
type AdminListLeadsParams struct {
	Page      *int                `form:"page,omitempty" json:"page,omitempty"`
	State     *string             `form:"state,omitempty" json:"state,omitempty"`
	Search    *string             `form:"search,omitempty" json:"search,omitempty"`
	Country   *string             `form:"country,omitempty" json:"country,omitempty"`
	Language  *string             `form:"language,omitempty" json:"language,omitempty"`
	Size      *string             `form:"size,omitempty" json:"size,omitempty"`
	StartDate *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetAdminSessionsParams defines parameters for GetAdminSessions.
type GetAdminSessionsParams struct {
	Page         *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit        *int    `form:"limit,omitempty" json:"limit,omitempty"`
	UserId       *string `form:"userId,omitempty" json:"userId,omitempty"`
	UserName     *string `form:"userName,omitempty" json:"userName,omitempty"`
	UserCountry  *string `form:"userCountry,omitempty" json:"userCountry,omitempty"`
	UserLanguage *string `form:"userLanguage,omitempty" json:"userLanguage,omitempty"`
}

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Page              *int                `form:"page,omitempty" json:"page,omitempty"`
	Limit             *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Name              *string             `form:"name,omitempty" json:"name,omitempty"`
	Country           *string             `form:"country,omitempty" json:"country,omitempty"`
	PreferredLanguage *string             `form:"preferredLanguage,omitempty" json:"preferredLanguage,omitempty"`
	IsActive          *bool               `form:"isActive,omitempty" json:"isActive,omitempty"`
	CreatedAt         *openapi_types.Date `form:"createdAt,omitempty" json:"createdAt,omitempty"`

	// Waitlisted true returns only pending waitlist signups; false only provisioned users; omitted returns both (waitlist first).
	Waitlisted *bool `form:"waitlisted,omitempty" json:"waitlisted,omitempty"`
}

// GetCommitmentsParams defines parameters for GetCommitments.
type GetCommitmentsParams struct {
	// History If true, returns all commitments (past and future), sorted by created date descending.
	History *bool `form:"history,omitempty" json:"history,omitempty"`
}

// GetEisenhowerMatrixParams defines parameters for GetEisenhowerMatrix.
type GetEisenhowerMatrixParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteCurrentUserDataParams defines parameters for DeleteCurrentUserData.
type DeleteCurrentUserDataParams struct {
	// Scope Comma-separated categories to erase. Omit for `all`. `memories` drops saved memories; `chat` drops the WhatsApp/Telegram conversation but keeps the connection; `commitments` drops commitments and their habit plans; `progress` drops session history, and with it the streak and the growth journey; `all` covers everything. Combining `all` with others is the same as `all`. An unrecognized value is rejected.
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetTransactionsParams defines parameters for GetTransactions.
type GetTransactionsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Grouped Collapse same-day runs of message_usage debits into one row per run.
	Grouped *bool `form:"grouped,omitempty" json:"grouped,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetMemoriesParams defines parameters for GetMemories.
type GetMemoriesParams struct {
	Page     *int            `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int            `form:"limit,omitempty" json:"limit,omitempty"`
	Category *MemoryCategory `form:"category,omitempty" json:"category,omitempty"`
	Text     *string         `form:"text,omitempty" json:"text,omitempty"`
}

// GetRandomQuoteParams defines parameters for GetRandomQuote.
type GetRandomQuoteParams struct {
	Category *QuoteCategory `form:"category,omitempty" json:"category,omitempty"`
}

// GetRecommendationsParams defines parameters for GetRecommendations.
type GetRecommendationsParams struct {
	Page  *int                          `form:"page,omitempty" json:"page,omitempty"`
	Limit *int                          `form:"limit,omitempty" json:"limit,omitempty"`
	Type  *GetRecommendationsParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// GetRecommendationsParamsType defines parameters for GetRecommendations.
type GetRecommendationsParamsType string

// GetSessionsParams defines parameters for GetSessions.
type GetSessionsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsageCalendarParams defines parameters for GetUsageCalendar.
type GetUsageCalendarParams struct {
	Month string `form:"month" json:"month"`
}

// GetWheelOfLifeParams defines parameters for GetWheelOfLife.
type GetWheelOfLifeParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminUpdateLeadJSONRequestBody defines body for AdminUpdateLead for application/json ContentType.
type AdminUpdateLeadJSONRequestBody = UpdateLeadRequest

// SetupTestDataJSONRequestBody defines body for SetupTestData for application/json ContentType.
type SetupTestDataJSONRequestBody = SetupTestDataRequest

// PatchAdminUsersIdJSONRequestBody defines body for PatchAdminUsersId for application/json ContentType.
type PatchAdminUsersIdJSONRequestBody = AdminUserPatchRequest

// PostAdminUsersIdCreditsJSONRequestBody defines body for PostAdminUsersIdCredits for application/json ContentType.
type PostAdminUsersIdCreditsJSONRequestBody = AdminCreditRequest

// AppleLoginJSONRequestBody defines body for AppleLogin for application/json ContentType.
type AppleLoginJSONRequestBody = AppleLoginRequest

// GoogleLoginJSONRequestBody defines body for GoogleLogin for application/json ContentType.
type GoogleLoginJSONRequestBody = GoogleLoginRequest

// LoginWithCodeJSONRequestBody defines body for LoginWithCode for application/json ContentType.
type LoginWithCodeJSONRequestBody = LoginWithCodeRequest

// UpdateIdentifierJSONRequestBody defines body for UpdateIdentifier for application/json ContentType.
type UpdateIdentifierJSONRequestBody = UpdateIdentifierRequest

// LinkAppleAccountJSONRequestBody defines body for LinkAppleAccount for application/json ContentType.
type LinkAppleAccountJSONRequestBody = LinkAppleRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = WaitlistRequest

// RequestVerificationJSONRequestBody defines body for RequestVerification for application/json ContentType.
type RequestVerificationJSONRequestBody = VerificationRequest

// VerifySSOJSONRequestBody defines body for VerifySSO for application/json ContentType.
type VerifySSOJSONRequestBody = SSOVerificationRequest

// VerifyCodeJSONRequestBody defines body for VerifyCode for application/json ContentType.
type VerifyCodeJSONRequestBody = VerificationCheck

// SubmitSessionFeedbackJSONRequestBody defines body for SubmitSessionFeedback for application/json ContentType.
type SubmitSessionFeedbackJSONRequestBody = SubmitFeedbackRequest

// CreateCommitmentJSONRequestBody defines body for CreateCommitment for application/json ContentType.
type CreateCommitmentJSONRequestBody = CreateCommitmentRequest

// UpdateCommitmentJSONRequestBody defines body for UpdateCommitment for application/json ContentType.
type UpdateCommitmentJSONRequestBody = UpdateCommitmentRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = FeedbackRequest

// PostLeadsJSONRequestBody defines body for PostLeads for application/json ContentType.
type PostLeadsJSONRequestBody = LeadRequest

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UserUpdateRequest

// RegisterFCMTokenJSONRequestBody defines body for RegisterFCMToken for application/json ContentType.
type RegisterFCMTokenJSONRequestBody = FCMTokenRequest

// UpdateIntegrationJSONRequestBody defines body for UpdateIntegration for application/json ContentType.
type UpdateIntegrationJSONRequestBody = ChannelUpdateRequest

// JoinWaitlistJSONRequestBody defines body for JoinWaitlist for application/json ContentType.
type JoinWaitlistJSONRequestBody = WaitlistRequest
