package quote

var growthQuotes = []QuoteData{
	{
		ID:       "growth-1",
		Author:   ptr("James Cash Penney"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Growth is never by mere chance; it is the result of forces working together.",
			"en-GB": "Growth is never by mere chance; it is the result of forces working together.",
			"pt-PT": "O crescimento nunca acontece por mero acaso; é o resultado de forças a trabalhar em conjunto.",
			"pt-BR": "O crescimento nunca acontece por mero acaso; é o resultado de forças trabalhando em conjunto.",
			"es":    "El crecimiento nunca es por pura casualidad; es el resultado de fuerzas que trabajan juntas.",
			"fr":    "La croissance n'est jamais le fruit du hasard ; elle est le résultat de forces travaillant ensemble.",
			"de":    "Wachstum geschieht nie durch bloßen Zufall; es ist das Ergebnis von Kräften, die zusammenwirken.",
			"it":    "La crescita non avviene mai per caso; è il risultato di forze che lavorano insieme.",
			"ja":    "成長は決して偶然には起こらない。それは力が結集して生まれる結果である。",
			"zh":    "成长从来不是偶然，而是各种力量共同作用的结果。",
			"ko":    "성장은 결코 우연이 아니다. 여러 힘이 함께 작용한 결과다.",
			"hi":    "विकास कभी संयोग से नहीं होता; यह मिलकर काम करने वाली शक्तियों का परिणाम है।",
			"pl":    "Rozwój nigdy nie jest dziełem przypadku; to rezultat sił działających razem.",
			"tr":    "Büyüme asla tesadüf değildir; birlikte çalışan güçlerin sonucudur.",
			"uk":    "Зростання ніколи не буває випадковим; це результат сил, що діють разом.",
			"sv":    "Växande sker aldrig av en slump; det är resultatet av krafter som samverkar.",
			"nl":    "Groei is nooit louter toeval; het is het resultaat van krachten die samenwerken.",
			"nb":    "Vekst skjer aldri ved ren tilfeldighet; den er resultatet av krefter som virker sammen.",
			"da":    "Vækst sker aldrig ved et rent tilfælde; den er resultatet af kræfter, der arbejder sammen.",
			"fi":    "Kasvu ei koskaan tapahdu sattumalta; se on yhdessä vaikuttavien voimien tulos.",
		},
	},
	{
		ID:       "growth-2",
		Author:   ptr("Peter Drucker"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "The best way to predict the future is to create it.",
			"en-GB": "The best way to predict the future is to create it.",
			"pt-PT": "A melhor forma de prever o futuro é criá-lo.",
			"pt-BR": "A melhor maneira de prever o futuro é criá-lo.",
			"es":    "La mejor forma de predecir el futuro es crearlo.",
			"fr":    "La meilleure façon de prédire l'avenir est de le créer.",
			"de":    "Der beste Weg, die Zukunft vorherzusagen, ist, sie zu gestalten.",
			"it":    "Il modo migliore per predire il futuro è crearlo.",
			"ja":    "未来を予測する最善の方法は、自らそれを創り出すことだ。",
			"zh":    "预测未来的最好方式，就是去创造未来。",
			"ko":    "미래를 예측하는 가장 좋은 방법은 미래를 만드는 것이다.",
			"hi":    "भविष्य की भविष्यवाणी करने का सबसे अच्छा तरीक़ा है उसे रचना।",
			"pl":    "Najlepszym sposobem przewidzenia przyszłości jest jej stworzenie.",
			"tr":    "Geleceği öngörmenin en iyi yolu onu yaratmaktır.",
			"uk":    "Найкращий спосіб передбачити майбутнє — створити його.",
			"sv":    "Det bästa sättet att förutsäga framtiden är att skapa den.",
			"nl":    "De beste manier om de toekomst te voorspellen is haar te creëren.",
			"nb":    "Den beste måten å forutsi fremtiden på er å skape den.",
			"da":    "Den bedste måde at forudsige fremtiden på er at skabe den.",
			"fi":    "Paras tapa ennustaa tulevaisuutta on luoda se.",
		},
	},
	{
		ID:       "growth-3",
		Author:   ptr("Zig Ziglar"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "What you get by achieving your goals is not as important as what you become by achieving your goals.",
			"en-GB": "What you get by achieving your goals is not as important as what you become by achieving your goals.",
			"pt-PT": "O que ganhas ao atingir os teus objetivos não é tão importante como aquilo em que te tornas ao atingi-los.",
			"pt-BR": "O que você ganha ao atingir seus objetivos não é tão importante quanto o que você se torna ao atingi-los.",
			"es":    "Lo que obtienes al lograr tus metas no es tan importante como lo que te conviertes al lograrlas.",
			"fr":    "Ce que vous obtenez en atteignant vos objectifs n'est pas aussi important que ce que vous devenez en les atteignant.",
			"de":    "Was du durch das Erreichen deiner Ziele bekommst, ist nicht so wichtig wie das, was du dabei wirst.",
			"it":    "Ciò che ottieni raggiungendo i tuoi obiettivi non è importante quanto ciò che diventi raggiungendoli.",
			"ja":    "目標を達成して得るものより、達成する過程でどんな人間になるかの方が大切だ。",
			"zh":    "实现目标所得到的，远不如你在实现目标的过程中成为怎样的人重要。",
			"ko":    "목표를 이루어 얻는 것보다, 목표를 이루며 어떤 사람이 되는가가 더 중요하다.",
			"hi":    "लक्ष्य पाकर जो मिलता है, वह उतना महत्वपूर्ण नहीं जितना कि लक्ष्य पाने की प्रक्रिया में आप जो बन जाते हैं।",
			"pl":    "To, co zyskujesz, osiągając swoje cele, nie jest tak ważne jak to, kim się stajesz, osiągając je.",
			"tr":    "Hedeflerine ulaşarak elde ettiklerin, onlara ulaşırken dönüştüğün kişi kadar önemli değildir.",
			"uk":    "Те, що ти отримуєш, досягаючи цілей, не так важливо, як те, ким ти стаєш, досягаючи їх.",
			"sv":    "Vad du får genom att nå dina mål är inte lika viktigt som vad du blir genom att nå dem.",
			"nl":    "Wat je krijgt door je doelen te bereiken is niet zo belangrijk als wat je wordt door ze te bereiken.",
			"nb":    "Det du får ved å nå målene dine, er ikke like viktig som det du blir ved å nå dem.",
			"da":    "Det, du får ved at nå dine mål, er ikke så vigtigt som det, du bliver ved at nå dem.",
			"fi":    "Se mitä saat saavuttamalla tavoitteesi ei ole yhtä tärkeää kuin se, millaiseksi kasvat niitä saavuttaessasi.",
		},
	},
	{
		ID:       "growth-4",
		Author:   ptr("Jim Rohn"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Your life does not get better by chance, it gets better by change.",
			"en-GB": "Your life does not get better by chance, it gets better by change.",
			"pt-PT": "A tua vida não melhora por acaso, melhora através da mudança.",
			"pt-BR": "Sua vida não melhora por acaso, melhora através da mudança.",
			"es":    "Tu vida no mejora por casualidad, mejora por el cambio.",
			"fr":    "Votre vie ne s'améliore pas par hasard, elle s'améliore par le changement.",
			"de":    "Dein Leben wird nicht durch Zufall besser, sondern durch Veränderung.",
			"it":    "La tua vita non migliora per caso, migliora con il cambiamento.",
			"ja":    "人生は偶然によって良くなるのではない。変化によって良くなるのだ。",
			"zh":    "生活不会因偶然而变好，只会因改变而变好。",
			"ko":    "삶은 우연히 나아지지 않는다. 변화를 통해 나아진다.",
			"hi":    "आपका जीवन संयोग से बेहतर नहीं होता, बदलाव से बेहतर होता है।",
			"pl":    "Twoje życie nie staje się lepsze przez przypadek, staje się lepsze przez zmianę.",
			"tr":    "Hayatın şansla değil, değişimle güzelleşir.",
			"uk":    "Життя стає кращим не завдяки випадку, а завдяки змінам.",
			"sv":    "Ditt liv blir inte bättre av en slump, det blir bättre genom förändring.",
			"nl":    "Je leven wordt niet beter door toeval, maar door verandering.",
			"nb":    "Livet ditt blir ikke bedre ved tilfeldighet, det blir bedre ved forandring.",
			"da":    "Dit liv bliver ikke bedre ved et tilfælde, det bliver bedre ved forandring.",
			"fi":    "Elämäsi ei parane sattumalta, se paranee muutoksen kautta.",
		},
	},
	{
		ID:       "growth-5",
		Author:   ptr("Mahatma Gandhi"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Be the change that you wish to see in the world.",
			"en-GB": "Be the change that you wish to see in the world.",
			"pt-PT": "Sê a mudança que desejas ver no mundo.",
			"pt-BR": "Seja a mudança que você deseja ver no mundo.",
			"es":    "Sé el cambio que deseas ver en el mundo.",
			"fr":    "Soyez le changement que vous voulez voir dans le monde.",
			"de":    "Sei du selbst die Veränderung, die du dir für die Welt wünschst.",
			"it":    "Sii il cambiamento che vuoi vedere nel mondo.",
			"ja":    "世界に望む変化に、あなた自身がなりなさい。",
			"zh":    "欲变世界，先变其身。",
			"ko":    "세상에서 보고 싶은 변화가 있다면, 스스로 그 변화가 되어라.",
			"hi":    "वह बदलाव ख़ुद बनो जो तुम दुनिया में देखना चाहते हो।",
			"pl":    "Bądź zmianą, którą pragniesz ujrzeć w świecie.",
			"tr":    "Dünyada görmek istediğin değişimin kendisi ol.",
			"uk":    "Будь тією зміною, яку хочеш бачити у світі.",
			"sv":    "Var den förändring du vill se i världen.",
			"nl":    "Wees zelf de verandering die je in de wereld wilt zien.",
			"nb":    "Vær den forandringen du ønsker å se i verden.",
			"da":    "Vær selv den forandring, du ønsker at se i verden.",
			"fi":    "Ole itse se muutos, jonka haluat nähdä maailmassa.",
		},
	},
	{
		ID:       "growth-6",
		Author:   ptr("Carol Dweck"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Becoming is better than being.",
			"en-GB": "Becoming is better than being.",
			"pt-PT": "Tornar-se é melhor do que ser.",
			"pt-BR": "Tornar-se é melhor do que ser.",
			"es":    "Llegar a ser es melhor que ser.",
			"fr":    "Devenir est mieux qu'être.",
			"de":    "Werden ist besser als Sein.",
			"it":    "Divenire è meglio che essere.",
			"ja":    "「なりつつある」ことは「である」ことに勝る。",
			"zh":    "成长中胜于已定型。",
			"ko":    "되어 가는 것이 머물러 있는 것보다 낫다.",
			"hi":    "बनते रहना, बने रहने से बेहतर है।",
			"pl":    "Stawanie się jest lepsze niż bycie.",
			"tr":    "Olmakta olmak, olmuş olmaktan iyidir.",
			"uk":    "Ставати кращим важливіше, ніж бути.",
			"sv":    "Att bli är bättre än att vara.",
			"nl":    "Worden is beter dan zijn.",
			"nb":    "Å bli er bedre enn å være.",
			"da":    "At blive er bedre end at være.",
			"fi":    "Tuleminen on parempaa kuin oleminen.",
		},
	},
	{
		ID:       "growth-7",
		Author:   ptr("Lao Tzu"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "A journey of a thousand miles begins with a single step.",
			"en-GB": "A journey of a thousand miles begins with a single step.",
			"pt-PT": "Uma jornada de mil milhas começa com um único passo.",
			"pt-BR": "Uma jornada de mil milhas começa com um único passo.",
			"es":    "Un viaje de mil millas comienza con un solo paso.",
			"fr":    "Un voyage de mille lieues commence par un seul pas.",
			"de":    "Eine Reise von tausend Meilen beginnt mit einem einzigen Schritt.",
			"it":    "Un viaggio di mille miglia comincia con un solo passo.",
			"ja":    "千里の道も一歩から。",
			"zh":    "千里之行，始于足下。",
			"ko":    "천 리 길도 한 걸음부터 시작된다.",
			"hi":    "हज़ार मील की यात्रा एक कदम से शुरू होती है।",
			"pl":    "Podróż tysiąca mil zaczyna się od jednego kroku.",
			"tr":    "Bin millik yolculuk tek bir adımla başlar.",
			"uk":    "Подорож у тисячу миль починається з одного кроку.",
			"sv":    "En resa på tusen mil börjar med ett enda steg.",
			"nl":    "Een reis van duizend mijl begint met één stap.",
			"nb":    "En reise på tusen mil begynner med ett skritt.",
			"da":    "En rejse på tusind mil begynder med et enkelt skridt.",
			"fi":    "Tuhannen mailin matka alkaa yhdellä askeleella.",
		},
	},
	{
		ID:       "growth-8",
		Author:   ptr("Albert Einstein"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "A person who never made a mistake never tried anything new.",
			"en-GB": "A person who never made a mistake never tried anything new.",
			"pt-PT": "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.",
			"pt-BR": "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.",
			"es":    "Una persona que nunca cometió un error nunca intentó nada nuevo.",
			"fr":    "Une personne qui n'a jamais commis d'erreur n'a jamais rien tenté de nouveau.",
			"de":    "Wer nie einen Fehler gemacht hat, hat nie etwas Neues ausprobiert.",
			"it":    "Chi non ha mai commesso un errore non ha mai provato nulla di nuovo.",
			"ja":    "一度も間違えたことのない人は、何も新しいことに挑戦したことがない人だ。",
			"zh":    "从不犯错的人，从未尝试过任何新事物。",
			"ko":    "한 번도 실수한 적 없는 사람은 한 번도 새로운 것을 시도해 본 적이 없는 사람이다.",
			"hi":    "जिसने कभी ग़लती नहीं की, उसने कभी कुछ नया आज़माया ही नहीं।",
			"pl":    "Człowiek, który nigdy nie popełnił błędu, nigdy nie spróbował niczego nowego.",
			"tr":    "Hiç hata yapmamış bir insan, hiçbir zaman yeni bir şey denememiştir.",
			"uk":    "Людина, яка ніколи не помилялася, ніколи не пробувала нічого нового.",
			"sv":    "En människa som aldrig gjort ett misstag har aldrig prövat något nytt.",
			"nl":    "Iemand die nooit een fout heeft gemaakt, heeft nooit iets nieuws geprobeerd.",
			"nb":    "En person som aldri har gjort en feil, har aldri prøvd noe nytt.",
			"da":    "Et menneske, der aldrig har begået en fejl, har aldrig prøvet noget nyt.",
			"fi":    "Ihminen, joka ei ole koskaan tehnyt virhettä, ei ole koskaan kokeillut mitään uutta.",
		},
	},
	{
		ID:       "growth-9",
		Author:   ptr("John Maxwell"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Growth inside fuels growth outside.",
			"en-GB": "Growth inside fuels growth outside.",
			"pt-PT": "O crescimento interior alimenta o crescimento exterior.",
			"pt-BR": "O crescimento interior alimenta o crescimento exterior.",
			"es":    "El crescimento interior alimenta el crecimiento exterior.",
			"fr":    "La croissance intérieure alimente la croissance extérieure.",
			"de":    "Inneres Wachstum nährt äußeres Wachstum.",
			"it":    "La crescita interiore alimenta la crescita esteriore.",
			"ja":    "内なる成長が、外の成長を育む。",
			"zh":    "内在的成长滋养外在的成长。",
			"ko":    "내면의 성장이 외면의 성장을 이끈다.",
			"hi":    "भीतर का विकास बाहर के विकास को ईंधन देता है।",
			"pl":    "Wzrost wewnętrzny napędza wzrost zewnętrzny.",
			"tr":    "İçerideki büyüme, dışarıdaki büyümeyi besler.",
			"uk":    "Внутрішнє зростання живить зовнішнє.",
			"sv":    "Inre växande ger näring åt yttre växande.",
			"nl":    "Innerlijke groei voedt uiterlijke groei.",
			"nb":    "Indre vekst gir næring til ytre vekst.",
			"da":    "Indre vækst nærer ydre vækst.",
			"fi":    "Sisäinen kasvu ruokkii ulkoista kasvua.",
		},
	},
	{
		ID:       "growth-10",
		Author:   ptr("Denis Waitley"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Personal growth is not a matter of luck, it's a matter of choice.",
			"en-GB": "Personal growth is not a matter of luck, it's a matter of choice.",
			"pt-PT": "O crescimento pessoal não é uma questão de sorte, é uma questão de escolha.",
			"pt-BR": "O crescimento pessoal não é uma questão de sorte, é uma questão de escolha.",
			"es":    "El crecimiento personal no es cuestión de suerte, es cuestión de elección.",
			"fr":    "La croissance personnelle n'est pas une question de chance, c'est une question de choix.",
			"de":    "Persönliches Wachstum ist keine Frage des Glücks, sondern der Entscheidung.",
			"it":    "La crescita personale non è questione di fortuna, è questione di scelta.",
			"ja":    "自己成長は運の問題ではなく、選択の問題である。",
			"zh":    "个人成长不是运气问题，而是选择问题。",
			"ko":    "자기 성장은 운의 문제가 아니라 선택의 문제다.",
			"hi":    "व्यक्तिगत विकास क़िस्मत की बात नहीं, चुनाव की बात है।",
			"pl":    "Rozwój osobisty to nie kwestia szczęścia, lecz wyboru.",
			"tr":    "Kişisel gelişim bir şans meselesi değil, bir seçim meselesidir.",
			"uk":    "Особисте зростання — це не питання удачі, а питання вибору.",
			"sv":    "Personlig utveckling är inte en fråga om tur, utan om val.",
			"nl":    "Persoonlijke groei is geen kwestie van geluk, maar van keuze.",
			"nb":    "Personlig vekst er ikke et spørsmål om flaks, men om valg.",
			"da":    "Personlig vækst er ikke et spørgsmål om held, men om valg.",
			"fi":    "Henkilökohtainen kasvu ei ole onnen asia, vaan valinnan asia.",
		},
	},
	{
		ID:       "growth-11",
		Author:   ptr("Earl Nightingale"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "We become what we think about.",
			"en-GB": "We become what we think about.",
			"pt-PT": "Tornamo-nos naquilo em que pensamos.",
			"pt-BR": "Nós nos tornamos aquilo que pensamos.",
			"es":    "Nos convertimos en lo que pensamos.",
			"fr":    "Nous devenons ce à quoi nous pensons.",
			"de":    "Wir werden zu dem, woran wir denken.",
			"it":    "Diventiamo ciò che pensiamo.",
			"ja":    "私たちは、心に思い描くものになる。",
			"zh":    "我们会成为自己所思所想的样子。",
			"ko":    "우리는 생각하는 대로 된다.",
			"hi":    "हम वही बन जाते हैं जिसके बारे में हम सोचते हैं।",
			"pl":    "Stajemy się tym, o czym myślimy.",
			"tr":    "Ne düşünürsek o oluruz.",
			"uk":    "Ми стаємо тим, про що думаємо.",
			"sv":    "Vi blir vad vi tänker på.",
			"nl":    "We worden waar we aan denken.",
			"nb":    "Vi blir det vi tenker på.",
			"da":    "Vi bliver det, vi tænker på.",
			"fi":    "Meistä tulee sitä, mitä ajattelemme.",
		},
	},
	{
		ID:       "growth-12",
		Author:   ptr("Brian Tracy"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable.",
			"en-GB": "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable.",
			"pt-PT": "Sai da tua zona de conforto. Só podes crescer se estiveres disposto a sentir-te estranho e desconfortável.",
			"pt-BR": "Saia da sua zona de conforto. Você só pode crescer se estiver disposto a se sentir estranho e desconfortável.",
			"es":    "Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo.",
			"fr":    "Sortez de votre zone de confort. Vous ne pouvez grandir que si vous êtes prêt à vous sentir maladroit et mal à l'aise.",
			"de":    "Verlasse deine Komfortzone. Du kannst nur wachsen, wenn du bereit bist, dich unbeholfen und unbehaglich zu fühlen.",
			"it":    "Esci dalla tua zona di comfort. Puoi crescere solo se sei disposto a sentirti goffo e a disagio.",
			"ja":    "コンフォートゾーンから踏み出せ。ぎこちなさや居心地の悪さを受け入れてこそ、人は成長できる。",
			"zh":    "走出舒适区。只有愿意接受尴尬和不适，你才能成长。",
			"ko":    "안전지대에서 벗어나라. 어색함과 불편함을 기꺼이 느낄 때에만 성장할 수 있다.",
			"hi":    "अपने आराम क्षेत्र से बाहर निकलो। आप तभी बढ़ सकते हैं जब आप असहज महसूस करने को तैयार हों।",
			"pl":    "Wyjdź ze swojej strefy komfortu. Możesz rosnąć tylko wtedy, gdy jesteś gotów czuć się niezręcznie i niewygodnie.",
			"tr":    "Konfor alanından çık. Ancak tuhaf ve rahatsız hissetmeye razı olursan büyüyebilirsin.",
			"uk":    "Вийди із зони комфорту. Ти можеш зростати, лише якщо готовий почуватися незручно й ніяково.",
			"sv":    "Lämna din bekvämlighetszon. Du kan bara växa om du är villig att känna dig klumpig och obekväm.",
			"nl":    "Stap uit je comfortzone. Je kunt alleen groeien als je bereid bent je onhandig en ongemakkelijk te voelen.",
			"nb":    "Gå ut av komfortsonen din. Du kan bare vokse hvis du er villig til å føle deg klosset og ubekvem.",
			"da":    "Træd ud af din komfortzone. Du kan kun vokse, hvis du er villig til at føle dig akavet og utilpas.",
			"fi":    "Astu ulos mukavuusalueeltasi. Voit kasvaa vain, jos olet valmis tuntemaan olosi kömpelöksi ja epämukavaksi.",
		},
	},
	{
		ID:       "growth-13",
		Author:   ptr("T.S. Eliot"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Only those who will risk going too far can possibly find out how far one can go.",
			"en-GB": "Only those who will risk going too far can possibly find out how far one can go.",
			"pt-PT": "Apenas aqueles que arriscam ir demasiado longe podem possivelmente descobrir quão longe se pode ir.",
			"pt-BR": "Apenas aqueles que arriscam ir longe demais podem possivelmente descobrir quão longe se pode ir.",
			"es":    "Solo aquellos que se arriesgan a ir demasiado lejos pueden descubrir hasta dónde se puede llegar.",
			"fr":    "Seuls ceux qui risquent d'aller trop loin peuvent découvrir jusqu'où l'on peut aller.",
			"de":    "Nur wer riskiert, zu weit zu gehen, kann herausfinden, wie weit man gehen kann.",
			"it":    "Solo chi rischia di andare troppo lontano può scoprire quanto lontano si può arrivare.",
			"ja":    "行き過ぎる危険を冒す者だけが、どこまで行けるかを知ることができる。",
			"zh":    "只有敢于冒险走得太远的人，才能发现人究竟能走多远。",
			"ko":    "너무 멀리 가는 위험을 무릅쓰는 사람만이 얼마나 멀리 갈 수 있는지 알아낼 수 있다.",
			"hi":    "केवल वही, जो बहुत दूर जाने का जोखिम उठाते हैं, जान सकते हैं कि कोई कितनी दूर जा सकता है।",
			"pl":    "Tylko ci, którzy zaryzykują pójście za daleko, mogą się przekonać, jak daleko można zajść.",
			"tr":    "Yalnızca çok ileri gitmeyi göze alanlar, insanın ne kadar ileri gidebileceğini keşfedebilir.",
			"uk":    "Лише той, хто ризикне зайти надто далеко, може дізнатися, як далеко можна зайти.",
			"sv":    "Bara de som vågar gå för långt kan upptäcka hur långt man kan gå.",
			"nl":    "Alleen wie het risico neemt te ver te gaan, kan ontdekken hoe ver je kunt gaan.",
			"nb":    "Bare de som våger å gå for langt, kan finne ut hvor langt man kan gå.",
			"da":    "Kun de, der vover at gå for langt, kan finde ud af, hvor langt man kan gå.",
			"fi":    "Vain se, joka uskaltaa mennä liian pitkälle, voi saada selville, kuinka pitkälle voi mennä.",
		},
	},
	{
		ID:       "growth-14",
		Author:   ptr("Eleanor Roosevelt"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Do one thing every day that scares you.",
			"en-GB": "Do one thing every day that scares you.",
			"pt-PT": "Faz todos os dias uma coisa que te assuste.",
			"pt-BR": "Faça uma coisa todos os dias que te assuste.",
			"es":    "Haz una cosa cada día que te asuste.",
			"fr":    "Faites chaque jour une chose qui vous fait peur.",
			"de":    "Tu jeden Tag eine Sache, die dir Angst macht.",
			"it":    "Fai ogni giorno una cosa che ti spaventa.",
			"ja":    "毎日ひとつ、自分が怖いと思うことをやってみよう。",
			"zh":    "每天做一件让你害怕的事。",
			"ko":    "매일 두려운 일을 한 가지씩 하라.",
			"hi":    "हर दिन एक ऐसा काम करो जिससे तुम्हें डर लगता हो।",
			"pl":    "Codziennie rób jedną rzecz, która cię przeraża.",
			"tr":    "Her gün seni korkutan bir şey yap.",
			"uk":    "Щодня роби одну справу, яка тебе лякає.",
			"sv":    "Gör en sak varje dag som skrämmer dig.",
			"nl":    "Doe elke dag één ding dat je bang maakt.",
			"nb":    "Gjør én ting hver dag som skremmer deg.",
			"da":    "Gør én ting hver dag, som skræmmer dig.",
			"fi":    "Tee joka päivä yksi asia, joka pelottaa sinua.",
		},
	},
	{
		ID:       "growth-15",
		Author:   ptr("Abraham Maslow"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "In any given moment we have two options: to step forward into growth or step back into safety.",
			"en-GB": "In any given moment we have two options: to step forward into growth or step back into safety.",
			"pt-PT": "Em qualquer momento temos duas opções: dar um passo em frente para o crescimento ou recuar para a segurança.",
			"pt-BR": "Em qualquer momento temos duas opções: dar um passo à frente para o crescimento ou recuar para a segurança.",
			"es":    "En cualquier momento tenemos dos opciones: dar un paso adelante hacia el crecimiento o retroceder hacia la seguridad.",
			"fr":    "À tout moment, nous avons deux options : avancer vers la croissance ou reculer vers la sécurité.",
			"de":    "In jedem Augenblick haben wir zwei Möglichkeiten: vorwärts ins Wachstum zu gehen oder zurück in die Sicherheit.",
			"it":    "In ogni momento abbiamo due opzioni: avanzare verso la crescita o arretrare verso la sicurezza.",
			"ja":    "どんな瞬間にも、私たちには二つの選択肢がある。成長へと踏み出すか、安全へと後退するかだ。",
			"zh":    "在任何时刻，我们都有两个选择：向前迈向成长，或退回到安全。",
			"ko":    "어느 순간이든 우리에게는 두 가지 선택지가 있다. 성장을 향해 나아가거나, 안전으로 물러서거나.",
			"hi":    "हर क्षण हमारे पास दो विकल्प होते हैं: विकास की ओर आगे बढ़ना या सुरक्षा की ओर पीछे हटना।",
			"pl":    "W każdej chwili mamy dwie opcje: zrobić krok naprzód ku rozwojowi albo cofnąć się w bezpieczeństwo.",
			"tr":    "Her an iki seçeneğimiz vardır: büyümeye doğru ilerlemek ya da güvenliğe geri çekilmek.",
			"uk":    "У будь-яку мить ми маємо два варіанти: крок уперед до зростання або крок назад до безпеки.",
			"sv":    "I varje ögonblick har vi två alternativ: att kliva framåt mot växande eller tillbaka mot trygghet.",
			"nl":    "Op elk moment hebben we twee opties: vooruitstappen naar groei of terugstappen naar veiligheid.",
			"nb":    "I ethvert øyeblikk har vi to valg: å gå fremover mot vekst eller tilbake mot trygghet.",
			"da":    "I ethvert øjeblik har vi to muligheder: at træde frem mod vækst eller tilbage mod tryghed.",
			"fi":    "Jokaisella hetkellä meillä on kaksi vaihtoehtoa: astua eteenpäin kohti kasvua tai taaksepäin turvallisuuteen.",
		},
	},
	{
		ID:       "growth-16",
		Author:   ptr("Ray Bennett"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Small shifts in your thinking lead to big shifts in your results.",
			"en-GB": "Small shifts in your thinking lead to big shifts in your results.",
			"pt-PT": "Pequenas mudanças no teu pensamento levam a grandes mudanças nos teus resultados.",
			"pt-BR": "Pequenas mudanças no seu pensamento levam a grandes mudanças nos seus resultados.",
			"es":    "Pequeños cambios en tu pensamiento conducen a grandes cambios en tus resultados.",
			"fr":    "De petits changements dans votre façon de penser mènent à de grands changements dans vos résultats.",
			"de":    "Kleine Veränderungen in deinem Denken führen zu großen Veränderungen in deinen Ergebnissen.",
			"it":    "Piccoli cambiamenti nel tuo modo di pensare portano a grandi cambiamenti nei tuoi risultati.",
			"ja":    "考え方の小さな変化が、結果の大きな変化をもたらす。",
			"zh":    "思维上的小转变会带来结果上的大转变。",
			"ko":    "생각의 작은 변화가 결과의 큰 변화를 만든다.",
			"hi":    "सोच में छोटे बदलाव नतीजों में बड़े बदलाव लाते हैं।",
			"pl":    "Małe zmiany w myśleniu prowadzą do wielkich zmian w rezultatach.",
			"tr":    "Düşüncendeki küçük değişimler, sonuçlarında büyük değişimlere yol açar.",
			"uk":    "Малі зрушення в мисленні ведуть до великих зрушень у результатах.",
			"sv":    "Små förändringar i ditt tänkande leder till stora förändringar i dina resultat.",
			"nl":    "Kleine verschuivingen in je denken leiden tot grote verschuivingen in je resultaten.",
			"nb":    "Små endringer i tankegangen din fører til store endringer i resultatene dine.",
			"da":    "Små ændringer i din tankegang fører til store ændringer i dine resultater.",
			"fi":    "Pienet muutokset ajattelussasi johtavat suuriin muutoksiin tuloksissasi.",
		},
	},
	{
		ID:       "growth-17",
		Author:   ptr("Tony Robbins"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "If you don't set a baseline for what you'll accept in your life, you'll find it's easy to slip into behaviors and attitudes that are far below what you deserve.",
			"en-GB": "If you don't set a baseline for what you'll accept in your life, you'll find it's easy to slip into behaviors and attitudes that are far below what you deserve.",
			"pt-PT": "Se não definires uma base para o que aceitas na tua vida, será fácil caíres em comportamentos e atitudes muito abaixo do que mereces.",
			"pt-BR": "Se você não estabelecer um limite para o que aceita em sua vida, verá que é fácil cair em comportamentos e atitudes muito abaixo do que você merece.",
			"es":    "Si no estableces un estándar para lo que aceptarás en tu vida, verás que es fácil caer en comportamientos y actitudes muy por debajo de lo que mereces.",
			"fr":    "Si vous ne fixez pas de base pour ce que vous accepterez dans votre vie, vous constaterez qu'il est facile de glisser vers des comportements et des attitudes bien en deçà de ce que vous méritez.",
			"de":    "Wenn du keine Grenze dafür setzt, was du in deinem Leben akzeptierst, rutschst du leicht in Verhaltensweisen und Haltungen ab, die weit unter dem liegen, was du verdienst.",
			"it":    "Se non stabilisci una soglia minima per ciò che accetti nella tua vita, ti sarà facile scivolare in comportamenti e atteggiamenti molto al di sotto di ciò che meriti.",
			"ja":    "人生で何を受け入れるかの基準を定めなければ、自分にふさわしい水準をはるかに下回る行動や態度へと、いつの間にか流されてしまう。",
			"zh":    "如果你不为自己的人生设定接受的底线，就很容易滑向远低于你应得水准的行为和态度。",
			"ko":    "삶에서 받아들일 것의 기준선을 정하지 않으면, 당신이 마땅히 누려야 할 수준보다 훨씬 낮은 행동과 태도로 쉽게 미끄러진다.",
			"hi":    "अगर आप यह तय नहीं करते कि जीवन में क्या स्वीकार करेंगे, तो आप आसानी से ऐसे व्यवहारों और रवैयों में फिसल जाएँगे जो आपकी योग्यता से बहुत नीचे हैं।",
			"pl":    "Jeśli nie ustalisz granicy tego, co zaakceptujesz w swoim życiu, łatwo osuniesz się w zachowania i postawy dalece poniżej tego, na co zasługujesz.",
			"tr":    "Hayatında neyi kabul edeceğine dair bir alt sınır koymazsan, hak ettiğinin çok altındaki davranış ve tutumlara kaymanın kolay olduğunu görürsün.",
			"uk":    "Якщо не визначиш межу того, що готовий приймати у своєму житті, легко скотишся до поведінки й поглядів, які значно нижчі за те, на що ти заслуговуєш.",
			"sv":    "Om du inte sätter en lägstanivå för vad du accepterar i ditt liv är det lätt att glida in i beteenden och attityder långt under vad du förtjänar.",
			"nl":    "Als je geen ondergrens stelt aan wat je in je leven accepteert, glijd je gemakkelijk af naar gedrag en houdingen die ver beneden je waarde liggen.",
			"nb":    "Hvis du ikke setter en grense for hva du godtar i livet ditt, vil du lett gli inn i atferd og holdninger som ligger langt under det du fortjener.",
			"da":    "Hvis du ikke sætter en grænse for, hvad du vil acceptere i dit liv, glider du let ind i adfærd og holdninger, der ligger langt under, hvad du fortjener.",
			"fi":    "Jos et aseta rajaa sille, mitä elämässäsi hyväksyt, huomaat helposti lipuvasi käytökseen ja asenteisiin, jotka ovat kaukana ansaitsemastasi tasosta.",
		},
	},
	{
		ID:       "growth-18",
		Author:   ptr("Jim Rohn"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Don't wish it were easier, wish you were better.",
			"en-GB": "Don't wish it were easier, wish you were better.",
			"pt-PT": "Não desejes que fosse mais fácil, deseja ser melhor.",
			"pt-BR": "Não deseje que fosse mais fácil, deseje ser melhor.",
			"es":    "No desees que fuera más fácil, desea ser mejor.",
			"fr":    "Ne souhaitez pas que ce soit plus facile, souhaitez être meilleur.",
			"de":    "Wünsch dir nicht, dass es leichter wäre. Wünsch dir, dass du besser wirst.",
			"it":    "Non desiderare che sia più facile, desidera di essere migliore.",
			"ja":    "もっと楽になればいいと願うな。もっと自分が成長すればいいと願え。",
			"zh":    "不要希望事情变得更容易，要希望自己变得更强。",
			"ko":    "일이 더 쉬워지길 바라지 말고, 자신이 더 나아지길 바라라.",
			"hi":    "यह मत चाहो कि काम आसान हो, यह चाहो कि तुम बेहतर बनो।",
			"pl":    "Nie życz sobie, żeby było łatwiej. Życz sobie, żebyś był lepszy.",
			"tr":    "Daha kolay olmasını dileme; daha iyi olmayı dile.",
			"uk":    "Не бажай, щоб було легше, — бажай стати кращим.",
			"sv":    "Önska inte att det vore lättare, önska att du vore bättre.",
			"nl":    "Wens niet dat het makkelijker was, wens dat je beter was.",
			"nb":    "Ikke ønsk at det var lettere, ønsk at du var bedre.",
			"da":    "Ønsk ikke, at det var lettere, ønsk, at du var bedre.",
			"fi":    "Älä toivo, että se olisi helpompaa, vaan että sinä olisit parempi.",
		},
	},
	{
		ID:       "growth-19",
		Author:   ptr("Eric Hoffer"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "In a time of drastic change it is the learners who inherit the future. The learned usually find themselves equipped to live in a world that no longer exists.",
			"en-GB": "In a time of drastic change it is the learners who inherit the future. The learned usually find themselves equipped to live in a world that no longer exists.",
			"pt-PT": "Num tempo de mudança drástica, são os que aprendem que herdam o futuro. Os que já aprenderam encontram-se equipados para viver num mundo que já não existe.",
			"pt-BR": "Em tempos de mudanças drásticas, são os aprendizes que herdam o futuro. Os instruídos geralmente se encontram equipados para viver em um mundo que não existe mais.",
			"es":    "En una época de cambios drásticos, son los aprendices quienes heredan el futuro. Los que creen saberlo todo se encuentran equipados para vivir en un mundo que ya no existe.",
			"fr":    "En période de changement radical, ce sont les apprenants qui héritent de l'avenir. Les savants se retrouvent généralement équipés pour vivre dans un monde qui n'existe plus.",
			"de":    "In Zeiten drastischen Wandels erben die Lernenden die Zukunft. Die Gelehrten finden sich meist gerüstet für eine Welt, die nicht mehr existiert.",
			"it":    "In tempi di cambiamenti radicali sono coloro che imparano a ereditare il futuro. I sapienti di solito si ritrovano attrezzati per un mondo che non esiste più.",
			"ja":    "激変の時代に未来を手にするのは、学び続ける者である。学び終えた者は、もはや存在しない世界に適応した自分に気づくことになる。",
			"zh":    "在剧变的时代，继承未来的是学习者。而学成者往往发现，自己所擅长应对的世界已不复存在。",
			"ko":    "격변의 시대에 미래를 물려받는 것은 배우는 사람들이다. 다 배웠다고 여기는 사람들은 대개 더 이상 존재하지 않는 세상에 맞춰져 있다.",
			"hi":    "भारी बदलाव के दौर में भविष्य सीखने वालों का होता है। जो सीख चुके हैं, वे प्रायः ऐसी दुनिया के लिए तैयार रह जाते हैं जो अब है ही नहीं।",
			"pl":    "W czasach gwałtownych zmian to uczący się dziedziczą przyszłość. Wykształceni zwykle odkrywają, że są przygotowani do życia w świecie, który już nie istnieje.",
			"tr":    "Köklü değişim zamanlarında geleceği öğrenenler devralır. Öğrenmiş olanlar ise genellikle artık var olmayan bir dünyaya donanımlı olduklarını görürler.",
			"uk":    "У часи різких змін майбутнє успадковують ті, хто вчиться. Ті, хто вже вивчився, зазвичай виявляються готовими до світу, якого більше не існує.",
			"sv":    "I en tid av drastisk förändring är det de lärande som ärver framtiden. De lärda finner sig oftast rustade för en värld som inte längre finns.",
			"nl":    "In tijden van drastische verandering erven de lerenden de toekomst. De geleerden blijken meestal toegerust voor een wereld die niet meer bestaat.",
			"nb":    "I en tid med drastiske endringer er det de lærende som arver fremtiden. De lærde er som regel rustet for en verden som ikke lenger finnes.",
			"da":    "I en tid med drastiske forandringer er det de lærende, der arver fremtiden. De lærde er som regel rustet til en verden, der ikke længere findes.",
			"fi":    "Rajun muutoksen aikoina tulevaisuuden perivät oppijat. Oppineet huomaavat yleensä olevansa varustautuneita maailmaan, jota ei enää ole.",
		},
	},
	{
		ID:       "growth-20",
		Author:   ptr("James Allen"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Self-control is strength. Right thought is mastery. Calmness is power.",
			"en-GB": "Self-control is strength. Right thought is mastery. Calmness is power.",
			"pt-PT": "O autocontrolo é força. O pensamento correto é mestria. A calma é poder.",
			"pt-BR": "O autocontrole é força. O pensamento correto é maestria. A calma é poder.",
			"es":    "El autocontrol es fuerza. El pensamiento correcto es maestría. La calma es poder.",
			"fr":    "La maîtrise de soi est une force. La pensée juste est une maîtrise. Le calme est un pouvoir.",
			"de":    "Selbstbeherrschung ist Stärke. Rechtes Denken ist Meisterschaft. Gelassenheit ist Macht.",
			"it":    "L'autocontrollo è forza. Il pensiero giusto è maestria. La calma è potere.",
			"ja":    "自制は強さ。正しい思考は熟達。平静は力である。",
			"zh":    "自制是力量，正念是精通，平静是能量。",
			"ko":    "자제력은 힘이다. 바른 생각은 통달이다. 평온함은 능력이다.",
			"hi":    "आत्म-संयम शक्ति है। सही विचार महारत है। शांति सामर्थ्य है।",
			"pl":    "Samokontrola to siła. Właściwa myśl to mistrzostwo. Spokój to potęga.",
			"tr":    "Özdenetim güçtür. Doğru düşünce ustalıktır. Sükûnet kudrettir.",
			"uk":    "Самовладання — це сила. Правильна думка — це майстерність. Спокій — це могутність.",
			"sv":    "Självbehärskning är styrka. Rätt tanke är mästerskap. Lugn är kraft.",
			"nl":    "Zelfbeheersing is kracht. Juist denken is meesterschap. Kalmte is macht.",
			"nb":    "Selvkontroll er styrke. Rett tanke er mesterskap. Ro er kraft.",
			"da":    "Selvbeherskelse er styrke. Ret tanke er mesterskab. Ro er kraft.",
			"fi":    "Itsehillintä on voimaa. Oikea ajattelu on mestaruutta. Tyyneys on valtaa.",
		},
	},
	{
		ID:       "growth-21",
		Author:   ptr("Robin Sharma"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Change is hard at first, messy in the middle and gorgeous at the end.",
			"en-GB": "Change is hard at first, messy in the middle and gorgeous at the end.",
			"pt-PT": "A mudança é difícil no início, confusa no meio e deslumbrante no fim.",
			"pt-BR": "A mudança é difícil no início, confusa no meio e deslumbrante no fim.",
			"es":    "El cambio es difícil al principio, caótico en el medio y hermoso al final.",
			"fr":    "Le changement est difficile au début, désordonné au milieu et magnifique à la fin.",
			"de":    "Veränderung ist am Anfang schwer, in der Mitte chaotisch und am Ende wunderschön.",
			"it":    "Il cambiamento è difficile all'inizio, caotico nel mezzo e splendido alla fine.",
			"ja":    "変化は、始めはつらく、途中は混沌とし、最後は美しい。",
			"zh":    "改变在开始时艰难，中途时混乱，结束时绚烂。",
			"ko":    "변화는 처음엔 힘들고, 중간엔 혼란스럽지만, 끝은 눈부시다.",
			"hi":    "बदलाव शुरू में कठिन, बीच में उलझा हुआ और अंत में शानदार होता है।",
			"pl":    "Zmiana jest trudna na początku, chaotyczna w środku i wspaniała na końcu.",
			"tr":    "Değişim başta zordur, ortada karmaşık, sonda ise muhteşemdir.",
			"uk":    "Зміни важкі на початку, безладні всередині та прекрасні наприкінці.",
			"sv":    "Förändring är svår i början, rörig i mitten och underbar i slutet.",
			"nl":    "Verandering is zwaar in het begin, rommelig in het midden en prachtig aan het einde.",
			"nb":    "Forandring er hard i begynnelsen, rotete på midten og vakker til slutt.",
			"da":    "Forandring er hård i begyndelsen, rodet i midten og smuk til sidst.",
			"fi":    "Muutos on alussa vaikeaa, keskellä sotkuista ja lopussa upeaa.",
		},
	},
	{
		ID:       "growth-22",
		Author:   ptr("W. Edwards Deming"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Learning is not compulsory... neither is survival.",
			"en-GB": "Learning is not compulsory... neither is survival.",
			"pt-PT": "Aprender não é obrigatório... nem a sobrevivência o é.",
			"pt-BR": "Aprender não é obrigatório... nem a sobrevivência o é.",
			"es":    "Aprender no es obligatorio... ni tampoco lo es la supervivencia.",
			"fr":    "L'apprentissage n'est pas obligatoire... la survie non plus.",
			"de":    "Lernen ist nicht Pflicht … Überleben auch nicht.",
			"it":    "Imparare non è obbligatorio... nemmeno sopravvivere lo è.",
			"ja":    "学ぶことは義務ではない……生き残ることも同じだ。",
			"zh":    "学习不是必须的……生存也不是。",
			"ko":    "배움은 의무가 아니다... 생존도 마찬가지다.",
			"hi":    "सीखना अनिवार्य नहीं है... जीवित रहना भी नहीं।",
			"pl":    "Nauka nie jest obowiązkowa... przetrwanie też nie.",
			"tr":    "Öğrenmek zorunlu değildir... hayatta kalmak da öyle.",
			"uk":    "Навчання не є обов'язковим... як і виживання.",
			"sv":    "Lärande är inte obligatoriskt... det är inte överlevnad heller.",
			"nl":    "Leren is niet verplicht... overleven ook niet.",
			"nb":    "Læring er ikke obligatorisk... det er ikke overlevelse heller.",
			"da":    "Læring er ikke obligatorisk... det er overlevelse heller ikke.",
			"fi":    "Oppiminen ei ole pakollista... ei ole selviytyminenkään.",
		},
	},
	{
		ID:       "growth-23",
		Author:   ptr("Ralph Waldo Emerson"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Unless you try to do something beyond what you have already mastered, you will never grow.",
			"en-GB": "Unless you try to do something beyond what you have already mastered, you will never grow.",
			"pt-PT": "A menos que tentes fazer algo além do que já dominas, nunca crescerás.",
			"pt-BR": "A menos que você tente fazer algo além do que já domina, você nunca crescerá.",
			"es":    "A menos que intentes hacer algo más allá de lo que ya dominas, nunca crecerás.",
			"fr":    "À moins que vous n'essayiez de faire quelque chose au-delà de ce que vous maîtrisez déjà, vous ne grandirez jamais.",
			"de":    "Wenn du nicht versuchst, über das hinauszugehen, was du bereits beherrschst, wirst du niemals wachsen.",
			"it":    "Se non provi a fare qualcosa oltre ciò che già padroneggi, non crescerai mai.",
			"ja":    "すでに習得したことの先に挑まなければ、決して成長することはない。",
			"zh":    "除非尝试去做超出你已掌握范围的事，否则你永远不会成长。",
			"ko":    "이미 익힌 것 너머에 도전하지 않으면 결코 성장할 수 없다.",
			"hi":    "जब तक आप उससे आगे कुछ करने की कोशिश नहीं करते जिसमें आप पहले से माहिर हैं, आप कभी विकसित नहीं होंगे।",
			"pl":    "Jeśli nie spróbujesz zrobić czegoś ponad to, co już opanowałeś, nigdy się nie rozwiniesz.",
			"tr":    "Zaten ustalaştığın şeylerin ötesine geçmeyi denemedikçe asla büyüyemezsin.",
			"uk":    "Якщо не спробуєш вийти за межі того, що вже опанував, ти ніколи не зростеш.",
			"sv":    "Om du inte försöker göra något utöver det du redan behärskar kommer du aldrig att växa.",
			"nl":    "Als je niet iets probeert boven wat je al beheerst, zul je nooit groeien.",
			"nb":    "Med mindre du prøver å gjøre noe utover det du allerede mestrer, vil du aldri vokse.",
			"da":    "Medmindre du forsøger at gøre noget ud over det, du allerede mestrer, vil du aldrig vokse.",
			"fi":    "Ellet yritä jotain sen yli, minkä jo hallitset, et koskaan kasva.",
		},
	},
	{
		ID:       "growth-24",
		Author:   ptr("Oliver Wendell Holmes"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "A mind that is stretched by a new experience can never go back to its old dimensions.",
			"en-GB": "A mind that is stretched by a new experience can never go back to its old dimensions.",
			"pt-PT": "Uma mente que é expandida por uma nova experiência nunca mais regressa às suas dimensões antigas.",
			"pt-BR": "Uma mente expandida por uma nova experiência nunca volta às suas dimensões antigas.",
			"es":    "Una mente que se expande por una nueva experiencia nunca puede volver a sus dimensiones antiguas.",
			"fr":    "Un esprit étiré par une nouvelle expérience ne peut jamais revenir à ses anciennes dimensions.",
			"de":    "Ein Geist, der durch eine neue Erfahrung gedehnt wurde, kann nie zu seinen alten Dimensionen zurückkehren.",
			"it":    "Una mente allargata da una nuova esperienza non può mai tornare alle sue vecchie dimensioni.",
			"ja":    "新しい経験によって広がった心は、二度と元の大きさには戻らない。",
			"zh":    "被新经验拓展过的头脑，永远无法回到原来的维度。",
			"ko":    "새로운 경험으로 넓어진 정신은 결코 예전의 크기로 돌아가지 않는다.",
			"hi":    "नए अनुभव से विस्तृत हुआ मन कभी अपने पुराने आयामों में वापस नहीं लौट सकता।",
			"pl":    "Umysł rozciągnięty przez nowe doświadczenie nigdy nie wróci do dawnych wymiarów.",
			"tr":    "Yeni bir deneyimle genişleyen zihin, asla eski boyutlarına dönemez.",
			"uk":    "Розум, розширений новим досвідом, ніколи не повернеться до колишніх меж.",
			"sv":    "Ett sinne som töjts av en ny erfarenhet kan aldrig återgå till sina gamla dimensioner.",
			"nl":    "Een geest die door een nieuwe ervaring is opgerekt, kan nooit meer terug naar zijn oude afmetingen.",
			"nb":    "Et sinn som er utvidet av en ny erfaring, kan aldri vende tilbake til sine gamle dimensjoner.",
			"da":    "Et sind, der er blevet udvidet af en ny erfaring, kan aldrig vende tilbage til sine gamle dimensioner.",
			"fi":    "Uuden kokemuksen avartama mieli ei voi koskaan palata entisiin mittoihinsa.",
		},
	},
	{
		ID:       "growth-25",
		Author:   ptr("George Bernard Shaw"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
			"en-GB": "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
			"pt-PT": "O progresso é impossível sem mudança, e aqueles que não conseguem mudar as suas mentes não conseguem mudar nada.",
			"pt-BR": "O progresso é impossível sem mudança, e aqueles que não conseguem mudar de ideia não conseguem mudar nada.",
			"es":    "El progreso es imposible sin cambio, y aquellos que no pueden cambiar de opinión no pueden cambiar nada.",
			"fr":    "Le progrès est impossible sans changement, et ceux qui ne peuvent pas changer d'avis ne peuvent rien changer.",
			"de":    "Fortschritt ist ohne Veränderung unmöglich, und wer seine Meinung nicht ändern kann, kann gar nichts ändern.",
			"it":    "Il progresso è impossibile senza cambiamento, e chi non riesce a cambiare idea non può cambiare nulla.",
			"ja":    "変化なくして進歩はあり得ない。自分の考えを変えられない者は、何も変えることができない。",
			"zh":    "没有改变就没有进步，无法改变想法的人什么也改变不了。",
			"ko":    "변화 없이 진보는 불가능하다. 생각을 바꾸지 못하는 사람은 아무것도 바꿀 수 없다.",
			"hi":    "परिवर्तन के बिना प्रगति असंभव है, और जो अपना मन नहीं बदल सकते, वे कुछ भी नहीं बदल सकते।",
			"pl":    "Postęp jest niemożliwy bez zmiany, a ci, którzy nie potrafią zmienić zdania, nie potrafią zmienić niczego.",
			"tr":    "Değişim olmadan ilerleme imkânsızdır; fikrini değiştiremeyenler hiçbir şeyi değiştiremez.",
			"uk":    "Прогрес неможливий без змін, і той, хто не може змінити свою думку, не може змінити нічого.",
			"sv":    "Framsteg är omöjliga utan förändring, och de som inte kan ändra sig kan inte förändra någonting.",
			"nl":    "Vooruitgang is onmogelijk zonder verandering, en wie zijn mening niet kan veranderen, kan niets veranderen.",
			"nb":    "Fremskritt er umulig uten forandring, og de som ikke kan endre mening, kan ikke endre noe som helst.",
			"da":    "Fremskridt er umuligt uden forandring, og de, der ikke kan ændre mening, kan ikke ændre noget som helst.",
			"fi":    "Edistys on mahdotonta ilman muutosta, ja ne, jotka eivät voi muuttaa mieltään, eivät voi muuttaa mitään.",
		},
	},
	{
		ID:       "growth-26",
		Author:   ptr("Maxwell Maltz"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Self-image sets the boundaries of individual accomplishment.",
			"en-GB": "Self-image sets the boundaries of individual accomplishment.",
			"pt-PT": "A autoimagem define os limites da realização individual.",
			"pt-BR": "A autoimagem define os limites da realização individual.",
			"es":    "La autoimagen establece los límites del logro individual.",
			"fr":    "L'image de soi fixe les limites de l'accomplissement individuel.",
			"de":    "Das Selbstbild setzt die Grenzen individueller Leistung.",
			"it":    "L'immagine di sé stabilisce i confini dei risultati individuali.",
			"ja":    "セルフイメージが、個人の達成の限界を決める。",
			"zh":    "自我形象决定了个人成就的边界。",
			"ko":    "자아상이 개인이 이룰 수 있는 것의 한계를 정한다.",
			"hi":    "आत्म-छवि व्यक्ति की उपलब्धि की सीमाएँ तय करती है।",
			"pl":    "Obraz samego siebie wyznacza granice indywidualnych osiągnięć.",
			"tr":    "Benlik imajı, bireysel başarının sınırlarını belirler.",
			"uk":    "Уявлення про себе визначає межі особистих досягнень.",
			"sv":    "Självbilden sätter gränserna för individuella prestationer.",
			"nl":    "Het zelfbeeld bepaalt de grenzen van individuele prestaties.",
			"nb":    "Selvbildet setter grensene for individuelle prestasjoner.",
			"da":    "Selvbilledet sætter grænserne for individuelle præstationer.",
			"fi":    "Minäkuva asettaa yksilön saavutusten rajat.",
		},
	},
	{
		ID:       "growth-27",
		Author:   ptr("Wayne Dyer"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "When you change the way you look at things, the things you look at change.",
			"en-GB": "When you change the way you look at things, the things you look at change.",
			"pt-PT": "Quando mudas a forma como olhas para as coisas, as coisas para as quais olhas mudam.",
			"pt-BR": "Quando você muda a forma como olha para as coisas, as coisas para as quais você olha mudam.",
			"es":    "Cuando cambias la forma en que miras las cosas, las cosas que miras cambian.",
			"fr":    "Quand vous changez votre façon de regarder les choses, les choses que vous regardez changent.",
			"de":    "Wenn du die Art änderst, wie du die Dinge betrachtest, ändern sich die Dinge, die du betrachtest.",
			"it":    "Quando cambi il modo in cui guardi le cose, le cose che guardi cambiano.",
			"ja":    "物事の見方を変えれば、見ている物事そのものが変わる。",
			"zh":    "当你改变看待事物的方式，你所看待的事物也会随之改变。",
			"ko":    "사물을 바라보는 방식을 바꾸면, 바라보는 사물이 달라진다.",
			"hi":    "जब आप चीज़ों को देखने का नज़रिया बदलते हैं, तो वे चीज़ें भी बदल जाती हैं।",
			"pl":    "Kiedy zmieniasz sposób patrzenia na rzeczy, rzeczy, na które patrzysz, się zmieniają.",
			"tr":    "Olaylara bakışını değiştirdiğinde, baktığın olaylar da değişir.",
			"uk":    "Коли змінюєш свій погляд на речі, змінюються й самі речі.",
			"sv":    "När du ändrar sättet du ser på saker förändras sakerna du ser på.",
			"nl":    "Als je de manier verandert waarop je naar dingen kijkt, veranderen de dingen waarnaar je kijkt.",
			"nb":    "Når du endrer måten du ser på ting, endrer tingene du ser på seg.",
			"da":    "Når du ændrer den måde, du ser på tingene, ændrer de ting, du ser på, sig.",
			"fi":    "Kun muutat tapaasi katsoa asioita, katsomasi asiat muuttuvat.",
		},
	},
	{
		ID:       "growth-28",
		Author:   ptr("Nathaniel Branden"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "The first step toward change is awareness. The second step is acceptance.",
			"en-GB": "The first step toward change is awareness. The second step is acceptance.",
			"pt-PT": "O primeiro passo para a mudança é a consciência. O segundo passo é a aceitação.",
			"pt-BR": "O primeiro passo para a mudança é a consciência. O segundo passo é a aceitação.",
			"es":    "El primer paso hacia el cambio es la conciencia. El segundo paso es la aceptación.",
			"fr":    "La première étape vers le changement est la conscience. La deuxième étape est l'acceptation.",
			"de":    "Der erste Schritt zur Veränderung ist Bewusstheit. Der zweite Schritt ist Akzeptanz.",
			"it":    "Il primo passo verso il cambiamento è la consapevolezza. Il secondo è l'accettazione.",
			"ja":    "変化への第一歩は気づき。第二歩は受容である。",
			"zh":    "改变的第一步是觉察，第二步是接纳。",
			"ko":    "변화의 첫걸음은 알아차림이고, 두 번째 걸음은 받아들임이다.",
			"hi":    "बदलाव की ओर पहला कदम है जागरूकता। दूसरा कदम है स्वीकृति।",
			"pl":    "Pierwszym krokiem ku zmianie jest świadomość. Drugim — akceptacja.",
			"tr":    "Değişime giden ilk adım farkındalıktır. İkinci adım kabullenmektir.",
			"uk":    "Перший крок до змін — усвідомлення. Другий — прийняття.",
			"sv":    "Det första steget mot förändring är medvetenhet. Det andra steget är acceptans.",
			"nl":    "De eerste stap naar verandering is bewustzijn. De tweede stap is acceptatie.",
			"nb":    "Det første skrittet mot forandring er bevissthet. Det andre er aksept.",
			"da":    "Det første skridt mod forandring er bevidsthed. Det andet er accept.",
			"fi":    "Ensimmäinen askel muutokseen on tietoisuus. Toinen askel on hyväksyntä.",
		},
	},
	{
		ID:       "growth-29",
		Author:   ptr("Henry Ford"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.",
			"en-GB": "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.",
			"pt-PT": "Qualquer pessoa que para de aprender é velha, quer tenha vinte ou oitenta anos. Qualquer pessoa que continua a aprender mantém-se jovem.",
			"pt-BR": "Quem para de aprender é velho, seja aos vinte ou aos oitenta anos. Quem continua aprendendo permanece jovem.",
			"es":    "Cualquiera que deje de aprender es viejo, ya sea a los veinte o a los ochenta. Cualquiera que siga aprendiendo se mantiene joven.",
			"fr":    "Quiconque cesse d'apprendre est vieux, qu'il ait vingt ou quatre-vingts ans. Quiconque continue d'apprendre reste jeune.",
			"de":    "Wer aufhört zu lernen, ist alt — ob mit zwanzig oder achtzig. Wer weiterlernt, bleibt jung.",
			"it":    "Chi smette di imparare è vecchio, che abbia venti o ottant'anni. Chi continua a imparare resta giovane.",
			"ja":    "学ぶことをやめた者は、二十歳でも八十歳でも老人である。学び続ける者は若さを保つ。",
			"zh":    "停止学习的人就是老人，无论二十岁还是八十岁。坚持学习的人永远年轻。",
			"ko":    "배움을 멈춘 사람은 스무 살이든 여든 살이든 늙은 것이다. 계속 배우는 사람은 젊음을 유지한다.",
			"hi":    "जो सीखना छोड़ देता है वह बूढ़ा है, चाहे बीस का हो या अस्सी का। जो सीखता रहता है वह जवान रहता है।",
			"pl":    "Kto przestaje się uczyć, jest stary — czy ma dwadzieścia, czy osiemdziesiąt lat. Kto uczy się dalej, pozostaje młody.",
			"tr":    "Öğrenmeyi bırakan yaşlanmıştır; ister yirmisinde olsun ister seksenlerinde. Öğrenmeye devam eden genç kalır.",
			"uk":    "Той, хто перестає вчитися, старий — байдуже, двадцять йому чи вісімдесят. Той, хто продовжує вчитися, залишається молодим.",
			"sv":    "Den som slutar lära sig är gammal, vare sig vid tjugo eller åttio. Den som fortsätter lära sig förblir ung.",
			"nl":    "Wie stopt met leren is oud, of je nu twintig bent of tachtig. Wie blijft leren, blijft jong.",
			"nb":    "Den som slutter å lære er gammel, enten han er tjue eller åtti. Den som fortsetter å lære, holder seg ung.",
			"da":    "Den, der holder op med at lære, er gammel, hvad enten han er tyve eller firs. Den, der bliver ved med at lære, forbliver ung.",
			"fi":    "Se, joka lakkaa oppimasta, on vanha — oli hän kaksikymmentä tai kahdeksankymmentä. Se, joka jatkaa oppimista, pysyy nuorena.",
		},
	},
	{
		ID:       "growth-30",
		Author:   ptr("Bruce Lee"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Absorb what is useful, discard what is useless, add what is specifically your own.",
			"en-GB": "Absorb what is useful, discard what is useless, add what is specifically your own.",
			"pt-PT": "Absorve o que é útil, descarta o que é inútil, adiciona o que é especificamente teu.",
			"pt-BR": "Absorva o que for útil, descarte o que for inútil e adicione o que for especificamente seu.",
			"es":    "Absorbe lo útil, descarta lo inútil, añade lo que es específicamente tuyo.",
			"fr":    "Absorbez ce qui est utile, jetez ce qui est inutile, ajoutez ce qui vous est propre.",
			"de":    "Nimm auf, was nützlich ist, verwirf, was unnütz ist, und füge hinzu, was ganz dein Eigenes ist.",
			"it":    "Assorbi ciò che è utile, scarta ciò che è inutile, aggiungi ciò che è specificamente tuo.",
			"ja":    "有用なものを吸収し、無用なものを捨て、自分ならではのものを加えよ。",
			"zh":    "吸收有用的，摒弃无用的，再加上你独有的。",
			"ko":    "유용한 것은 흡수하고, 쓸모없는 것은 버리고, 온전히 자신만의 것을 더하라.",
			"hi":    "जो उपयोगी है उसे आत्मसात करो, जो व्यर्थ है उसे त्याग दो, और जो विशेष रूप से तुम्हारा है उसे जोड़ो।",
			"pl":    "Przyswajaj to, co użyteczne, odrzucaj to, co bezużyteczne, i dodawaj to, co jest wyłącznie twoje.",
			"tr":    "Yararlı olanı özümse, yararsız olanı at, sana özgü olanı ekle.",
			"uk":    "Вбирай корисне, відкидай непотрібне, додавай те, що є суто твоїм.",
			"sv":    "Ta till dig det användbara, förkasta det oanvändbara och lägg till det som är just ditt eget.",
			"nl":    "Neem op wat nuttig is, verwerp wat nutteloos is, en voeg toe wat specifiek van jou is.",
			"nb":    "Ta til deg det som er nyttig, forkast det som er unyttig, og legg til det som er ditt eget.",
			"da":    "Optag det nyttige, kassér det unyttige, og tilføj det, der er helt dit eget.",
			"fi":    "Omaksu se, mikä on hyödyllistä, hylkää hyödytön ja lisää se, mikä on erityisesti omaasi.",
		},
	},
	{
		ID:       "growth-31",
		Author:   ptr("Chinese Proverb"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Be not afraid of growing slowly, be afraid only of standing still.",
			"en-GB": "Be not afraid of growing slowly, be afraid only of standing still.",
			"pt-PT": "Não tenhas medo de crescer lentamente, tem medo apenas de ficar parado.",
			"pt-BR": "Não tenha medo de crescer lentamente, tenha medo apenas de ficar parado.",
			"es":    "No temas crecer lentamente, teme sólo quedarte quieto.",
			"fr":    "N'ayez pas peur de grandir lentement, ayez seulement peur de rester immobile.",
			"de":    "Fürchte dich nicht vor langsamem Wachstum, fürchte dich nur vor dem Stillstand.",
			"it":    "Non temere di crescere lentamente, temi soltanto di restare fermo.",
			"ja":    "ゆっくり成長することを恐れるな。恐れるべきは、立ち止まることだけだ。",
			"zh":    "不怕慢，只怕站。",
			"ko":    "천천히 자라는 것을 두려워하지 말고, 멈춰 서 있는 것만을 두려워하라.",
			"hi":    "धीरे-धीरे बढ़ने से मत डरो, डरो तो केवल रुक जाने से।",
			"pl":    "Nie bój się rosnąć powoli, bój się jedynie stać w miejscu.",
			"tr":    "Yavaş büyümekten korkma, yalnızca yerinde saymaktan kork.",
			"uk":    "Не бійся рости повільно — бійся лише стояти на місці.",
			"sv":    "Var inte rädd för att växa långsamt, var bara rädd för att stå still.",
			"nl":    "Wees niet bang om langzaam te groeien, wees alleen bang om stil te staan.",
			"nb":    "Vær ikke redd for å vokse langsomt, vær bare redd for å stå stille.",
			"da":    "Vær ikke bange for at vokse langsomt, vær kun bange for at stå stille.",
			"fi":    "Älä pelkää hidasta kasvua, pelkää vain paikallaan pysymistä.",
		},
	},
	{
		ID:       "growth-32",
		Author:   ptr("Ralph Waldo Emerson"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "The only person you are destined to become is the person you decide to be.",
			"en-GB": "The only person you are destined to become is the person you decide to be.",
			"pt-PT": "A única pessoa que estás destinado a ser é a pessoa que decidires ser.",
			"pt-BR": "A única pessoa que você está destinado a se tornar é a pessoa que você decidir ser.",
			"es":    "La única persona que estás destinado a ser es la que tú decidas ser.",
			"fr":    "La seule personne que vous êtes destiné à devenir est celle que vous décidez d'être.",
			"de":    "Der einzige Mensch, der du werden sollst, ist der Mensch, der du dich entscheidest zu sein.",
			"it":    "L'unica persona che sei destinato a diventare è la persona che decidi di essere.",
			"ja":    "あなたがなるべき唯一の人間は、あなたがなろうと決めた人間だ。",
			"zh":    "你唯一注定要成为的人，是你自己决定成为的那个人。",
			"ko":    "당신이 되도록 정해진 유일한 사람은, 당신이 되기로 결심한 사람이다.",
			"hi":    "आप केवल वही व्यक्ति बनने के लिए नियत हैं, जो आप बनने का निर्णय करते हैं।",
			"pl":    "Jedyną osobą, którą masz się stać, jest osoba, którą sam postanowisz być.",
			"tr":    "Olmaya yazgılı olduğun tek kişi, olmaya karar verdiğin kişidir.",
			"uk":    "Єдина людина, якою тобі судилося стати, — це людина, якою ти вирішиш бути.",
			"sv":    "Den enda person du är ämnad att bli är den person du bestämmer dig för att vara.",
			"nl":    "De enige persoon die je voorbestemd bent te worden, is de persoon die je besluit te zijn.",
			"nb":    "Den eneste personen du er bestemt til å bli, er den personen du bestemmer deg for å være.",
			"da":    "Den eneste person, du er bestemt til at blive, er den person, du beslutter dig for at være.",
			"fi":    "Ainoa ihminen, joksi sinun on määrä tulla, on se ihminen, joksi päätät tulla.",
		},
	},
	{
		ID:       "growth-33",
		Author:   ptr("John Henry Newman"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Growth is the only evidence of life.",
			"en-GB": "Growth is the only evidence of life.",
			"pt-PT": "O crescimento é a única evidência de vida.",
			"pt-BR": "O crescimento é a única evidência de vida.",
			"es":    "El crecimiento es la única evidencia de vida.",
			"fr":    "La croissance est la seule preuve de vie.",
			"de":    "Wachstum ist der einzige Beweis des Lebens.",
			"it":    "La crescita è l'unica prova della vita.",
			"ja":    "成長こそ、生きていることの唯一の証である。",
			"zh":    "成长是生命唯一的证明。",
			"ko":    "성장은 살아 있음의 유일한 증거다.",
			"hi":    "विकास ही जीवन का एकमात्र प्रमाण है।",
			"pl":    "Wzrost jest jedynym dowodem życia.",
			"tr":    "Büyüme, yaşamın tek kanıtıdır.",
			"uk":    "Зростання — єдиний доказ життя.",
			"sv":    "Växande är det enda beviset på liv.",
			"nl":    "Groei is het enige bewijs van leven.",
			"nb":    "Vekst er det eneste beviset på liv.",
			"da":    "Vækst er det eneste bevis på liv.",
			"fi":    "Kasvu on elämän ainoa todiste.",
		},
	},
	{
		ID:       "growth-34",
		Author:   ptr("George Addair"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Everything you've ever wanted is on the other side of fear.",
			"en-GB": "Everything you've ever wanted is on the other side of fear.",
			"pt-PT": "Tudo o que sempre quiseste está do outro lado do medo.",
			"pt-BR": "Tudo o que você sempre quis está do outro lado do medo.",
			"es":    "Todo lo que siempre has querido está al otro lado del miedo.",
			"fr":    "Tout ce que vous avez toujours voulu se trouve de l'autre côté de la peur.",
			"de":    "Alles, was du dir je gewünscht hast, liegt auf der anderen Seite der Angst.",
			"it":    "Tutto ciò che hai sempre desiderato è dall'altra parte della paura.",
			"ja":    "あなたが望んできたすべては、恐れの向こう側にある。",
			"zh":    "你想要的一切，都在恐惧的另一边。",
			"ko":    "당신이 원해 온 모든 것은 두려움 너머에 있다.",
			"hi":    "जो कुछ भी आपने कभी चाहा है, वह डर के उस पार है।",
			"pl":    "Wszystko, czego kiedykolwiek pragnąłeś, jest po drugiej stronie strachu.",
			"tr":    "Şimdiye dek istediğin her şey, korkunun öte yanındadır.",
			"uk":    "Усе, чого ти будь-коли прагнув, — по той бік страху.",
			"sv":    "Allt du någonsin velat ha finns på andra sidan rädslan.",
			"nl":    "Alles wat je ooit hebt gewild, ligt aan de andere kant van de angst.",
			"nb":    "Alt du noen gang har ønsket deg, ligger på den andre siden av frykten.",
			"da":    "Alt, hvad du nogensinde har ønsket dig, ligger på den anden side af frygten.",
			"fi":    "Kaikki mitä olet koskaan halunnut on pelon toisella puolella.",
		},
	},
	{
		ID:       "growth-35",
		Author:   ptr("Albert Einstein"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "In the middle of a difficulty lies opportunity.",
			"en-GB": "In the middle of a difficulty lies opportunity.",
			"pt-PT": "No meio da dificuldade encontra-se a oportunidade.",
			"pt-BR": "No meio da dificuldade encontra-se a oportunidade.",
			"es":    "En medio de la dificultad reside la oportunidad.",
			"fr":    "Au milieu de la difficulté se trouve l'opportunité.",
			"de":    "Inmitten der Schwierigkeit liegt die Gelegenheit.",
			"it":    "Nel mezzo delle difficoltà nascono le opportunità.",
			"ja":    "困難の中にこそ、好機がある。",
			"zh":    "困难之中蕴藏着机遇。",
			"ko":    "어려움의 한가운데에 기회가 있다.",
			"hi":    "कठिनाई के बीच में ही अवसर छिपा होता है।",
			"pl":    "W środku trudności leży szansa.",
			"tr":    "Zorluğun ortasında fırsat yatar.",
			"uk":    "Посеред труднощів криється можливість.",
			"sv":    "Mitt i svårigheten ligger möjligheten.",
			"nl":    "Midden in de moeilijkheid ligt de kans.",
			"nb":    "Midt i vanskeligheten ligger muligheten.",
			"da":    "Midt i vanskeligheden ligger muligheden.",
			"fi":    "Vaikeuden keskellä piilee mahdollisuus.",
		},
	},
	{
		ID:       "growth-36",
		Author:   ptr("Alan Cohen"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Personal growth is not a matter of learning new information but of unlearning old limits.",
			"en-GB": "Personal growth is not a matter of learning new information but of unlearning old limits.",
			"pt-PT": "O crescimento pessoal não é uma questão de aprender novas informações, mas de desaprender velhos limites.",
			"pt-BR": "O crescimento pessoal não é uma questão de aprender novas informações, mas de desaprender velhos limites.",
			"es":    "El crecimiento personal no es una cuestión de aprender nueva información, sino de desaprender viejos límites.",
			"fr":    "La croissance personnelle n'est pas une question d'apprentissage de nouvelles informations, mais de désapprentissage des anciennes limites.",
			"de":    "Persönliches Wachstum bedeutet nicht, neues Wissen zu erwerben, sondern alte Grenzen zu verlernen.",
			"it":    "La crescita personale non consiste nell'apprendere nuove informazioni ma nel disimparare vecchi limiti.",
			"ja":    "自己成長とは、新しい知識を学ぶことではなく、古い限界を手放すことである。",
			"zh":    "个人成长不在于学习新知识，而在于卸下旧有的限制。",
			"ko":    "자기 성장은 새로운 지식을 배우는 것이 아니라 낡은 한계를 지우는 것이다.",
			"hi":    "व्यक्तिगत विकास नई जानकारी सीखने की बात नहीं, बल्कि पुरानी सीमाओं को भुलाने की बात है।",
			"pl":    "Rozwój osobisty to nie kwestia uczenia się nowych informacji, lecz oduczania się dawnych ograniczeń.",
			"tr":    "Kişisel gelişim yeni bilgiler öğrenmek değil, eski sınırları unutmaktır.",
			"uk":    "Особисте зростання — це не засвоєння нової інформації, а звільнення від старих обмежень.",
			"sv":    "Personlig utveckling handlar inte om att lära sig ny information utan om att lära bort gamla begränsningar.",
			"nl":    "Persoonlijke groei is geen kwestie van nieuwe informatie leren, maar van oude beperkingen afleren.",
			"nb":    "Personlig vekst handler ikke om å lære ny informasjon, men om å avlære gamle begrensninger.",
			"da":    "Personlig vækst handler ikke om at lære ny viden, men om at aflære gamle begrænsninger.",
			"fi":    "Henkilökohtaisessa kasvussa ei ole kyse uuden tiedon oppimisesta, vaan vanhoista rajoituksista poisoppimisesta.",
		},
	},
	{
		ID:       "growth-37",
		Author:   ptr("Warren Buffett"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "The greatest investment you can make is in yourself.",
			"en-GB": "The greatest investment you can make is in yourself.",
			"pt-PT": "O maior investimento que podes fazer é em ti próprio.",
			"pt-BR": "O maior investimento que você pode fazer é em você mesmo.",
			"es":    "La mejor inversión que puedes hacer es en ti mismo.",
			"fr":    "Le meilleur investissement que vous puissiez faire est en vous-même.",
			"de":    "Die beste Investition, die du machen kannst, ist die in dich selbst.",
			"it":    "Il miglior investimento che puoi fare è su te stesso.",
			"ja":    "できる最大の投資は、自分自身への投資である。",
			"zh":    "你能做的最好的投资，就是投资自己。",
			"ko":    "당신이 할 수 있는 최고의 투자는 자기 자신에 대한 투자다.",
			"hi":    "सबसे बड़ा निवेश जो आप कर सकते हैं, वह है ख़ुद में निवेश।",
			"pl":    "Największą inwestycją, jaką możesz poczynić, jest inwestycja w siebie.",
			"tr":    "Yapabileceğin en büyük yatırım kendine yaptığındır.",
			"uk":    "Найкраща інвестиція, яку ти можеш зробити, — у самого себе.",
			"sv":    "Den största investering du kan göra är i dig själv.",
			"nl":    "De beste investering die je kunt doen, is in jezelf.",
			"nb":    "Den beste investeringen du kan gjøre, er i deg selv.",
			"da":    "Den bedste investering, du kan foretage, er i dig selv.",
			"fi":    "Paras sijoitus, jonka voit tehdä, on sijoitus itseesi.",
		},
	},
	{
		ID:       "growth-38",
		Author:   ptr("Aristotle"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
			"en-GB": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
			"pt-PT": "Somos o que fazemos repetidamente. A excelência, então, não é um ato, mas um hábito.",
			"pt-BR": "Nós somos o que fazemos repetidamente. A excelência, então, não é um ato, mas um hábito.",
			"es":    "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.",
			"fr":    "Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas um acte, mais une habitude.",
			"de":    "Wir sind, was wir wiederholt tun. Vortrefflichkeit ist daher keine Handlung, sondern eine Gewohnheit.",
			"it":    "Siamo ciò che facciamo ripetutamente. L'eccellenza, quindi, non è un atto, ma un'abitudine.",
			"ja":    "私たちは繰り返し行うことの積み重ねでできている。ゆえに卓越とは行為ではなく、習慣である。",
			"zh":    "我们由反复的行为造就。因此，卓越不是一种行为，而是一种习惯。",
			"ko":    "우리는 반복적으로 하는 행동 그 자체다. 그러므로 탁월함은 행위가 아니라 습관이다.",
			"hi":    "हम वही हैं जो हम बार-बार करते हैं। इसलिए उत्कृष्टता कोई कार्य नहीं, बल्कि एक आदत है।",
			"pl":    "Jesteśmy tym, co czynimy wielokrotnie. Doskonałość nie jest więc aktem, lecz nawykiem.",
			"tr":    "Biz, tekrar tekrar yaptıklarımızız. O halde mükemmellik bir eylem değil, bir alışkanlıktır.",
			"uk":    "Ми — це те, що робимо постійно. Отже, досконалість — не вчинок, а звичка.",
			"sv":    "Vi är vad vi upprepade gånger gör. Förträfflighet är därför inte en handling utan en vana.",
			"nl":    "We zijn wat we herhaaldelijk doen. Uitmuntendheid is daarom geen daad, maar een gewoonte.",
			"nb":    "Vi er det vi gjentatte ganger gjør. Fortreffelighet er derfor ikke en handling, men en vane.",
			"da":    "Vi er, hvad vi gentagne gange gør. Fortræffelighed er derfor ikke en handling, men en vane.",
			"fi":    "Olemme sitä, mitä toistuvasti teemme. Erinomaisuus ei siis ole teko, vaan tapa.",
		},
	},
	{
		ID:       "growth-39",
		Author:   ptr("Socrates"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
			"en-GB": "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
			"pt-PT": "O segredo da mudança é focar toda a tua energia, não em lutar contra o velho, mas em construir o novo.",
			"pt-BR": "O segredo da mudança é focar toda a sua energia, não em lutar contra o velho, mas em construir o novo.",
			"es":    "El secreto del cambio consiste en centrar toda tu energía, no en luchar contra lo viejo, sino en construir lo nuevo.",
			"fr":    "Le secret du changement consiste à concentrer toute votre énergie, non pas à combattre l'ancien, mais à construire le nouveau.",
			"de":    "Das Geheimnis der Veränderung besteht darin, all deine Energie nicht auf den Kampf gegen das Alte zu richten, sondern auf den Aufbau des Neuen.",
			"it":    "Il segreto del cambiamento è concentrare tutta la tua energia non nel combattere il vecchio, ma nel costruire il nuovo.",
			"ja":    "変化の秘訣は、古いものと戦うことではなく、新しいものを築くことに全エネルギーを注ぐことである。",
			"zh":    "改变的秘诀，是把所有精力放在建设新事物上，而不是与旧事物对抗上。",
			"ko":    "변화의 비결은 낡은 것과 싸우는 데가 아니라 새로운 것을 세우는 데 온 에너지를 쏟는 것이다.",
			"hi":    "बदलाव का रहस्य है अपनी सारी ऊर्जा पुराने से लड़ने में नहीं, बल्कि नए के निर्माण में लगाना।",
			"pl":    "Sekret zmiany polega na tym, by całą energię skupić nie na walce ze starym, lecz na budowaniu nowego.",
			"tr":    "Değişimin sırrı, tüm enerjini eskiyle savaşmaya değil, yeniyi inşa etmeye odaklamaktır.",
			"uk":    "Секрет змін у тому, щоб зосередити всю енергію не на боротьбі зі старим, а на побудові нового.",
			"sv":    "Hemligheten med förändring är att rikta all din energi, inte på att bekämpa det gamla, utan på att bygga det nya.",
			"nl":    "Het geheim van verandering is al je energie te richten, niet op het bestrijden van het oude, maar op het bouwen van het nieuwe.",
			"nb":    "Hemmeligheten bak forandring er å rette all energien din, ikke mot å bekjempe det gamle, men mot å bygge det nye.",
			"da":    "Hemmeligheden bag forandring er at rette al din energi, ikke mod at bekæmpe det gamle, men mod at bygge det nye.",
			"fi":    "Muutoksen salaisuus on keskittää kaikki energiasi vanhan vastustamisen sijaan uuden rakentamiseen.",
		},
	},
	{
		ID:       "growth-40",
		Author:   ptr("Maya Angelou"),
		Category: "growth",
		Translations: map[string]string{
			"en-US": "Do the best you can until you know better. Then when you know better, do better.",
			"en-GB": "Do the best you can until you know better. Then when you know better, do better.",
			"pt-PT": "Faz o melhor que puderes até saberes mais. Então, quando souberes mais, faz melhor.",
			"pt-BR": "Faça o melhor que puder até saber mais. Então, quando souber mais, faça melhor.",
			"es":    "Hazlo lo mejor que puedas hasta que sepas más. Luego, cuando sepas más, hazlo mejor.",
			"fr":    "Faites de votre mieux jusqu'à ce que vous sachiez mieux. Puis, quand vous saurez mieux, agissez mieux.",
			"de":    "Tu dein Bestes, bis du es besser weißt. Und wenn du es besser weißt, dann mach es besser.",
			"it":    "Fai del tuo meglio finché non sai fare di meglio. E quando sai fare di meglio, fai di meglio.",
			"ja":    "より良い方法を知るまでは、精一杯やればいい。そして知ったなら、より良くやればいい。",
			"zh":    "在懂得更多之前，尽力而为。当你懂得更多时，就做得更好。",
			"ko":    "더 잘 알게 되기 전까지는 최선을 다하라. 그리고 더 잘 알게 되면, 더 잘하라.",
			"hi":    "जब तक बेहतर न जानो, अपना सर्वश्रेष्ठ करो। और जब बेहतर जान जाओ, तो बेहतर करो।",
			"pl":    "Rób, co możesz najlepiej, dopóki nie wiesz więcej. A gdy już wiesz więcej, rób lepiej.",
			"tr":    "Daha iyisini öğrenene dek elinden gelenin en iyisini yap. Daha iyisini öğrendiğinde, daha iyisini yap.",
			"uk":    "Роби якнайкраще, поки не знаєш, як краще. А коли дізнаєшся — роби краще.",
			"sv":    "Gör ditt bästa tills du vet bättre. När du vet bättre, gör bättre.",
			"nl":    "Doe je best tot je beter weet. En als je beter weet, doe het dan beter.",
			"nb":    "Gjør ditt beste til du vet bedre. Når du vet bedre, gjør det bedre.",
			"da":    "Gør dit bedste, indtil du ved bedre. Når du ved bedre, så gør det bedre.",
			"fi":    "Tee parhaasi, kunnes tiedät paremmin. Kun tiedät paremmin, tee paremmin.",
		},
	},
}
