package quote

var resilienceQuotes = []QuoteData{
	{
		ID:       "resilience-1",
		Author:   ptr("Confucius"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "It does not matter how slowly you go as long as you do not stop.",
			"en-GB": "It does not matter how slowly you go as long as you do not stop.",
			"pt-PT": "Não importa o quão devagar vais, desde que não pares.",
			"pt-BR": "Não importa o quão devagar você vá, desde que não pare.",
			"es":    "No importa cuán lento vayas, siempre y cuando no te detengas.",
			"fr":    "Peu importe la lenteur à laquelle vous allez, tant que vous ne vous arrêtez pas.",
			"de":    "Es ist egal, wie langsam du gehst, solange du nicht stehen bleibst.",
			"it":    "Non importa quanto vai piano, l'importante è non fermarsi.",
			"ja":    "どんなにゆっくりでも、止まらなければよい。",
			"zh":    "不怕慢，只怕停。",
			"ko":    "멈추지 않는 한, 얼마나 천천히 가는지는 중요하지 않다.",
			"hi":    "आप कितनी भी धीमी गति से चलें, फ़र्क़ नहीं पड़ता—बस रुकिए मत।",
			"pl":    "Nieważne, jak wolno idziesz, dopóki się nie zatrzymujesz.",
			"tr":    "Durmadığın sürece ne kadar yavaş gittiğinin önemi yok.",
			"uk":    "Неважливо, як повільно ти йдеш, головне — не зупинятися.",
			"sv":    "Det spelar ingen roll hur långsamt du går, så länge du inte stannar.",
			"nl":    "Het maakt niet uit hoe langzaam je gaat, zolang je maar niet stopt.",
			"nb":    "Det spiller ingen rolle hvor sakte du går, så lenge du ikke stopper.",
			"da":    "Det betyder ikke noget, hvor langsomt du går, så længe du ikke standser.",
			"fi":    "Ei ole väliä kuinka hitaasti kuljet, kunhan et pysähdy.",
		},
	},
	{
		ID:       "resilience-2",
		Author:   ptr("Winston Churchill"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
			"en-GB": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
			"pt-PT": "O sucesso não é final, o fracasso não é fatal: o que conta é a coragem de continuar.",
			"pt-BR": "O sucesso não é final, o fracasso não é fatal: o que conta é a coragem de continuar.",
			"es":    "El éxito no es el final, el fracaso no es fatal: es el coraje para continuar lo que cuenta.",
			"fr":    "Le succès n'est pas définitif, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
			"de":    "Erfolg ist nicht endgültig, Scheitern ist nicht tödlich: Was zählt, ist der Mut, weiterzumachen.",
			"it":    "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di continuare.",
			"ja":    "成功は終わりではなく、失敗は致命的ではない。大切なのは続ける勇気である。",
			"zh":    "成功不是终点，失败也非末日：重要的是继续前行的勇气。",
			"ko":    "성공은 끝이 아니고 실패는 치명적이지 않다. 중요한 것은 계속해 나갈 용기다.",
			"hi":    "सफलता अंतिम नहीं है, असफलता घातक नहीं है: मायने रखता है आगे बढ़ते रहने का साहस।",
			"pl":    "Sukces nie jest ostateczny, porażka nie jest śmiertelna: liczy się odwaga, by iść dalej.",
			"tr":    "Başarı nihai değildir, başarısızlık ölümcül değildir: Önemli olan devam etme cesaretidir.",
			"uk":    "Успіх не остаточний, поразка не смертельна: важлива лише мужність продовжувати.",
			"sv":    "Framgång är inte slutgiltig, misslyckande är inte ödesdigert: det är modet att fortsätta som räknas.",
			"nl":    "Succes is niet definitief, falen is niet fataal: het is de moed om door te gaan die telt.",
			"nb":    "Suksess er ikke endelig, nederlag er ikke fatalt: det er motet til å fortsette som teller.",
			"da":    "Succes er ikke endelig, nederlag er ikke fatalt: det er modet til at fortsætte, der tæller.",
			"fi":    "Menestys ei ole lopullista, epäonnistuminen ei ole kohtalokasta: ratkaisevaa on rohkeus jatkaa.",
		},
	},
	{
		ID:       "resilience-3",
		Author:   ptr("C.S. Lewis"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Hardships often prepare ordinary people for an extraordinary destiny.",
			"en-GB": "Hardships often prepare ordinary people for an extraordinary destiny.",
			"pt-PT": "As dificuldades muitas vezes preparam pessoas comuns para um destino extraordinário.",
			"pt-BR": "As dificuldades muitas vezes preparam pessoas comuns para um destino extraordinário.",
			"es":    "Las dificultades a menudo preparan a personas comunes para un destino extraordinario.",
			"fr":    "Les épreuves préparent souvent les gens ordinaires à un destin extraordinaire.",
			"de":    "Härten bereiten gewöhnliche Menschen oft auf ein außergewöhnliches Schicksal vor.",
			"it":    "Le avversità spesso preparano persone comuni a un destino straordinario.",
			"ja":    "苦難はしばしば、平凡な人を非凡な運命へと導く準備となる。",
			"zh":    "苦难往往是在为平凡的人准备不平凡的命运。",
			"ko":    "고난은 종종 평범한 사람을 비범한 운명으로 이끌 준비를 시킨다.",
			"hi":    "कठिनाइयाँ अक्सर साधारण लोगों को असाधारण नियति के लिए तैयार करती हैं।",
			"pl":    "Trudy często przygotowują zwykłych ludzi do niezwykłego przeznaczenia.",
			"tr":    "Zorluklar çoğu zaman sıradan insanları olağanüstü bir kadere hazırlar.",
			"uk":    "Труднощі часто готують звичайних людей до незвичайної долі.",
			"sv":    "Prövningar förbereder ofta vanliga människor för ett ovanligt öde.",
			"nl":    "Tegenslagen bereiden gewone mensen vaak voor op een buitengewone bestemming.",
			"nb":    "Motgang forbereder ofte vanlige mennesker på en usedvanlig skjebne.",
			"da":    "Modgang forbereder ofte almindelige mennesker på en usædvanlig skæbne.",
			"fi":    "Vastoinkäymiset valmistavat usein tavallisia ihmisiä epätavalliseen kohtaloon.",
		},
	},
	{
		ID:       "resilience-4",
		Author:   ptr("Nelson Mandela"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Do not judge me by my success, judge me by how many times I fell down and got back up again.",
			"en-GB": "Do not judge me by my success, judge me by how many times I fell down and got back up again.",
			"pt-PT": "Não me julgues pelo meu sucesso, julga-me pelo número de vezes que caí e me levantei novamente.",
			"pt-BR": "Não me julgue pelo meu sucesso, julgue-me pelo número de vezes que caí e me levantei novamente.",
			"es":    "No me juzgues por mis éxitos, júzgame por cuántas veces me caí y volví a levantarme.",
			"fr":    "Ne me jugez pas sur mes succès, jugez-moi sur le nombre de fois où je suis tombé et où je me suis relevé.",
			"de":    "Beurteile mich nicht nach meinen Erfolgen, sondern danach, wie oft ich hingefallen und wieder aufgestanden bin.",
			"it":    "Non giudicarmi dai miei successi, giudicami da quante volte sono caduto e mi sono rialzato.",
			"ja":    "私を成功で判断するな。何度倒れ、何度立ち上がったかで判断してほしい。",
			"zh":    "不要以成功评判我，要看我跌倒了多少次又重新站起来。",
			"ko":    "나를 성공으로 평가하지 말고, 몇 번 넘어졌다가 다시 일어났는지로 평가하라.",
			"hi":    "मुझे मेरी सफलता से मत आँको, इससे आँको कि मैं कितनी बार गिरा और फिर उठ खड़ा हुआ।",
			"pl":    "Nie oceniaj mnie po sukcesach, oceń mnie po tym, ile razy upadłem i znów się podniosłem.",
			"tr":    "Beni başarımla yargılama; kaç kez düşüp yeniden ayağa kalktığımla yargıla.",
			"uk":    "Не суди мене за успіхами — суди за тим, скільки разів я падав і знову підводився.",
			"sv":    "Döm mig inte efter mina framgångar, döm mig efter hur många gånger jag föll och reste mig igen.",
			"nl":    "Beoordeel me niet op mijn succes, maar op hoe vaak ik viel en weer opstond.",
			"nb":    "Døm meg ikke etter min suksess, døm meg etter hvor mange ganger jeg falt og reiste meg igjen.",
			"da":    "Døm mig ikke på min succes, døm mig på, hvor mange gange jeg faldt og rejste mig igen.",
			"fi":    "Älä arvioi minua menestykseni perusteella, vaan sen mukaan, kuinka monta kertaa kaaduin ja nousin taas ylös.",
		},
	},
	{
		ID:       "resilience-5",
		Author:   ptr("Maya Angelou"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "I can be changed by what happens to me. But I refuse to be reduced by it.",
			"en-GB": "I can be changed by what happens to me. But I refuse to be reduced by it.",
			"pt-PT": "Posso ser mudada pelo que me acontece. Mas recuso-me a ser reduzida por isso.",
			"pt-BR": "Posso ser mudada pelo que me acontece. Mas recuso-me a ser reduzida por isso.",
			"es":    "Puedo ser cambiado por lo que me sucede. Pero me niego a ser reducido por ello.",
			"fr":    "Je peux être changé par ce qui m'arrive. Mais je refuse d'en être réduit.",
			"de":    "Was mir widerfährt, kann mich verändern. Aber ich weigere mich, davon kleiner gemacht zu werden.",
			"it":    "Ciò che mi accade può cambiarmi. Ma mi rifiuto di esserne sminuito.",
			"ja":    "起こった出来事が私を変えることはあっても、私はそれによって小さくされることを拒む。",
			"zh":    "遭遇可以改变我，但我拒绝被它贬低。",
			"ko":    "내게 일어나는 일이 나를 바꿀 수는 있다. 그러나 나는 그것에 의해 작아지기를 거부한다.",
			"hi":    "जो मेरे साथ होता है, वह मुझे बदल सकता है। पर मैं उससे छोटा होने से इनकार करती हूँ।",
			"pl":    "To, co mnie spotyka, może mnie zmienić. Ale nie pozwolę, by mnie pomniejszyło.",
			"tr":    "Başıma gelenler beni değiştirebilir. Ama onlar tarafından küçültülmeyi reddediyorum.",
			"uk":    "Те, що зі мною стається, може мене змінити. Але я відмовляюся дозволити цьому мене применшити.",
			"sv":    "Jag kan förändras av det som händer mig. Men jag vägrar att förminskas av det.",
			"nl":    "Ik kan veranderd worden door wat mij overkomt. Maar ik weiger erdoor verkleind te worden.",
			"nb":    "Jeg kan bli forandret av det som skjer meg. Men jeg nekter å bli forminsket av det.",
			"da":    "Jeg kan blive forandret af det, der sker mig. Men jeg nægter at blive formindsket af det.",
			"fi":    "Se mitä minulle tapahtuu voi muuttaa minua. Mutta kieltäydyn antamasta sen pienentää minua.",
		},
	},
	{
		ID:       "resilience-6",
		Author:   ptr("Helen Keller"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Although the world is full of suffering, it is also full of the overcoming of it.",
			"en-GB": "Although the world is full of suffering, it is also full of the overcoming of it.",
			"pt-PT": "Embora o mundo esteja cheio de sofrimento, também está cheio de superação do mesmo.",
			"pt-BR": "Embora o mundo esteja cheio de sofrimento, também está cheio de superação do mesmo.",
			"es":    "Aunque el mundo está lleno de sufrimiento, también está lleno de su superación.",
			"fr":    "Bien que le monde soit plein de souffrance, il est aussi plein de la façon de la surmonter.",
			"de":    "Obwohl die Welt voller Leid ist, ist sie auch voll von dessen Überwindung.",
			"it":    "Sebbene il mondo sia pieno di sofferenza, è anche pieno di vittorie su di essa.",
			"ja":    "世界は苦しみに満ちているが、それを乗り越える力にも満ちている。",
			"zh":    "世界固然充满苦难，但也充满对苦难的战胜。",
			"ko":    "세상은 고통으로 가득하지만, 그것을 이겨 내는 일로도 가득하다.",
			"hi":    "यद्यपि दुनिया दुखों से भरी है, यह उन पर विजय से भी भरी है।",
			"pl":    "Choć świat jest pełen cierpienia, jest też pełen jego przezwyciężania.",
			"tr":    "Dünya acılarla dolu olsa da, o acıların üstesinden gelmekle de doludur.",
			"uk":    "Хоча світ повний страждань, він також повний їх подолання.",
			"sv":    "Även om världen är full av lidande är den också full av dess övervinnande.",
			"nl":    "Hoewel de wereld vol lijden is, is ze ook vol van het overwinnen ervan.",
			"nb":    "Selv om verden er full av lidelse, er den også full av overvinnelse av den.",
			"da":    "Selvom verden er fuld af lidelse, er den også fuld af dens overvindelse.",
			"fi":    "Vaikka maailma on täynnä kärsimystä, se on myös täynnä sen voittamista.",
		},
	},
	{
		ID:       "resilience-7",
		Author:   ptr("Japanese Proverb"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Fall seven times, stand up eight.",
			"en-GB": "Fall seven times, stand up eight.",
			"pt-PT": "Cai sete vezes, levanta-te oito.",
			"pt-BR": "Cair sete vezes, levantar oito.",
			"es":    "Cáete siete veces, levántate ocho.",
			"fr":    "Tombe sept fois, relève-toi huit.",
			"de":    "Siebenmal hinfallen, achtmal aufstehen.",
			"it":    "Cadi sette volte, rialzati otto.",
			"ja":    "七転び八起き。",
			"zh":    "七倒八起。",
			"ko":    "일곱 번 넘어져도 여덟 번 일어나라.",
			"hi":    "सात बार गिरो, आठ बार उठो।",
			"pl":    "Upadnij siedem razy, wstań osiem.",
			"tr":    "Yedi kez düş, sekiz kez kalk.",
			"uk":    "Впади сім разів — підведися вісім.",
			"sv":    "Fall sju gånger, res dig åtta.",
			"nl":    "Val zeven keer, sta acht keer op.",
			"nb":    "Fall sju ganger, reis deg åtte.",
			"da":    "Fald syv gange, rejs dig otte.",
			"fi":    "Kaadu seitsemän kertaa, nouse kahdeksan.",
		},
	},
	{
		ID:       "resilience-8",
		Author:   ptr("Steve Goodier"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "My scars remind me that I did indeed survive my deepest wounds.",
			"en-GB": "My scars remind me that I did indeed survive my deepest wounds.",
			"pt-PT": "As minhas cicatrizes lembram-me que sobrevivi de facto às minhas feridas mais profundas.",
			"pt-BR": "Minhas cicatrizes me lembram que eu de fato sobrevivi às minhas feridas mais profundas.",
			"es":    "Mis cicatrices me recuerdan que de hecho sobreviví a mis heridas más profundas.",
			"fr":    "Mes cicatrices me rappellent que j'ai bel et bien survécu à mes blessures les plus profondes.",
			"de":    "Meine Narben erinnern mich daran, dass ich meine tiefsten Wunden tatsächlich überlebt habe.",
			"it":    "Le mie cicatrici mi ricordano che sono davvero sopravvissuto alle mie ferite più profonde.",
			"ja":    "私の傷跡は、最も深い傷さえ確かに生き延びたことを思い出させてくれる。",
			"zh":    "我的伤疤提醒我：最深的伤口，我确实都挺过来了。",
			"ko":    "내 흉터는 내가 가장 깊은 상처마저 정말로 이겨 냈음을 일깨워 준다.",
			"hi":    "मेरे निशान मुझे याद दिलाते हैं कि मैं सचमुच अपने सबसे गहरे घावों से उबर गया।",
			"pl":    "Moje blizny przypominają mi, że naprawdę przetrwałem swoje najgłębsze rany.",
			"tr":    "Yaralarımın izleri, en derin yaralarımdan gerçekten sağ çıktığımı hatırlatıyor bana.",
			"uk":    "Мої шрами нагадують мені, що я справді пережив свої найглибші рани.",
			"sv":    "Mina ärr påminner mig om att jag verkligen överlevde mina djupaste sår.",
			"nl":    "Mijn littekens herinneren me eraan dat ik mijn diepste wonden werkelijk heb overleefd.",
			"nb":    "Arrene mine minner meg om at jeg faktisk overlevde mine dypeste sår.",
			"da":    "Mine ar minder mig om, at jeg faktisk overlevede mine dybeste sår.",
			"fi":    "Arpeni muistuttavat minua siitä, että todella selvisin syvimmistä haavoistani.",
		},
	},
	{
		ID:       "resilience-9",
		Author:   ptr("Gerry Spence"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "I'd rather have a mind opened by wonder than one closed by belief.",
			"en-GB": "I'd rather have a mind opened by wonder than one closed by belief.",
			"pt-PT": "Prefiro ter uma mente aberta pelo espanto do que uma fechada pela crença.",
			"pt-BR": "Prefiro ter uma mente aberta pelo espanto do que uma fechada pela crença.",
			"es":    "Prefiero tener una mente abierta por el asombro que una cerrada por la creencia.",
			"fr":    "Je préfère avoir un esprit ouvert par l'émerveillement qu'un esprit fermé par la croyance.",
			"de":    "Mir ist ein Geist, den das Staunen öffnet, lieber als einer, den der Glaube verschließt.",
			"it":    "Preferisco una mente aperta dalla meraviglia a una chiusa dalla convinzione.",
			"ja":    "信念で閉ざされた心より、驚きで開かれた心を持ちたい。",
			"zh":    "我宁愿拥有一颗被好奇打开的心，也不要一颗被成见关闭的心。",
			"ko":    "믿음으로 닫힌 마음보다 경이로움으로 열린 마음을 갖고 싶다.",
			"hi":    "मैं ऐसा मन चाहूँगा जो विस्मय से खुला हो, न कि ऐसा जो धारणा से बंद हो।",
			"pl":    "Wolę umysł otwarty zdumieniem niż zamknięty przekonaniem.",
			"tr":    "İnançla kapanmış bir zihindense, hayretle açılmış bir zihni yeğlerim.",
			"uk":    "Я волію розум, відкритий подивом, аніж закритий переконанням.",
			"sv":    "Jag vill hellre ha ett sinne öppnat av förundran än ett stängt av övertygelse.",
			"nl":    "Ik heb liever een geest die door verwondering is geopend dan een die door overtuiging is gesloten.",
			"nb":    "Jeg vil heller ha et sinn åpnet av undring enn et lukket av overbevisning.",
			"da":    "Jeg vil hellere have et sind åbnet af undren end et lukket af overbevisning.",
			"fi":    "Haluan mieluummin mielen, jonka ihmetys on avannut, kuin mielen, jonka vakaumus on sulkenut.",
		},
	},
	{
		ID:       "resilience-10",
		Author:   ptr("Epictetus"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "It's not what happens to you, but how you react to it that matters.",
			"en-GB": "It's not what happens to you, but how you react to it that matters.",
			"pt-PT": "Não é o que te acontece, mas como reages a isso que importa.",
			"pt-BR": "Não é o que acontece com você, mas como você reage a isso que importa.",
			"es":    "No es lo que te sucede, sino cómo reaccionas ante ello lo que importa.",
			"fr":    "Ce n'est pas ce qui vous arrive, mais la façon dont vous y réagissez qui compte.",
			"de":    "Es kommt nicht darauf an, was dir widerfährt, sondern wie du darauf reagierst.",
			"it":    "Non è ciò che ti accade che conta, ma come reagisci.",
			"ja":    "大事なのは何が起こるかではなく、それにどう応じるかである。",
			"zh":    "重要的不是发生在你身上的事，而是你如何应对。",
			"ko":    "중요한 것은 당신에게 일어나는 일이 아니라, 그것에 어떻게 반응하는가이다.",
			"hi":    "मायने यह नहीं रखता कि आपके साथ क्या होता है, बल्कि यह कि आप उस पर कैसी प्रतिक्रिया देते हैं।",
			"pl":    "Liczy się nie to, co ci się przydarza, lecz to, jak na to reagujesz.",
			"tr":    "Önemli olan başına ne geldiği değil, ona nasıl tepki verdiğindir.",
			"uk":    "Важливо не те, що з тобою стається, а те, як ти на це реагуєш.",
			"sv":    "Det är inte vad som händer dig som räknas, utan hur du reagerar på det.",
			"nl":    "Het gaat er niet om wat je overkomt, maar hoe je erop reageert.",
			"nb":    "Det er ikke det som skjer med deg som teller, men hvordan du reagerer på det.",
			"da":    "Det afgørende er ikke, hvad der sker dig, men hvordan du reagerer på det.",
			"fi":    "Ratkaisevaa ei ole se, mitä sinulle tapahtuu, vaan miten siihen reagoit.",
		},
	},
	{
		ID:       "resilience-11",
		Author:   ptr("Victor Frankl"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "When we are no longer able to change a situation, we are challenged to change ourselves.",
			"en-GB": "When we are no longer able to change a situation, we are challenged to change ourselves.",
			"pt-PT": "Quando já não somos capazes de mudar uma situação, somos desafiados a mudarmo-nos a nós próprios.",
			"pt-BR": "Quando não somos mais capazes de mudar uma situação, somos desafiados a mudar a nós mesmos.",
			"es":    "Cuando ya no somos capaces de cambiar una situación, nos enfrentamos al desafío de cambiarnos a nosotros mismos.",
			"fr":    "Quand nous ne sommes plus en mesure de changer une situation, nous sommes mis au défi de nous changer nous-mêmes.",
			"de":    "Wenn wir eine Situation nicht mehr ändern können, sind wir herausgefordert, uns selbst zu ändern.",
			"it":    "Quando non siamo più in grado di cambiare una situazione, siamo chiamati a cambiare noi stessi.",
			"ja":    "状況を変えられなくなったとき、私たちは自分自身を変えるという課題に直面する。",
			"zh":    "当我们无法再改变处境时，我们面临的挑战就是改变自己。",
			"ko":    "상황을 바꿀 수 없을 때, 우리는 자신을 바꾸라는 도전에 직면한다.",
			"hi":    "जब हम किसी परिस्थिति को बदल नहीं सकते, तब हमारे सामने ख़ुद को बदलने की चुनौती होती है।",
			"pl":    "Kiedy nie możemy już zmienić sytuacji, stajemy przed wyzwaniem zmiany samych siebie.",
			"tr":    "Bir durumu artık değiştiremediğimizde, kendimizi değiştirme sınavıyla karşı karşıya kalırız.",
			"uk":    "Коли ми більше не можемо змінити ситуацію, перед нами постає виклик змінити самих себе.",
			"sv":    "När vi inte längre kan förändra en situation utmanas vi att förändra oss själva.",
			"nl":    "Wanneer we een situatie niet meer kunnen veranderen, worden we uitgedaagd onszelf te veranderen.",
			"nb":    "Når vi ikke lenger kan endre en situasjon, utfordres vi til å endre oss selv.",
			"da":    "Når vi ikke længere kan ændre en situation, udfordres vi til at ændre os selv.",
			"fi":    "Kun emme enää voi muuttaa tilannetta, haasteemme on muuttaa itseämme.",
		},
	},
	{
		ID:       "resilience-12",
		Author:   ptr("Elbert Hubbard"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "The greatest mistake you can make in life is to be continually fearing you will make one.",
			"en-GB": "The greatest mistake you can make in life is to be continually fearing you will make one.",
			"pt-PT": "O maior erro que podes cometer na vida é ter continuamente medo de cometer um.",
			"pt-BR": "O maior erro que você pode cometer na vida é ter continuamente medo de cometer um.",
			"es":    "El mayor error que puedes cometer en la vida es temer continuamente que cometerás uno.",
			"fr":    "La plus grande erreur que vous puissiez commettre dans la vie est d'avoir continuellement peur d'en commettre une.",
			"de":    "Der größte Fehler, den du im Leben machen kannst, ist, ständig zu fürchten, einen zu machen.",
			"it":    "Il più grande errore che puoi fare nella vita è temere continuamente di commetterne uno.",
			"ja":    "人生で犯しうる最大の過ちは、過ちを犯すことを絶えず恐れることである。",
			"zh":    "人生中最大的错误，就是总是害怕犯错。",
			"ko":    "인생에서 저지를 수 있는 가장 큰 실수는 실수할까 봐 끊임없이 두려워하는 것이다.",
			"hi":    "जीवन में सबसे बड़ी ग़लती यह है कि आप हर समय ग़लती करने से डरते रहें।",
			"pl":    "Największym błędem, jaki możesz popełnić w życiu, jest ciągły strach przed popełnieniem błędu.",
			"tr":    "Hayatta yapabileceğin en büyük hata, sürekli hata yapmaktan korkmaktır.",
			"uk":    "Найбільша помилка, якої можна припуститися в житті, — постійно боятися помилитися.",
			"sv":    "Det största misstaget du kan göra i livet är att ständigt frukta att du ska begå ett.",
			"nl":    "De grootste fout die je in het leven kunt maken, is voortdurend bang zijn er een te maken.",
			"nb":    "Den største feilen du kan gjøre i livet, er å stadig frykte at du skal gjøre en.",
			"da":    "Den største fejl, du kan begå i livet, er hele tiden at frygte, at du begår en.",
			"fi":    "Suurin virhe, jonka voit elämässä tehdä, on jatkuvasti pelätä virheen tekemistä.",
		},
	},
	{
		ID:       "resilience-13",
		Author:   ptr("Robert Frost"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "In three words I can sum up everything I've learned about life: it goes on.",
			"en-GB": "In three words I can sum up everything I've learned about life: it goes on.",
			"pt-PT": "Em três palavras posso resumir tudo o que aprendi sobre a vida: ela continua.",
			"pt-BR": "Em três palavras posso resumir tudo o que aprendi sobre a vida: ela continua.",
			"es":    "En tres palabras puedo resumir todo lo que he aprendido sobre la vida: continúa.",
			"fr":    "En trois mots, je peux résumer tout ce que j'ai appris sur la vie : elle continue.",
			"de":    "In drei Worten kann ich alles zusammenfassen, was ich über das Leben gelernt habe: Es geht weiter.",
			"it":    "In tre parole posso riassumere tutto ciò che ho imparato sulla vita: essa va avanti.",
			"ja":    "人生について学んだすべてを、一言でまとめられる。「それでも続く」。",
			"zh":    "关于人生我学到的一切，可以用三个字概括：会继续。",
			"ko":    "인생에 대해 배운 모든 것을 세 단어로 요약할 수 있다. 그래도 계속된다.",
			"hi":    "जीवन के बारे में मैंने जो कुछ सीखा, उसे तीन शब्दों में कह सकता हूँ: यह चलता रहता है।",
			"pl":    "W trzech słowach mogę podsumować wszystko, czego nauczyłem się o życiu: toczy się dalej.",
			"tr":    "Hayat hakkında öğrendiğim her şeyi üç kelimeyle özetleyebilirim: Devam ediyor.",
			"uk":    "Трьома словами я можу підсумувати все, що дізнався про життя: воно триває далі.",
			"sv":    "Med tre ord kan jag sammanfatta allt jag lärt mig om livet: det går vidare.",
			"nl":    "In drie woorden kan ik alles samenvatten wat ik over het leven heb geleerd: het gaat door.",
			"nb":    "Med tre ord kan jeg oppsummere alt jeg har lært om livet: det går videre.",
			"da":    "Med tre ord kan jeg sammenfatte alt, hvad jeg har lært om livet: det går videre.",
			"fi":    "Kolmella sanalla voin tiivistää kaiken, mitä olen elämästä oppinut: se jatkuu silti.",
		},
	},
	{
		ID:       "resilience-14",
		Author:   ptr("Charles Swindoll"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Life is 10% what happens to you and 90% how you react to it.",
			"en-GB": "Life is 10% what happens to you and 90% how you react to it.",
			"pt-PT": "A vida é 10% o que te acontece e 90% como reages a isso.",
			"pt-BR": "A vida é 10% o que acontece com você e 90% como você reage a isso.",
			"es":    "La vida es un 10% lo que te sucede y un 90% cómo reaccionas ante ello.",
			"fr":    "La vie, c'est 10 % ce qui vous arrive et 90 % la façon dont vous y réagissez.",
			"de":    "Das Leben besteht zu 10 % aus dem, was dir passiert, und zu 90 % daraus, wie du darauf reagierst.",
			"it":    "La vita è per il 10% ciò che ti accade e per il 90% come reagisci.",
			"ja":    "人生の10％は何が起こるかで、90％はそれにどう応じるかで決まる。",
			"zh":    "生活的10%取决于你的遭遇，90%取决于你如何应对。",
			"ko":    "인생의 10%는 당신에게 일어나는 일이고, 90%는 그 일에 어떻게 반응하는가이다.",
			"hi":    "जीवन 10% वह है जो आपके साथ होता है और 90% वह है कि आप उस पर कैसे प्रतिक्रिया करते हैं।",
			"pl":    "Życie to w 10% to, co ci się przydarza, a w 90% to, jak na to reagujesz.",
			"tr":    "Hayat %10 başına gelenler, %90 onlara nasıl tepki verdiğindir.",
			"uk":    "Життя — це 10% того, що з тобою стається, і 90% того, як ти на це реагуєш.",
			"sv":    "Livet är 10 % vad som händer dig och 90 % hur du reagerar på det.",
			"nl":    "Het leven is 10% wat je overkomt en 90% hoe je erop reageert.",
			"nb":    "Livet er 10 % hva som skjer med deg og 90 % hvordan du reagerer på det.",
			"da":    "Livet er 10 % det, der sker dig, og 90 % hvordan du reagerer på det.",
			"fi":    "Elämä on 10 % sitä, mitä sinulle tapahtuu, ja 90 % sitä, miten siihen reagoit.",
		},
	},
	{
		ID:       "resilience-15",
		Author:   ptr("Elizabeth Edwards"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Resilience is accepting your new reality, even if it's less good than the one you had before.",
			"en-GB": "Resilience is accepting your new reality, even if it's less good than the one you had before.",
			"pt-PT": "Resiliência é aceitar a tua nova realidade, mesmo que seja menos boa do que a que tinhas antes.",
			"pt-BR": "Resiliência é aceitar sua nova realidade, mesmo que seja menos boa do que a que você tinha antes.",
			"es":    "La resiliencia consiste en aceptar tu nueva realidad, aunque sea menos buena que la que tenías antes.",
			"fr":    "La résilience consiste à accepter votre nouvelle réalité, même si elle est moins bonne que celle que vous aviez auparavant.",
			"de":    "Resilienz heißt, deine neue Realität anzunehmen, auch wenn sie schlechter ist als die, die du vorher hattest.",
			"it":    "La resilienza è accettare la tua nuova realtà, anche se è meno buona di quella che avevi prima.",
			"ja":    "レジリエンスとは、以前より良くなくても、新しい現実を受け入れることである。",
			"zh":    "韧性就是接受你的新现实，即使它不如从前。",
			"ko":    "회복탄력성이란 새로운 현실이 이전보다 못하더라도 그것을 받아들이는 것이다.",
			"hi":    "लचीलापन है अपनी नई वास्तविकता को स्वीकार करना, भले ही वह पहले वाली से कम अच्छी हो।",
			"pl":    "Odporność to akceptacja nowej rzeczywistości, nawet jeśli jest gorsza od tej, którą miałeś wcześniej.",
			"tr":    "Dayanıklılık, öncekinden daha iyi olmasa bile yeni gerçekliğini kabullenmektir.",
			"uk":    "Стійкість — це прийняти свою нову реальність, навіть якщо вона гірша за ту, що була раніше.",
			"sv":    "Motståndskraft är att acceptera din nya verklighet, även om den är sämre än den du hade förut.",
			"nl":    "Veerkracht is je nieuwe realiteit aanvaarden, ook al is die minder goed dan die je eerst had.",
			"nb":    "Motstandskraft er å akseptere din nye virkelighet, selv om den er mindre god enn den du hadde før.",
			"da":    "Modstandskraft er at acceptere din nye virkelighed, selv om den er mindre god end den, du havde før.",
			"fi":    "Sitkeys on uuden todellisuutesi hyväksymistä, vaikka se olisi huonompi kuin entinen.",
		},
	},
	{
		ID:       "resilience-16",
		Author:   ptr("Haruki Murakami"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "And once the storm is over, you won't remember how you made it through... but one thing is certain. When you come out of the storm, you won't be the same person who walked in.",
			"en-GB": "And once the storm is over, you won't remember how you made it through... but one thing is certain. When you come out of the storm, you won't be the same person who walked in.",
			"pt-PT": "E assim que a tempestade passar, não te lembrarás de como a atravessaste... mas uma coisa é certa. Quando saíres da tempestade, não serás a mesma pessoa que entrou nela.",
			"pt-BR": "E quando a tempestade passar, você não se lembrará de como conseguiu atravessá-la... mas uma coisa é certa. Quando você sair da tempestade, não será a mesma pessoa que entrou nela.",
			"es":    "Y una vez que la tormenta haya pasado, no recordarás cómo lo lograste... pero una cosa es segura. Cuando salgas de la tormenta, no serás la misma persona que entró en ella.",
			"fr":    "Et une fois la tempête passée, vous ne vous rappellerez pas comment vous l'avez traversée... mais une chose est sûre. Quand vous sortirez de la tempête, vous ne serez plus la même personne qu'à l'entrée.",
			"de":    "Und wenn der Sturm vorüber ist, wirst du nicht mehr wissen, wie du ihn überstanden hast … Aber eines ist sicher: Wenn du aus dem Sturm herauskommst, bist du nicht mehr derselbe Mensch, der hineinging.",
			"it":    "E quando la tempesta sarà finita, non ricorderai come hai fatto ad attraversarla... Ma una cosa è certa: quando ne uscirai, non sarai la stessa persona che vi era entrata.",
			"ja":    "嵐が過ぎ去ったとき、どうやって乗り越えたのか覚えていないだろう……だが一つだけ確かなことがある。嵐から出てきたあなたは、そこに入っていったときのあなたではないということだ。",
			"zh":    "暴风雨结束后，你不会记得自己是怎样活下来的……但有一件事是确定的：当你穿过了暴风雨，你早已不再是原来那个人。",
			"ko":    "폭풍이 지나가면 어떻게 견뎌 냈는지 기억나지 않을 것이다... 하지만 한 가지는 확실하다. 폭풍을 빠져나왔을 때, 당신은 들어갈 때의 그 사람이 아니라는 것이다.",
			"hi":    "और जब तूफ़ान थम जाएगा, तुम्हें याद नहीं रहेगा कि तुम उससे कैसे गुज़रे... पर एक बात निश्चित है। जब तुम तूफ़ान से बाहर निकलोगे, तो तुम वह इंसान नहीं रहोगे जो उसमें दाख़िल हुआ था।",
			"pl":    "A kiedy burza minie, nie będziesz pamiętał, jak ją przetrwałeś... Ale jedno jest pewne: gdy z niej wyjdziesz, nie będziesz już tą samą osobą, która w nią weszła.",
			"tr":    "Fırtına dindiğinde, onu nasıl atlattığını hatırlamayacaksın... Ama bir şey kesin: Fırtınadan çıktığında, içine giren kişi olmayacaksın.",
			"uk":    "І коли буря вщухне, ти не пам'ятатимеш, як пройшов крізь неї... Але одне певно: вийшовши з бурі, ти вже не будеш тією людиною, яка в неї увійшла.",
			"sv":    "Och när stormen är över kommer du inte att minnas hur du tog dig igenom... Men en sak är säker. När du kommer ut ur stormen är du inte samma person som gick in.",
			"nl":    "En als de storm voorbij is, weet je niet meer hoe je erdoorheen bent gekomen... Maar één ding is zeker: als je uit de storm komt, ben je niet meer dezelfde persoon die erin ging.",
			"nb":    "Og når stormen er over, vil du ikke huske hvordan du kom deg gjennom... Men én ting er sikkert: Når du kommer ut av stormen, er du ikke den samme personen som gikk inn.",
			"da":    "Og når stormen er ovre, vil du ikke huske, hvordan du kom igennem... Men én ting er sikkert: Når du kommer ud af stormen, er du ikke den samme person, som gik ind.",
			"fi":    "Ja kun myrsky on ohi, et muista, miten selvisit sen läpi... Mutta yksi asia on varma: kun tulet ulos myrskystä, et ole sama ihminen, joka siihen astui.",
		},
	},
	{
		ID:       "resilience-17",
		Author:   ptr("Marcus Aurelius"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "The impediment to commitment advances commitment. What stands in the way becomes the way.",
			"en-GB": "The impediment to commitment advances commitment. What stands in the way becomes the way.",
			"pt-PT": "O impedimento à ação avança a ação. O que está no caminho torna-se o caminho.",
			"pt-BR": "O impedimento à ação promove a ação. O que está no caminho se torna o caminho.",
			"es":    "El impedimento a la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino.",
			"fr":    "L'obstacle à l'commitment fait avancer l'commitment. Ce qui barre le chemin devient le chemin.",
			"de":    "Das Hindernis des Handelns fördert das Handeln. Was im Weg steht, wird zum Weg.",
			"it":    "L'impedimento all'azione fa avanzare l'azione. Ciò che sbarra la strada diventa la strada.",
			"ja":    "行動を妨げるものが、行動を前進させる。道をふさぐものこそが道となる。",
			"zh":    "行动的障碍反而推动行动。挡路之物，终成道路。",
			"ko":    "행동을 가로막는 것이 행동을 전진시킨다. 길을 막는 것이 곧 길이 된다.",
			"hi":    "कर्म की बाधा कर्म को आगे बढ़ाती है। जो राह में खड़ा है, वही राह बन जाता है।",
			"pl":    "Przeszkoda w działaniu popycha działanie naprzód. To, co staje na drodze, staje się drogą.",
			"tr":    "Eylemin önündeki engel, eylemi ilerletir. Yolda duran, yolun kendisi olur.",
			"uk":    "Перешкода дії просуває дію. Те, що стоїть на шляху, стає шляхом.",
			"sv":    "Hindret för handling för handlingen framåt. Det som står i vägen blir vägen.",
			"nl":    "Wat het handelen belemmert, brengt het handelen vooruit. Wat in de weg staat, wordt de weg.",
			"nb":    "Hindringen for handling driver handlingen fremover. Det som står i veien, blir veien.",
			"da":    "Hindringen for handling fremmer handlingen. Det, der står i vejen, bliver vejen.",
			"fi":    "Toiminnan este vie toimintaa eteenpäin. Se mikä on tiellä, siitä tulee tie.",
		},
	},
	{
		ID:       "resilience-18",
		Author:   ptr("Amit Ray"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
			"en-GB": "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
			"pt-PT": "Se queres conquistar a ansiedade da vida, vive o momento, vive a respiração.",
			"pt-BR": "Se você quer conquistar a ansiedade da vida, viva o momento, viva a respiração.",
			"es":    "Si quieres conquistar la ansiedad de la vida, vive el momento, vive la respiración.",
			"fr":    "Si vous voulez vaincre l'anxiété de la vie, vivez l'instant présent, vivez la respiration.",
			"de":    "Wenn du die Angst des Lebens besiegen willst, lebe im Augenblick, lebe im Atem.",
			"it":    "Se vuoi vincere l'ansia della vita, vivi nel momento, vivi nel respiro.",
			"ja":    "人生の不安に打ち勝ちたければ、今この瞬間を生き、呼吸の中に生きよ。",
			"zh":    "想要战胜生活的焦虑，就活在当下，活在呼吸之间。",
			"ko":    "삶의 불안을 이기고 싶다면 지금 이 순간을 살고, 호흡 속에 살아라.",
			"hi":    "अगर जीवन की चिंता को जीतना है, तो वर्तमान क्षण में जियो, साँस में जियो।",
			"pl":    "Jeśli chcesz pokonać lęk życia, żyj chwilą, żyj oddechem.",
			"tr":    "Hayatın kaygısını yenmek istiyorsan, anda yaşa, nefeste yaşa.",
			"uk":    "Якщо хочеш подолати тривогу життя, живи в миті, живи в диханні.",
			"sv":    "Om du vill besegra livets ångest, lev i stunden, lev i andetaget.",
			"nl":    "Als je de angst van het leven wilt overwinnen, leef in het moment, leef in de ademhaling.",
			"nb":    "Vil du overvinne livets angst, lev i øyeblikket, lev i pusten.",
			"da":    "Vil du besejre livets angst, så lev i øjeblikket, lev i åndedrættet.",
			"fi":    "Jos haluat voittaa elämän ahdistuksen, elä hetkessä, elä hengityksessä.",
		},
	},
	{
		ID:       "resilience-19",
		Author:   ptr("Bruce Lee"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Do not pray for an easy life, pray for the strength to endure a difficult one.",
			"en-GB": "Do not pray for an easy life, pray for the strength to endure a difficult one.",
			"pt-PT": "Não peças uma vida fácil, pede força para suportar uma difícil.",
			"pt-BR": "Não peça uma vida fácil, peça força para suportar uma difícil.",
			"es":    "No pidas una vida fácil, pide la fuerza necesaria para soportar una difícil.",
			"fr":    "Ne priez pas pour une vie facile, priez pour avoir la force d'en supporter une difficile.",
			"de":    "Bete nicht um ein leichtes Leben, bete um die Kraft, ein schweres zu ertragen.",
			"it":    "Non pregare per una vita facile, prega per la forza di sopportarne una difficile.",
			"ja":    "楽な人生を祈るな。困難な人生に耐える強さを祈れ。",
			"zh":    "不要祈求安逸的人生，要祈求承受艰难人生的力量。",
			"ko":    "편안한 삶을 기도하지 말고, 힘든 삶을 견딜 힘을 기도하라.",
			"hi":    "आसान जीवन की प्रार्थना मत करो, कठिन जीवन को सहने की शक्ति की प्रार्थना करो।",
			"pl":    "Nie módl się o łatwe życie, módl się o siłę, by znieść trudne.",
			"tr":    "Kolay bir hayat için dua etme; zor bir hayata dayanacak güç için dua et.",
			"uk":    "Не молися про легке життя — молися про силу витримати важке.",
			"sv":    "Be inte om ett lätt liv, be om styrkan att uthärda ett svårt.",
			"nl":    "Bid niet om een gemakkelijk leven, bid om de kracht om een moeilijk leven te doorstaan.",
			"nb":    "Ikke be om et lett liv, be om styrken til å utholde et vanskelig.",
			"da":    "Bed ikke om et let liv, bed om styrken til at udholde et svært.",
			"fi":    "Älä rukoile helppoa elämää, rukoile voimaa kestää vaikea.",
		},
	},
	{
		ID:       "resilience-20",
		Author:   ptr("Friedrich Nietzsche"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "That which does not kill us makes us stronger.",
			"en-GB": "That which does not kill us makes us stronger.",
			"pt-PT": "Aquilo que não nos mata torna-nos mais fortes.",
			"pt-BR": "Aquilo que não nos mata nos torna mais fortes.",
			"es":    "Lo que no nos mata nos hace más fuertes.",
			"fr":    "Tout ce qui ne nous tue pas nous rend plus forts.",
			"de":    "Was uns nicht umbringt, macht uns stärker.",
			"it":    "Ciò che non ci uccide ci rende più forti.",
			"ja":    "私たちを殺さないものは、私たちを強くする。",
			"zh":    "凡不能毁灭我们的，必使我们更强大。",
			"ko":    "우리를 죽이지 못하는 것은 우리를 더 강하게 만든다.",
			"hi":    "जो हमें मारता नहीं, वह हमें और मज़बूत बनाता है।",
			"pl":    "Co nas nie zabije, to nas wzmocni.",
			"tr":    "Bizi öldürmeyen şey güçlendirir.",
			"uk":    "Те, що нас не вбиває, робить нас сильнішими.",
			"sv":    "Det som inte dödar oss gör oss starkare.",
			"nl":    "Wat ons niet doodt, maakt ons sterker.",
			"nb":    "Det som ikke dreper oss, gjør oss sterkere.",
			"da":    "Det, der ikke slår os ihjel, gør os stærkere.",
			"fi":    "Se mikä ei tapa meitä, vahvistaa meitä.",
		},
	},
	{
		ID:       "resilience-21",
		Author:   ptr("Vivian Greene"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Life isn't about waiting for the storm to pass... It's about learning to dance in the rain.",
			"en-GB": "Life isn't about waiting for the storm to pass... It's about learning to dance in the rain.",
			"pt-PT": "A vida não é esperar que a tempestade passe... É aprender a dançar à chuva.",
			"pt-BR": "A vida não é esperar a tempestade passar... É aprender a dançar na chuva.",
			"es":    "La vida no consiste en esperar a que pase la tormenta... consiste en aprender a bailar bajo la lluvia.",
			"fr":    "La vie, ce n'est pas d'attendre que l'orage passe... c'est d'apprendre à danser sous la pluie.",
			"de":    "Im Leben geht es nicht darum, zu warten, bis der Sturm vorbeizieht … sondern zu lernen, im Regen zu tanzen.",
			"it":    "La vita non è aspettare che passi la tempesta... è imparare a ballare sotto la pioggia.",
			"ja":    "人生とは嵐が過ぎるのを待つことではない……雨の中で踊ることを学ぶことである。",
			"zh":    "生活不是等待暴风雨过去……而是学会在雨中起舞。",
			"ko":    "인생은 폭풍이 지나가기를 기다리는 것이 아니라... 빗속에서 춤추는 법을 배우는 것이다.",
			"hi":    "जीवन तूफ़ान के गुज़रने का इंतज़ार करना नहीं है... बल्कि बारिश में नाचना सीखना है।",
			"pl":    "Życie nie polega na czekaniu, aż burza minie... Polega na uczeniu się tańca w deszczu.",
			"tr":    "Hayat fırtınanın dinmesini beklemek değildir... Yağmurda dans etmeyi öğrenmektir.",
			"uk":    "Життя — це не чекання, поки мине буря... Це вміння танцювати під дощем.",
			"sv":    "Livet handlar inte om att vänta på att stormen ska dra förbi... Det handlar om att lära sig dansa i regnet.",
			"nl":    "Het leven gaat niet over wachten tot de storm voorbij is... Het gaat over leren dansen in de regen.",
			"nb":    "Livet handler ikke om å vente på at stormen skal gå over... Det handler om å lære å danse i regnet.",
			"da":    "Livet handler ikke om at vente på, at stormen driver over... Det handler om at lære at danse i regnen.",
			"fi":    "Elämässä ei ole kyse myrskyn laantumisen odottamisesta... vaan siitä, että oppii tanssimaan sateessa.",
		},
	},
	{
		ID:       "resilience-22",
		Author:   ptr("Martin Luther King Jr."),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "We must accept finite disappointment, but never lose infinite hope.",
			"en-GB": "We must accept finite disappointment, but never lose infinite hope.",
			"pt-PT": "Devemos aceitar a desilusão finita, mas nunca perder a esperança infinita.",
			"pt-BR": "Devemos aceitar a decepção finita, mas nunca perder a esperança infinita.",
			"es":    "Debemos aceptar la decepción finita, pero nunca perder la esperanza infinita.",
			"fr":    "Nous devons accepter une déception finie, mais ne jamais perdre un espoir infini.",
			"de":    "Wir müssen endliche Enttäuschungen hinnehmen, dürfen aber nie die unendliche Hoffnung verlieren.",
			"it":    "Dobbiamo accettare delusioni finite, ma non perdere mai la speranza infinita.",
			"ja":    "有限の失望は受け入れなければならない。しかし無限の希望を失ってはならない。",
			"zh":    "我们必须接受有限的失望，但绝不能失去无限的希望。",
			"ko":    "우리는 유한한 실망은 받아들여야 하지만, 무한한 희망은 결코 잃어서는 안 된다.",
			"hi":    "हमें सीमित निराशा स्वीकार करनी चाहिए, लेकिन असीम आशा कभी नहीं खोनी चाहिए।",
			"pl":    "Musimy pogodzić się ze skończonym rozczarowaniem, ale nigdy nie tracić nieskończonej nadziei.",
			"tr":    "Sonlu hayal kırıklıklarını kabullenmeliyiz ama sonsuz umudu asla yitirmemeliyiz.",
			"uk":    "Ми мусимо приймати скінченні розчарування, але ніколи не втрачати нескінченної надії.",
			"sv":    "Vi måste acceptera ändlig besvikelse, men aldrig förlora oändligt hopp.",
			"nl":    "We moeten eindige teleurstelling aanvaarden, maar nooit de oneindige hoop verliezen.",
			"nb":    "Vi må godta endelig skuffelse, men aldri miste uendelig håp.",
			"da":    "Vi må acceptere endelig skuffelse, men aldrig miste uendeligt håb.",
			"fi":    "Meidän on hyväksyttävä rajallinen pettymys, mutta emme saa koskaan menettää rajatonta toivoa.",
		},
	},
	{
		ID:       "resilience-23",
		Author:   ptr("Albert Camus"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "In the midst of winter, I found there was, within me, an invincible summer.",
			"en-GB": "In the midst of winter, I found there was, within me, an invincible summer.",
			"pt-PT": "No meio do inverno, descobri que havia, dentro de mim, um verão invencível.",
			"pt-BR": "No meio do inverno, descobri que havia, dentro de mim, um verão invencível.",
			"es":    "En medio del invierno, descubrí que había en mí un verano invencible.",
			"fr":    "Au milieu de l'hiver, j'ai découvert qu'il y avait en moi un été invincible.",
			"de":    "Mitten im Winter erfuhr ich, dass in mir ein unbesiegbarer Sommer wohnt.",
			"it":    "Nel bel mezzo dell'inverno, ho scoperto che c'era in me un'estate invincibile.",
			"ja":    "冬のさなか、私は自分の中に揺るぎない夏があることを知った。",
			"zh":    "在隆冬，我终于发现，我心中有一个不可战胜的夏天。",
			"ko":    "한겨울에 나는 내 안에 무적의 여름이 있음을 알았다.",
			"hi":    "कड़कड़ाती सर्दी के बीच, मैंने पाया कि मेरे भीतर एक अजेय ग्रीष्म है।",
			"pl":    "W środku zimy odkryłem, że jest we mnie niezwyciężone lato.",
			"tr":    "Kışın ortasında, içimde yenilmez bir yaz olduğunu keşfettim.",
			"uk":    "Посеред зими я відкрив, що в мені живе непереможне літо.",
			"sv":    "Mitt i vintern fann jag att det inom mig fanns en oövervinnerlig sommar.",
			"nl":    "Midden in de winter ontdekte ik dat er in mij een onoverwinnelijke zomer was.",
			"nb":    "Midt på vinteren oppdaget jeg at det i meg fantes en uovervinnelig sommer.",
			"da":    "Midt om vinteren opdagede jeg, at der i mig var en uovervindelig sommer.",
			"fi":    "Keskellä talvea huomasin, että sisälläni oli voittamaton kesä.",
		},
	},
	{
		ID:       "resilience-24",
		Author:   ptr("Roy T. Bennett"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Difficulties strengthen the mind, as labor does the body.",
			"en-GB": "Difficulties strengthen the mind, as labor does the body.",
			"pt-PT": "As dificuldades fortalecem a mente, tal como o trabalho fortalece o corpo.",
			"pt-BR": "As dificuldades fortalecem a mente, assim como o trabalho fortalece o corpo.",
			"es":    "Las dificultades fortalecen la mente, igual que el trabajo fortalece el cuerpo.",
			"fr":    "Les difficultés fortifient l'esprit, tout comme le travail fortifie le corps.",
			"de":    "Schwierigkeiten stärken den Geist, wie Arbeit den Körper.",
			"it":    "Le difficoltà rafforzano la mente, come il lavoro rafforza il corpo.",
			"ja":    "労働が体を鍛えるように、困難は精神を鍛える。",
			"zh":    "困难磨炼心智，正如劳动锻炼身体。",
			"ko":    "노동이 몸을 단련하듯 어려움은 정신을 단련한다.",
			"hi":    "कठिनाइयाँ मन को वैसे ही मज़बूत करती हैं जैसे श्रम शरीर को।",
			"pl":    "Trudności wzmacniają umysł, tak jak praca wzmacnia ciało.",
			"tr":    "Zorluklar zihni güçlendirir, tıpkı emeğin bedeni güçlendirdiği gibi.",
			"uk":    "Труднощі загартовують розум, як праця — тіло.",
			"sv":    "Svårigheter stärker sinnet, liksom arbete stärker kroppen.",
			"nl":    "Moeilijkheden sterken de geest, zoals arbeid het lichaam sterkt.",
			"nb":    "Vanskeligheter styrker sinnet, slik arbeid styrker kroppen.",
			"da":    "Vanskeligheder styrker sindet, ligesom arbejde styrker kroppen.",
			"fi":    "Vaikeudet vahvistavat mieltä, kuten työ vahvistaa kehoa.",
		},
	},
	{
		ID:       "resilience-25",
		Author:   ptr("William Ernest Henley"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "I am the master of my fate: I am the captain of my soul.",
			"en-GB": "I am the master of my fate: I am the captain of my soul.",
			"pt-PT": "Eu sou o mestre do meu destino: eu sou o capitão da minha alma.",
			"pt-BR": "Eu sou o mestre do meu destino: eu sou o capitão da minha alma.",
			"es":    "Soy el amo de mi destino: soy el capitán de mi alma.",
			"fr":    "Je suis le maître de mon destin : je suis le capitaine de mon âme.",
			"de":    "Ich bin der Herr meines Schicksals: Ich bin der Kapitän meiner Seele.",
			"it":    "Sono il padrone del mio destino: sono il capitano della mia anima.",
			"ja":    "私は我が運命の支配者、我が魂の船長である。",
			"zh":    "我是我命运的主人，我是我灵魂的统帅。",
			"ko":    "나는 내 운명의 주인이며, 내 영혼의 선장이다.",
			"hi":    "मैं अपने भाग्य का स्वामी हूँ: मैं अपनी आत्मा का कप्तान हूँ।",
			"pl":    "Jestem panem swojego losu: jestem kapitanem swojej duszy.",
			"tr":    "Kaderimin efendisiyim: Ruhumun kaptanıyım.",
			"uk":    "Я господар своєї долі: я капітан своєї душі.",
			"sv":    "Jag är herre över mitt öde: jag är kapten över min själ.",
			"nl":    "Ik ben de meester van mijn lot: ik ben de kapitein van mijn ziel.",
			"nb":    "Jeg er herre over min skjebne: Jeg er kaptein over min sjel.",
			"da":    "Jeg er herre over min skæbne: Jeg er kaptajn for min sjæl.",
			"fi":    "Olen kohtaloni herra: olen sieluni kapteeni.",
		},
	},
	{
		ID:       "resilience-26",
		Author:   ptr("A.P.J. Abdul Kalam"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Man needs his difficulties because they are necessary to enjoy success.",
			"en-GB": "Man needs his difficulties because they are necessary to enjoy success.",
			"pt-PT": "O homem precisa das suas dificuldades porque são necessárias para desfrutar do sucesso.",
			"pt-BR": "O homem precisa de suas dificuldades porque elas são necessárias para desfrutar do sucesso.",
			"es":    "El hombre necesita sus dificultades porque son necesarias para disfrutar del éxito.",
			"fr":    "L'homme a besoin de ses difficultés car elles sont nécessaires pour savourer le succès.",
			"de":    "Der Mensch braucht seine Schwierigkeiten, denn sie sind nötig, um den Erfolg zu genießen.",
			"it":    "L'uomo ha bisogno delle sue difficoltà, perché sono necessarie per godere del successo.",
			"ja":    "人には困難が必要である。成功を味わうために欠かせないものだからだ。",
			"zh":    "人需要困难，因为唯有经历困难，才能享受成功。",
			"ko":    "인간에게는 어려움이 필요하다. 성공을 누리기 위해 꼭 필요한 것이기 때문이다.",
			"hi":    "मनुष्य को अपनी कठिनाइयों की आवश्यकता है, क्योंकि सफलता का आनंद लेने के लिए वे ज़रूरी हैं।",
			"pl":    "Człowiek potrzebuje trudności, bo są one niezbędne, by cieszyć się sukcesem.",
			"tr":    "İnsanın zorluklara ihtiyacı vardır; çünkü başarının tadını çıkarmak için gereklidirler.",
			"uk":    "Людині потрібні труднощі, адже вони необхідні, щоб насолодитися успіхом.",
			"sv":    "Människan behöver sina svårigheter, för de är nödvändiga för att njuta av framgången.",
			"nl":    "De mens heeft zijn moeilijkheden nodig, want ze zijn noodzakelijk om van succes te genieten.",
			"nb":    "Mennesket trenger sine vanskeligheter, for de er nødvendige for å nyte suksessen.",
			"da":    "Mennesket har brug for sine vanskeligheder, for de er nødvendige for at nyde succesen.",
			"fi":    "Ihminen tarvitsee vaikeutensa, sillä ne ovat välttämättömiä menestyksestä nauttimiseksi.",
		},
	},
	{
		ID:       "resilience-27",
		Author:   ptr("Rumi"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "The wound is the place where the Light enters you.",
			"en-GB": "The wound is the place where the Light enters you.",
			"pt-PT": "A ferida é o lugar onde a Luz entra em ti.",
			"pt-BR": "A ferida é o lugar por onde a luz entra em você.",
			"es":    "La herida es el lugar por donde te entra la Luz.",
			"fr":    "La blessure est l'endroit où la lumière entre en vous.",
			"de":    "Die Wunde ist der Ort, durch den das Licht in dich eintritt.",
			"it":    "La ferita è il luogo da cui la Luce entra in te.",
			"ja":    "傷とは、光があなたの中へ入ってくる場所である。",
			"zh":    "伤口是光进入你内心的地方。",
			"ko":    "상처는 빛이 당신 안으로 들어오는 자리다.",
			"hi":    "घाव वह जगह है जहाँ से रोशनी तुम्हारे भीतर प्रवेश करती है।",
			"pl":    "Rana jest miejscem, przez które wnika w ciebie Światło.",
			"tr":    "Yara, Işığın içine girdiği yerdir.",
			"uk":    "Рана — це місце, крізь яке в тебе входить Світло.",
			"sv":    "Såret är platsen där Ljuset kommer in i dig.",
			"nl":    "De wond is de plek waar het Licht bij je binnenkomt.",
			"nb":    "Såret er stedet der Lyset kommer inn i deg.",
			"da":    "Såret er stedet, hvor Lyset trænger ind i dig.",
			"fi":    "Haava on paikka, josta Valo astuu sisääsi.",
		},
	},
	{
		ID:       "resilience-28",
		Author:   ptr("W. Clement Stone"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
			"en-GB": "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
			"pt-PT": "Cada adversidade, cada fracasso, cada mágoa traz consigo a semente de um benefício igual ou maior.",
			"pt-BR": "Cada adversidade, cada fracasso, cada mágoa traz consigo a semente de um benefício igual ou maior.",
			"es":    "Toda adversidad, todo fracaso, toda angustia lleva consigo la semilla de un beneficio igual o mayor.",
			"fr":    "Chaque adversité, chaque échec, chaque chagrin d'amour porte en lui la graine d'un avantage égal ou supérieur.",
			"de":    "Jedes Unglück, jedes Scheitern, jeder Kummer trägt den Keim eines gleich großen oder größeren Vorteils in sich.",
			"it":    "Ogni avversità, ogni fallimento, ogni dolore porta con sé il seme di un beneficio uguale o maggiore.",
			"ja":    "あらゆる逆境、あらゆる失敗、あらゆる心痛は、それと同等かそれ以上の恩恵の種を宿している。",
			"zh":    "每一次逆境、每一次失败、每一次心痛，都蕴含着同等或更大益处的种子。",
			"ko":    "모든 역경, 모든 실패, 모든 아픔은 그와 같거나 더 큰 이로움의 씨앗을 품고 있다.",
			"hi":    "हर विपत्ति, हर असफलता, हर पीड़ा अपने साथ उतने ही या उससे बड़े लाभ का बीज लेकर आती है।",
			"pl":    "Każda przeciwność, każda porażka, każdy ból serca niesie w sobie ziarno równej lub większej korzyści.",
			"tr":    "Her sıkıntı, her başarısızlık, her keder, kendisiyle eşit ya da daha büyük bir yararın tohumunu taşır.",
			"uk":    "Кожна негода, кожна невдача, кожен біль несуть у собі зерно рівної або більшої вигоди.",
			"sv":    "Varje motgång, varje misslyckande, varje hjärtesorg bär med sig fröet till en lika stor eller större fördel.",
			"nl":    "Elke tegenslag, elke mislukking, elk verdriet draagt het zaad van een gelijk of groter voordeel in zich.",
			"nb":    "Enhver motgang, ethvert nederlag, enhver hjertesorg bærer med seg frøet til en like stor eller større fordel.",
			"da":    "Enhver modgang, ethvert nederlag, enhver hjertesorg bærer i sig frøet til en lige så stor eller større fordel.",
			"fi":    "Jokainen vastoinkäyminen, jokainen epäonnistuminen, jokainen sydänsuru kantaa mukanaan yhtä suuren tai suuremman hyödyn siemenen.",
		},
	},
	{
		ID:       "resilience-29",
		Author:   ptr("Viktor Frankl"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.",
			"en-GB": "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.",
			"pt-PT": "Tudo pode ser tirado de um homem, exceto uma coisa: a última das liberdades humanas — escolher a sua atitude em qualquer conjunto de circunstâncias, escolher o seu próprio caminho.",
			"pt-BR": "Tudo pode ser tirado de um homem, exceto uma coisa: a última das liberdades humanas — a de escolher sua atitude em qualquer conjunto de circunstâncias, a de escolher seu próprio caminho.",
			"es":    "A un hombre se le puede quitar todo, menos una cosa: la última de las libertades humanas —la de elegir su actitud ante cualquier serie de circunstancias, la de elegir su propio camino.",
			"fr":    "On peut tout enlever à un homme, sauf une chose : la dernière des libertés humaines — celle de choisir son attitude dans n'importe quel ensemble de circonstances, de choisir sa propre voie.",
			"de":    "Man kann dem Menschen alles nehmen, nur eines nicht: die letzte menschliche Freiheit — unter allen Umständen seine Haltung zu wählen, seinen eigenen Weg zu wählen.",
			"it":    "All'uomo si può togliere tutto tranne una cosa: l'ultima delle libertà umane — scegliere il proprio atteggiamento in qualsiasi circostanza, scegliere la propria strada.",
			"ja":    "人からすべてを奪うことはできても、ただ一つだけ奪えないものがある。それは人間に残された最後の自由──いかなる状況においても自分の態度を選び、自分の道を選ぶ自由である。",
			"zh":    "人所拥有的一切都可以被剥夺，唯独一样不能：人类最后的自由——在任何境遇中选择自己态度、选择自己道路的自由。",
			"ko":    "인간에게서 모든 것을 빼앗을 수 있어도 단 하나는 빼앗을 수 없다. 마지막 남은 인간의 자유, 곧 어떤 상황에서도 자신의 태도를 선택하고 자신의 길을 선택할 자유다.",
			"hi":    "मनुष्य से सब कुछ छीना जा सकता है, सिवाय एक चीज़ के: मानवीय स्वतंत्रताओं में अंतिम—किसी भी परिस्थिति में अपना दृष्टिकोण चुनना, अपना रास्ता चुनना।",
			"pl":    "Człowiekowi można odebrać wszystko oprócz jednego: ostatniej z ludzkich wolności — wyboru własnej postawy w każdych okolicznościach, wyboru własnej drogi.",
			"tr":    "İnsandan her şey alınabilir, bir şey hariç: insan özgürlüklerinin sonuncusu — her koşulda kendi tutumunu seçme, kendi yolunu seçme özgürlüğü.",
			"uk":    "У людини можна відібрати все, крім одного: останньої з людських свобод — обирати своє ставлення за будь-яких обставин, обирати власний шлях.",
			"sv":    "Allt kan tas ifrån en människa utom en sak: den sista av de mänskliga friheterna — att välja sin inställning under vilka omständigheter som helst, att välja sin egen väg.",
			"nl":    "Alles kan een mens worden afgenomen, behalve één ding: de laatste van de menselijke vrijheden — in elke omstandigheid je eigen houding te kiezen, je eigen weg te kiezen.",
			"nb":    "Alt kan tas fra et menneske bortsett fra én ting: den siste av de menneskelige friheter — å velge sin holdning under enhver omstendighet, å velge sin egen vei.",
			"da":    "Alt kan tages fra et menneske undtagen én ting: den sidste af de menneskelige friheder — at vælge sin indstilling under alle omstændigheder, at vælge sin egen vej.",
			"fi":    "Ihmiseltä voidaan viedä kaikki paitsi yksi asia: viimeinen inhimillisistä vapauksista — valita asenteensa missä tahansa olosuhteissa, valita oma tiensä.",
		},
	},
	{
		ID:       "resilience-30",
		Author:   ptr("Paulo Coelho"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "The secret of life, though, is to fall seven times and to get up eight times.",
			"en-GB": "The secret of life, though, is to fall seven times and to get up eight times.",
			"pt-PT": "O segredo da vida, no entanto, é cair sete vezes e levantar-se oito vezes.",
			"pt-BR": "O segredo da vida, no entanto, é cair sete vezes e levantar-se oito vezes.",
			"es":    "Sin embargo, el secreto de la vida es caer siete veces y levantarse ocho veces.",
			"fr":    "Le secret de la vie, pourtant, est de tomber sept fois et de se relever huit fois.",
			"de":    "Das Geheimnis des Lebens besteht jedoch darin, siebenmal zu fallen und achtmal aufzustehen.",
			"it":    "Il segreto della vita, però, è cadere sette volte e rialzarsi otto.",
			"ja":    "だが人生の秘訣は、七度転んで八度起き上がることである。",
			"zh":    "而生活的秘诀，就在于跌倒七次，爬起来八次。",
			"ko":    "그러나 삶의 비결은 일곱 번 넘어지고 여덟 번 일어나는 것이다.",
			"hi":    "जीवन का रहस्य यही है कि सात बार गिरो और आठ बार उठो।",
			"pl":    "Sekretem życia jest jednak upaść siedem razy i wstać osiem razy.",
			"tr":    "Ama hayatın sırrı, yedi kez düşüp sekiz kez ayağa kalkmaktır.",
			"uk":    "Але секрет життя в тому, щоб упасти сім разів і піднятися вісім.",
			"sv":    "Livets hemlighet är dock att falla sju gånger och resa sig åtta.",
			"nl":    "Het geheim van het leven is echter zeven keer vallen en acht keer opstaan.",
			"nb":    "Livets hemmelighet er imidlertid å falle sju ganger og reise seg åtte.",
			"da":    "Livets hemmelighed er imidlertid at falde syv gange og rejse sig otte.",
			"fi":    "Elämän salaisuus on kuitenkin kaatua seitsemän kertaa ja nousta kahdeksan.",
		},
	},
	{
		ID:       "resilience-31",
		Author:   ptr("Friedrich Nietzsche"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "That which does not kill us makes us stronger.",
			"en-GB": "That which does not kill us makes us stronger.",
			"pt-PT": "O que não nos mata, torna-nos mais fortes.",
			"pt-BR": "Aquilo que não nos mata, nos torna mais fortes.",
			"es":    "Lo que no nos mata, nos hace más fuertes.",
			"fr":    "Ce qui ne nous tue pas nous rend plus forts.",
			"de":    "Was uns nicht umbringt, macht uns stärker.",
			"it":    "Ciò che non ci uccide ci rende più forti.",
			"ja":    "私たちを殺さないものは、私たちを強くする。",
			"zh":    "凡不能毁灭我们的，必使我们更强大。",
			"ko":    "우리를 죽이지 못하는 것은 우리를 더 강하게 만든다.",
			"hi":    "जो हमें मारता नहीं, वह हमें और मज़बूत बनाता है।",
			"pl":    "Co nas nie zabije, to nas wzmocni.",
			"tr":    "Bizi öldürmeyen şey güçlendirir.",
			"uk":    "Те, що нас не вбиває, робить нас сильнішими.",
			"sv":    "Det som inte dödar oss gör oss starkare.",
			"nl":    "Wat ons niet doodt, maakt ons sterker.",
			"nb":    "Det som ikke dreper oss, gjør oss sterkere.",
			"da":    "Det, der ikke slår os ihjel, gør os stærkere.",
			"fi":    "Se mikä ei tapa meitä, vahvistaa meitä.",
		},
	},
	{
		ID:       "resilience-32",
		Author:   ptr("Jodi Picoult"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "The human capacity for burden is like bamboo – far more flexible than you'd ever believe at first glance.",
			"en-GB": "The human capacity for burden is like bamboo – far more flexible than you'd ever believe at first glance.",
			"pt-PT": "A capacidade humana de carregar fardos é como o bambu – muito mais flexível do que acreditarias à primeira vista.",
			"pt-BR": "A capacidade humana de carregar fardos é como o bambu – muito mais flexível do que você acreditaria à primeira vista.",
			"es":    "La capacidad humana para soportar cargas es como el bambú: mucho más flexible de lo que creerías a primera vista.",
			"fr":    "La capacité humaine à porter des fardeaux est comme le bambou – bien plus flexible que ce que l'on pourrait croire au premier abord.",
			"de":    "Die menschliche Fähigkeit, Lasten zu tragen, ist wie Bambus — weit biegsamer, als man auf den ersten Blick je glauben würde.",
			"it":    "La capacità umana di sopportare i pesi è come il bambù: molto più flessibile di quanto si possa credere a prima vista.",
			"ja":    "重荷に耐える人間の力は竹のようなもの。一見して信じられないほど、はるかにしなやかである。",
			"zh":    "人承受重负的能力就像竹子——远比你乍看之下所相信的更有韧性。",
			"ko":    "짐을 견디는 인간의 능력은 대나무와 같다. 언뜻 보기보다 훨씬 더 유연하다.",
			"hi":    "बोझ सहने की मानवीय क्षमता बाँस की तरह है—पहली नज़र में जितना आप मानेंगे, उससे कहीं अधिक लचीली।",
			"pl":    "Ludzka zdolność do dźwigania ciężarów jest jak bambus — o wiele bardziej giętka, niż mógłbyś uwierzyć na pierwszy rzut oka.",
			"tr":    "İnsanın yük taşıma kapasitesi bambu gibidir — ilk bakışta inanacağından çok daha esnektir.",
			"uk":    "Людська здатність нести тягар подібна до бамбука — куди гнучкіша, ніж можна повірити з першого погляду.",
			"sv":    "Människans förmåga att bära bördor är som bambu — långt mer böjlig än du någonsin skulle tro vid första anblicken.",
			"nl":    "Het menselijk vermogen om lasten te dragen is als bamboe — veel buigzamer dan je op het eerste gezicht ooit zou geloven.",
			"nb":    "Menneskets evne til å bære byrder er som bambus — langt mer bøyelig enn du noen gang ville tro ved første øyekast.",
			"da":    "Menneskets evne til at bære byrder er som bambus — langt mere bøjelig, end man umiddelbart skulle tro.",
			"fi":    "Ihmisen kyky kantaa taakkoja on kuin bambu — paljon taipuisampi kuin ensi silmäyksellä uskoisi.",
		},
	},
	{
		ID:       "resilience-33",
		Author:   ptr("Mary Holloway"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Resilience is knowing that you are the only one that has the power and the responsibility to pick yourself up.",
			"en-GB": "Resilience is knowing that you are the only one that has the power and the responsibility to pick yourself up.",
			"pt-PT": "Resiliência é saber que és o único que tem o poder e a responsabilidade de se levantar.",
			"pt-BR": "Resiliência é saber que você é o único que tem o poder e a responsabilidade de se levantar.",
			"es":    "La resiliencia es saber que eres el único que tiene el poder y la responsabilidad de levantarse.",
			"fr":    "La résilience, c'est savoir que vous êtes le seul à avoir le pouvoir et la responsabilité de vous relever.",
			"de":    "Resilienz ist das Wissen, dass du der Einzige bist, der die Kraft und die Verantwortung hat, dich wieder aufzurichten.",
			"it":    "La resilienza è sapere che sei tu l'unico ad avere il potere e la responsabilità di rialzarti.",
			"ja":    "レジリエンスとは、自分を立ち直らせる力と責任を持つのは自分だけだと知っていることである。",
			"zh":    "韧性，是明白只有你自己拥有让自己重新站起来的力量和责任。",
			"ko":    "회복탄력성이란 자신을 다시 일으켜 세울 힘과 책임이 오직 자신에게 있음을 아는 것이다.",
			"hi":    "लचीलापन यह जानना है कि केवल आपके पास ही ख़ुद को उठाने की शक्ति और ज़िम्मेदारी है।",
			"pl":    "Odporność to świadomość, że tylko ty masz moc i odpowiedzialność, by się podnieść.",
			"tr":    "Dayanıklılık, kendini ayağa kaldıracak güce ve sorumluluğa sahip tek kişinin sen olduğunu bilmektir.",
			"uk":    "Стійкість — це знати, що лише ти маєш силу й відповідальність підняти себе.",
			"sv":    "Motståndskraft är att veta att du är den enda som har kraften och ansvaret att resa dig själv.",
			"nl":    "Veerkracht is weten dat jij de enige bent die de kracht en de verantwoordelijkheid heeft om jezelf op te rapen.",
			"nb":    "Motstandskraft er å vite at du er den eneste som har kraften og ansvaret til å reise deg selv.",
			"da":    "Modstandskraft er at vide, at du er den eneste, der har kraften og ansvaret til at rejse dig selv.",
			"fi":    "Sitkeys on tietoa siitä, että vain sinulla on voima ja vastuu nostaa itsesi ylös.",
		},
	},
	{
		ID:       "resilience-34",
		Author:   ptr("Bob Riley"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Hard times don't create heroes. They reveal the hero within.",
			"en-GB": "Hard times don't create heroes. They reveal the hero within.",
			"pt-PT": "Os tempos difíceis não criam heróis. Eles revelam o herói interior.",
			"pt-BR": "Os tempos difíceis não criam heróis. Eles revelam o herói interior.",
			"es":    "Los tiempos difíciles no crean héroes. Revelan al héroe que llevamos dentro.",
			"fr":    "Les temps difficiles ne créent pas de héros. Ils révèlent le héros qui sommeille en nous.",
			"de":    "Schwere Zeiten schaffen keine Helden. Sie enthüllen den Helden im Inneren.",
			"it":    "I tempi difficili non creano eroi. Rivelano l'eroe che è dentro di noi.",
			"ja":    "苦難の時代が英雄を作るのではない。内に潜む英雄を明らかにするのだ。",
			"zh":    "艰难的时刻不会造就英雄，它们只是揭示内心的英雄。",
			"ko":    "힘든 시기가 영웅을 만드는 것이 아니다. 내면의 영웅을 드러낼 뿐이다.",
			"hi":    "कठिन समय नायक नहीं बनाता। वह भीतर छिपे नायक को प्रकट करता है।",
			"pl":    "Trudne czasy nie tworzą bohaterów. One odsłaniają bohatera, który jest w nas.",
			"tr":    "Zor zamanlar kahraman yaratmaz. İçteki kahramanı ortaya çıkarır.",
			"uk":    "Важкі часи не створюють героїв. Вони виявляють героя всередині.",
			"sv":    "Hårda tider skapar inte hjältar. De avslöjar hjälten inom oss.",
			"nl":    "Zware tijden creëren geen helden. Ze onthullen de held vanbinnen.",
			"nb":    "Harde tider skaper ikke helter. De avslører helten i oss.",
			"da":    "Hårde tider skaber ikke helte. De afslører helten indeni.",
			"fi":    "Kovat ajat eivät luo sankareita. Ne paljastavat sisällä olevan sankarin.",
		},
	},
	{
		ID:       "resilience-35",
		Author:   ptr("Albert Einstein"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "It’s not that I’m so smart, it’s just that I stay with problems longer.",
			"en-GB": "It’s not that I’m so smart, it’s just that I stay with problems longer.",
			"pt-PT": "Não é que eu seja tão inteligente, é que eu fico mais tempo com os problemas.",
			"pt-BR": "Não é que eu seja tão inteligente, é que eu fico mais tempo com os problemas.",
			"es":    "No es que sea tan inteligente, es solo que me quedo más tiempo con los problemas.",
			"fr":    "Ce n'est pas que je sois si intelligent, c'est juste que je reste plus longtemps avec les problèmes.",
			"de":    "Ich bin nicht besonders klug — ich bleibe nur länger an Problemen dran.",
			"it":    "Non è che io sia così intelligente, è solo che resto sui problemi più a lungo.",
			"ja":    "私は特別頭が良いわけではない。ただ、人より長く問題と向き合っているだけだ。",
			"zh":    "并不是我有多聪明，只是我与问题周旋得更久。",
			"ko":    "내가 그렇게 똑똑한 것이 아니라, 단지 문제를 더 오래 붙들고 있을 뿐이다.",
			"hi":    "ऐसा नहीं कि मैं बहुत बुद्धिमान हूँ, बस मैं समस्याओं के साथ अधिक देर तक टिका रहता हूँ।",
			"pl":    "Nie jestem aż tak mądry — po prostu dłużej siedzę nad problemami.",
			"tr":    "Çok zeki olduğumdan değil; sadece sorunların üzerinde daha uzun süre kalırım.",
			"uk":    "Річ не в тому, що я такий розумний, — я просто довше залишаюся з проблемами.",
			"sv":    "Det är inte det att jag är så smart, det är bara det att jag stannar längre hos problemen.",
			"nl":    "Het is niet dat ik zo slim ben, ik blijf alleen langer bij de problemen.",
			"nb":    "Det er ikke det at jeg er så smart, det er bare det at jeg blir lenger hos problemene.",
			"da":    "Det er ikke, fordi jeg er så klog, det er bare, fordi jeg bliver længere ved problemerne.",
			"fi":    "En ole erityisen älykäs — pysyttelen vain ongelmien parissa pidempään.",
		},
	},
	{
		ID:       "resilience-36",
		Author:   ptr("Winston Churchill"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
			"en-GB": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
			"pt-PT": "O sucesso não é definitivo, o fracasso não é fatal: o que conta é a coragem de continuar.",
			"pt-BR": "O sucesso não é definitivo, o fracasso não é fatal: o que importa é a coragem de continuar.",
			"es":    "El éxito no es el final, el fracaso no es fatal: lo que cuenta es el valor de continuar.",
			"fr":    "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
			"de":    "Erfolg ist nicht endgültig, Scheitern ist nicht tödlich: Was zählt, ist der Mut, weiterzumachen.",
			"it":    "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di continuare.",
			"ja":    "成功は終わりではなく、失敗は致命的ではない。大切なのは続ける勇気である。",
			"zh":    "成功不是终点，失败也非末日：重要的是继续前行的勇气。",
			"ko":    "성공은 끝이 아니고 실패는 치명적이지 않다. 중요한 것은 계속해 나갈 용기다.",
			"hi":    "सफलता अंतिम नहीं है, असफलता घातक नहीं है: मायने रखता है आगे बढ़ते रहने का साहस।",
			"pl":    "Sukces nie jest ostateczny, porażka nie jest śmiertelna: liczy się odwaga, by iść dalej.",
			"tr":    "Başarı nihai değildir, başarısızlık ölümcül değildir: Önemli olan devam etme cesaretidir.",
			"uk":    "Успіх не остаточний, поразка не смертельна: важлива лише мужність продовжувати.",
			"sv":    "Framgång är inte slutgiltig, misslyckande är inte ödesdigert: det är modet att fortsätta som räknas.",
			"nl":    "Succes is niet definitief, falen is niet fataal: het is de moed om door te gaan die telt.",
			"nb":    "Suksess er ikke endelig, nederlag er ikke fatalt: det er motet til å fortsette som teller.",
			"da":    "Succes er ikke endelig, nederlag er ikke fatalt: det er modet til at fortsætte, der tæller.",
			"fi":    "Menestys ei ole lopullista, epäonnistuminen ei ole kohtalokasta: ratkaisevaa on rohkeus jatkaa.",
		},
	},
	{
		ID:       "resilience-37",
		Author:   ptr("Maya Angelou"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it.",
			"en-GB": "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it.",
			"pt-PT": "Podes encontrar muitas derrotas, mas não deves ser derrotado. Na verdade, pode ser necessário encontrar as derrotas para que possas saber quem és, de onde te podes levantar, como ainda podes sair dessa.",
			"pt-BR": "Você pode encontrar muitas derrotas, mas não deve ser derrotado. Na verdade, pode ser necessário enfrentar as derrotas para que você possa saber quem você é, de onde você pode se levantar e como ainda pode sair dessa.",
			"es":    "Puede que encuentres muchas derrotas, pero no debes ser derrotado. De hecho, puede ser necesario encontrar las derrotas, para que puedas saber quién eres, de qué puedes levantarte, cómo puedes salir de ello.",
			"fr":    "Vous rencontrerez peut-être de nombreuses défaites, mais vous ne devez pas être vaincu. En fait, il peut être nécessaire de rencontrer les défaites, afin de savoir qui vous êtes, de quoi vous pouvez vous relever, comment vous pouvez encore vous en sortir.",
			"de":    "Du magst vielen Niederlagen begegnen, aber du darfst nicht besiegt werden. Vielleicht ist es sogar nötig, den Niederlagen zu begegnen — damit du erfährst, wer du bist, woraus du dich erheben kannst und wie du dennoch daraus hervorgehen kannst.",
			"it":    "Potrai incontrare molte sconfitte, ma non devi lasciarti sconfiggere. Anzi, potrebbe essere necessario incontrare le sconfitte, per sapere chi sei, da cosa riesci a risollevarti, e come puoi comunque uscirne.",
			"ja":    "多くの敗北に出会うかもしれない。だが、打ち負かされてはならない。むしろ敗北に出会うことは必要なのかもしれない。自分が何者か、何から立ち上がれるのか、どうすればそこから抜け出せるのかを知るために。",
			"zh":    "你可能会遭遇许多失败，但你绝不能被打败。事实上，遭遇失败也许是必要的，这样你才能知道自己是谁、能从何处站起、如何依然走出困境。",
			"ko":    "많은 패배를 겪을 수는 있지만, 패배당해서는 안 된다. 오히려 패배를 겪는 것이 필요할지도 모른다. 그래야 자신이 누구인지, 무엇에서 다시 일어설 수 있는지, 어떻게 그 속에서도 헤쳐 나올 수 있는지 알 수 있기 때문이다.",
			"hi":    "आपको कई हारों का सामना करना पड़ सकता है, पर आपको हारना नहीं है। दरअसल, हारों का सामना करना ज़रूरी भी हो सकता है, ताकि आप जान सकें कि आप कौन हैं, आप किससे उबर सकते हैं, और फिर भी उससे कैसे बाहर निकल सकते हैं।",
			"pl":    "Możesz napotkać wiele porażek, ale nie wolno ci dać się pokonać. Być może napotkanie porażek jest wręcz konieczne, byś wiedział, kim jesteś, z czego potrafisz się podnieść i jak mimo wszystko możesz z tego wyjść.",
			"tr":    "Birçok yenilgiyle karşılaşabilirsin ama yenilmemelisin. Aslında yenilgilerle karşılaşmak gerekli bile olabilir; böylece kim olduğunu, neyin içinden doğrulabildiğini ve yine de nasıl çıkabildiğini öğrenirsin.",
			"uk":    "Ти можеш зазнати багатьох поразок, але не повинен бути переможеним. Можливо, поразки навіть необхідні — щоб ти знав, хто ти, з чого можеш піднятися і як усе ж таки можеш вийти з цього.",
			"sv":    "Du kan möta många nederlag, men du får inte bli besegrad. Det kan till och med vara nödvändigt att möta nederlagen, så att du vet vem du är, vad du kan resa dig ur och hur du ändå kan ta dig igenom.",
			"nl":    "Je kunt veel nederlagen tegenkomen, maar je mag niet verslagen worden. Sterker nog, misschien is het nodig de nederlagen tegen te komen, zodat je weet wie je bent, waaruit je kunt opstaan en hoe je er toch uit kunt komen.",
			"nb":    "Du kan møte mange nederlag, men du må ikke bli beseiret. Faktisk kan det være nødvendig å møte nederlagene, slik at du vet hvem du er, hva du kan reise deg fra, og hvordan du likevel kan komme deg gjennom.",
			"da":    "Du kan møde mange nederlag, men du må ikke lade dig besejre. Faktisk kan det være nødvendigt at møde nederlagene, så du ved, hvem du er, hvad du kan rejse dig fra, og hvordan du alligevel kan komme igennem.",
			"fi":    "Saatat kohdata monia tappioita, mutta et saa antaa niiden lannistaa itseäsi. Itse asiassa tappioiden kohtaaminen voi olla tarpeen, jotta tiedät kuka olet, mistä pystyt nousemaan ja miten silti selviät niistä.",
		},
	},
	{
		ID:       "resilience-38",
		Author:   ptr("Christopher Reeve"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.",
			"en-GB": "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.",
			"pt-PT": "Um herói é um indivíduo comum que encontra a força para perseverar e resistir, apesar de obstáculos esmagadores.",
			"pt-BR": "Um herói é um indivíduo comum que encontra a força para perseverar e resistir, apesar de obstáculos esmagadores.",
			"es":    "Un héroe es un individuo corriente que encuentra la fuerza para perseverar y resistir a pesar de los obstáculos abrumadores.",
			"fr":    "Un héros est um individu ordinaire qui trouve la force de persévérer et d'endurer malgré des obstacles écrasants.",
			"de":    "Ein Held ist ein gewöhnlicher Mensch, der die Kraft findet, trotz überwältigender Hindernisse durchzuhalten und auszuharren.",
			"it":    "Un eroe è un individuo comune che trova la forza di perseverare e resistere nonostante ostacoli schiaccianti.",
			"ja":    "英雄とは、圧倒的な障害にもかかわらず、耐え抜き、やり遂げる力を見出す普通の人間である。",
			"zh":    "英雄就是普通人，只是在面对压倒性的障碍时，找到了坚持和忍耐的力量。",
			"ko":    "영웅이란 압도적인 장애물에도 불구하고 버티고 견뎌 낼 힘을 찾아내는 평범한 사람이다.",
			"hi":    "नायक एक साधारण व्यक्ति है जो भारी बाधाओं के बावजूद डटे रहने और सहने की शक्ति खोज लेता है।",
			"pl":    "Bohater to zwykły człowiek, który znajduje siłę, by wytrwać i przetrzymać mimo przytłaczających przeszkód.",
			"tr":    "Kahraman, ezici engellere rağmen dayanma ve sebat etme gücünü bulan sıradan bir insandır.",
			"uk":    "Герой — це звичайна людина, яка знаходить силу вистояти й витримати попри нездоланні перешкоди.",
			"sv":    "En hjälte är en vanlig människa som finner styrkan att hålla ut och härda ut trots överväldigande hinder.",
			"nl":    "Een held is een gewoon mens die de kracht vindt om vol te houden en te volharden ondanks overweldigende obstakels.",
			"nb":    "En helt er et vanlig menneske som finner styrken til å holde ut og utholde til tross for overveldende hindringer.",
			"da":    "En helt er et almindeligt menneske, der finder styrken til at holde ud og udholde trods overvældende forhindringer.",
			"fi":    "Sankari on tavallinen ihminen, joka löytää voiman sinnitellä ja kestää ylivoimaisista esteistä huolimatta.",
		},
	},
	{
		ID:       "resilience-39",
		Author:   ptr("Oliver Goldsmith"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Our greatest glory is not in never falling, but in rising every time we fall.",
			"en-GB": "Our greatest glory is not in never falling, but in rising every time we fall.",
			"pt-PT": "A nossa maior glória não reside em nunca cair, mas em levantarmo-nos sempre que caímos.",
			"pt-BR": "Nossa maior glória não está em nunca cair, mas em nos levantarmos toda vez que caímos.",
			"es":    "Nuestra mayor gloria no consiste en no caer nunca, sino en levantarnos cada vez que caemos.",
			"fr":    "Notre plus grande gloire n'est pas de ne jamais tomber, mais de nous relever à chaque fois que nous tombons.",
			"de":    "Unser größter Ruhm liegt nicht darin, niemals zu fallen, sondern darin, nach jedem Fall wieder aufzustehen.",
			"it":    "La nostra gloria più grande non sta nel non cadere mai, ma nel rialzarci ogni volta che cadiamo.",
			"ja":    "私たちの最大の栄光は、決して転ばないことではなく、転ぶたびに立ち上がることにある。",
			"zh":    "我们最大的光荣不在于从不跌倒，而在于每次跌倒后都能站起来。",
			"ko":    "우리의 가장 큰 영광은 결코 넘어지지 않는 데 있는 것이 아니라, 넘어질 때마다 일어서는 데 있다.",
			"hi":    "हमारा सबसे बड़ा गौरव कभी न गिरने में नहीं, बल्कि हर बार गिरकर उठ खड़े होने में है।",
			"pl":    "Nasza największa chwała nie polega na tym, że nigdy nie upadamy, lecz na tym, że podnosimy się po każdym upadku.",
			"tr":    "En büyük zaferimiz hiç düşmemek değil, her düştüğümüzde yeniden kalkmaktır.",
			"uk":    "Наша найбільша слава не в тому, щоб ніколи не падати, а в тому, щоб підводитися після кожного падіння.",
			"sv":    "Vår största ära ligger inte i att aldrig falla, utan i att resa oss varje gång vi faller.",
			"nl":    "Onze grootste glorie ligt niet in nooit vallen, maar in elke keer weer opstaan als we vallen.",
			"nb":    "Vår største ære ligger ikke i aldri å falle, men i å reise oss hver gang vi faller.",
			"da":    "Vores største ære ligger ikke i aldrig at falde, men i at rejse os, hver gang vi falder.",
			"fi":    "Suurin kunniamme ei ole siinä, ettemme koskaan kaadu, vaan siinä, että nousemme joka kerta kaatuessamme.",
		},
	},
	{
		ID:       "resilience-40",
		Author:   ptr("Steve Maraboli"),
		Category: "resilience",
		Translations: map[string]string{
			"en-US": "Life doesn't get easier or more forgiving, we get stronger and more resilient.",
			"en-GB": "Life doesn't get easier or more forgiving, we get stronger and more resilient.",
			"pt-PT": "A vida não fica mais fácil ou mais tolerante, nós ficamos mais fortes e mais resilientes.",
			"pt-BR": "A vida não fica mais fácil ou mais tolerante, nós ficamos mais fortes e mais resilientes.",
			"es":    "La vida no se vuelve más fácil ni perdona más, nosotros nos volvemos más fuertes y resistentes.",
			"fr":    "La vie ne devient pas plus facile ou plus indulgente, nous devenons plus forts et plus résilients.",
			"de":    "Das Leben wird nicht leichter oder nachsichtiger; wir werden stärker und widerstandsfähiger.",
			"it":    "La vita non diventa più facile o più indulgente; siamo noi a diventare più forti e resilienti.",
			"ja":    "人生が楽になったり寛容になったりするのではない。私たちが強く、しなやかになるのだ。",
			"zh":    "生活不会变得更容易、更宽容，是我们变得更坚强、更有韧性。",
			"ko":    "삶이 더 쉬워지거나 너그러워지는 것이 아니다. 우리가 더 강해지고 더 단단해지는 것이다.",
			"hi":    "जीवन आसान या उदार नहीं होता; हम ही अधिक मज़बूत और लचीले बन जाते हैं।",
			"pl":    "Życie nie staje się łatwiejsze ani bardziej wyrozumiałe; to my stajemy się silniejsi i odporniejsi.",
			"tr":    "Hayat kolaylaşmaz ya da bağışlayıcı olmaz; biz daha güçlü ve dayanıklı hale geliriz.",
			"uk":    "Життя не стає легшим чи поблажливішим — це ми стаємо сильнішими і стійкішими.",
			"sv":    "Livet blir inte lättare eller mer förlåtande; vi blir starkare och mer motståndskraftiga.",
			"nl":    "Het leven wordt niet makkelijker of vergevingsgezinder; wij worden sterker en veerkrachtiger.",
			"nb":    "Livet blir ikke lettere eller mer tilgivende; vi blir sterkere og mer motstandsdyktige.",
			"da":    "Livet bliver ikke lettere eller mere tilgivende; vi bliver stærkere og mere modstandsdygtige.",
			"fi":    "Elämästä ei tule helpompaa tai armollisempaa; meistä tulee vahvempia ja sitkeämpiä.",
		},
	},
}
