package quote

var actionQuotes = []QuoteData{
	{
		ID:       "commitment-1",
		Author:   ptr("Mark Twain"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The secret of getting ahead is getting started.",
			"en-GB": "The secret of getting ahead is getting started.",
			"pt-PT": "O segredo de avançar é começar.",
			"pt-BR": "O segredo de progredir é começar.",
			"es":    "El secreto de salir adelante es comenzar.",
			"fr":    "Le secret pour avancer, c'est de commencer.",
			"de":    "Das Geheimnis des Vorankommens liegt darin, anzufangen.",
			"it":    "Il segreto per andare avanti è iniziare.",
			"ja":    "前進する秘訣は、まず始めることだ。",
			"zh":    "取得进步的秘诀在于开始行动。",
			"ko":    "앞서 나가는 비결은 시작하는 것이다.",
			"hi":    "आगे बढ़ने का रहस्य शुरुआत करने में है।",
			"pl":    "Sekretem osiągania postępów jest zacząć.",
			"tr":    "İlerlemenin sırrı başlamaktır.",
			"uk":    "Секрет просування вперед — почати.",
			"sv":    "Hemligheten med att komma framåt är att komma igång.",
			"nl":    "Het geheim van vooruitkomen is beginnen.",
			"nb":    "Hemmeligheten bak å komme videre er å komme i gang.",
			"da":    "Hemmeligheden bag at komme videre er at komme i gang.",
			"fi":    "Eteenpäin pääsemisen salaisuus on aloittaminen.",
		},
	},
	{
		ID:       "commitment-2",
		Author:   ptr("Sam Levenson"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Don't watch the clock; do what it does. Keep going.",
			"en-GB": "Don't watch the clock; do what it does. Keep going.",
			"pt-PT": "Não olhes para o relógio; faz o que ele faz. Continua.",
			"pt-BR": "Não olhe para o relógio; faça o que ele faz. Continue.",
			"es":    "No mires el reloj; haz lo que él hace. Sigue adelante.",
			"fr":    "Ne regardez pas la montre ; faites ce qu'elle fait. Continuez.",
			"de":    "Schau nicht auf die Uhr; mach es wie sie. Bleib in Bewegung.",
			"it":    "Non guardare l'orologio; fai come lui. Continua ad andare avanti.",
			"ja":    "時計を見つめるな。時計のように動き続けよ。",
			"zh":    "别盯着时钟看；要像它一样不停地走。",
			"ko":    "시계를 쳐다보지 말고 시계처럼 하라. 계속 나아가라.",
			"hi":    "घड़ी मत देखो; वही करो जो घड़ी करती है। चलते रहो।",
			"pl":    "Nie patrz na zegar; rób to, co on. Idź dalej.",
			"tr":    "Saate bakma; onun yaptığını yap. Devam et.",
			"uk":    "Не дивись на годинник; роби те, що робить він. Рухайся далі.",
			"sv":    "Titta inte på klockan; gör som den. Fortsätt framåt.",
			"nl":    "Kijk niet op de klok; doe wat de klok doet. Ga door.",
			"nb":    "Ikke se på klokka; gjør som den. Fortsett videre.",
			"da":    "Se ikke på uret; gør som det. Bliv ved.",
			"fi":    "Älä tuijota kelloa; tee kuten se. Jatka eteenpäin.",
		},
	},
	{
		ID:       "commitment-3",
		Author:   ptr("Pablo Picasso"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Commitment is the foundational key to all success.",
			"en-GB": "Commitment is the foundational key to all success.",
			"pt-PT": "A ação é a chave fundamental para todo o sucesso.",
			"pt-BR": "A ação é a chave fundamental para todo o sucesso.",
			"es":    "La acción es la clave fundamental para todo éxito.",
			"fr":    "L'commitment est la clé fondamentale de tout succès.",
			"de":    "Handeln ist der grundlegende Schlüssel zu jedem Erfolg.",
			"it":    "L'azione è la chiave fondamentale di ogni successo.",
			"ja":    "行動こそ、あらゆる成功の根本的な鍵である。",
			"zh":    "行动是一切成功的根本关键。",
			"ko":    "행동은 모든 성공의 근본적인 열쇠다.",
			"hi":    "कर्म ही हर सफलता की बुनियादी कुंजी है।",
			"pl":    "Działanie jest podstawowym kluczem do każdego sukcesu.",
			"tr":    "Eylem, tüm başarının temel anahtarıdır.",
			"uk":    "Дія — основний ключ до будь-якого успіху.",
			"sv":    "Handling är den grundläggande nyckeln till all framgång.",
			"nl":    "Actie is de fundamentele sleutel tot elk succes.",
			"nb":    "Handling er den grunnleggende nøkkelen til all suksess.",
			"da":    "Handling er den grundlæggende nøgle til al succes.",
			"fi":    "Toiminta on kaiken menestyksen perusavain.",
		},
	},
	{
		ID:       "commitment-4",
		Author:   ptr("Jim Rohn"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Either you run the day, or the day runs you.",
			"en-GB": "Either you run the day, or the day runs you.",
			"pt-PT": "Ou tu controlas o dia, ou o dia controla-te a ti.",
			"pt-BR": "Ou você comanda o dia, ou o dia comanda você.",
			"es":    "O tú diriges el día, o el día te dirige a ti.",
			"fr":    "Soit vous dirigez la journée, soit la journée vous dirige.",
			"de":    "Entweder du bestimmst den Tag, oder der Tag bestimmt dich.",
			"it":    "O guidi tu la giornata, o la giornata guida te.",
			"ja":    "あなたが一日を動かすか、一日に動かされるかのどちらかだ。",
			"zh":    "不是你掌控这一天，就是这一天掌控你。",
			"ko":    "당신이 하루를 이끌든가, 하루가 당신을 이끌든가 둘 중 하나다.",
			"hi":    "या तो आप दिन को चलाते हैं, या दिन आपको चलाता है।",
			"pl":    "Albo ty kierujesz dniem, albo dzień kieruje tobą.",
			"tr":    "Ya günü sen yönetirsin ya da gün seni yönetir.",
			"uk":    "Або ти керуєш днем, або день керує тобою.",
			"sv":    "Antingen styr du dagen, eller så styr dagen dig.",
			"nl":    "Of jij bepaalt de dag, of de dag bepaalt jou.",
			"nb":    "Enten styrer du dagen, eller så styrer dagen deg.",
			"da":    "Enten styrer du dagen, eller også styrer dagen dig.",
			"fi":    "Joko sinä hallitset päivää tai päivä hallitsee sinua.",
		},
	},
	{
		ID:       "commitment-5",
		Author:   ptr("Robin Sharma"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Small daily improvements over time lead to stunning results.",
			"en-GB": "Small daily improvements over time lead to stunning results.",
			"pt-PT": "Pequenas melhorias diárias ao longo do tempo levam a resultados impressionantes.",
			"pt-BR": "Pequenas melhorias diárias ao longo do tempo levam a resultados impressionantes.",
			"es":    "Pequeñas mejoras diarias a lo largo del tempo conducen a resultados impressionantes.",
			"fr":    "De petites améliorations quotidiennes au fil du temps mènent à des résultats époustouflants.",
			"de":    "Kleine tägliche Verbesserungen führen mit der Zeit zu erstaunlichen Ergebnissen.",
			"it":    "Piccoli miglioramenti quotidiani portano nel tempo a risultati sorprendenti.",
			"ja":    "日々の小さな改善が、時とともに驚くべき成果をもたらす。",
			"zh":    "每天小小的进步，随着时间推移会带来惊人的成果。",
			"ko":    "매일의 작은 개선이 시간이 지나면 놀라운 결과로 이어진다.",
			"hi":    "रोज़ के छोटे-छोटे सुधार समय के साथ शानदार परिणाम लाते हैं।",
			"pl":    "Małe codzienne ulepszenia z czasem prowadzą do zdumiewających rezultatów.",
			"tr":    "Küçük günlük gelişmeler zamanla çarpıcı sonuçlara yol açar.",
			"uk":    "Маленькі щоденні покращення з часом ведуть до вражаючих результатів.",
			"sv":    "Små dagliga förbättringar leder med tiden till fantastiska resultat.",
			"nl":    "Kleine dagelijkse verbeteringen leiden na verloop van tijd tot verbluffende resultaten.",
			"nb":    "Små daglige forbedringer fører over tid til fantastiske resultater.",
			"da":    "Små daglige forbedringer fører med tiden til forbløffende resultater.",
			"fi":    "Pienet päivittäiset parannukset johtavat ajan myötä huikeisiin tuloksiin.",
		},
	},
	{
		ID:       "commitment-6",
		Author:   ptr("Jim Rohn"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Discipline is the bridge between goals and accomplishment.",
			"en-GB": "Discipline is the bridge between goals and accomplishment.",
			"pt-PT": "A disciplina é a ponte entre os objetivos e a realização.",
			"pt-BR": "A disciplina é a ponte entre as metas e as realizações.",
			"es":    "La disciplina es el puente entre las metas y los logros.",
			"fr":    "La discipline est le pont entre les objectifs et l'accomplissement.",
			"de":    "Disziplin ist die Brücke zwischen Zielen und Erfolg.",
			"it":    "La disciplina è il ponte tra gli obiettivi e il loro raggiungimento.",
			"ja":    "規律は、目標と達成をつなぐ橋である。",
			"zh":    "自律是连接目标与成就的桥梁。",
			"ko":    "규율은 목표와 성취를 잇는 다리다.",
			"hi":    "अनुशासन लक्ष्यों और उपलब्धि के बीच का पुल है।",
			"pl":    "Dyscyplina to most między celami a ich osiągnięciem.",
			"tr":    "Disiplin, hedefler ile başarı arasındaki köprüdür.",
			"uk":    "Дисципліна — це міст між цілями та їх досягненням.",
			"sv":    "Disciplin är bron mellan mål och förverkligande.",
			"nl":    "Discipline is de brug tussen doelen en verwezenlijking.",
			"nb":    "Disiplin er broen mellom mål og gjennomføring.",
			"da":    "Disciplin er broen mellem mål og resultater.",
			"fi":    "Kuri on silta tavoitteiden ja saavutusten välillä.",
		},
	},
	{
		ID:       "commitment-7",
		Author:   ptr("Johann Wolfgang von Goethe"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Knowing is not enough; we must apply. Willing is not enough; we must do.",
			"en-GB": "Knowing is not enough; we must apply. Willing is not enough; we must do.",
			"pt-PT": "Saber não é suficiente; devemos aplicar. Querer não é suficiente; devemos fazer.",
			"pt-BR": "Saber não é suficiente; devemos aplicar. Querer não é suficiente; devemos fazer.",
			"es":    "Saber no es suficiente; debemos aplicar. Querer no es suficiente; debemos hacer.",
			"fr":    "Savoir ne suffit pas ; il faut appliquer. Vouloir ne suffit pas ; il faut faire.",
			"de":    "Es ist nicht genug zu wissen, man muss auch anwenden; es ist nicht genug zu wollen, man muss auch tun.",
			"it":    "Sapere non basta; dobbiamo applicare. Volere non basta; dobbiamo fare.",
			"ja":    "知るだけでは足りない。応用しなければ。望むだけでは足りない。実行しなければ。",
			"zh":    "知道是不够的，必须运用；愿意是不够的，必须行动。",
			"ko":    "아는 것만으로는 충분하지 않다. 적용해야 한다. 원하는 것만으로는 충분하지 않다. 실행해야 한다.",
			"hi":    "जानना काफ़ी नहीं; हमें लागू करना होगा। चाहना काफ़ी नहीं; हमें करना होगा।",
			"pl":    "Wiedzieć nie wystarczy; trzeba stosować. Chcieć nie wystarczy; trzeba działać.",
			"tr":    "Bilmek yetmez; uygulamalıyız. İstemek yetmez; yapmalıyız.",
			"uk":    "Знати недостатньо — треба застосовувати. Бажати недостатньо — треба діяти.",
			"sv":    "Att veta räcker inte; vi måste tillämpa. Att vilja räcker inte; vi måste göra.",
			"nl":    "Weten is niet genoeg; we moeten toepassen. Willen is niet genoeg; we moeten doen.",
			"nb":    "Å vite er ikke nok; vi må anvende. Å ville er ikke nok; vi må gjøre.",
			"da":    "At vide er ikke nok; vi må anvende. At ville er ikke nok; vi må handle.",
			"fi":    "Tietäminen ei riitä; on sovellettava. Tahtominen ei riitä; on tehtävä.",
		},
	},
	{
		ID:       "commitment-8",
		Author:   ptr("Napoleon Hill"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Don't wait. The time will never be just right.",
			"en-GB": "Don't wait. The time will never be just right.",
			"pt-PT": "Não esperes. O momento nunca será o ideal.",
			"pt-BR": "Não espere. O momento nunca será o ideal.",
			"es":    "No esperes. El momento nunca será el ideal.",
			"fr":    "N'attendez pas. Le moment ne sera jamais tout à fait propice.",
			"de":    "Warte nicht. Der Zeitpunkt wird nie genau richtig sein.",
			"it":    "Non aspettare. Il momento non sarà mai perfetto.",
			"ja":    "待つな。完璧なタイミングなど決して来ない。",
			"zh":    "别等了。时机永远不会刚刚好。",
			"ko":    "기다리지 마라. 완벽한 때는 결코 오지 않는다.",
			"hi":    "इंतज़ार मत करो। समय कभी बिल्कुल सही नहीं होगा।",
			"pl":    "Nie czekaj. Czas nigdy nie będzie idealny.",
			"tr":    "Bekleme. Zaman asla tam olarak uygun olmayacak.",
			"uk":    "Не чекай. Час ніколи не буде ідеальним.",
			"sv":    "Vänta inte. Tiden kommer aldrig att vara helt rätt.",
			"nl":    "Wacht niet. Het moment zal nooit precies goed zijn.",
			"nb":    "Ikke vent. Tidspunktet vil aldri være helt riktig.",
			"da":    "Vent ikke. Tidspunktet bliver aldrig helt rigtigt.",
			"fi":    "Älä odota. Aika ei koskaan ole täysin oikea.",
		},
	},
	{
		ID:       "commitment-9",
		Author:   ptr("Nike"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Just do it.",
			"en-GB": "Just do it.",
			"pt-PT": "Apenas faz.",
			"pt-BR": "Apenas faça.",
			"es":    "Simplemente hazlo.",
			"fr":    "Fais-le, tout simplement.",
			"de":    "Tu es einfach.",
			"it":    "Fallo e basta.",
			"ja":    "とにかくやってみよう。",
			"zh":    "放手去做。",
			"ko":    "그냥 하라.",
			"hi":    "बस कर डालो।",
			"pl":    "Po prostu to zrób.",
			"tr":    "Sadece yap.",
			"uk":    "Просто зроби це.",
			"sv":    "Gör det bara.",
			"nl":    "Doe het gewoon.",
			"nb":    "Bare gjør det.",
			"da":    "Bare gør det.",
			"fi":    "Tee se.",
		},
	},
	{
		ID:       "commitment-10",
		Author:   ptr("Lao Tzu"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The journey of a thousand miles begins with one step.",
			"en-GB": "The journey of a thousand miles begins with one step.",
			"pt-PT": "A jornada de mil milhas começa com um passo.",
			"pt-BR": "A jornada de mil milhas começa com um passo.",
			"es":    "El viaje de mil millas comienza con un paso.",
			"fr":    "Le voyage de mille lieues commence par un pas.",
			"de":    "Eine Reise von tausend Meilen beginnt mit einem einzigen Schritt.",
			"it":    "Un viaggio di mille miglia comincia con un solo passo.",
			"ja":    "千里の道も一歩から。",
			"zh":    "千里之行，始于足下。",
			"ko":    "천 리 길도 한 걸음부터 시작된다.",
			"hi":    "हज़ार मील की यात्रा एक कदम से शुरू होती है।",
			"pl":    "Podróż tysiąca mil zaczyna się od jednego kroku.",
			"tr":    "Bin millik yolculuk tek bir adımla başlar.",
			"uk":    "Подорож у тисячу миль починається з одного кроку.",
			"sv":    "En resa på tusen mil börjar med ett enda steg.",
			"nl":    "Een reis van duizend mijl begint met één stap.",
			"nb":    "En reise på tusen mil begynner med ett skritt.",
			"da":    "En rejse på tusind mil begynder med et enkelt skridt.",
			"fi":    "Tuhannen mailin matka alkaa yhdellä askeleella.",
		},
	},
	{
		ID:       "commitment-11",
		Author:   ptr("Dale Carnegie"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Inaction breeds doubt and fear. Commitment breeds confidence and courage.",
			"en-GB": "Inaction breeds doubt and fear. Commitment breeds confidence and courage.",
			"pt-PT": "A inação gera dúvida e medo. A ação gera confiança e coragem.",
			"pt-BR": "A inação gera dúvida e medo. A ação gera confiança e coragem.",
			"es":    "La inacción engendra duda y miedo. La acción engendra confianza y coraje.",
			"fr":    "L'inaction engendre le doute et la peur. L'commitment engendre la confiance et le courage.",
			"de":    "Untätigkeit erzeugt Zweifel und Angst. Handeln erzeugt Selbstvertrauen und Mut.",
			"it":    "L'inazione genera dubbio e paura. L'azione genera fiducia e coraggio.",
			"ja":    "行動しなければ疑いと恐れが生まれる。行動すれば自信と勇気が生まれる。",
			"zh":    "不行动滋生疑虑和恐惧，行动孕育信心和勇气。",
			"ko":    "행동하지 않으면 의심과 두려움이 자라고, 행동하면 자신감과 용기가 자란다.",
			"hi":    "निष्क्रियता संदेह और भय पैदा करती है। कर्म आत्मविश्वास और साहस पैदा करता है।",
			"pl":    "Bezczynność rodzi wątpliwości i strach. Działanie rodzi pewność siebie i odwagę.",
			"tr":    "Eylemsizlik şüphe ve korku doğurur. Eylem güven ve cesaret doğurur.",
			"uk":    "Бездіяльність породжує сумніви і страх. Дія породжує впевненість і сміливість.",
			"sv":    "Passivitet föder tvivel och rädsla. Handling föder självförtroende och mod.",
			"nl":    "Niets doen kweekt twijfel en angst. Actie kweekt vertrouwen en moed.",
			"nb":    "Passivitet avler tvil og frykt. Handling avler selvtillit og mot.",
			"da":    "Passivitet avler tvivl og frygt. Handling avler selvtillid og mod.",
			"fi":    "Toimettomuus synnyttää epäilystä ja pelkoa. Toiminta synnyttää itseluottamusta ja rohkeutta.",
		},
	},
	{
		ID:       "commitment-12",
		Author:   ptr("Thomas Edison"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The value of an idea lies in the using of it.",
			"en-GB": "The value of an idea lies in the using of it.",
			"pt-PT": "O valor de uma ideia reside na sua utilização.",
			"pt-BR": "O valor de uma ideia reside na sua utilização.",
			"es":    "El valor de una idea radica en su uso.",
			"fr":    "La valeur d'une idée réside dans son utilisation.",
			"de":    "Der Wert einer Idee liegt in ihrer Anwendung.",
			"it":    "Il valore di un'idea sta nel metterla in pratica.",
			"ja":    "アイデアの価値は、それを使うことにある。",
			"zh":    "一个想法的价值在于运用它。",
			"ko":    "아이디어의 가치는 그것을 활용하는 데 있다.",
			"hi":    "किसी विचार का मूल्य उसके उपयोग में है।",
			"pl":    "Wartość pomysłu tkwi w jego wykorzystaniu.",
			"tr":    "Bir fikrin değeri onu kullanmakta yatar.",
			"uk":    "Цінність ідеї полягає в її застосуванні.",
			"sv":    "Värdet av en idé ligger i att använda den.",
			"nl":    "De waarde van een idee ligt in het gebruik ervan.",
			"nb":    "Verdien av en idé ligger i bruken av den.",
			"da":    "Værdien af en idé ligger i at bruge den.",
			"fi":    "Idean arvo on sen käyttämisessä.",
		},
	},
	{
		ID:       "commitment-13",
		Author:   ptr("Bruce Lee"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "If you spend too much time thinking about a thing, you'll never get it done.",
			"en-GB": "If you spend too much time thinking about a thing, you'll never get it done.",
			"pt-PT": "Se passares demasiado tempo a pensar numa coisa, nunca a farás.",
			"pt-BR": "Se você passar muito tempo pensando em algo, nunca o fará.",
			"es":    "Si pasas demasiado tiempo pensando en algo, nunca lo harás.",
			"fr":    "Si vous passez trop de temps à penser à une chose, vous ne la ferez jamais.",
			"de":    "Wenn du zu viel Zeit damit verbringst, über eine Sache nachzudenken, wirst du sie nie erledigen.",
			"it":    "Se passi troppo tempo a pensare a una cosa, non la porterai mai a termine.",
			"ja":    "考えることに時間をかけすぎれば、決してやり遂げられない。",
			"zh":    "如果花太多时间去想一件事，你永远也做不成它。",
			"ko":    "어떤 일을 너무 오래 생각만 하면 결코 해내지 못한다.",
			"hi":    "अगर आप किसी चीज़ के बारे में बहुत ज़्यादा सोचते रहेंगे, तो उसे कभी पूरा नहीं कर पाएँगे।",
			"pl":    "Jeśli poświęcasz zbyt wiele czasu na myślenie o czymś, nigdy tego nie zrobisz.",
			"tr":    "Bir şey üzerine çok fazla düşünürsen, onu asla bitiremezsin.",
			"uk":    "Якщо надто довго думати про справу, ніколи її не зробиш.",
			"sv":    "Om du ägnar för mycket tid åt att tänka på en sak blir den aldrig gjord.",
			"nl":    "Als je te veel tijd besteedt aan nadenken over iets, krijg je het nooit gedaan.",
			"nb":    "Bruker du for mye tid på å tenke på noe, får du det aldri gjort.",
			"da":    "Bruger du for meget tid på at tænke over noget, får du det aldrig gjort.",
			"fi":    "Jos käytät liikaa aikaa asian miettimiseen, et koskaan saa sitä tehtyä.",
		},
	},
	{
		ID:       "commitment-14",
		Author:   ptr("Benjamin Franklin"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Well done is better than well said.",
			"en-GB": "Well done is better than well said.",
			"pt-PT": "Bem feito é melhor do que bem dito.",
			"pt-BR": "Bem feito é melhor do que bem dito.",
			"es":    "Bien hecho es mejor que bien dicho.",
			"fr":    "Bien fait vaut mieux que bien dit.",
			"de":    "Gut gemacht ist besser als gut gesagt.",
			"it":    "Ben fatto è meglio che ben detto.",
			"ja":    "立派に行うことは、立派に語ることに勝る。",
			"zh":    "做得好胜过说得好。",
			"ko":    "잘 해내는 것이 잘 말하는 것보다 낫다.",
			"hi":    "अच्छा करना अच्छा कहने से बेहतर है।",
			"pl":    "Dobrze zrobione jest lepsze niż dobrze powiedziane.",
			"tr":    "İyi yapılmış, iyi söylenmişten daha iyidir.",
			"uk":    "Добре зроблене краще за добре сказане.",
			"sv":    "Väl gjort är bättre än väl sagt.",
			"nl":    "Goed gedaan is beter dan goed gezegd.",
			"nb":    "Godt gjort er bedre enn godt sagt.",
			"da":    "Godt gjort er bedre end godt sagt.",
			"fi":    "Hyvin tehty on parempi kuin hyvin sanottu.",
		},
	},
	{
		ID:       "commitment-15",
		Author:   ptr("Amelia Earhart"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The most effective way to do it, is to do it.",
			"en-GB": "The most effective way to do it, is to do it.",
			"pt-PT": "A forma mais eficaz de o fazer, é fazê-lo.",
			"pt-BR": "A maneira mais eficaz de fazer algo é fazendo.",
			"es":    "La forma más eficaz de hacerlo es haciéndolo.",
			"fr":    "La façon la plus efficace de le faire est de le faire.",
			"de":    "Der wirksamste Weg, etwas zu tun, ist, es zu tun.",
			"it":    "Il modo più efficace per farlo è farlo.",
			"ja":    "物事を成し遂げる最も効果的な方法は、それを実行することだ。",
			"zh":    "做成一件事最有效的方法，就是去做。",
			"ko":    "무언가를 해내는 가장 효과적인 방법은 그것을 하는 것이다.",
			"hi":    "किसी काम को करने का सबसे प्रभावी तरीक़ा है, उसे कर डालना।",
			"pl":    "Najskuteczniejszym sposobem, by coś zrobić, jest to zrobić.",
			"tr":    "Bir şeyi yapmanın en etkili yolu, onu yapmaktır.",
			"uk":    "Найефективніший спосіб щось зробити — зробити це.",
			"sv":    "Det mest effektiva sättet att göra något är att göra det.",
			"nl":    "De meest effectieve manier om iets te doen, is het te doen.",
			"nb":    "Den mest effektive måten å gjøre noe på, er å gjøre det.",
			"da":    "Den mest effektive måde at gøre noget på er at gøre det.",
			"fi":    "Tehokkain tapa tehdä jotain on tehdä se.",
		},
	},
	{
		ID:       "commitment-16",
		Author:   ptr("Steve Backley"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "There are no shortcuts to any place worth going.",
			"en-GB": "There are no shortcuts to any place worth going.",
			"pt-PT": "Não há atalhos para nenhum lugar que valha a pena ir.",
			"pt-BR": "Não há atalhos para nenhum lugar que valha a pena ir.",
			"es":    "No hay atajos para ningún lugar al que valga la pena ir.",
			"fr":    "Il n'y a pas de raccourcis pour les endroits qui en valent la peine.",
			"de":    "Es gibt keine Abkürzungen zu einem Ort, der es wert ist, erreicht zu werden.",
			"it":    "Non ci sono scorciatoie per i luoghi che vale la pena raggiungere.",
			"ja":    "行く価値のある場所への近道は存在しない。",
			"zh":    "凡是值得去的地方，都没有捷径。",
			"ko":    "갈 만한 가치가 있는 곳에 지름길은 없다.",
			"hi":    "जहाँ जाना सार्थक हो, वहाँ का कोई शॉर्टकट नहीं होता।",
			"pl":    "Nie ma drogi na skróty do miejsc, do których warto dotrzeć.",
			"tr":    "Gitmeye değer hiçbir yere kestirme yol yoktur.",
			"uk":    "До місць, куди варто дійти, не буває коротких шляхів.",
			"sv":    "Det finns inga genvägar till platser värda att nå.",
			"nl":    "Er zijn geen kortere wegen naar plekken die de moeite waard zijn.",
			"nb":    "Det finnes ingen snarveier til steder som er verdt å nå.",
			"da":    "Der findes ingen genveje til steder, der er værd at nå.",
			"fi":    "Paikkaan, jonne kannattaa mennä, ei ole oikoteitä.",
		},
	},
	{
		ID:       "commitment-17",
		Author:   ptr("Robert Louis Stevenson"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Don't judge each day by the harvest you reap but by the seeds that you plant.",
			"en-GB": "Don't judge each day by the harvest you reap but by the seeds that you plant.",
			"pt-PT": "Não julgues cada dia pela colheita que colhes, mas pelas sementes que plantas.",
			"pt-BR": "Não julgue cada dia pela colheita que você colhe, mas pelas sementes que você planta.",
			"es":    "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.",
			"fr":    "Ne jugez pas chaque journée à la récolte que vous faites, mais aux graines que vous semez.",
			"de":    "Beurteile den Tag nicht nach der Ernte, die du einfährst, sondern nach den Samen, die du säst.",
			"it":    "Non giudicare ogni giorno dal raccolto che ottieni, ma dai semi che pianti.",
			"ja":    "一日を刈り取った収穫で判断するな。蒔いた種で判断せよ。",
			"zh":    "评判一天，不要看你收获了什么，而要看你播下了什么种子。",
			"ko":    "하루를 거둔 수확이 아니라 심은 씨앗으로 평가하라.",
			"hi":    "हर दिन को उस फ़सल से मत आँको जो आप काटते हैं, बल्कि उन बीजों से आँको जो आप बोते हैं।",
			"pl":    "Nie oceniaj dnia po zbiorach, które zebrałeś, lecz po ziarnach, które zasiałeś.",
			"tr":    "Her günü topladığın hasada göre değil, ektiğin tohumlara göre değerlendir.",
			"uk":    "Суди про день не за врожаєм, який зібрав, а за насінням, яке посіяв.",
			"sv":    "Döm inte dagen efter skörden du bärgar utan efter fröna du sår.",
			"nl":    "Beoordeel de dag niet naar de oogst die je binnenhaalt, maar naar de zaden die je plant.",
			"nb":    "Døm ikke dagen etter avlingen du høster, men etter frøene du sår.",
			"da":    "Døm ikke dagen på den høst, du henter, men på de frø, du sår.",
			"fi":    "Älä arvioi päivää korjaamasi sadon mukaan, vaan kylvämiesi siementen mukaan.",
		},
	},
	{
		ID:       "commitment-18",
		Author:   ptr("Theodore Roosevelt"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Do what you can, with what you have, where you are.",
			"en-GB": "Do what you can, with what you have, where you are.",
			"pt-PT": "Faz o que podes, com o que tens, onde estás.",
			"pt-BR": "Faça o que puder, com o que tiver, onde estiver.",
			"es":    "Haz lo que puedas, con lo que tengas, donde estés.",
			"fr":    "Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.",
			"de":    "Tu, was du kannst, mit dem, was du hast, dort, wo du bist.",
			"it":    "Fai ciò che puoi, con ciò che hai, dove sei.",
			"ja":    "今いる場所で、持っているもので、できることをせよ。",
			"zh":    "在你所在之处，用你所拥有的，做你能做的。",
			"ko":    "지금 있는 곳에서, 가진 것으로, 할 수 있는 일을 하라.",
			"hi":    "जो कर सकते हो करो, जो है उसके साथ, जहाँ हो वहीं।",
			"pl":    "Rób, co możesz, tym, co masz, tam, gdzie jesteś.",
			"tr":    "Bulunduğun yerde, sahip olduklarınla, yapabildiğini yap.",
			"uk":    "Роби, що можеш, з тим, що маєш, там, де ти є.",
			"sv":    "Gör vad du kan, med vad du har, där du är.",
			"nl":    "Doe wat je kunt, met wat je hebt, waar je bent.",
			"nb":    "Gjør det du kan, med det du har, der du er.",
			"da":    "Gør, hvad du kan, med hvad du har, dér hvor du er.",
			"fi":    "Tee mitä voit, sillä mitä sinulla on, siellä missä olet.",
		},
	},
	{
		ID:       "commitment-19",
		Author:   ptr("William Hazlitt"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Procrastination is the thief of time.",
			"en-GB": "Procrastination is the thief of time.",
			"pt-PT": "A procrastinação é a ladra do tempo.",
			"pt-BR": "A procrastinação é a ladra do tempo.",
			"es":    "La procrastinación é el ladrón del tiempo.",
			"fr":    "La procrastination est le voleur de temps.",
			"de":    "Aufschub ist der Dieb der Zeit.",
			"it":    "La procrastinazione è la ladra del tempo.",
			"ja":    "先延ばしは時間の泥棒である。",
			"zh":    "拖延是时间的窃贼。",
			"ko":    "미루는 습관은 시간을 훔치는 도둑이다.",
			"hi":    "टालमटोल समय की चोर है।",
			"pl":    "Prokrastynacja to złodziej czasu.",
			"tr":    "Erteleme, zamanın hırsızıdır.",
			"uk":    "Зволікання — злодій часу.",
			"sv":    "Uppskjutandet är tidens tjuv.",
			"nl":    "Uitstel is de dief van de tijd.",
			"nb":    "Utsettelse er tidens tyv.",
			"da":    "Udsættelse er tidens tyv.",
			"fi":    "Vitkastelu on ajan varas.",
		},
	},
	{
		ID:       "commitment-20",
		Author:   ptr("Scott Belsky"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "It’s not about ideas. It’s about making ideas happen.",
			"en-GB": "It’s not about ideas. It’s about making ideas happen.",
			"pt-PT": "Não se trata de ideias. Trata-se de fazer as ideias acontecerem.",
			"pt-BR": "Não se trata de ideias. Trata-se de fazer as ideias acontecerem.",
			"es":    "No se trata de ideas. Se trata de hacer que las ideas sucedan.",
			"fr":    "Il ne s'agit pas d'idées. Il s'agit de faire en sorte que les idées se réalisent.",
			"de":    "Es geht nicht um Ideen. Es geht darum, Ideen Wirklichkeit werden zu lassen.",
			"it":    "Non si tratta di avere idee. Si tratta di realizzarle.",
			"ja":    "大事なのはアイデアではない。アイデアを実現することだ。",
			"zh":    "重要的不是想法，而是把想法变成现实。",
			"ko":    "중요한 건 아이디어가 아니다. 아이디어를 실현하는 것이다.",
			"hi":    "बात विचारों की नहीं है। बात विचारों को साकार करने की है।",
			"pl":    "Nie chodzi o pomysły. Chodzi o ich urzeczywistnianie.",
			"tr":    "Mesele fikirler değil. Mesele fikirleri gerçeğe dönüştürmektir.",
			"uk":    "Справа не в ідеях. Справа в тому, щоб втілювати їх у життя.",
			"sv":    "Det handlar inte om idéer. Det handlar om att förverkliga dem.",
			"nl":    "Het gaat niet om ideeën. Het gaat erom ideeën waar te maken.",
			"nb":    "Det handler ikke om ideer. Det handler om å gjøre ideer til virkelighet.",
			"da":    "Det handler ikke om idéer. Det handler om at føre idéer ud i livet.",
			"fi":    "Kyse ei ole ideoista, vaan siitä, että ideat toteutetaan.",
		},
	},
	{
		ID:       "commitment-21",
		Author:   ptr("Marie Forleo"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Everything is figureoutable.",
			"en-GB": "Everything is figureoutable.",
			"pt-PT": "Tudo é resolúvel.",
			"pt-BR": "Tudo é resolvível.",
			"es":    "Todo tiene solución.",
			"fr":    "Tout est possible à résoudre.",
			"de":    "Für alles lässt sich eine Lösung finden.",
			"it":    "Tutto si può risolvere.",
			"ja":    "どんなことにも必ず解決策はある。",
			"zh":    "凡事皆有办法解决。",
			"ko":    "모든 일은 해결할 방법이 있다.",
			"hi":    "हर चीज़ का हल निकाला जा सकता है।",
			"pl":    "Wszystko da się rozwiązać.",
			"tr":    "Her şeyin bir çözümü vardır.",
			"uk":    "Будь-яку задачу можна розв'язати.",
			"sv":    "Allt går att lösa.",
			"nl":    "Alles is op te lossen.",
			"nb":    "Alt kan løses.",
			"da":    "Alt kan løses.",
			"fi":    "Kaikki on ratkaistavissa.",
		},
	},
	{
		ID:       "commitment-22",
		Author:   ptr("Joe Namath"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "If you aren't going all the way, why go at all?",
			"en-GB": "If you aren't going all the way, why go at all?",
			"pt-PT": "Se não vais até ao fim, para quê ir sequer?",
			"pt-BR": "Se você não for até o fim, por que ir sequer?",
			"es":    "Si no vas a llegar hasta el final, ¿para qué ir siquiera?",
			"fr":    "Si vous n'allez pas jusqu'au bout, pourquoi y aller du tout ?",
			"de":    "Wenn du nicht den ganzen Weg gehst, warum überhaupt losgehen?",
			"it":    "Se non vai fino in fondo, perché partire?",
			"ja":    "最後までやり抜かないなら、なぜ始めるのか。",
			"zh":    "如果不打算走到底，又何必出发？",
			"ko":    "끝까지 가지 않을 거라면, 애초에 왜 가는가?",
			"hi":    "अगर पूरा रास्ता तय नहीं करना, तो चलना ही क्यों?",
			"pl":    "Jeśli nie zamierzasz iść do końca, po co w ogóle iść?",
			"tr":    "Sonuna kadar gitmeyeceksen, neden yola çıkasın ki?",
			"uk":    "Якщо не збираєшся йти до кінця, навіщо взагалі йти?",
			"sv":    "Om du inte tänker gå hela vägen, varför gå alls?",
			"nl":    "Als je niet helemaal wilt gaan, waarom zou je dan überhaupt gaan?",
			"nb":    "Hvis du ikke skal gå hele veien, hvorfor gå i det hele tatt?",
			"da":    "Hvis du ikke går hele vejen, hvorfor så overhovedet gå?",
			"fi":    "Jos et aio mennä loppuun asti, miksi lähteä lainkaan?",
		},
	},
	{
		ID:       "commitment-23",
		Author:   ptr("Winston Churchill"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "I never worry about commitment, but only about inaction.",
			"en-GB": "I never worry about commitment, but only about inaction.",
			"pt-PT": "Nunca me preocupo com a ação, mas apenas com a inação.",
			"pt-BR": "Nunca me preocupo com a ação, apenas com a inação.",
			"es":    "Nunca me preocupa la acción, sino únicamente la inacción.",
			"fr":    "Je ne m'inquiète jamais de l'commitment, mais seulement de l'inaction.",
			"de":    "Ich sorge mich nie über das Handeln, sondern nur über das Nichthandeln.",
			"it":    "Non mi preoccupo mai dell'azione, ma solo dell'inazione.",
			"ja":    "私が心配するのは行動することではなく、行動しないことだけだ。",
			"zh":    "我从不担心行动，我只担心不行动。",
			"ko":    "나는 행동을 걱정한 적이 없다. 오직 행동하지 않는 것을 걱정할 뿐이다.",
			"hi":    "मुझे कभी कर्म की चिंता नहीं होती, चिंता होती है तो केवल निष्क्रियता की।",
			"pl":    "Nigdy nie martwię się działaniem, a jedynie bezczynnością.",
			"tr":    "Ben asla eylemden değil, yalnızca eylemsizlikten endişe duyarım.",
			"uk":    "Я ніколи не тривожуся через дію — лише через бездіяльність.",
			"sv":    "Jag oroar mig aldrig för handling, bara for overksamhet.",
			"nl":    "Ik maak me nooit zorgen over actie, alleen over inactie.",
			"nb":    "Jeg bekymrer meg aldri for handling, bare for passivitet.",
			"da":    "Jeg bekymrer mig aldrig om handling, kun om passivitet.",
			"fi":    "En koskaan huolehdi toiminnasta, vaan ainoastaan toimettomuudesta.",
		},
	},
	{
		ID:       "commitment-24",
		Author:   ptr("Francis of Assisi"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
			"en-GB": "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
			"pt-PT": "Começa por fazer o que é necessário; depois faz o que é possível; e de repente estás a fazer o impossível.",
			"pt-BR": "Comece fazendo o que é necessário; depois faça o que é possível; e de repente você estará fazendo o impossível.",
			"es":    "Empieza haciendo lo necesario; luego haz lo posible; y de repente estarás haciendo lo imposible.",
			"fr":    "Commencez par faire ce qui est nécessaire ; puis faites ce qui est possible ; et soudain vous ferez l'impossible.",
			"de":    "Beginne mit dem Notwendigen, dann tu das Mögliche, und plötzlich schaffst du das Unmögliche.",
			"it":    "Comincia col fare ciò che è necessario, poi ciò che è possibile, e all'improvviso ti sorprenderai a fare l'impossibile.",
			"ja":    "まず必要なことから始めよ。次に可能なことを。すると気づけば不可能なことを成し遂げている。",
			"zh":    "先做必要的事，再做可能的事，突然之间你就在做不可能的事了。",
			"ko":    "먼저 필요한 일을 하고, 그다음 가능한 일을 하라. 그러면 어느새 불가능한 일을 하고 있을 것이다.",
			"hi":    "पहले वह करो जो ज़रूरी है; फिर वह जो संभव है; और अचानक तुम असंभव कर रहे होगे।",
			"pl":    "Zacznij od tego, co konieczne; potem zrób to, co możliwe; a nagle odkryjesz, że dokonujesz niemożliwego.",
			"tr":    "Önce gerekli olanı yap, sonra mümkün olanı; bir de bakmışsın imkânsızı başarıyorsun.",
			"uk":    "Почни з необхідного, потім зроби можливе — і раптом ти вже робиш неможливе.",
			"sv":    "Börja med det nödvändiga, gör sedan det möjliga, och plötsligt gör du det omöjliga.",
			"nl":    "Begin met wat noodzakelijk is; doe dan wat mogelijk is; en opeens doe je het onmogelijke.",
			"nb":    "Begynn med det nødvendige, gjør så det mulige, og plutselig gjør du det umulige.",
			"da":    "Begynd med det nødvendige; gør så det mulige; og pludselig gør du det umulige.",
			"fi":    "Aloita välttämättömästä, tee sitten mahdollinen — ja yhtäkkiä teet mahdotonta.",
		},
	},
	{
		ID:       "commitment-25",
		Author:   ptr("Pablo Picasso"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Inspiration exists, but it has to find you working.",
			"en-GB": "Inspiration exists, but it has to find you working.",
			"pt-PT": "A inspiração existe, mas tem de te encontrar a trabalhar.",
			"pt-BR": "A inspiração existe, mas tem de te encontrar trabalhando.",
			"es":    "La inspiración existe, pero tiene que encontrarte trabajando.",
			"fr":    "L'inspiration existe, mais elle doit vous trouver en train de travailler.",
			"de":    "Inspiration existiert, aber sie muss dich bei der Arbeit antreffen.",
			"it":    "L'ispirazione esiste, ma deve trovarti al lavoro.",
			"ja":    "ひらめきは存在する。だが、それは働いているあなたのもとにしか訪れない。",
			"zh":    "灵感是存在的，但它必须在你工作时才会找到你。",
			"ko":    "영감은 존재한다. 하지만 그것은 일하고 있는 당신을 찾아온다.",
			"hi":    "प्रेरणा होती है, लेकिन उसे आपको काम करते हुए पाना चाहिए।",
			"pl":    "Natchnienie istnieje, ale musi zastać cię przy pracy.",
			"tr":    "İlham vardır, ama seni çalışırken bulmalıdır.",
			"uk":    "Натхнення існує, але воно має застати тебе за роботою.",
			"sv":    "Inspiration finns, men den måste hitta dig i arbete.",
			"nl":    "Inspiratie bestaat, maar ze moet je werkend aantreffen.",
			"nb":    "Inspirasjon finnes, men den må finne deg i arbeid.",
			"da":    "Inspiration findes, men den skal finde dig i arbejde.",
			"fi":    "Inspiraatio on olemassa, mutta sen on löydettävä sinut työn ääreltä.",
		},
	},
	{
		ID:       "commitment-26",
		Author:   ptr("David Allen"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Your mind is for having ideas, not holding them.",
			"en-GB": "Your mind is for having ideas, not holding them.",
			"pt-PT": "A tua mente serve para ter ideias, não para as guardar.",
			"pt-BR": "Sua mente serve para ter ideias, não para guardá-las.",
			"es":    "Tu mente está para tener ideas, no para guardarlas.",
			"fr":    "Votre esprit est fait pour avoir des idées, pas pour les retenir.",
			"de":    "Dein Kopf ist da, um Ideen zu haben, nicht um sie festzuhalten.",
			"it":    "La tua mente serve ad avere idee, non a trattenerle.",
			"ja":    "頭はアイデアを生み出すためにあり、抱え込むためにあるのではない。",
			"zh":    "大脑是用来产生想法的，不是用来储存想法的。",
			"ko":    "머리는 아이디어를 떠올리기 위한 것이지, 붙들어 두기 위한 것이 아니다.",
			"hi":    "आपका दिमाग़ विचार पैदा करने के लिए है, उन्हें संभालकर रखने के लिए नहीं।",
			"pl":    "Twój umysł służy do tworzenia pomysłów, nie do ich przechowywania.",
			"tr":    "Zihnin fikir üretmek içindir, fikirleri tutmak için değil.",
			"uk":    "Розум створений, щоб народжувати ідеї, а не тримати їх у собі.",
			"sv":    "Ditt sinne är till för att få idéer, inte för att lagra dem.",
			"nl":    "Je hoofd is er om ideeën te krijgen, niet om ze vast te houden.",
			"nb":    "Hodet ditt er til for å få ideer, ikke for å holde på dem.",
			"da":    "Dit hoved er til at få idéer, ikke til at holde på dem.",
			"fi":    "Mielesi on ideoiden keksimistä varten, ei niiden säilyttämistä varten.",
		},
	},
	{
		ID:       "commitment-27",
		Author:   ptr("Sheryl Sandberg"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Done is better than perfect.",
			"en-GB": "Done is better than perfect.",
			"pt-PT": "Feito é melhor do que perfeito.",
			"pt-BR": "Feito é melhor que perfeito.",
			"es":    "Hecho es mejor que perfecto.",
			"fr":    "Mieux vaut fait que parfait.",
			"de":    "Fertig ist besser als perfekt.",
			"it":    "Fatto è meglio che perfetto.",
			"ja":    "完璧を目指すより、まず終わらせよ。",
			"zh":    "完成胜于完美。",
			"ko":    "완벽보다 완성이 낫다.",
			"hi":    "पूरा किया हुआ, परफ़ेक्ट से बेहतर है।",
			"pl":    "Zrobione jest lepsze niż doskonałe.",
			"tr":    "Bitmiş, mükemmelden iyidir.",
			"uk":    "Зроблене краще за ідеальне.",
			"sv":    "Klart är bättre än perfekt.",
			"nl":    "Af is beter dan perfect.",
			"nb":    "Ferdig er bedre enn perfekt.",
			"da":    "Færdigt er bedre end perfekt.",
			"fi":    "Valmis on parempi kuin täydellinen.",
		},
	},
	{
		ID:       "commitment-28",
		Author:   ptr("Jim Ryun"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Motivation is what gets you started. Habit is what keeps you going.",
			"en-GB": "Motivation is what gets you started. Habit is what keeps you going.",
			"pt-PT": "A motivação é o que te faz começar. O hábito é o que te faz continuar.",
			"pt-BR": "Motivação é o que faz você começar. Hábito é o que faz você continuar.",
			"es":    "La motivación es lo que te pone en marcha. El hábito es lo que te mantiene en movimiento.",
			"fr":    "La motivation est ce qui vous fait démarrer. L'habitude est ce qui vous fait continuer.",
			"de":    "Motivation bringt dich in Gang. Gewohnheit hält dich in Bewegung.",
			"it":    "La motivazione ti fa iniziare. L'abitudine ti fa continuare.",
			"ja":    "モチベーションは始める力。習慣は続ける力。",
			"zh":    "动力让你开始，习惯让你坚持。",
			"ko":    "동기는 시작하게 하고, 습관은 계속하게 한다.",
			"hi":    "प्रेरणा आपको शुरुआत कराती है। आदत आपको चलते रहने देती है।",
			"pl":    "Motywacja sprawia, że zaczynasz. Nawyk sprawia, że nie ustajesz.",
			"tr":    "Motivasyon seni başlatır. Alışkanlık seni devam ettirir.",
			"uk":    "Мотивація змушує почати. Звичка допомагає продовжувати.",
			"sv":    "Motivation får dig att börja. Vanan håller dig igång.",
			"nl":    "Motivatie zet je in beweging. Gewoonte houdt je op gang.",
			"nb":    "Motivasjon får deg i gang. Vane holder deg gående.",
			"da":    "Motivation får dig i gang. Vanen holder dig i gang.",
			"fi":    "Motivaatio saa sinut alkuun. Tottumus pitää sinut liikkeessä.",
		},
	},
	{
		ID:       "commitment-29",
		Author:   ptr("Charles Dickens"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Procrastination is the thief of time, collar him.",
			"en-GB": "Procrastination is the thief of time, collar him.",
			"pt-PT": "A procrastinação é a ladra do tempo, agarra-a pelo colarinho.",
			"pt-BR": "A procrastinação é a ladra do tempo, agarre-a pelo colarinho.",
			"es":    "La procrastinación es el ladrón del tiempo, atrápalo.",
			"fr":    "La procrastination est le voleur de temps, arrêtez-la.",
			"de":    "Aufschub ist der Dieb der Zeit — pack ihn beim Kragen.",
			"it":    "La procrastinazione è la ladra del tempo: acciuffala.",
			"ja":    "先延ばしは時間の泥棒だ。取り押さえよ。",
			"zh":    "拖延是时间的窃贼，抓住它。",
			"ko":    "미루기는 시간을 훔치는 도둑이다. 그 멱살을 잡아라.",
			"hi":    "टालमटोल समय की चोर है, उसे पकड़ लो।",
			"pl":    "Prokrastynacja to złodziej czasu — złap go za kołnierz.",
			"tr":    "Erteleme zamanın hırsızıdır, yakala onu.",
			"uk":    "Зволікання — злодій часу; схопи його за комір.",
			"sv":    "Uppskjutandet är tidens tjuv — grip honom.",
			"nl":    "Uitstel is de dief van de tijd; grijp hem in de kraag.",
			"nb":    "Utsettelse er tidens tyv — grip ham i kragen.",
			"da":    "Udsættelse er tidens tyv — grib ham i kraven.",
			"fi":    "Vitkastelu on ajan varas — ota se kiinni.",
		},
	},
	{
		ID:       "commitment-30",
		Author:   ptr("Unknown"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The best way to get something done is to begin.",
			"en-GB": "The best way to get something done is to begin.",
			"pt-PT": "A melhor forma de fazer algo é começar.",
			"pt-BR": "A melhor maneira de fazer algo é começar.",
			"es":    "La mejor forma de hacer algo es empezar.",
			"fr":    "La meilleure façon de faire avancer les choses est de commencer.",
			"de":    "Der beste Weg, etwas zu erledigen, ist anzufangen.",
			"it":    "Il modo migliore per fare qualcosa è cominciare.",
			"ja":    "物事を成し遂げる最善の方法は、始めることだ。",
			"zh":    "完成一件事的最好方法就是开始。",
			"ko":    "일을 끝내는 가장 좋은 방법은 시작하는 것이다.",
			"hi":    "किसी काम को पूरा करने का सबसे अच्छा तरीक़ा है शुरू करना।",
			"pl":    "Najlepszym sposobem, by coś zrobić, jest zacząć.",
			"tr":    "Bir işi bitirmenin en iyi yolu başlamaktır.",
			"uk":    "Найкращий спосіб щось зробити — почати.",
			"sv":    "Det bästa sättet att få något gjort är att börja.",
			"nl":    "De beste manier om iets gedaan te krijgen, is beginnen.",
			"nb":    "Den beste måten å få noe gjort på, er å begynne.",
			"da":    "Den bedste måde at få noget gjort på er at begynde.",
			"fi":    "Paras tapa saada jotain tehtyä on aloittaa.",
		},
	},
	{
		ID:       "commitment-31",
		Author:   ptr("Pablo Picasso"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Commitment is the foundational key to all success.",
			"en-GB": "Commitment is the foundational key to all success.",
			"pt-PT": "A ação é a chave fundamental para todo o sucesso.",
			"pt-BR": "A ação é a chave fundamental para todo o sucesso.",
			"es":    "La acción es la clave fundamental de todo éxito.",
			"fr":    "L'commitment est la clé fondamentale de tout succès.",
			"de":    "Handeln ist der grundlegende Schlüssel zu jedem Erfolg.",
			"it":    "L'azione è la chiave fondamentale di ogni successo.",
			"ja":    "行動こそ、あらゆる成功の根本的な鍵である。",
			"zh":    "行动是一切成功的根本关键。",
			"ko":    "행동은 모든 성공의 근본적인 열쇠다.",
			"hi":    "कर्म ही हर सफलता की बुनियादी कुंजी है।",
			"pl":    "Działanie jest podstawowym kluczem do każdego sukcesu.",
			"tr":    "Eylem, tüm başarının temel anahtarıdır.",
			"uk":    "Дія — основний ключ до будь-якого успіху.",
			"sv":    "Handling är den grundläggande nyckeln till all framgång.",
			"nl":    "Actie is de fundamentele sleutel tot elk succes.",
			"nb":    "Handling er den grunnleggende nøkkelen til all suksess.",
			"da":    "Handling er den grundlæggende nøgle til al succes.",
			"fi":    "Toiminta on kaiken menestyksen perusavain.",
		},
	},
	{
		ID:       "commitment-32",
		Author:   ptr("Walt Disney"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The way to get started is to quit talking and begin doing.",
			"en-GB": "The way to get started is to quit talking and begin doing.",
			"pt-PT": "A maneira de começar é parar de falar e começar a fazer.",
			"pt-BR": "A maneira de começar é parar de falar e começar a fazer.",
			"es":    "La forma de empezar es dejar de hablar y empezar a hacer.",
			"fr":    "Le moyen de commencer est d'arrêter de parler et de commencer à faire.",
			"de":    "Der Weg loszulegen ist, aufzuhören zu reden und anzufangen zu handeln.",
			"it":    "Il modo per iniziare è smettere di parlare e cominciare a fare.",
			"ja":    "始めるための方法は、語るのをやめて動き出すことだ。",
			"zh":    "起步的方法就是停止空谈，开始行动。",
			"ko":    "시작하는 방법은 말을 멈추고 행동에 옮기는 것이다.",
			"hi":    "शुरुआत करने का तरीक़ा है बात करना बंद करके काम शुरू करना।",
			"pl":    "Sposobem na rozpoczęcie jest przestać mówić i zacząć działać.",
			"tr":    "Başlamanın yolu konuşmayı bırakıp yapmaya koyulmaktır.",
			"uk":    "Щоб почати, треба перестати говорити й почати діяти.",
			"sv":    "Sättet att komma igång är att sluta prata och börja göra.",
			"nl":    "De manier om te beginnen is stoppen met praten en beginnen met doen.",
			"nb":    "Måten å komme i gang på er å slutte å snakke og begynne å gjøre.",
			"da":    "Måden at komme i gang på er at holde op med at tale og begynde at handle.",
			"fi":    "Tapa päästä alkuun on lakata puhumasta ja alkaa tehdä.",
		},
	},
	{
		ID:       "commitment-33",
		Author:   ptr("Karen Lamb"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "A year from now you may wish you had started today.",
			"en-GB": "A year from now you may wish you had started today.",
			"pt-PT": "Daqui a um ano vais desejar ter começado hoje.",
			"pt-BR": "Daqui a um ano você poderá desejar ter começado hoje.",
			"es":    "Dentro de un año desearás haber empezado hoy.",
			"fr":    "Dans un an, vous souhaiteriez avoir commencé aujourd'hui.",
			"de":    "In einem Jahr wirst du dir vielleicht wünschen, du hättest heute angefangen.",
			"it":    "Tra un anno potresti desiderare di aver iniziato oggi.",
			"ja":    "一年後、今日始めていればよかったと思うかもしれない。",
			"zh":    "一年后的你，也许会希望自己今天就已开始。",
			"ko":    "일 년 뒤의 당신은 오늘 시작했기를 바랄지도 모른다.",
			"hi":    "एक साल बाद आप चाहेंगे कि काश आज ही शुरुआत की होती।",
			"pl":    "Za rok możesz żałować, że nie zacząłeś dzisiaj.",
			"tr":    "Bir yıl sonra, bugün başlamış olmayı dileyebilirsin.",
			"uk":    "Через рік ти, можливо, пошкодуєш, що не почав сьогодні.",
			"sv":    "Om ett år kanske du önskar att du hade börjat i dag.",
			"nl":    "Over een jaar wou je misschien dat je vandaag was begonnen.",
			"nb":    "Om et år vil du kanskje ønske at du hadde begynt i dag.",
			"da":    "Om et år ville du måske ønske, at du var begyndt i dag.",
			"fi":    "Vuoden päästä saatat toivoa, että olisit aloittanut tänään.",
		},
	},
	{
		ID:       "commitment-34",
		Author:   ptr("Peter Marshall"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Small deeds done are better than great deeds planned.",
			"en-GB": "Small deeds done are better than great deeds planned.",
			"pt-PT": "Pequenas ações realizadas são melhores do que grandes ações planeadas.",
			"pt-BR": "Pequenas ações realizadas são melhores do que grandes ações planejadas.",
			"es":    "Pequeñas acciones realizadas son mejores que grandes acciones planeadas.",
			"fr":    "Les petites commitments accomplies valent mieux que les grandes commitments planifiées.",
			"de":    "Kleine vollbrachte Taten sind besser als große geplante.",
			"it":    "Piccole azioni compiute valgono più di grandi imprese pianificate.",
			"ja":    "実行された小さな行いは、計画された偉業に勝る。",
			"zh":    "做成的小事胜过计划中的大事。",
			"ko":    "실행한 작은 일이 계획만 한 큰 일보다 낫다.",
			"hi":    "किए गए छोटे काम, योजना में रह गए बड़े कामों से बेहतर हैं।",
			"pl":    "Małe czyny dokonane są lepsze niż wielkie czyny zaplanowane.",
			"tr":    "Yapılmış küçük işler, planlanmış büyük işlerden iyidir.",
			"uk":    "Малі здійснені справи кращі за великі заплановані.",
			"sv":    "Små utförda gärningar är bättre än stora planerade.",
			"nl":    "Kleine daden die gedaan zijn, zijn beter dan grote daden die gepland zijn.",
			"nb":    "Små gjerninger som er gjort, er bedre enn store gjerninger som er planlagt.",
			"da":    "Små udførte gerninger er bedre end store planlagte.",
			"fi":    "Pienet tehdyt teot ovat parempia kuin suuret suunnitellut.",
		},
	},
	{
		ID:       "commitment-35",
		Author:   ptr("Tony Robbins"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "The only impossible journey is the one you never begin.",
			"en-GB": "The only impossible journey is the one you never begin.",
			"pt-PT": "A única jornada impossível é aquela que nunca começas.",
			"pt-BR": "A única jornada impossível é aquela que você nunca começa.",
			"es":    "El único viaje imposible es el que nunca comienzas.",
			"fr":    "Le seul voyage impossible est celui que vous ne commencez jamais.",
			"de":    "Die einzige unmögliche Reise ist die, die du nie beginnst.",
			"it":    "L'unico viaggio impossibile è quello che non inizi mai.",
			"ja":    "唯一不可能な旅は、決して始めない旅だ。",
			"zh":    "唯一不可能的旅程，是你从未开始的那一段。",
			"ko":    "유일하게 불가능한 여정은 결코 시작하지 않는 여정이다.",
			"hi":    "एकमात्र असंभव यात्रा वह है जो आप कभी शुरू ही नहीं करते।",
			"pl":    "Jedyna niemożliwa podróż to ta, której nigdy nie rozpoczniesz.",
			"tr":    "Tek imkânsız yolculuk, hiç başlamadığındır.",
			"uk":    "Єдина неможлива подорож — та, яку ти так і не почав.",
			"sv":    "Den enda omöjliga resan är den du aldrig påbörjar.",
			"nl":    "De enige onmogelijke reis is die je nooit begint.",
			"nb":    "Den eneste umulige reisen er den du aldri begynner på.",
			"da":    "Den eneste umulige rejse er den, du aldrig begynder på.",
			"fi":    "Ainoa mahdoton matka on se, jota et koskaan aloita.",
		},
	},
	{
		ID:       "commitment-36",
		Author:   ptr("Napoleon Hill"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.",
			"en-GB": "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.",
			"pt-PT": "Não esperes; o tempo nunca será o 'certo'. Começa onde estás e trabalha com as ferramentas que tiveres à mão, e melhores ferramentas surgirão pelo caminho.",
			"pt-BR": "Não espere; o tempo nunca será o 'certo'. Comece onde está e trabalhe com as ferramentas que tiver à mão, e melhores ferramentas surgirão pelo caminho.",
			"es":    "No esperes; el momento nunca será el 'adecuado'. Empieza donde estás y trabaja con las herramientas que tengas a tu disposición, y encontrarás mejores herramientas a medida que avances.",
			"fr":    "N'attendez pas ; le moment ne sera jamais « le bon ». Commencez là où vous êtes, et travaillez avec tous les outils que vous avez à votre disposition, et vous en trouverez de meilleurs au fur et à mesure.",
			"de":    "Warte nicht; der Zeitpunkt wird nie „genau richtig“ sein. Beginne dort, wo du stehst, arbeite mit den Werkzeugen, die dir zur Verfügung stehen — bessere werden sich unterwegs finden.",
			"it":    "Non aspettare: il momento non sarà mai «perfetto». Comincia da dove ti trovi, usa gli strumenti che hai a disposizione, e strumenti migliori si troveranno strada facendo.",
			"ja":    "待ってはいけない。「ちょうど良い時」など決して来ない。今いる場所で始め、手元にある道具で取り組め。より良い道具は進むうちに見つかる。",
			"zh":    "不要等待；时机永远不会「刚刚好」。从你站立的地方开始，用你手头的工具去做，更好的工具会在前进的路上出现。",
			"ko":    "기다리지 마라. '딱 맞는 때'는 결코 오지 않는다. 서 있는 자리에서 시작하고, 지금 가진 도구로 일하라. 더 나은 도구는 나아가는 길에 찾게 될 것이다.",
			"hi":    "इंतज़ार मत करो; समय कभी 'बिल्कुल सही' नहीं होगा। जहाँ खड़े हो वहीं से शुरू करो, जो साधन पास हैं उन्हीं से काम करो, बेहतर साधन रास्ते में मिलते जाएँगे।",
			"pl":    "Nie czekaj; czas nigdy nie będzie „idealny”. Zacznij tam, gdzie stoisz, pracuj narzędziami, które masz pod ręką — lepsze znajdą się po drodze.",
			"tr":    "Bekleme; zaman asla 'tam uygun' olmayacak. Durduğun yerden başla, elindeki araçlarla çalış; daha iyileri yol boyunca bulunacaktır.",
			"uk":    "Не чекай; час ніколи не буде «ідеальним». Починай там, де стоїш, працюй тими інструментами, які маєш, — кращі знайдуться дорогою.",
			"sv":    "Vänta inte; tiden blir aldrig ”helt rätt”. Börja där du står, arbeta med de verktyg du har till hands, så hittar du bättre verktyg längs vägen.",
			"nl":    "Wacht niet; het moment zal nooit 'precies goed' zijn. Begin waar je staat, werk met de middelen die je hebt, en betere middelen vind je onderweg.",
			"nb":    "Ikke vent; tidspunktet blir aldri «helt riktig». Begynn der du står, bruk de verktøyene du har for hånden, så finner du bedre verktøy underveis.",
			"da":    "Vent ikke; tidspunktet bliver aldrig »helt rigtigt«. Begynd, hvor du står, arbejd med de redskaber, du har ved hånden, og bedre redskaber vil dukke op undervejs.",
			"fi":    "Älä odota; aika ei koskaan ole 'juuri oikea'. Aloita siitä missä seisot, käytä niitä työkaluja joita sinulla on — parempia löytyy matkan varrella.",
		},
	},
	{
		ID:       "commitment-37",
		Author:   ptr("Johann Wolfgang von Goethe"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Thinking is easy, acting is difficult, and to put one's thoughts into commitment is the most difficult thing in the world.",
			"en-GB": "Thinking is easy, acting is difficult, and to put one's thoughts into commitment is the most difficult thing in the world.",
			"pt-PT": "Pensar é fácil, agir é difícil, e colocar os pensamentos em ação é a coisa mais difícil do mundo.",
			"pt-BR": "Pensar é fácil, agir é difícil, e colocar os pensamentos em ação é a coisa mais difícil do mundo.",
			"es":    "Pensar es fácil, actuar es difícil, y poner los pensamientos en acción es lo más difícil del mundo.",
			"fr":    "Penser est facile, agir est difficile, et mettre ses pensées en commitment est la chose la plus difficile au monde.",
			"de":    "Denken ist leicht, Handeln ist schwer, und seine Gedanken in Taten umzusetzen ist das Schwierigste auf der Welt.",
			"it":    "Pensare è facile, agire è difficile, e mettere in azione i propri pensieri è la cosa più difficile del mondo.",
			"ja":    "考えることはたやすく、行動することは難しい。そして思考を行動に移すことは、世界で最も難しいことである。",
			"zh":    "思考容易，行动困难，而把思想付诸行动是世界上最难的事。",
			"ko":    "생각하기는 쉽고 행동하기는 어렵다. 그리고 생각을 행동으로 옮기는 것은 세상에서 가장 어려운 일이다.",
			"hi":    "सोचना आसान है, करना कठिन है, और अपने विचारों को कर्म में बदलना दुनिया का सबसे कठिन काम है।",
			"pl":    "Myślenie jest łatwe, działanie jest trudne, a przekuwanie myśli w czyn to najtrudniejsza rzecz na świecie.",
			"tr":    "Düşünmek kolay, eylemek zordur; düşüncelerini eyleme dökmek ise dünyanın en zor işidir.",
			"uk":    "Думати легко, діяти важко, а втілити думки в дію — найважче у світі.",
			"sv":    "Att tänka är lätt, att handla är svårt, och att omsätta sina tankar i handling är det svåraste i världen.",
			"nl":    "Denken is makkelijk, handelen is moeilijk, en je gedachten omzetten in daden is het moeilijkste ter wereld.",
			"nb":    "Å tenke er lett, å handle er vanskelig, og å omsette tankene sine i handling er det vanskeligste i verden.",
			"da":    "At tænke er let, at handle er svært, og at omsætte sine tanker til handling er det sværeste i verden.",
			"fi":    "Ajatteleminen on helppoa, toimiminen vaikeaa, ja ajatusten muuttaminen teoiksi on maailman vaikein asia.",
		},
	},
	{
		ID:       "commitment-38",
		Author:   ptr("Zig Ziglar"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "You don't have to be great to start, but you have to start to be great.",
			"en-GB": "You don't have to be great to start, but you have to start to be great.",
			"pt-PT": "Não precisas de ser grande para começar, mas precisas de começar para ser grande.",
			"pt-BR": "Você não precisa ser grande para começar, mas precisa começar para ser grande.",
			"es":    "No hace falta ser grande para empezar, pero hay que empezar para ser grande.",
			"fr":    "Il n'est pas nécessaire d'être grand pour commencer, mais il faut commencer pour être grand.",
			"de":    "Du musst nicht großartig sein, um anzufangen, aber du musst anfangen, um großartig zu werden.",
			"it":    "Non devi essere grande per iniziare, ma devi iniziare per diventare grande.",
			"ja":    "始めるために偉大である必要はない。だが偉大になるためには始めなければならない。",
			"zh":    "你不必很出色才开始，但你必须开始才能变得出色。",
			"ko":    "시작하기 위해 위대할 필요는 없다. 그러나 위대해지려면 시작해야 한다.",
			"hi":    "शुरुआत करने के लिए महान होना ज़रूरी नहीं, लेकिन महान बनने के लिए शुरुआत करना ज़रूरी है।",
			"pl":    "Nie musisz być wielki, żeby zacząć, ale musisz zacząć, żeby być wielki.",
			"tr":    "Başlamak için harika olmak zorunda değilsin, ama harika olmak için başlamak zorundasın.",
			"uk":    "Не потрібно бути великим, щоб почати, але потрібно почати, щоб стати великим.",
			"sv":    "Du behöver inte vara stor för att börja, men du måste börja för att bli stor.",
			"nl":    "Je hoeft niet geweldig te zijn om te beginnen, maar je moet beginnen om geweldig te worden.",
			"nb":    "Du trenger ikke være stor for å begynne, men du må begynne for å bli stor.",
			"da":    "Du behøver ikke være stor for at begynde, men du må begynde for at blive stor.",
			"fi":    "Sinun ei tarvitse olla loistava aloittaaksesi, mutta sinun on aloitettava ollaksesi loistava.",
		},
	},
	{
		ID:       "commitment-39",
		Author:   ptr("Dale Carnegie"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "Inaction breeds doubt and fear. Commitment breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.",
			"en-GB": "Inaction breeds doubt and fear. Commitment breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.",
			"pt-PT": "A inação gera dúvida e medo. A ação gera confiança e coragem. Se queres vencer o medo, não fiques sentado em casa a pensar nele. Sai e ocupa-te.",
			"pt-BR": "A inação gera dúvida e medo. A ação gera confiança e coragem. Se você quer vencer o medo, não fique sentado em casa pensando nele. Saia e ocupe-se.",
			"es":    "La inacción engendra duda y miedo. La acción engendra confianza y coraje. Si quieres vencer el miedo, no te quedes en casa pensando en ello. Sal y ponte manos a la obra.",
			"fr":    "L'inaction engendre le doute et la peur. L'commitment engendre la confiance et le courage. Si vous voulez vaincre la peur, ne restez pas assis chez vous à y penser. Sortez et occupez-vous.",
			"de":    "Untätigkeit erzeugt Zweifel und Angst. Handeln erzeugt Selbstvertrauen und Mut. Wenn du die Angst besiegen willst, sitze nicht zu Hause und grüble darüber nach. Geh hinaus und werde aktiv.",
			"it":    "L'inazione genera dubbio e paura. L'azione genera fiducia e coraggio. Se vuoi vincere la paura, non startene a casa a pensarci. Esci e datti da fare.",
			"ja":    "行動しなければ疑いと恐れが生まれ、行動すれば自信と勇気が生まれる。恐怖を克服したければ、家で考え込むな。外に出て動き出せ。",
			"zh":    "不行动滋生疑虑和恐惧，行动孕育信心和勇气。想要战胜恐惧，就不要坐在家里空想，走出去，忙起来。",
			"ko":    "행동하지 않으면 의심과 두려움이 자라고, 행동하면 자신감과 용기가 자란다. 두려움을 이기고 싶다면 집에 앉아 생각만 하지 마라. 밖으로 나가 움직여라.",
			"hi":    "निष्क्रियता संदेह और भय पैदा करती है। कर्म आत्मविश्वास और साहस पैदा करता है। अगर डर को जीतना है, तो घर बैठकर उसके बारे में मत सोचो। बाहर निकलो और काम में जुट जाओ।",
			"pl":    "Bezczynność rodzi wątpliwości i strach. Działanie rodzi pewność siebie i odwagę. Jeśli chcesz pokonać strach, nie siedź w domu, rozmyślając o nim. Wyjdź i weź się do pracy.",
			"tr":    "Eylemsizlik şüphe ve korku doğurur. Eylem güven ve cesaret doğurur. Korkuyu yenmek istiyorsan evde oturup düşünme. Dışarı çık ve harekete geç.",
			"uk":    "Бездіяльність породжує сумніви і страх. Дія породжує впевненість і сміливість. Якщо хочеш подолати страх, не сиди вдома в роздумах — виходь і берися до справи.",
			"sv":    "Passivitet föder tvivel och rädsla. Handling föder självförtroende och mod. Vill du besegra rädslan, sitt inte hemma och grubbla. Gå ut och sätt igång.",
			"nl":    "Niets doen kweekt twijfel en angst. Actie kweekt vertrouwen en moed. Wil je angst overwinnen, blijf dan niet thuis zitten piekeren. Ga naar buiten en kom in actie.",
			"nb":    "Passivitet avler tvil og frykt. Handling avler selvtillit og mot. Vil du overvinne frykten, ikke sitt hjemme og gruble på den. Gå ut og sett i gang.",
			"da":    "Passivitet avler tvivl og frygt. Handling avler selvtillid og mod. Vil du besejre frygten, så sid ikke derhjemme og spekuler. Gå ud og kom i gang.",
			"fi":    "Toimettomuus synnyttää epäilystä ja pelkoa. Toiminta synnyttää itseluottamusta ja rohkeutta. Jos haluat voittaa pelon, älä istu kotona miettimässä sitä. Mene ulos ja ryhdy toimeen.",
		},
	},
	{
		ID:       "commitment-40",
		Author:   ptr("Muhammad Ali"),
		Category: "commitment",
		Translations: map[string]string{
			"en-US": "He who is not courageous enough to take risks will accomplish nothing in life.",
			"en-GB": "He who is not courageous enough to take risks will accomplish nothing in life.",
			"pt-PT": "Aquele que não é corajoso o suficiente para correr riscos não conseguirá nada na vida.",
			"pt-BR": "Aquele que não é corajoso o suficiente para correr riscos não conseguirá nada na vida.",
			"es":    "Quien no sea lo suficientemente valiente para correr riesgos no logrará nada en la vida.",
			"fr":    "Celui qui n'est pas assez courageux pour prendre des risques n'accomplira rien dans la vie.",
			"de":    "Wer nicht mutig genug ist, Risiken einzugehen, wird im Leben nichts erreichen.",
			"it":    "Chi non ha il coraggio di rischiare non otterrà nulla nella vita.",
			"ja":    "危険を冒す勇気のない者は、人生で何も成し遂げられない。",
			"zh":    "没有勇气冒险的人，一生将一事无成。",
			"ko":    "위험을 감수할 용기가 없는 사람은 인생에서 아무것도 이루지 못한다.",
			"hi":    "जिसमें जोखिम उठाने का साहस नहीं, वह जीवन में कुछ हासिल नहीं करेगा।",
			"pl":    "Kto nie ma odwagi podejmować ryzyka, ten niczego w życiu nie osiągnie.",
			"tr":    "Risk almaya cesareti olmayan, hayatta hiçbir şey başaramaz.",
			"uk":    "Хто не має сміливості ризикувати, той нічого не досягне в житті.",
			"sv":    "Den som inte är modig nog att ta risker kommer inte att uppnå något i livet.",
			"nl":    "Wie niet moedig genoeg is om risico's te nemen, zal niets bereiken in het leven.",
			"nb":    "Den som ikke er modig nok til å ta risiko, vil ikke oppnå noe i livet.",
			"da":    "Den, der ikke er modig nok til at løbe en risiko, opnår intet i livet.",
			"fi":    "Se, jolla ei ole rohkeutta ottaa riskejä, ei saavuta elämässä mitään.",
		},
	},
}
