package quote

var wisdomQuotes = []QuoteData{
	{
		ID:       "wisdom-1",
		Author:   ptr("Rumi"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
			"en-GB": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
			"pt-PT": "Ontem eu era inteligente, por isso queria mudar o mundo. Hoje sou sábio, por isso estou a mudar-me a mim próprio.",
			"pt-BR": "Ontem eu era inteligente, então queria mudar o mundo. Hoje sou sábio, então estou mudando a mim mesmo.",
			"es":    "Ayer era inteligente, así que quería cambiar el mundo. Hoy soy sabio, así que me estoy cambiando a mí mismo.",
			"fr":    "Hier, j'étais intelligent, alors je voulais changer le monde. Aujourd'hui, je suis sage, alors je me change moi-même.",
			"de":    "Gestern war ich klug, darum wollte ich die Welt verändern. Heute bin ich weise, darum verändere ich mich selbst.",
			"it":    "Ieri ero intelligente, così volevo cambiare il mondo. Oggi sono saggio, così sto cambiando me stesso.",
			"ja":    "昨日の私は賢く、世界を変えようとしていた。今日の私は知恵を得て、自分自身を変えようとしている。",
			"zh":    "昨天我很聪明，所以想改变世界。今天我有了智慧，所以正在改变自己。",
			"ko":    "어제의 나는 영리해서 세상을 바꾸려 했다. 오늘의 나는 지혜로워져 나 자신을 바꾸고 있다.",
			"hi":    "कल मैं चतुर था, इसलिए दुनिया बदलना चाहता था। आज मैं बुद्धिमान हूँ, इसलिए स्वयं को बदल रहा हूँ।",
			"pl":    "Wczoraj byłem sprytny, więc chciałem zmienić świat. Dziś jestem mądry, więc zmieniam siebie.",
			"tr":    "Dün zekiydim, dünyayı değiştirmek istiyordum. Bugün bilgeyim, kendimi değiştiriyorum.",
			"uk":    "Учора я був розумний і хотів змінити світ. Сьогодні я мудрий і змінюю себе.",
			"sv":    "I går var jag klok, så jag ville förändra världen. I dag är jag vis, så jag förändrar mig själv.",
			"nl":    "Gisteren was ik slim, dus wilde ik de wereld veranderen. Vandaag ben ik wijs, dus verander ik mezelf.",
			"nb":    "I går var jeg klok, så jeg ville forandre verden. I dag er jeg vis, så jeg forandrer meg selv.",
			"da":    "I går var jeg klog, så jeg ville forandre verden. I dag er jeg vis, så jeg forandrer mig selv.",
			"fi":    "Eilen olin älykäs, joten halusin muuttaa maailmaa. Tänään olen viisas, joten muutan itseäni.",
		},
	},
	{
		ID:       "wisdom-2",
		Author:   ptr("Warren Buffett"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The best investment you can make is in yourself.",
			"en-GB": "The best investment you can make is in yourself.",
			"pt-PT": "O melhor investimento que podes fazer é em ti próprio.",
			"pt-BR": "O melhor investimento que você pode fazer é em você mesmo.",
			"es":    "La mejor inversión que puedes hacer es en ti mismo.",
			"fr":    "Le meilleur investissement que vous puissiez faire est en vous-même.",
			"de":    "Die beste Investition, die du machen kannst, ist die in dich selbst.",
			"it":    "Il miglior investimento che puoi fare è su te stesso.",
			"ja":    "できる最大の投資は、自分自身への投資である。",
			"zh":    "你能做的最好的投资，就是投资自己。",
			"ko":    "당신이 할 수 있는 최고의 투자는 자기 자신에 대한 투자다.",
			"hi":    "सबसे अच्छा निवेश जो आप कर सकते हैं, वह है ख़ुद में निवेश।",
			"pl":    "Najlepszą inwestycją, jaką możesz poczynić, jest inwestycja w siebie.",
			"tr":    "Yapabileceğin en iyi yatırım kendine yaptığındır.",
			"uk":    "Найкраща інвестиція, яку ти можеш зробити, — у самого себе.",
			"sv":    "Den bästa investering du kan göra är i dig själv.",
			"nl":    "De beste investering die je kunt doen, is in jezelf.",
			"nb":    "Den beste investeringen du kan gjøre, er i deg selv.",
			"da":    "Den bedste investering, du kan foretage, er i dig selv.",
			"fi":    "Paras sijoitus, jonka voit tehdä, on sijoitus itseesi.",
		},
	},
	{
		ID:       "wisdom-3",
		Author:   ptr("Chinese Proverb"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The best time to plant a tree was 20 years ago. The second best time is now.",
			"en-GB": "The best time to plant a tree was 20 years ago. The second best time is now.",
			"pt-PT": "A melhor altura para plantar uma árvore foi há 20 anos. A segunda melhor altura é agora.",
			"pt-BR": "A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor é agora.",
			"es":    "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.",
			"fr":    "Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.",
			"de":    "Die beste Zeit, einen Baum zu pflanzen, war vor 20 Jahren. Die zweitbeste Zeit ist jetzt.",
			"it":    "Il momento migliore per piantare un albero era 20 anni fa. Il secondo momento migliore è adesso.",
			"ja":    "木を植える最良の時期は20年前だった。次に良い時期は今である。",
			"zh":    "种一棵树最好的时间是二十年前，其次是现在。",
			"ko":    "나무를 심기에 가장 좋았던 때는 20년 전이었다. 두 번째로 좋은 때는 바로 지금이다.",
			"hi":    "पेड़ लगाने का सबसे अच्छा समय 20 साल पहले था। दूसरा सबसे अच्छा समय अभी है।",
			"pl":    "Najlepszy czas na zasadzenie drzewa był 20 lat temu. Drugi najlepszy czas jest teraz.",
			"tr":    "Bir ağaç dikmek için en iyi zaman 20 yıl önceydi. İkinci en iyi zaman şimdi.",
			"uk":    "Найкращий час посадити дерево був 20 років тому. Другий найкращий час — зараз.",
			"sv":    "Den bästa tiden att plantera ett träd var för 20 år sedan. Den näst bästa tiden är nu.",
			"nl":    "De beste tijd om een boom te planten was 20 jaar geleden. De op één na beste tijd is nu.",
			"nb":    "Den beste tiden å plante et tre på var for 20 år siden. Den nest beste tiden er nå.",
			"da":    "Det bedste tidspunkt at plante et træ på var for 20 år siden. Det næstbedste tidspunkt er nu.",
			"fi":    "Paras aika istuttaa puu oli 20 vuotta sitten. Toiseksi paras aika on nyt.",
		},
	},
	{
		ID:       "wisdom-4",
		Author:   ptr("Socrates"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "An unexamined life is not worth living.",
			"en-GB": "An unexamined life is not worth living.",
			"pt-PT": "Uma vida não examinada não vale a pena ser vivida.",
			"pt-BR": "Uma vida não examinada não vale a pena ser vivida.",
			"es":    "Una vida sin examen no merece ser vivida.",
			"fr":    "Une vie sans examen ne vaut pas la peine d'être vécue.",
			"de":    "Ein ungeprüftes Leben ist nicht lebenswert.",
			"it":    "Una vita senza esame non è degna di essere vissuta.",
			"ja":    "吟味されない人生は、生きるに値しない。",
			"zh":    "未经审视的人生不值得过。",
			"ko":    "성찰하지 않는 삶은 살 가치가 없다.",
			"hi":    "बिना परखा हुआ जीवन जीने योग्य नहीं है।",
			"pl":    "Życie niepoddane refleksji nie jest warte życia.",
			"tr":    "Sorgulanmamış bir hayat yaşamaya değmez.",
			"uk":    "Життя без самопізнання не варте того, щоб його жити.",
			"sv":    "Ett oprövat liv är inte värt att leva.",
			"nl":    "Een niet-onderzocht leven is het niet waard geleefd te worden.",
			"nb":    "Et liv uten selvransakelse er ikke verdt å leve.",
			"da":    "Et uransaget liv er ikke værd at leve.",
			"fi":    "Tutkimaton elämä ei ole elämisen arvoinen.",
		},
	},
	{
		ID:       "wisdom-5",
		Author:   ptr("Dalai Lama"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Happiness is not something readymade. It comes from your own commitments.",
			"en-GB": "Happiness is not something readymade. It comes from your own commitments.",
			"pt-PT": "A felicidade não é algo que já venha feito. É o resultado das tuas próprias ações.",
			"pt-BR": "A felicidade não é algo pronto. Ela vem de suas próprias ações.",
			"es":    "La felicidad no es algo ya hecho. Proviene de tus propias acciones.",
			"fr":    "Le bonheur n'est pas quelque chose de tout fait. Il vient de vos propres commitments.",
			"de":    "Glück ist nichts Fertiges. Es entsteht aus deinen eigenen Taten.",
			"it":    "La felicità non è qualcosa di preconfezionato. Nasce dalle tue azioni.",
			"ja":    "幸福とは出来合いのものではない。あなた自身の行いから生まれるものだ。",
			"zh":    "幸福不是现成的，它来自你自己的行动。",
			"ko":    "행복은 만들어져 있는 것이 아니다. 당신 자신의 행동에서 나온다.",
			"hi":    "ख़ुशी कोई बनी-बनाई चीज़ नहीं है। यह आपके अपने कर्मों से आती है।",
			"pl":    "Szczęście nie jest czymś gotowym. Rodzi się z twoich własnych działań.",
			"tr":    "Mutluluk hazır bir şey değildir. Kendi eylemlerinden doğar.",
			"uk":    "Щастя не буває готовим. Воно народжується з твоїх власних дій.",
			"sv":    "Lycka är inget färdigt. Den kommer ur dina egna handlingar.",
			"nl":    "Geluk is niet iets kant-en-klaars. Het komt voort uit je eigen daden.",
			"nb":    "Lykke er ikke noe ferdiglaget. Den kommer fra dine egne handlinger.",
			"da":    "Lykke er ikke noget færdiglavet. Den kommer af dine egne handlinger.",
			"fi":    "Onnellisuus ei ole valmiiksi tehtyä. Se syntyy omista teoistasi.",
		},
	},
	{
		ID:       "wisdom-6",
		Author:   ptr("John Muir"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The power of imagination makes us infinite.",
			"en-GB": "The power of imagination makes us infinite.",
			"pt-PT": "O poder da imaginação torna-nos infinitos.",
			"pt-BR": "O poder da imaginação nos torna infinitos.",
			"es":    "El poder de la imaginación nos hace infinitos.",
			"fr":    "Le pouvoir de l'imagination nous rend infinis.",
			"de":    "Die Kraft der Vorstellung macht uns unendlich.",
			"it":    "Il potere dell'immaginazione ci rende infiniti.",
			"ja":    "想像力は私たちを無限にする。",
			"zh":    "想象的力量使我们无限。",
			"ko":    "상상의 힘은 우리를 무한하게 만든다.",
			"hi":    "कल्पना की शक्ति हमें अनंत बनाती है।",
			"pl":    "Siła wyobraźni czyni nas nieskończonymi.",
			"tr":    "Hayal gücünün kudreti bizi sonsuz kılar.",
			"uk":    "Сила уяви робить нас безмежними.",
			"sv":    "Fantasins kraft gör oss oändliga.",
			"nl":    "De kracht van de verbeelding maakt ons oneindig.",
			"nb":    "Fantasiens kraft gjør oss uendelige.",
			"da":    "Fantasiens kraft gør os uendelige.",
			"fi":    "Mielikuvituksen voima tekee meistä äärettömiä.",
		},
	},
	{
		ID:       "wisdom-7",
		Author:   ptr("Lao Tzu"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
			"en-GB": "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
			"pt-PT": "Conhecer os outros é inteligência; conhecer-te a ti próprio é verdadeira sabedoria. Dominar os outros é força; dominar-te a ti próprio é verdadeiro poder.",
			"pt-BR": "Conhecer os outros é inteligência; conhecer a si mesmo é verdadeira sabedoria. Dominar os outros é força; dominar a si mesmo é verdadeiro poder.",
			"es":    "Conocer a los demás es inteligencia; conocerse a sí mismo es verdadera sabiduría. Dominar a otros es fuerza; dominarse a sí mismo es verdadero poder.",
			"fr":    "Connaître les autres est intelligent ; se connaître soi-même est la vraie sagesse. Maîtriser les autres est une force ; se maîtriser soi-même est le vrai pouvoir.",
			"de":    "Andere zu kennen ist Klugheit; sich selbst zu kennen ist wahre Weisheit. Andere zu beherrschen ist Stärke; sich selbst zu beherrschen ist wahre Macht.",
			"it":    "Conoscere gli altri è intelligenza; conoscere se stessi è vera saggezza. Dominare gli altri è forza; dominare se stessi è vero potere.",
			"ja":    "他人を知る者は賢く、自分を知る者こそ真に明知である。他人に勝つ者は力があり、自分に勝つ者こそ真に強い。",
			"zh":    "知人者智，自知者明。胜人者有力，自胜者强。",
			"ko":    "남을 아는 것은 지혜요, 자신을 아는 것이 참된 밝음이다. 남을 이기는 것은 힘이요, 자신을 이기는 것이 참된 강함이다.",
			"hi":    "दूसरों को जानना बुद्धिमत्ता है; स्वयं को जानना सच्चा ज्ञान है। दूसरों पर विजय शक्ति है; स्वयं पर विजय सच्चा सामर्थ्य है।",
			"pl":    "Znać innych to inteligencja; znać siebie to prawdziwa mądrość. Panować nad innymi to siła; panować nad sobą to prawdziwa potęga.",
			"tr":    "Başkalarını bilmek zekâdır; kendini bilmek gerçek bilgeliktir. Başkalarına hükmetmek kuvvettir; kendine hükmetmek gerçek kudrettir.",
			"uk":    "Знати інших — розум; знати себе — справжня мудрість. Панувати над іншими — сила; панувати над собою — справжня могутність.",
			"sv":    "Att känna andra är intelligens; att känna sig själv är sann visdom. Att bemästra andra är styrka; att bemästra sig själv är sann makt.",
			"nl":    "Anderen kennen is intelligentie; jezelf kennen is ware wijsheid. Anderen beheersen is kracht; jezelf beheersen is ware macht.",
			"nb":    "Å kjenne andre er intelligens; å kjenne seg selv er sann visdom. Å mestre andre er styrke; å mestre seg selv er sann makt.",
			"da":    "At kende andre er intelligens; at kende sig selv er sand visdom. At mestre andre er styrke; at mestre sig selv er sand magt.",
			"fi":    "Toisten tunteminen on älykkyyttä; itsensä tunteminen on todellista viisautta. Toisten hallitseminen on voimaa; itsensä hallitseminen on todellista valtaa.",
		},
	},
	{
		ID:       "wisdom-8",
		Author:   ptr("Albert Einstein"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Imagination is more important than knowledge.",
			"en-GB": "Imagination is more important than knowledge.",
			"pt-PT": "A imaginação é mais importante do que o conhecimento.",
			"pt-BR": "A imaginação é mais importante que o conhecimento.",
			"es":    "La imaginación es más importante que el conocimiento.",
			"fr":    "L'imagination est plus importante que la connaissance.",
			"de":    "Fantasie ist wichtiger als Wissen.",
			"it":    "L'immaginazione è più importante della conoscenza.",
			"ja":    "想像力は知識よりも重要である。",
			"zh":    "想象力比知识更重要。",
			"ko":    "상상력은 지식보다 중요하다.",
			"hi":    "कल्पना ज्ञान से अधिक महत्वपूर्ण है।",
			"pl":    "Wyobraźnia jest ważniejsza od wiedzy.",
			"tr":    "Hayal gücü bilgiden daha önemlidir.",
			"uk":    "Уява важливіша за знання.",
			"sv":    "Fantasi är viktigare än kunskap.",
			"nl":    "Verbeelding is belangrijker dan kennis.",
			"nb":    "Fantasi er viktigere enn kunnskap.",
			"da":    "Fantasi er vigtigere end viden.",
			"fi":    "Mielikuvitus on tärkeämpää kuin tieto.",
		},
	},
	{
		ID:       "wisdom-9",
		Author:   ptr("Benjamin Franklin"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "An investment in knowledge pays the best interest.",
			"en-GB": "An investment in knowledge pays the best interest.",
			"pt-PT": "Um investimento em conhecimento paga os melhores juros.",
			"pt-BR": "Um investimento em conhecimento paga os melhores juros.",
			"es":    "Una inversión en conocimiento paga el mejor interés.",
			"fr":    "Un investissement dans la connaissance rapporte les meilleurs intérêts.",
			"de":    "Eine Investition in Wissen bringt die besten Zinsen.",
			"it":    "Un investimento in conoscenza paga i migliori interessi.",
			"ja":    "知識への投資は、最も高い利息を生む。",
			"zh":    "对知识的投资收益最佳。",
			"ko":    "지식에 대한 투자는 최고의 이자를 낳는다.",
			"hi":    "ज्ञान में किया गया निवेश सबसे अच्छा ब्याज देता है।",
			"pl":    "Inwestycja w wiedzę przynosi najlepsze odsetki.",
			"tr":    "Bilgiye yapılan yatırım en iyi faizi öder.",
			"uk":    "Інвестиція у знання приносить найкращі відсотки.",
			"sv":    "En investering i kunskap ger den bästa räntan.",
			"nl":    "Een investering in kennis levert de beste rente op.",
			"nb":    "En investering i kunnskap gir den beste renten.",
			"da":    "En investering i viden giver den bedste rente.",
			"fi":    "Sijoitus tietoon maksaa parhaan koron.",
		},
	},
	{
		ID:       "wisdom-10",
		Author:   ptr("Epictetus"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.",
			"en-GB": "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.",
			"pt-PT": "Sábio é o homem que não se lamenta pelas coisas que não tem, mas se alegra por aquelas que possui.",
			"pt-BR": "Sábio é o homem que não se lamenta pelas coisas que não tem, mas se alegra por aquelas que possui.",
			"es":    "Es un hombre sabio aquel que no se aflige por las cosas que no tiene, sino que se alegra por las que tiene.",
			"fr":    "Savant est l'homme qui ne s'afflige pas de ce qu'il n'a pas, mais se réjouit de ce qu'il a.",
			"de":    "Weise ist, wer nicht trauert um das, was er nicht hat, sondern sich freut über das, was er hat.",
			"it":    "È saggio colui che non si affligge per le cose che non ha, ma gioisce di quelle che ha.",
			"ja":    "持たないものを嘆かず、持っているものを喜ぶ者こそ賢者である。",
			"zh":    "智者不为自己没有的东西悲伤，而为自己拥有的东西欢喜。",
			"ko":    "갖지 못한 것을 슬퍼하지 않고 가진 것을 기뻐하는 사람이 지혜로운 사람이다.",
			"hi":    "बुद्धिमान वह है जो उन चीज़ों का शोक नहीं करता जो उसके पास नहीं हैं, बल्कि उन चीज़ों में आनंदित होता है जो उसके पास हैं।",
			"pl":    "Mądry jest ten, kto nie smuci się z powodu tego, czego nie ma, lecz cieszy się tym, co ma.",
			"tr":    "Bilge insan, sahip olmadıklarına üzülmeyen, sahip olduklarına sevinendir.",
			"uk":    "Мудрий той, хто не сумує за тим, чого не має, а радіє тому, що має.",
			"sv":    "Vis är den som inte sörjer över det han inte har, utan gläds över det han har.",
			"nl":    "Wijs is hij die niet treurt om wat hij niet heeft, maar zich verheugt over wat hij wel heeft.",
			"nb":    "Vis er den som ikke sørger over det han ikke har, men gleder seg over det han har.",
			"da":    "Vis er den, der ikke sørger over det, han ikke har, men glæder sig over det, han har.",
			"fi":    "Viisas on se, joka ei sure sitä mitä hänellä ei ole, vaan iloitsee siitä mitä hänellä on.",
		},
	},
	{
		ID:       "wisdom-11",
		Author:   ptr("Marcus Aurelius"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
			"en-GB": "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
			"pt-PT": "Muito pouco é necessário para se ter uma vida feliz; está tudo dentro de ti, na tua forma de pensar.",
			"pt-BR": "Muito pouco é necessário para ter uma vida feliz; está tudo dentro de você, no seu modo de pensar.",
			"es":    "Se necesita muy poco para tener una vida feliz; todo está dentro de ti, en tu forma de pensar.",
			"fr":    "Il faut très peu de chose pour mener une vie heureuse ; tout est en vous-même, dans votre façon de penser.",
			"de":    "Es braucht sehr wenig für ein glückliches Leben; alles liegt in dir selbst, in deiner Art zu denken.",
			"it":    "Occorre molto poco per una vita felice; è tutto dentro di te, nel tuo modo di pensare.",
			"ja":    "幸せな人生に必要なものはごくわずかである。すべてはあなたの内側、あなたの考え方の中にある。",
			"zh":    "幸福的生活所需甚少；一切都在你自己心中，在你的思维方式里。",
			"ko":    "행복한 삶에 필요한 것은 아주 적다. 모든 것은 당신 안에, 당신의 생각하는 방식에 있다.",
			"hi":    "सुखी जीवन के लिए बहुत कम चाहिए; सब कुछ आपके भीतर है, आपके सोचने के तरीक़े में।",
			"pl":    "Do szczęśliwego życia potrzeba bardzo niewiele; wszystko jest w tobie, w twoim sposobie myślenia.",
			"tr":    "Mutlu bir yaşam için çok az şey gerekir; hepsi senin içindedir, düşünme biçimindedir.",
			"uk":    "Для щасливого життя потрібно дуже мало; усе — всередині тебе, у твоєму способі мислення.",
			"sv":    "Det behövs väldigt lite för ett lyckligt liv; allt finns inom dig själv, i ditt sätt att tänka.",
			"nl":    "Er is maar heel weinig nodig voor een gelukkig leven; het zit allemaal in jezelf, in je manier van denken.",
			"nb":    "Det skal svært lite til for et lykkelig liv; alt ligger i deg selv, i måten du tenker på.",
			"da":    "Der skal meget lidt til for et lykkeligt liv; det hele ligger i dig selv, i din måde at tænke på.",
			"fi":    "Onnelliseen elämään tarvitaan hyvin vähän; kaikki on sinussa itsessäsi, ajattelutavassasi.",
		},
	},
	{
		ID:       "wisdom-12",
		Author:   ptr("Voltaire"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Common sense is not so common.",
			"en-GB": "Common sense is not so common.",
			"pt-PT": "O senso comum não é assim tão comum.",
			"pt-BR": "O senso comum não é tão comum.",
			"es":    "El sentido común no es tan común.",
			"fr":    "Le sens commun n'est pas si commun.",
			"de":    "Gesunder Menschenverstand ist gar nicht so verbreitet.",
			"it":    "Il buon senso non è poi così comune.",
			"ja":    "常識というものは、それほど一般的ではない。",
			"zh":    "常识并不寻常。",
			"ko":    "상식은 그리 흔하지 않다.",
			"hi":    "सामान्य बुद्धि इतनी सामान्य नहीं है।",
			"pl":    "Zdrowy rozsądek nie jest wcale taki powszechny.",
			"tr":    "Sağduyu o kadar da yaygın değildir.",
			"uk":    "Здоровий глузд не такий уже й поширений.",
			"sv":    "Sunt förnuft är inte så vanligt.",
			"nl":    "Gezond verstand is niet zo gewoon.",
			"nb":    "Sunn fornuft er ikke så vanlig.",
			"da":    "Sund fornuft er ikke så almindelig.",
			"fi":    "Terve järki ei ole kovin yleistä.",
		},
	},
	{
		ID:       "wisdom-13",
		Author:   ptr("Oscar Wilde"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Be yourself; everyone else is already taken.",
			"en-GB": "Be yourself; everyone else is already taken.",
			"pt-PT": "Sê tu próprio; todos os outros já estão ocupados.",
			"pt-BR": "Seja você mesmo; todos os outros já existem.",
			"es":    "Sé tú mismo; todos los demás ya están ocupados.",
			"fr":    "Soyez vous-même ; tous les autres sont déjà pris.",
			"de":    "Sei du selbst; alle anderen sind bereits vergeben.",
			"it":    "Sii te stesso; tutti gli altri sono già presi.",
			"ja":    "自分らしくあれ。他の誰かはもう存在しているのだから。",
			"zh":    "做你自己，因为别人都有人做了。",
			"ko":    "자기 자신이 되어라. 다른 사람은 이미 다 있으니까.",
			"hi":    "स्वयं बनो; बाक़ी सब तो पहले से ही कोई और है।",
			"pl":    "Bądź sobą; wszyscy inni są już zajęci.",
			"tr":    "Kendin ol; diğer herkes zaten alınmış.",
			"uk":    "Будь собою; усі інші вже зайняті.",
			"sv":    "Var dig själv; alla andra är redan upptagna.",
			"nl":    "Wees jezelf; alle anderen zijn al bezet.",
			"nb":    "Vær deg selv; alle andre er allerede opptatt.",
			"da":    "Vær dig selv; alle andre er allerede optaget.",
			"fi":    "Ole oma itsesi; kaikki muut ovat jo varattuja.",
		},
	},
	{
		ID:       "wisdom-14",
		Author:   ptr("Ralph Waldo Emerson"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
			"en-GB": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
			"pt-PT": "Seres tu próprio num mundo que está constantemente a tentar fazer de ti outra coisa é a maior realização.",
			"pt-BR": "Ser você mesmo em um mundo que está constantemente tentando fazer de você outra coisa é a maior realização.",
			"es":    "Ser uno mismo en un mundo que constantemente intenta convertirte en otra cosa es el mayor logro.",
			"fr":    "Être soi-même dans un monde qui essaie constamment de faire de vous quelqu'un d'autre est le plus grand accomplissement.",
			"de":    "In einer Welt, die dich ständig zu etwas anderem machen will, du selbst zu sein, ist die größte Leistung.",
			"it":    "Essere se stessi in un mondo che cerca costantemente di renderti qualcos'altro è il più grande dei successi.",
			"ja":    "絶えずあなたを別の何かに変えようとする世界で自分自身であり続けることは、最大の偉業である。",
			"zh":    "在一个不断想把你变成别人的世界里做自己，是最伟大的成就。",
			"ko":    "끊임없이 당신을 다른 무언가로 만들려는 세상에서 자기 자신으로 사는 것이야말로 가장 위대한 성취다.",
			"hi":    "ऐसी दुनिया में स्वयं बने रहना जो आपको लगातार कुछ और बनाने की कोशिश करती है, सबसे बड़ी उपलब्धि है।",
			"pl":    "Być sobą w świecie, który nieustannie próbuje uczynić cię kimś innym, to największe osiągnięcie.",
			"tr":    "Seni sürekli başka bir şeye dönüştürmeye çalışan bir dünyada kendin olmak, en büyük başarıdır.",
			"uk":    "Бути собою у світі, який постійно намагається зробити тебе кимось іншим, — найбільше досягнення.",
			"sv":    "Att vara sig själv i en värld som ständigt försöker göra dig till något annat är den största bedriften.",
			"nl":    "Jezelf zijn in een wereld die voortdurend probeert iets anders van je te maken, is de grootste prestatie.",
			"nb":    "Å være seg selv i en verden som stadig prøver å gjøre deg til noe annet, er den største bragden.",
			"da":    "At være sig selv i en verden, der konstant forsøger at gøre dig til noget andet, er den største bedrift.",
			"fi":    "Olla oma itsensä maailmassa, joka jatkuvasti yrittää tehdä sinusta jotain muuta, on suurin saavutus.",
		},
	},
	{
		ID:       "wisdom-15",
		Author:   ptr("Henry David Thoreau"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Go confidently in the direction of your dreams. Live the life you have imagined.",
			"en-GB": "Go confidently in the direction of your dreams. Live the life you have imagined.",
			"pt-PT": "Vai confiante na direção dos teus sonhos. Vive a vida que imaginaste.",
			"pt-BR": "Vá com confiança na direção dos seus sonhos. Viva a vida que você imaginou.",
			"es":    "Ve con confianza en la dirección de tus sueños. Vive la vida que has imaginado.",
			"fr":    "Allez avec confiance dans la direction de vos rêves. Vivez la vie que vous avez imaginée.",
			"de":    "Geh zuversichtlich in die Richtung deiner Träume. Lebe das Leben, das du dir vorgestellt hast.",
			"it":    "Vai con fiducia nella direzione dei tuoi sogni. Vivi la vita che hai immaginato.",
			"ja":    "自信を持って夢の方向へ進め。思い描いた人生を生きよ。",
			"zh":    "满怀信心地朝着梦想的方向前进，过你想象中的生活。",
			"ko":    "확신을 갖고 꿈이 향하는 방향으로 나아가라. 상상해 온 삶을 살아라.",
			"hi":    "अपने सपनों की दिशा में आत्मविश्वास से बढ़ो। वह जीवन जियो जिसकी तुमने कल्पना की है।",
			"pl":    "Idź pewnie w kierunku swoich marzeń. Żyj życiem, które sobie wyobraziłeś.",
			"tr":    "Hayallerinin yönünde güvenle ilerle. Hayalini kurduğun hayatı yaşa.",
			"uk":    "Іди впевнено в напрямку своїх мрій. Живи життям, яке собі уявив.",
			"sv":    "Gå tryggt i riktning mot dina drömmar. Lev det liv du har föreställt dig.",
			"nl":    "Ga vol vertrouwen in de richting van je dromen. Leef het leven dat je je hebt voorgesteld.",
			"nb":    "Gå trygt i retning av drømmene dine. Lev det livet du har forestilt deg.",
			"da":    "Gå trygt i retning af dine drømme. Lev det liv, du har forestillet dig.",
			"fi":    "Kulje luottavaisesti unelmiesi suuntaan. Elä sitä elämää, jonka olet kuvitellut.",
		},
	},
	{
		ID:       "wisdom-16",
		Author:   ptr("Aristotle"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Knowing yourself is the beginning of all wisdom.",
			"en-GB": "Knowing yourself is the beginning of all wisdom.",
			"pt-PT": "Conhecer-te a ti próprio é o princípio de toda a sabedoria.",
			"pt-BR": "Conhecer a si mesmo é o começo de toda sabedoria.",
			"es":    "Conocerse a uno mismo es el principio de toda sabiduría.",
			"fr":    "Se connaître soi-même est le début de toute sagesse.",
			"de":    "Sich selbst zu kennen ist der Anfang aller Weisheit.",
			"it":    "Conoscere se stessi è l'inizio di ogni saggezza.",
			"ja":    "自分自身を知ることは、あらゆる知恵の始まりである。",
			"zh":    "认识自己是一切智慧的开端。",
			"ko":    "자신을 아는 것이 모든 지혜의 시작이다.",
			"hi":    "स्वयं को जानना समस्त ज्ञान का आरंभ है।",
			"pl":    "Poznanie samego siebie jest początkiem wszelkiej mądrości.",
			"tr":    "Kendini bilmek tüm bilgeliğin başlangıcıdır.",
			"uk":    "Пізнання себе — початок усієї мудрості.",
			"sv":    "Att känna sig själv är början på all visdom.",
			"nl":    "Jezelf kennen is het begin van alle wijsheid.",
			"nb":    "Å kjenne seg selv er begynnelsen på all visdom.",
			"da":    "At kende sig selv er begyndelsen på al visdom.",
			"fi":    "Itsensä tunteminen on kaiken viisauden alku.",
		},
	},
	{
		ID:       "wisdom-17",
		Author:   ptr("Plato"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The first and greatest victory is to conquer yourself.",
			"en-GB": "The first and greatest victory is to conquer yourself.",
			"pt-PT": "A primeira e maior vitória é conquistares-te a ti próprio.",
			"pt-BR": "A primeira e maior vitória é conquistar a si mesmo.",
			"es":    "La primera y más grande victoria es conquistarte a ti mismo.",
			"fr":    "La première et la plus grande victoire est de se conquérir soi-même.",
			"de":    "Der erste und größte Sieg ist der Sieg über sich selbst.",
			"it":    "La prima e più grande vittoria è conquistare se stessi.",
			"ja":    "最初にして最大の勝利は、自分自身に打ち勝つことである。",
			"zh":    "第一个也是最伟大的胜利，是战胜自己。",
			"ko":    "첫 번째이자 가장 위대한 승리는 자기 자신을 이기는 것이다.",
			"hi":    "पहली और सबसे बड़ी विजय स्वयं पर विजय है।",
			"pl":    "Pierwszym i największym zwycięstwem jest zwyciężyć samego siebie.",
			"tr":    "İlk ve en büyük zafer, insanın kendini fethetmesidir.",
			"uk":    "Перша і найбільша перемога — перемога над собою.",
			"sv":    "Den första och största segern är att besegra sig själv.",
			"nl":    "De eerste en grootste overwinning is jezelf overwinnen.",
			"nb":    "Den første og største seieren er å beseire seg selv.",
			"da":    "Den første og største sejr er at besejre sig selv.",
			"fi":    "Ensimmäinen ja suurin voitto on itsensä voittaminen.",
		},
	},
	{
		ID:       "wisdom-18",
		Author:   ptr("Seneca"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "As long as you live, keep learning how to live.",
			"en-GB": "As long as you live, keep learning how to live.",
			"pt-PT": "Enquanto viveres, continua a aprender a viver.",
			"pt-BR": "Enquanto você viver, continue aprendendo como viver.",
			"es":    "Mientras vivas, sigue aprendiendo a vivir.",
			"fr":    "Tant que vous vivez, continuez d'apprendre comment vivre.",
			"de":    "Solange du lebst, lerne weiter, wie man lebt.",
			"it":    "Finché vivi, continua a imparare a vivere.",
			"ja":    "生きている限り、生き方を学び続けよ。",
			"zh":    "只要你活着，就要不断学习如何生活。",
			"ko":    "살아 있는 한, 사는 법을 계속 배워라.",
			"hi":    "जब तक जियो, जीना सीखते रहो।",
			"pl":    "Dopóki żyjesz, ucz się, jak żyć.",
			"tr":    "Yaşadığın sürece, yaşamayı öğrenmeye devam et.",
			"uk":    "Поки живеш — учися жити.",
			"sv":    "Så länge du lever, fortsätt lära dig att leva.",
			"nl":    "Zolang je leeft, blijf leren hoe te leven.",
			"nb":    "Så lenge du lever, fortsett å lære hvordan du skal leve.",
			"da":    "Så længe du lever, så bliv ved med at lære at leve.",
			"fi":    "Niin kauan kuin elät, opettele elämään.",
		},
	},
	{
		ID:       "wisdom-19",
		Author:   ptr("Rumi"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
			"en-GB": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
			"pt-PT": "Ontem eu era inteligente, por isso queria mudar o mundo. Hoje sou sábio, por isso estou a mudar-me a mim próprio.",
			"pt-BR": "Ontem eu era inteligente, então queria mudar o mundo. Hoje sou sábio, então estou mudando a mim mesmo.",
			"es":    "Ayer era inteligente, así que quería cambiar el mundo. Hoy soy sabio, así que me estoy cambiando a mí mismo.",
			"fr":    "Hier j'étais intelligent, alors je voulais changer le monde. Aujourd'hui je suis sage, alors je me change moi-même.",
			"de":    "Gestern war ich klug, darum wollte ich die Welt verändern. Heute bin ich weise, darum verändere ich mich selbst.",
			"it":    "Ieri ero intelligente, così volevo cambiare il mondo. Oggi sono saggio, così sto cambiando me stesso.",
			"ja":    "昨日の私は賢く、世界を変えようとしていた。今日の私は知恵を得て、自分自身を変えようとしている。",
			"zh":    "昨天我很聪明，所以想改变世界。今天我有了智慧，所以正在改变自己。",
			"ko":    "어제의 나는 영리해서 세상을 바꾸려 했다. 오늘의 나는 지혜로워져 나 자신을 바꾸고 있다.",
			"hi":    "कल मैं चतुर था, इसलिए दुनिया बदलना चाहता था। आज मैं बुद्धिमान हूँ, इसलिए स्वयं को बदल रहा हूँ।",
			"pl":    "Wczoraj byłem sprytny, więc chciałem zmienić świat. Dziś jestem mądry, więc zmieniam siebie.",
			"tr":    "Dün zekiydim, dünyayı değiştirmek istiyordum. Bugün bilgeyim, kendimi değiştiriyorum.",
			"uk":    "Учора я був розумний і хотів змінити світ. Сьогодні я мудрий і змінюю себе.",
			"sv":    "I går var jag klok, så jag ville förändra världen. I dag är jag vis, så jag förändrar mig själv.",
			"nl":    "Gisteren was ik slim, dus wilde ik de wereld veranderen. Vandaag ben ik wijs, dus verander ik mezelf.",
			"nb":    "I går var jeg klok, så jeg ville forandre verden. I dag er jeg vis, så jeg forandrer meg selv.",
			"da":    "I går var jeg klog, så jeg ville forandre verden. I dag er jeg vis, så jeg forandrer mig selv.",
			"fi":    "Eilen olin älykäs, joten halusin muuttaa maailmaa. Tänään olen viisas, joten muutan itseäni.",
		},
	},
	{
		ID:       "wisdom-20",
		Author:   ptr("Mark Twain"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Kindness is the language which the deaf can hear and the blind can see.",
			"en-GB": "Kindness is the language which the deaf can hear and the blind can see.",
			"pt-PT": "A bondade é a linguagem que os surdos podem ouvir e os cegos podem ver.",
			"pt-BR": "A bondade é a linguagem que os surdos podem ouvir e os cegos podem ver.",
			"es":    "La amabilidad es el lenguaje que los sordos pueden oír y los ciegos pueden ver.",
			"fr":    "La gentillesse est le langage que les sourds peuvent entendre et les aveugles voir.",
			"de":    "Freundlichkeit ist die Sprache, die Gehörlose hören und Blinde sehen können.",
			"it":    "La gentilezza è la lingua che i sordi possono udire e i ciechi possono vedere.",
			"ja":    "優しさとは、耳の聞こえない人にも聞こえ、目の見えない人にも見える言葉である。",
			"zh":    "善良是聋人能听见、盲人能看见的语言。",
			"ko":    "친절은 듣지 못하는 사람도 들을 수 있고 보지 못하는 사람도 볼 수 있는 언어다.",
			"hi":    "दया वह भाषा है जिसे बहरे सुन सकते हैं और अंधे देख सकते हैं।",
			"pl":    "Życzliwość to język, który głusi mogą usłyszeć, a niewidomi zobaczyć.",
			"tr":    "Nezaket, sağırların duyabildiği ve körlerin görebildiği dildir.",
			"uk":    "Доброта — це мова, яку глухі можуть почути, а сліпі — побачити.",
			"sv":    "Vänlighet är det språk som de döva kan höra och de blinda kan se.",
			"nl":    "Vriendelijkheid is de taal die doven kunnen horen en blinden kunnen zien.",
			"nb":    "Vennlighet er språket som de døve kan høre og de blinde kan se.",
			"da":    "Venlighed er det sprog, som de døve kan høre, og de blinde kan se.",
			"fi":    "Ystävällisyys on kieli, jonka kuurot voivat kuulla ja sokeat nähdä.",
		},
	},
	{
		ID:       "wisdom-21",
		Author:   ptr("Albert Camus"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend.",
			"en-GB": "Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend.",
			"pt-PT": "Não caminhes atrás de mim; posso não liderar. Não caminhes à minha frente; posso não seguir. Caminha apenas ao meu lado e sê meu amigo.",
			"pt-BR": "Não caminhe atrás de mim; posso não liderar. Não caminhe à minha frente; posso não seguir. Apenas caminhe ao meu lado e seja meu amigo.",
			"es":    "No camines detrás de mí; puede que no te guíe. No camines delante de mí; puede que no te siga. Solo camina a mi lado y sé mi amigo.",
			"fr":    "Ne marche pas derrière moi, je ne te guiderai peut-être pas. Ne marche pas devant moi, je ne te suivrai peut-être pas. Marche simplement à côté de moi et sois mon ami.",
			"de":    "Geh nicht hinter mir; vielleicht führe ich nicht. Geh nicht vor mir; vielleicht folge ich nicht. Geh einfach neben mir und sei mein Freund.",
			"it":    "Non camminare dietro di me; potrei non condurti. Non camminare davanti a me; potrei non seguirti. Cammina semplicemente al mio fianco e sii mio amico.",
			"ja":    "私の後ろを歩かないでほしい。導けないかもしれないから。私の前を歩かないでほしい。ついていけないかもしれないから。ただ隣を歩いて、友達でいてほしい。",
			"zh":    "不要走在我身后，我可能不会引路；不要走在我前面，我可能不会跟随；请走在我身边，做我的朋友。",
			"ko":    "내 뒤에서 걷지 마라. 내가 이끌지 못할 수도 있으니. 내 앞에서 걷지 마라. 내가 따르지 못할 수도 있으니. 그저 내 곁에서 걸으며 내 친구가 되어 달라.",
			"hi":    "मेरे पीछे मत चलो; शायद मैं नेतृत्व न करूँ। मेरे आगे मत चलो; शायद मैं अनुसरण न करूँ। बस मेरे साथ चलो और मेरे मित्र बनो।",
			"pl":    "Nie idź za mną, bo mogę nie prowadzić. Nie idź przede mną, bo mogę nie podążyć. Po prostu idź obok mnie i bądź moim przyjacielem.",
			"tr":    "Arkamdan yürüme; önderlik etmeyebilirim. Önümde yürüme; takip etmeyebilirim. Sadece yanımda yürü ve arkadaşım ol.",
			"uk":    "Не йди позаду мене — я можу не вести. Не йди попереду мене — я можу не піти слідом. Просто йди поруч і будь моїм другом.",
			"sv":    "Gå inte bakom mig; jag kanske inte leder. Gå inte framför mig; jag kanske inte följer. Gå bara bredvid mig och var min vän.",
			"nl":    "Loop niet achter me; misschien leid ik niet. Loop niet voor me; misschien volg ik niet. Loop gewoon naast me en wees mijn vriend.",
			"nb":    "Ikke gå bak meg; jeg leder kanskje ikke. Ikke gå foran meg; jeg følger kanskje ikke. Bare gå ved siden av meg og vær vennen min.",
			"da":    "Gå ikke bag mig; jeg fører måske ikke an. Gå ikke foran mig; jeg følger måske ikke efter. Gå blot ved siden af mig og vær min ven.",
			"fi":    "Älä kulje takanani; en ehkä johda. Älä kulje edelläni; en ehkä seuraa. Kulje vain rinnallani ja ole ystäväni.",
		},
	},
	{
		ID:       "wisdom-22",
		Author:   ptr("Johann Wolfgang von Goethe"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Character is developed in the stream of life.",
			"en-GB": "Character is developed in the stream of life.",
			"pt-PT": "O caráter desenvolve-se na corrente da vida.",
			"pt-BR": "O caráter se desenvolve no fluxo da vida.",
			"es":    "El carácter se desarrolla en el fluir de la vida.",
			"fr":    "Le caractère se développe dans le courant de la vie.",
			"de":    "Der Charakter entwickelt sich im Strom des Lebens.",
			"it":    "Il carattere si sviluppa nella corrente della vita.",
			"ja":    "人格は人生の流れの中で育まれる。",
			"zh":    "品格是在生活的洪流中形成的。",
			"ko":    "인격은 삶의 흐름 속에서 길러진다.",
			"hi":    "चरित्र जीवन की धारा में विकसित होता है।",
			"pl":    "Charakter kształtuje się w nurcie życia.",
			"tr":    "Karakter, hayatın akışı içinde gelişir.",
			"uk":    "Характер формується в потоці життя.",
			"sv":    "Karaktären utvecklas i livets ström.",
			"nl":    "Karakter wordt gevormd in de stroom van het leven.",
			"nb":    "Karakteren utvikles i livets strøm.",
			"da":    "Karakteren udvikles i livets strøm.",
			"fi":    "Luonne kehittyy elämän virrassa.",
		},
	},
	{
		ID:       "wisdom-23",
		Author:   ptr("Socrates"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The only true wisdom is in knowing you know nothing.",
			"en-GB": "The only true wisdom is in knowing you know nothing.",
			"pt-PT": "A única verdadeira sabedoria está em saberes que não sabes nada.",
			"pt-BR": "A única verdadeira sabedoria está em saber que você não sabe nada.",
			"es":    "La única verdadera sabiduría consiste en saber que no se sabe nada.",
			"fr":    "La seule vraie sagesse est de savoir que vous ne savez rien.",
			"de":    "Die einzige wahre Weisheit liegt darin, zu wissen, dass man nichts weiß.",
			"it":    "L'unica vera saggezza è sapere di non sapere nulla.",
			"ja":    "唯一の真の知恵は、自分が何も知らないと知ることである。",
			"zh":    "唯一真正的智慧，是知道自己一无所知。",
			"ko":    "유일한 참된 지혜는 자신이 아무것도 모른다는 것을 아는 데 있다.",
			"hi":    "एकमात्र सच्चा ज्ञान यह जानने में है कि आप कुछ नहीं जानते।",
			"pl":    "Jedyną prawdziwą mądrością jest wiedzieć, że nic się nie wie.",
			"tr":    "Tek gerçek bilgelik, hiçbir şey bilmediğini bilmektir.",
			"uk":    "Єдина справжня мудрість — знати, що ти нічого не знаєш.",
			"sv":    "Den enda sanna visdomen är att veta att man ingenting vet.",
			"nl":    "De enige ware wijsheid is weten dat je niets weet.",
			"nb":    "Den eneste sanne visdom er å vite at du ingenting vet.",
			"da":    "Den eneste sande visdom er at vide, at man intet ved.",
			"fi":    "Ainoa todellinen viisaus on tietää, ettei tiedä mitään.",
		},
	},
	{
		ID:       "wisdom-24",
		Author:   ptr("Mahatma Gandhi"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The weak can never forgive. Forgiveness is the attribute of the strong.",
			"en-GB": "The weak can never forgive. Forgiveness is the attribute of the strong.",
			"pt-PT": "Os fracos nunca podem perdoar. O perdão é o atributo dos fortes.",
			"pt-BR": "Os fracos nunca podem perdoar. O perdão é o atributo dos fortes.",
			"es":    "Los débiles nunca pueden perdonar. El perdón es el atributo de los fuertes.",
			"fr":    "Les faibles ne peuvent jamais pardonner. Le pardon est l'attribut des forts.",
			"de":    "Die Schwachen können nie verzeihen. Vergebung ist eine Eigenschaft der Starken.",
			"it":    "I deboli non possono mai perdonare. Il perdono è un attributo dei forti.",
			"ja":    "弱い者は決して許すことができない。許しは強い者の特質である。",
			"zh":    "弱者永远不会宽恕。宽恕是强者的特质。",
			"ko":    "약한 자는 결코 용서할 수 없다. 용서는 강한 자의 속성이다.",
			"hi":    "कमज़ोर कभी क्षमा नहीं कर सकते। क्षमा बलवानों का गुण है।",
			"pl":    "Słabi nigdy nie potrafią przebaczyć. Przebaczenie jest cechą silnych.",
			"tr":    "Zayıflar asla affedemez. Affetmek güçlülerin özelliğidir.",
			"uk":    "Слабкі ніколи не вміють прощати. Прощення — риса сильних.",
			"sv":    "De svaga kan aldrig förlåta. Förlåtelse är de starkas egenskap.",
			"nl":    "De zwakken kunnen nooit vergeven. Vergeving is een eigenschap van de sterken.",
			"nb":    "De svake kan aldri tilgi. Tilgivelse er de sterkes egenskap.",
			"da":    "De svage kan aldrig tilgive. Tilgivelse er de stærkes egenskab.",
			"fi":    "Heikot eivät koskaan voi antaa anteeksi. Anteeksianto on vahvojen ominaisuus.",
		},
	},
	{
		ID:       "wisdom-25",
		Author:   ptr("Unknown"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Silence is a source of great strength.",
			"en-GB": "Silence is a source of great strength.",
			"pt-PT": "O silêncio é uma fonte de grande força.",
			"pt-BR": "O silêncio é uma fonte de grande força.",
			"es":    "El silencio es una fuente de gran fortaleza.",
			"fr":    "Le silence est une source de grande force.",
			"de":    "Stille ist eine Quelle großer Kraft.",
			"it":    "Il silenzio è fonte di grande forza.",
			"ja":    "沈黙は大いなる力の源である。",
			"zh":    "静默是巨大力量的源泉。",
			"ko":    "침묵은 큰 힘의 원천이다.",
			"hi":    "मौन महान शक्ति का स्रोत है।",
			"pl":    "Cisza jest źródłem wielkiej siły.",
			"tr":    "Sessizlik büyük bir güç kaynağıdır.",
			"uk":    "Тиша — джерело великої сили.",
			"sv":    "Tystnad är en källa till stor styrka.",
			"nl":    "Stilte is een bron van grote kracht.",
			"nb":    "Stillhet er en kilde til stor styrke.",
			"da":    "Stilhed er en kilde til stor styrke.",
			"fi":    "Hiljaisuus on suuren voiman lähde.",
		},
	},
	{
		ID:       "wisdom-26",
		Author:   ptr("Victor Hugo"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "To love another person is to see the face of God.",
			"en-GB": "To love another person is to see the face of God.",
			"pt-PT": "Amar outra pessoa é ver a face de Deus.",
			"pt-BR": "Amar outra pessoa é ver a face de Deus.",
			"es":    "Amar a otra persona es ver el rostro de Dios.",
			"fr":    "Aimer une autre personne, c'est voir le visage de Dieu.",
			"de":    "Einen anderen Menschen zu lieben heißt, das Angesicht Gottes zu sehen.",
			"it":    "Amare un'altra persona è vedere il volto di Dio.",
			"ja":    "人を愛することは、神の御顔を見ることである。",
			"zh":    "爱另一个人，就是看见上帝的面容。",
			"ko":    "다른 사람을 사랑하는 것은 신의 얼굴을 보는 것이다.",
			"hi":    "किसी दूसरे इंसान से प्रेम करना ईश्वर का चेहरा देखना है।",
			"pl":    "Kochać drugiego człowieka to widzieć oblicze Boga.",
			"tr":    "Bir başka insanı sevmek, Tanrı'nın yüzünü görmektir.",
			"uk":    "Любити іншу людину — означає бачити обличчя Бога.",
			"sv":    "Att älska en annan människa är att se Guds ansikte.",
			"nl":    "Een ander mens liefhebben is het gelaat van God zien.",
			"nb":    "Å elske et annet menneske er å se Guds ansikt.",
			"da":    "At elske et andet menneske er at se Guds ansigt.",
			"fi":    "Toisen ihmisen rakastaminen on Jumalan kasvojen näkemistä.",
		},
	},
	{
		ID:       "wisdom-27",
		Author:   ptr("Anne Frank"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
			"en-GB": "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
			"pt-PT": "Como é maravilhoso que ninguém precise de esperar um único momento antes de começar a melhorar o mundo.",
			"pt-BR": "Como é maravilhoso que ninguém precise esperar um único momento antes de começar a melhorar o mundo.",
			"es":    "Qué maravilloso es que nadie tenga que esperar ni un solo momento antes de empezar a mejorar el mundo.",
			"fr":    "Comme il est merveilleux que personne n'ait besoin d'attendre un seul instant avant de commencer à améliorer le monde.",
			"de":    "Wie wunderbar ist es, dass niemand auch nur einen Augenblick warten muss, um anzufangen, die Welt zu verbessern.",
			"it":    "Com'è meraviglioso che nessuno debba aspettare un solo istante prima di cominciare a migliorare il mondo.",
			"ja":    "世界を良くし始めるのに、誰ひとり一瞬たりとも待つ必要がないとは、なんと素晴らしいことだろう。",
			"zh":    "多么美好啊，任何人都无需等待片刻，就可以开始改善这个世界。",
			"ko":    "세상을 더 좋게 만들기 시작하는 데 단 한 순간도 기다릴 필요가 없다는 것은 얼마나 멋진 일인가.",
			"hi":    "कितनी अद्भुत बात है कि दुनिया को बेहतर बनाना शुरू करने के लिए किसी को एक पल भी इंतज़ार नहीं करना पड़ता।",
			"pl":    "Jakie to cudowne, że nikt nie musi czekać ani chwili, by zacząć ulepszać świat.",
			"tr":    "Ne harika ki, dünyayı iyileştirmeye başlamak için kimsenin bir an bile beklemesi gerekmiyor.",
			"uk":    "Як чудово, що нікому не треба чекати ані миті, щоб почати покращувати світ.",
			"sv":    "Så underbart att ingen behöver vänta ett enda ögonblick med att börja förbättra världen.",
			"nl":    "Wat is het geweldig dat niemand ook maar één moment hoeft te wachten om de wereld te gaan verbeteren.",
			"nb":    "Så vidunderlig at ingen trenger å vente et eneste øyeblikk med å begynne å forbedre verden.",
			"da":    "Hvor er det vidunderligt, at ingen behøver at vente et eneste øjeblik med at begynde at forbedre verden.",
			"fi":    "Miten ihmeellistä onkaan, ettei kenenkään tarvitse odottaa hetkeäkään aloittaakseen maailman parantamisen.",
		},
	},
	{
		ID:       "wisdom-28",
		Author:   ptr("Thich Nhat Hanh"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Smile, breathe and go slowly.",
			"en-GB": "Smile, breathe and go slowly.",
			"pt-PT": "Sorri, respira e vai devagar.",
			"pt-BR": "Sorria, respire e vá devagar.",
			"es":    "Sonríe, respira y ve despacio.",
			"fr":    "Souriez, respirez et allez doucement.",
			"de":    "Lächle, atme und geh langsam.",
			"it":    "Sorridi, respira e vai piano.",
			"ja":    "微笑んで、呼吸して、ゆっくり歩もう。",
			"zh":    "微笑，呼吸，慢慢走。",
			"ko":    "미소 짓고, 숨 쉬고, 천천히 가라.",
			"hi":    "मुस्कुराओ, साँस लो और धीरे-धीरे चलो।",
			"pl":    "Uśmiechaj się, oddychaj i idź powoli.",
			"tr":    "Gülümse, nefes al ve yavaş yürü.",
			"uk":    "Усміхайся, дихай і йди повільно.",
			"sv":    "Le, andas och gå långsamt.",
			"nl":    "Glimlach, adem en ga langzaam.",
			"nb":    "Smil, pust og gå sakte.",
			"da":    "Smil, træk vejret og gå langsomt.",
			"fi":    "Hymyile, hengitä ja kulje hitaasti.",
		},
	},
	{
		ID:       "wisdom-29",
		Author:   ptr("Blaise Pascal"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
			"en-GB": "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
			"pt-PT": "Todos os problemas da humanidade derivam da incapacidade do homem de se sentar calmamente numa sala sozinho.",
			"pt-BR": "Todos os problemas da humanidade derivam da incapacidade do homem de se sentar calmamente sozinho em uma sala.",
			"es":    "Todos los problemas de la humanidad provienen de la incapacidad del hombre para sentarse tranquilamente solo en una habitación.",
			"fr":    "Tous les problèmes de l'humanité proviennent de l'incapacité de l'homme à s'asseoir tranquillement seul dans une pièce.",
			"de":    "Alle Probleme der Menschheit rühren daher, dass der Mensch nicht fähig ist, still allein in einem Zimmer zu sitzen.",
			"it":    "Tutti i problemi dell'umanità derivano dall'incapacità dell'uomo di starsene seduto da solo, in silenzio, in una stanza.",
			"ja":    "人類のあらゆる問題は、人がひとり静かに部屋に座っていられないことに由来する。",
			"zh":    "人类的一切问题，都源于人无法独自安静地坐在房间里。",
			"ko":    "인류의 모든 문제는 인간이 방에 혼자 조용히 앉아 있지 못하는 데서 비롯된다.",
			"hi":    "मानवता की सारी समस्याएँ इंसान की उस अक्षमता से उपजती हैं कि वह एक कमरे में अकेला चुपचाप नहीं बैठ सकता।",
			"pl":    "Wszystkie problemy ludzkości biorą się z tego, że człowiek nie potrafi usiedzieć spokojnie sam w pokoju.",
			"tr":    "İnsanlığın bütün sorunları, insanın bir odada tek başına sessizce oturamamasından kaynaklanır.",
			"uk":    "Усі проблеми людства походять від нездатності людини тихо сидіти на самоті в кімнаті.",
			"sv":    "Alla mänsklighetens problem beror på människans oförmåga att sitta tyst ensam i ett rum.",
			"nl":    "Alle problemen van de mensheid komen voort uit het onvermogen van de mens om alleen rustig in een kamer te zitten.",
			"nb":    "Alle menneskehetens problemer stammer fra menneskets manglende evne til å sitte stille alene i et rom.",
			"da":    "Alle menneskehedens problemer udspringer af menneskets manglende evne til at sidde stille alene i et rum.",
			"fi":    "Kaikki ihmiskunnan ongelmat johtuvat ihmisen kyvyttömyydestä istua hiljaa yksin huoneessa.",
		},
	},
	{
		ID:       "wisdom-30",
		Author:   ptr("John Lennon"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Life is what happens when you're busy making other plans.",
			"en-GB": "Life is what happens when you're busy making other plans.",
			"pt-PT": "A vida é o que acontece enquanto estás ocupado a fazer outros planos.",
			"pt-BR": "A vida é o que acontece enquanto você está ocupado fazendo outros planos.",
			"es":    "La vida es lo que te sucede mientras estás ocupado haciendo otros planes.",
			"fr":    "La vie, c'est ce qui arrive quand on est occupé à faire d'autres projets.",
			"de":    "Leben ist das, was passiert, während du eifrig dabei bist, andere Pläne zu machen.",
			"it":    "La vita è ciò che ti accade mentre sei impegnato a fare altri progetti.",
			"ja":    "人生とは、他の計画を立てるのに忙しくしている間に起こるものだ。",
			"zh":    "生活就是当你忙着制订别的计划时发生的事。",
			"ko":    "인생이란 당신이 다른 계획을 세우느라 바쁠 때 일어나는 일이다.",
			"hi":    "ज़िंदगी वह है जो तब घटित होती है जब आप दूसरी योजनाएँ बनाने में व्यस्त होते हैं।",
			"pl":    "Życie jest tym, co ci się przydarza, gdy jesteś zajęty układaniem innych planów.",
			"tr":    "Hayat, sen başka planlar yapmakla meşgulken olup bitendir.",
			"uk":    "Життя — це те, що відбувається, поки ти зайнятий іншими планами.",
			"sv":    "Livet är det som händer medan du är upptagen med att göra andra planer.",
			"nl":    "Het leven is wat er gebeurt terwijl je druk bezig bent andere plannen te maken.",
			"nb":    "Livet er det som skjer mens du er travelt opptatt med å legge andre planer.",
			"da":    "Livet er det, der sker, mens du har travlt med at lægge andre planer.",
			"fi":    "Elämä on sitä, mitä tapahtuu, kun olet kiireinen tehdessäsi muita suunnitelmia.",
		},
	},
	{
		ID:       "wisdom-31",
		Author:   ptr("Socrates"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The only true wisdom is in knowing you know nothing.",
			"en-GB": "The only true wisdom is in knowing you know nothing.",
			"pt-PT": "A única verdadeira sabedoria está em saberes que não sabes nada.",
			"pt-BR": "A única verdadeira sabedoria está em saber que você não sabe nada.",
			"es":    "La única verdadera sabiduría consiste en saber que no se sabe nada.",
			"fr":    "La seule vraie sagesse est de savoir que l'on ne sait rien.",
			"de":    "Die einzige wahre Weisheit liegt darin, zu wissen, dass man nichts weiß.",
			"it":    "L'unica vera saggezza è sapere di non sapere nulla.",
			"ja":    "唯一の真の知恵は、自分が何も知らないと知ることである。",
			"zh":    "唯一真正的智慧，是知道自己一无所知。",
			"ko":    "유일한 참된 지혜는 자신이 아무것도 모른다는 것을 아는 데 있다.",
			"hi":    "एकमात्र सच्चा ज्ञान यह जानने में है कि आप कुछ नहीं जानते।",
			"pl":    "Jedyną prawdziwą mądrością jest wiedzieć, że nic się nie wie.",
			"tr":    "Tek gerçek bilgelik, hiçbir şey bilmediğini bilmektir.",
			"uk":    "Єдина справжня мудрість — знати, що ти нічого не знаєш.",
			"sv":    "Den enda sanna visdomen är att veta att man ingenting vet.",
			"nl":    "De enige ware wijsheid is weten dat je niets weet.",
			"nb":    "Den eneste sanne visdom er å vite at du ingenting vet.",
			"da":    "Den eneste sande visdom er at vide, at man intet ved.",
			"fi":    "Ainoa todellinen viisaus on tietää, ettei tiedä mitään.",
		},
	},
	{
		ID:       "wisdom-32",
		Author:   ptr("Steve Jobs"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Your time is limited, so don't waste it living someone else's life.",
			"en-GB": "Your time is limited, so don't waste it living someone else's life.",
			"pt-PT": "O teu tempo é limitado, por isso não o desperdices a viver a vida de outra pessoa.",
			"pt-BR": "Seu tempo é limitado, então não o desperdice vivendo a vida de outra pessoa.",
			"es":    "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de alguien más.",
			"fr":    "Votre temps est limité, alors ne le gaspillez pas à vivre la vie de quelqu'un d'autre.",
			"de":    "Deine Zeit ist begrenzt, also verschwende sie nicht damit, das Leben eines anderen zu leben.",
			"it":    "Il tuo tempo è limitato, quindi non sprecarlo vivendo la vita di qualcun altro.",
			"ja":    "あなたの時間は限られている。他人の人生を生きて無駄にしてはいけない。",
			"zh":    "你的时间有限，所以不要浪费在过别人的生活上。",
			"ko":    "당신의 시간은 한정되어 있다. 그러니 다른 사람의 삶을 사느라 시간을 낭비하지 마라.",
			"hi":    "आपका समय सीमित है, इसलिए इसे किसी और की ज़िंदगी जीने में बर्बाद मत करो।",
			"pl":    "Twój czas jest ograniczony, więc nie marnuj go na życie cudzym życiem.",
			"tr":    "Zamanın sınırlı; onu başkasının hayatını yaşayarak harcama.",
			"uk":    "Твій час обмежений, тож не витрачай його на те, щоб жити чужим життям.",
			"sv":    "Din tid är begränsad, så slösa den inte på att leva någon annans liv.",
			"nl":    "Je tijd is beperkt, dus verspil hem niet door het leven van iemand anders te leiden.",
			"nb":    "Tiden din er begrenset, så ikke kast den bort på å leve noen andres liv.",
			"da":    "Din tid er begrænset, så spild den ikke på at leve en andens liv.",
			"fi":    "Aikasi on rajallinen, joten älä tuhlaa sitä elämällä jonkun toisen elämää.",
		},
	},
	{
		ID:       "wisdom-33",
		Author:   ptr("Aristotle"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Knowing yourself is the beginning of all wisdom.",
			"en-GB": "Knowing yourself is the beginning of all wisdom.",
			"pt-PT": "Conhecer-te a ti próprio é o princípio de toda a sabedoria.",
			"pt-BR": "Conhecer a si mesmo é o começo de toda a sabedoria.",
			"es":    "Conocerse a uno mismo es el principio de toda sabiduría.",
			"fr":    "Se connaître soi-même est le commencement de toute sagesse.",
			"de":    "Sich selbst zu kennen ist der Anfang aller Weisheit.",
			"it":    "Conoscere se stessi è l'inizio di ogni saggezza.",
			"ja":    "自分自身を知ることは、あらゆる知恵の始まりである。",
			"zh":    "认识自己是一切智慧的开端。",
			"ko":    "자신을 아는 것이 모든 지혜의 시작이다.",
			"hi":    "स्वयं को जानना समस्त ज्ञान का आरंभ है।",
			"pl":    "Poznanie samego siebie jest początkiem wszelkiej mądrości.",
			"tr":    "Kendini bilmek tüm bilgeliğin başlangıcıdır.",
			"uk":    "Пізнання себе — початок усієї мудрості.",
			"sv":    "Att känna sig själv är början på all visdom.",
			"nl":    "Jezelf kennen is het begin van alle wijsheid.",
			"nb":    "Å kjenne seg selv er begynnelsen på all visdom.",
			"da":    "At kende sig selv er begyndelsen på al visdom.",
			"fi":    "Itsensä tunteminen on kaiken viisauden alku.",
		},
	},
	{
		ID:       "wisdom-34",
		Author:   ptr("James Russell Lowell"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "A wise man travels to discover himself.",
			"en-GB": "A wise man travels to discover himself.",
			"pt-PT": "Um homem sábio viaja para se descobrir a si próprio.",
			"pt-BR": "Um homem sábio viaja para descobrir a si mesmo.",
			"es":    "Un hombre sabio viaja para descubrirse a sí mismo.",
			"fr":    "Un homme sage voyage pour se découvrir lui-même.",
			"de":    "Ein weiser Mensch reist, um sich selbst zu entdecken.",
			"it":    "L'uomo saggio viaggia per scoprire se stesso.",
			"ja":    "賢者は自分自身を発見するために旅をする。",
			"zh":    "智者远行，为的是发现自己。",
			"ko":    "지혜로운 사람은 자신을 발견하기 위해 여행한다.",
			"hi":    "बुद्धिमान व्यक्ति स्वयं को खोजने के लिए यात्रा करता है।",
			"pl":    "Mądry człowiek podróżuje, by odkryć samego siebie.",
			"tr":    "Bilge insan kendini keşfetmek için yolculuk eder.",
			"uk":    "Мудра людина мандрує, щоб відкрити себе.",
			"sv":    "En vis människa reser för att upptäcka sig själv.",
			"nl":    "Een wijs mens reist om zichzelf te ontdekken.",
			"nb":    "Et vist menneske reiser for å oppdage seg selv.",
			"da":    "Et viist menneske rejser for at opdage sig selv.",
			"fi":    "Viisas ihminen matkustaa löytääkseen itsensä.",
		},
	},
	{
		ID:       "wisdom-35",
		Author:   ptr("Albert Einstein"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The measure of intelligence is the ability to change.",
			"en-GB": "The measure of intelligence is the ability to change.",
			"pt-PT": "A medida da inteligência é a capacidade de mudar.",
			"pt-BR": "A medida da inteligência é a capacidade de mudar.",
			"es":    "La medida de la inteligencia es la capacidad de cambiar.",
			"fr":    "La mesure de l'intelligence est la capacité de changer.",
			"de":    "Das Maß der Intelligenz ist die Fähigkeit, sich zu verändern.",
			"it":    "La misura dell'intelligenza è la capacità di cambiare.",
			"ja":    "知性の尺度は、変わる能力である。",
			"zh":    "智力的衡量标准是改变的能力。",
			"ko":    "지성의 척도는 변화할 수 있는 능력이다.",
			"hi":    "बुद्धिमत्ता की कसौटी है बदलने की क्षमता।",
			"pl":    "Miarą inteligencji jest zdolność do zmiany.",
			"tr":    "Zekânın ölçüsü, değişebilme yeteneğidir.",
			"uk":    "Мірило інтелекту — здатність змінюватися.",
			"sv":    "Måttet på intelligens är förmågan att förändras.",
			"nl":    "De maatstaf van intelligentie is het vermogen om te veranderen.",
			"nb":    "Målet på intelligens er evnen til å forandre seg.",
			"da":    "Målet for intelligens er evnen til at forandre sig.",
			"fi":    "Älykkyyden mitta on kyky muuttua.",
		},
	},
	{
		ID:       "wisdom-36",
		Author:   ptr("Oprah Winfrey"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Turn your wounds into wisdom.",
			"en-GB": "Turn your wounds into wisdom.",
			"pt-PT": "Transforma as tuas feridas em sabedoria.",
			"pt-BR": "Transforme suas feridas em sabedoria.",
			"es":    "Convierte tus heridas en sabiduría.",
			"fr":    "Transformez vos blessures en sagesse.",
			"de":    "Verwandle deine Wunden in Weisheit.",
			"it":    "Trasforma le tue ferite in saggezza.",
			"ja":    "あなたの傷を知恵に変えなさい。",
			"zh":    "把你的伤口化为智慧。",
			"ko":    "당신의 상처를 지혜로 바꾸라.",
			"hi":    "अपने घावों को ज्ञान में बदल दो।",
			"pl":    "Zamień swoje rany w mądrość.",
			"tr":    "Yaralarını bilgeliğe dönüştür.",
			"uk":    "Перетвори свої рани на мудрість.",
			"sv":    "Förvandla dina sår till visdom.",
			"nl":    "Verander je wonden in wijsheid.",
			"nb":    "Gjør sårene dine om til visdom.",
			"da":    "Forvandl dine sår til visdom.",
			"fi":    "Muuta haavasi viisaudeksi.",
		},
	},
	{
		ID:       "wisdom-37",
		Author:   ptr("Anaïs Nin"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "We don't see things as they are, we see them as we are.",
			"en-GB": "We don't see things as they are, we see them as we are.",
			"pt-PT": "Não vemos as coisas como elas são, vemo-las como nós somos.",
			"pt-BR": "Não vemos as coisas como elas são, vemo-las como nós somos.",
			"es":    "No vemos las cosas como son, las vemos como somos.",
			"fr":    "Nous ne voyons pas les choses telles qu'elles sont, nous les voyons telles que nous sommes.",
			"de":    "Wir sehen die Dinge nicht, wie sie sind. Wir sehen sie so, wie wir sind.",
			"it":    "Non vediamo le cose come sono, le vediamo come siamo noi.",
			"ja":    "私たちは物事をあるがままに見ているのではない。自分のあり方を通して見ているのだ。",
			"zh":    "我们看到的不是事物的本相，而是我们自己的模样。",
			"ko":    "우리는 사물을 있는 그대로 보지 않는다. 우리 자신의 모습대로 본다.",
			"hi":    "हम चीज़ों को वैसा नहीं देखते जैसी वे हैं, हम उन्हें वैसा देखते हैं जैसे हम हैं।",
			"pl":    "Nie widzimy rzeczy takimi, jakie są. Widzimy je takimi, jacy sami jesteśmy.",
			"tr":    "Şeyleri oldukları gibi değil, kendimiz gibi görürüz.",
			"uk":    "Ми бачимо речі не такими, якими вони є, а такими, якими є ми самі.",
			"sv":    "Vi ser inte tingen som de är, vi ser dem som vi är.",
			"nl":    "We zien de dingen niet zoals ze zijn, we zien ze zoals wij zijn.",
			"nb":    "Vi ser ikke tingene som de er, vi ser dem som vi er.",
			"da":    "Vi ser ikke tingene, som de er, vi ser dem, som vi er.",
			"fi":    "Emme näe asioita sellaisina kuin ne ovat, vaan sellaisina kuin me olemme.",
		},
	},
	{
		ID:       "wisdom-38",
		Author:   ptr("Claude Lévi-Strauss"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "The wise man does not give the right answers, he poses the right questions.",
			"en-GB": "The wise man does not give the right answers, he poses the right questions.",
			"pt-PT": "O homem sábio não dá as respostas certas, ele coloca as perguntas certas.",
			"pt-BR": "O homem sábio não dá as respostas certas, ele coloca as perguntas certas.",
			"es":    "El sabio no da las respuestas correctas, plantea las preguntas adecuadas.",
			"fr":    "Le sage ne donne pas les bonnes réponses, il pose les bonnes questions.",
			"de":    "Der Weise gibt nicht die richtigen Antworten, er stellt die richtigen Fragen.",
			"it":    "Il saggio non dà le risposte giuste, pone le domande giuste.",
			"ja":    "賢者は正しい答えを与えるのではなく、正しい問いを投げかける。",
			"zh":    "智者不给出正确的答案，而是提出正确的问题。",
			"ko":    "지혜로운 사람은 옳은 답을 주지 않는다. 옳은 질문을 던진다.",
			"hi":    "बुद्धिमान व्यक्ति सही उत्तर नहीं देता, वह सही प्रश्न पूछता है।",
			"pl":    "Mędrzec nie udziela właściwych odpowiedzi — zadaje właściwe pytania.",
			"tr":    "Bilge insan doğru yanıtları vermez, doğru soruları sorar.",
			"uk":    "Мудрець не дає правильних відповідей — він ставить правильні запитання.",
			"sv":    "Den vise ger inte de rätta svaren, han ställer de rätta frågorna.",
			"nl":    "De wijze geeft niet de juiste antwoorden, hij stelt de juiste vragen.",
			"nb":    "Den vise gir ikke de riktige svarene, han stiller de riktige spørsmålene.",
			"da":    "Den vise giver ikke de rigtige svar, han stiller de rigtige spørgsmål.",
			"fi":    "Viisas ei anna oikeita vastauksia, hän esittää oikeat kysymykset.",
		},
	},
	{
		ID:       "wisdom-39",
		Author:   ptr("Socrates"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "Wisdom begins in wonder.",
			"en-GB": "Wisdom begins in wonder.",
			"pt-PT": "A sabedoria começa no espanto.",
			"pt-BR": "A sabedoria começa no espanto.",
			"es":    "La sabiduría empieza en el asombro.",
			"fr":    "La sagesse commence par l'émerveillement.",
			"de":    "Weisheit beginnt mit dem Staunen.",
			"it":    "La saggezza comincia con la meraviglia.",
			"ja":    "知恵は驚きから始まる。",
			"zh":    "智慧始于惊奇。",
			"ko":    "지혜는 경이로움에서 시작된다.",
			"hi":    "ज्ञान का आरंभ विस्मय से होता है।",
			"pl":    "Mądrość zaczyna się od zdumienia.",
			"tr":    "Bilgelik hayretle başlar.",
			"uk":    "Мудрість починається з подиву.",
			"sv":    "Visdom börjar i förundran.",
			"nl":    "Wijsheid begint met verwondering.",
			"nb":    "Visdom begynner med undring.",
			"da":    "Visdom begynder med undren.",
			"fi":    "Viisaus alkaa ihmetyksestä.",
		},
	},
	{
		ID:       "wisdom-40",
		Author:   ptr("Nicolaus Copernicus"),
		Category: "wisdom",
		Translations: map[string]string{
			"en-US": "To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.",
			"en-GB": "To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.",
			"pt-PT": "Saber que sabemos o que sabemos, e saber que não sabemos o que não sabemos, isso é o verdadeiro conhecimento.",
			"pt-BR": "Saber que sabemos o que sabemos, e saber que não sabemos o que não sabemos, isso é o verdadeiro conhecimento.",
			"es":    "Saber que sabemos lo que sabemos, y saber que no sabemos lo que no sabemos, eso es el verdadero conocimiento.",
			"fr":    "Savoir que nous savons ce que nous savons, et savoir que nous ne savons pas ce que nous ne savons pas, c'est cela la vraie connaissance.",
			"de":    "Zu wissen, dass wir wissen, was wir wissen, und zu wissen, dass wir nicht wissen, was wir nicht wissen — das ist wahres Wissen.",
			"it":    "Sapere di sapere ciò che sappiamo, e sapere di non sapere ciò che non sappiamo: questa è la vera conoscenza.",
			"ja":    "知っていることを知っていると知り、知らないことを知らないと知る。それが真の知である。",
			"zh":    "知之为知之，不知为不知，是知也。",
			"ko":    "아는 것을 안다고 하고 모르는 것을 모른다고 하는 것, 그것이 참된 앎이다.",
			"hi":    "यह जानना कि हम जो जानते हैं उसे जानते हैं, और यह जानना कि जो नहीं जानते उसे नहीं जानते—यही सच्चा ज्ञान है।",
			"pl":    "Wiedzieć, że wiemy to, co wiemy, i wiedzieć, że nie wiemy tego, czego nie wiemy — oto prawdziwa wiedza.",
			"tr":    "Bildiğimizi bildiğimizi bilmek ve bilmediğimizi bilmediğimizi bilmek — işte gerçek bilgi budur.",
			"uk":    "Знати, що ми знаємо те, що знаємо, і знати, що ми не знаємо того, чого не знаємо, — оце і є справжнє знання.",
			"sv":    "Att veta att vi vet det vi vet, och att veta att vi inte vet det vi inte vet — det är sann kunskap.",
			"nl":    "Weten dat we weten wat we weten, en weten dat we niet weten wat we niet weten — dat is ware kennis.",
			"nb":    "Å vite at vi vet det vi vet, og å vite at vi ikke vet det vi ikke vet — det er sann kunnskap.",
			"da":    "At vide, at vi ved, hvad vi ved, og at vide, at vi ikke ved, hvad vi ikke ved — det er sand viden.",
			"fi":    "Tietää tietävänsä sen minkä tietää, ja tietää ettei tiedä sitä mitä ei tiedä — se on todellista tietoa.",
		},
	},
}
