package quote

var mindsetQuotes = []QuoteData{
	{
		ID:       "mindset-1",
		Author:   ptr("Theodore Roosevelt"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Believe you can and you're halfway there.",
			"en-GB": "Believe you can and you're halfway there.",
			"pt-PT": "Acredita que consegues e já estás a meio caminho.",
			"pt-BR": "Acredite que você pode e você já está no meio do caminho.",
			"es":    "Cree que puedes y ya estarás a medio camino.",
			"fr":    "Croyez que vous le pouvez et vous êtes déjà à mi-chemin.",
			"de":    "Glaube, dass du es kannst, und du bist schon halb am Ziel.",
			"it":    "Credi di potercela fare e sei già a metà strada.",
			"ja":    "できると信じれば、もう半分は達成したようなものだ。",
			"zh":    "相信自己能行，你就已经成功了一半。",
			"ko":    "할 수 있다고 믿으면 이미 절반은 이룬 것이다.",
			"hi":    "विश्वास करो कि तुम कर सकते हो, और तुम आधा रास्ता पार कर चुके हो।",
			"pl":    "Uwierz, że potrafisz, a jesteś już w połowie drogi.",
			"tr":    "Yapabileceğine inan, yolun yarısını gitmişsin demektir.",
			"uk":    "Повір, що зможеш, — і ти вже на півдорозі.",
			"sv":    "Tro att du kan, så är du redan halvvägs.",
			"nl":    "Geloof dat je het kunt en je bent al halverwege.",
			"nb":    "Tro at du kan, så er du allerede halvveis.",
			"da":    "Tro på, at du kan, så er du allerede halvvejs.",
			"fi":    "Usko että pystyt, niin olet jo puolivälissä.",
		},
	},
	{
		ID:       "mindset-2",
		Author:   ptr("George Addair"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Everything you've ever wanted is on the other side of fear.",
			"en-GB": "Everything you've ever wanted is on the other side of fear.",
			"pt-PT": "Tudo o que sempre quiseste está do outro lado do medo.",
			"pt-BR": "Tudo o que você sempre quis está do outro lado do medo.",
			"es":    "Todo lo que siempre has querido está al otro lado del miedo.",
			"fr":    "Tout ce que vous avez toujours voulu est de l'autre côté de la peur.",
			"de":    "Alles, was du dir je gewünscht hast, liegt auf der anderen Seite der Angst.",
			"it":    "Tutto ciò che hai sempre desiderato è dall'altra parte della paura.",
			"ja":    "あなたが望んできたすべては、恐れの向こう側にある。",
			"zh":    "你想要的一切，都在恐惧的另一边。",
			"ko":    "당신이 원해 온 모든 것은 두려움 너머에 있다.",
			"hi":    "जो कुछ भी आपने कभी चाहा है, वह डर के उस पार है।",
			"pl":    "Wszystko, czego kiedykolwiek pragnąłeś, jest po drugiej stronie strachu.",
			"tr":    "Şimdiye dek istediğin her şey, korkunun öte yanındadır.",
			"uk":    "Усе, чого ти будь-коли прагнув, — по той бік страху.",
			"sv":    "Allt du någonsin velat ha finns på andra sidan rädslan.",
			"nl":    "Alles wat je ooit hebt gewild, ligt aan de andere kant van de angst.",
			"nb":    "Alt du noen gang har ønsket deg, ligger på den andre siden av frykten.",
			"da":    "Alt, hvad du nogensinde har ønsket dig, ligger på den anden side af frygten.",
			"fi":    "Kaikki mitä olet koskaan halunnut on pelon toisella puolella.",
		},
	},
	{
		ID:       "mindset-3",
		Author:   ptr("C.S. Lewis"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "You are never too old to set another goal or to dream a new dream.",
			"en-GB": "You are never too old to set another goal or to dream a new dream.",
			"pt-PT": "Nunca és demasiado velho para definir outro objetivo ou sonhar um novo sonho.",
			"pt-BR": "Você nunca é velho demais para estabelecer outro objetivo ou sonhar um novo sonho.",
			"es":    "Nunca eres demasiado viejo para fijarte otra meta o para soñar un nuevo sueño.",
			"fr":    "On n'est jamais trop vieux pour se fixer un autre objectif ou pour faire un novo rêve.",
			"de":    "Man ist nie zu alt, um sich ein neues Ziel zu setzen oder einen neuen Traum zu träumen.",
			"it":    "Non si è mai troppo vecchi per fissare un nuovo obiettivo o sognare un nuovo sogno.",
			"ja":    "新しい目標を立てたり、新しい夢を見たりするのに、歳を取りすぎているということはない。",
			"zh":    "无论多大年纪，都可以设立新的目标、编织新的梦想。",
			"ko":    "새로운 목표를 세우거나 새로운 꿈을 꾸기에 너무 늦은 나이는 없다.",
			"hi":    "नया लक्ष्य बनाने या नया सपना देखने के लिए आप कभी बहुत बूढ़े नहीं होते।",
			"pl":    "Nigdy nie jesteś za stary, by wyznaczyć sobie nowy cel albo wyśnić nowe marzenie.",
			"tr":    "Yeni bir hedef koymak ya da yeni bir hayal kurmak için asla çok yaşlı değilsin.",
			"uk":    "Ніколи не пізно поставити нову мету чи наважитися на нову мрію.",
			"sv":    "Man är aldrig för gammal för att sätta ett nytt mål eller drömma en ny dröm.",
			"nl":    "Je bent nooit te oud om een nieuw doel te stellen of een nieuwe droom te dromen.",
			"nb":    "Du er aldri for gammel til å sette deg et nytt mål eller drømme en ny drøm.",
			"da":    "Man er aldrig for gammel til at sætte sig et nyt mål eller drømme en ny drøm.",
			"fi":    "Koskaan et ole liian vanha asettamaan uutta tavoitetta tai unelmoimaan uutta unelmaa.",
		},
	},
	{
		ID:       "mindset-4",
		Author:   ptr("Stephen Covey"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "I am not a product of my circumstances. I am a product of my decisions.",
			"en-GB": "I am not a product of my circumstances. I am a product of my decisions.",
			"pt-PT": "Não sou um produto das minhas circunstâncias. Sou um produto das minhas decisões.",
			"pt-BR": "Não sou um produto das minhas circunstâncias. Sou um produto das minhas decisões.",
			"es":    "No soy un producto de mis circunstancias. Soy un producto de mis decisiones.",
			"fr":    "Je ne suis pas le produit de mes circonstances. Je suis le produit de mes décisions.",
			"de":    "Ich bin nicht das Produkt meiner Umstände. Ich bin das Produkt meiner Entscheidungen.",
			"it":    "Non sono il prodotto delle mie circostanze. Sono il prodotto delle mie decisioni.",
			"ja":    "私は環境の産物ではない。自らの決断の産物である。",
			"zh":    "我不是环境的产物，而是我自己决定的产物。",
			"ko":    "나는 환경의 산물이 아니다. 내 결정의 산물이다.",
			"hi":    "मैं अपनी परिस्थितियों की उपज नहीं हूँ। मैं अपने निर्णयों की उपज हूँ।",
			"pl":    "Nie jestem wytworem okoliczności. Jestem wytworem swoich decyzji.",
			"tr":    "Ben koşullarımın ürünü değilim. Kararlarımın ürünüyüm.",
			"uk":    "Я не продукт обставин. Я продукт своїх рішень.",
			"sv":    "Jag är inte en produkt av mina omständigheter. Jag är en produkt av mina beslut.",
			"nl":    "Ik ben geen product van mijn omstandigheden. Ik ben een product van mijn beslissingen.",
			"nb":    "Jeg er ikke et produkt av omstendighetene mine. Jeg er et produkt av beslutningene mine.",
			"da":    "Jeg er ikke et produkt af mine omstændigheder. Jeg er et produkt af mine beslutninger.",
			"fi":    "En ole olosuhteideni tuote. Olen päätösteni tuote.",
		},
	},
	{
		ID:       "mindset-5",
		Author:   ptr("Ralph Waldo Emerson"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The only person you are destined to become is the person you decide to be.",
			"en-GB": "The only person you are destined to become is the person you decide to be.",
			"pt-PT": "A única pessoa que estás destinado a ser é a pessoa que decidires ser.",
			"pt-BR": "A única pessoa que você está destinado a se tornar é a pessoa que você decidir ser.",
			"es":    "La única persona que estás destinado a ser es la persona que decides ser.",
			"fr":    "La seule personne que vous êtes destiné à devenir est celle que vous décidez d'être.",
			"de":    "Der einzige Mensch, der du werden sollst, ist der Mensch, der du dich entscheidest zu sein.",
			"it":    "L'unica persona che sei destinato a diventare è la persona che decidi di essere.",
			"ja":    "あなたがなるべき唯一の人間は、あなたがなろうと決めた人間だ。",
			"zh":    "你唯一注定要成为的人，是你自己决定成为的那个人。",
			"ko":    "당신이 되도록 정해진 유일한 사람은, 당신이 되기로 결심한 사람이다.",
			"hi":    "आप केवल वही व्यक्ति बनने के लिए नियत हैं, जो आप बनने का निर्णय करते हैं।",
			"pl":    "Jedyną osobą, którą masz się stać, jest osoba, którą sam postanowisz być.",
			"tr":    "Olmaya yazgılı olduğun tek kişi, olmaya karar verdiğin kişidir.",
			"uk":    "Єдина людина, якою тобі судилося стати, — це людина, якою ти вирішиш бути.",
			"sv":    "Den enda person du är ämnad att bli är den person du bestämmer dig för att vara.",
			"nl":    "De enige persoon die je voorbestemd bent te worden, is de persoon die je besluit te zijn.",
			"nb":    "Den eneste personen du er bestemt til å bli, er den personen du bestemmer deg for å være.",
			"da":    "Den eneste person, du er bestemt til at blive, er den person, du beslutter dig for at være.",
			"fi":    "Ainoa ihminen, joksi sinun on määrä tulla, on se ihminen, joksi päätät tulla.",
		},
	},
	{
		ID:       "mindset-6",
		Author:   ptr("Unknown"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "If you want to achieve greatness stop asking for permission.",
			"en-GB": "If you want to achieve greatness stop asking for permission.",
			"pt-PT": "Se queres alcançar a grandeza, para de pedir permissão.",
			"pt-BR": "Se você quer alcançar a grandeza, pare de pedir permissão.",
			"es":    "Si quieres alcanzar la grandeza, deja de pedir permiso.",
			"fr":    "Si vous voulez atteindre la grandeur, arrêtez de demander la permission.",
			"de":    "Wenn du Großes erreichen willst, hör auf, um Erlaubnis zu bitten.",
			"it":    "Se vuoi raggiungere la grandezza, smetti di chiedere il permesso.",
			"ja":    "偉大なことを成し遂げたいなら、許可を求めるのをやめよ。",
			"zh":    "想要成就伟大，就别再请求许可。",
			"ko":    "위대함을 이루고 싶다면 허락을 구하는 것을 멈춰라.",
			"hi":    "अगर महानता हासिल करनी है, तो अनुमति माँगना बंद करो।",
			"pl":    "Jeśli chcesz osiągnąć wielkość, przestań pytać o pozwolenie.",
			"tr":    "Büyük işler başarmak istiyorsan izin istemeyi bırak.",
			"uk":    "Якщо хочеш досягти величі, перестань просити дозволу.",
			"sv":    "Om du vill uppnå storhet, sluta be om lov.",
			"nl":    "Als je grootsheid wilt bereiken, stop dan met toestemming vragen.",
			"nb":    "Vil du oppnå storhet, slutt å be om tillatelse.",
			"da":    "Vil du opnå storhed, så hold op med at bede om lov.",
			"fi":    "Jos haluat saavuttaa suuruutta, lakkaa pyytämästä lupaa.",
		},
	},
	{
		ID:       "mindset-7",
		Author:   ptr("Walt Disney"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "If you can dream it, you can do it.",
			"en-GB": "If you can dream it, you can do it.",
			"pt-PT": "Se consegues sonhar, consegues fazê-lo.",
			"pt-BR": "Se você pode sonhar, você pode fazer.",
			"es":    "Si puedes soñarlo, puedes hacerlo.",
			"fr":    "Si vous pouvez le rêver, vous pouvez le faire.",
			"de":    "Wenn du es träumen kannst, kannst du es auch tun.",
			"it":    "Se puoi sognarlo, puoi farlo.",
			"ja":    "夢見ることができれば、それは実現できる。",
			"zh":    "只要敢于梦想，就能做到。",
			"ko":    "꿈꿀 수 있다면 이룰 수도 있다.",
			"hi":    "अगर आप इसका सपना देख सकते हैं, तो आप इसे कर भी सकते हैं।",
			"pl":    "Jeśli potrafisz o czymś marzyć, potrafisz to zrobić.",
			"tr":    "Hayal edebiliyorsan, yapabilirsin.",
			"uk":    "Якщо можеш це уявити — можеш це зробити.",
			"sv":    "Om du kan drömma det kan du göra det.",
			"nl":    "Als je het kunt dromen, kun je het doen.",
			"nb":    "Kan du drømme det, kan du gjøre det.",
			"da":    "Hvis du kan drømme det, kan du gøre det.",
			"fi":    "Jos voit unelmoida sen, voit myös tehdä sen.",
		},
	},
	{
		ID:       "mindset-8",
		Author:   ptr("Buddha"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The mind is everything. What you think you become.",
			"en-GB": "The mind is everything. What you think you become.",
			"pt-PT": "A mente é tudo. Tornas-te naquilo que pensas.",
			"pt-BR": "A mente é tudo. Você se torna aquilo que você pensa.",
			"es":    "La mente lo es todo. Te conviertes en lo que piensas.",
			"fr":    "L'esprit est tout. Ce que vous pensez, vous le devenez.",
			"de":    "Der Geist ist alles. Was du denkst, das wirst du.",
			"it":    "La mente è tutto. Ciò che pensi, diventi.",
			"ja":    "心がすべてである。思った通りの人間になる。",
			"zh":    "心即一切。你想什么，就会成为什么。",
			"ko":    "마음이 전부다. 생각하는 대로 이루어진다.",
			"hi":    "मन ही सब कुछ है। जो सोचते हो, वही बन जाते हो।",
			"pl":    "Umysł jest wszystkim. Stajesz się tym, o czym myślisz.",
			"tr":    "Zihin her şeydir. Ne düşünürsen o olursun.",
			"uk":    "Розум — це все. Ким себе мислиш, тим і стаєш.",
			"sv":    "Sinnet är allt. Vad du tänker blir du.",
			"nl":    "De geest is alles. Wat je denkt, word je.",
			"nb":    "Sinnet er alt. Det du tenker, blir du.",
			"da":    "Sindet er alt. Hvad du tænker, bliver du.",
			"fi":    "Mieli on kaikki. Siitä mitä ajattelet, tulet.",
		},
	},
	{
		ID:       "mindset-9",
		Author:   ptr("Henry Ford"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Whether you think you can, or you think you can't—you're right.",
			"en-GB": "Whether you think you can, or you think you can't—you're right.",
			"pt-PT": "Quer penses que consegues, quer penses que não consegues — estás certo.",
			"pt-BR": "Se você pensa que pode ou se pensa que não pode, de qualquer forma você está certo.",
			"es":    "Tanto si piensas que puedes como si piensas que no puedes, tienes razón.",
			"fr":    "Que vous pensiez pouvoir le faire ou non, vous avez raison.",
			"de":    "Ob du denkst, du kannst es, oder du kannst es nicht: Du wirst auf jeden Fall recht behalten.",
			"it":    "Che tu creda di farcela o di non farcela, avrai comunque ragione.",
			"ja":    "できると思うにせよ、できないと思うにせよ、あなたは正しい。",
			"zh":    "无论你认为自己行还是不行，你都是对的。",
			"ko":    "할 수 있다고 생각하든 할 수 없다고 생각하든, 당신 생각이 옳다.",
			"hi":    "चाहे आप सोचें कि आप कर सकते हैं, या सोचें कि नहीं कर सकते—दोनों ही सूरत में आप सही हैं।",
			"pl":    "Niezależnie od tego, czy myślisz, że potrafisz, czy że nie potrafisz — masz rację.",
			"tr":    "Yapabileceğini de düşünsen, yapamayacağını da düşünsen haklısın.",
			"uk":    "Думаєш, що зможеш, чи думаєш, що ні, — у будь-якому разі ти маєш рацію.",
			"sv":    "Vare sig du tror att du kan eller att du inte kan, har du rätt.",
			"nl":    "Of je nu denkt dat je het kunt of dat je het niet kunt, je hebt gelijk.",
			"nb":    "Enten du tror du kan eller tror du ikke kan, har du rett.",
			"da":    "Uanset om du tror, du kan, eller du tror, du ikke kan, har du ret.",
			"fi":    "Ajattelitpa että pystyt tai että et pysty — olet oikeassa.",
		},
	},
	{
		ID:       "mindset-10",
		Author:   ptr("Norman Vincent Peale"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Change your thoughts and you change your world.",
			"en-GB": "Change your thoughts and you change your world.",
			"pt-PT": "Muda os teus pensamentos e mudas o teu mundo.",
			"pt-BR": "Mude seus pensamentos e você mudará seu mundo.",
			"es":    "Cambia tus pensamientos y cambiarás tu mundo.",
			"fr":    "Changez vos pensées et vous changerez votre monde.",
			"de":    "Ändere deine Gedanken, und du änderst deine Welt.",
			"it":    "Cambia i tuoi pensieri e cambierai il tuo mondo.",
			"ja":    "考えを変えれば、世界が変わる。",
			"zh":    "改变你的思想，就能改变你的世界。",
			"ko":    "생각을 바꾸면 세상이 바뀐다.",
			"hi":    "अपने विचार बदलो और तुम्हारी दुनिया बदल जाएगी।",
			"pl":    "Zmień swoje myśli, a zmienisz swój świat.",
			"tr":    "Düşüncelerini değiştir, dünyan değişsin.",
			"uk":    "Зміни свої думки — і зміниш свій світ.",
			"sv":    "Förändra dina tankar så förändrar du din värld.",
			"nl":    "Verander je gedachten en je verandert je wereld.",
			"nb":    "Endre tankene dine, og du endrer verden din.",
			"da":    "Skift dine tanker, og du forandrer din verden.",
			"fi":    "Muuta ajatuksesi, niin muutat maailmasi.",
		},
	},
	{
		ID:       "mindset-11",
		Author:   ptr("Marcus Aurelius"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The happiness of your life depends upon the quality of your thoughts.",
			"en-GB": "The happiness of your life depends upon the quality of your thoughts.",
			"pt-PT": "A felicidade da tua vida depende da qualidade dos teus pensamentos.",
			"pt-BR": "A felicidade de sua vida depende da qualidade de seus pensamentos.",
			"es":    "La felicidad de tu vida depende de la calidad de tus pensamientos.",
			"fr":    "Le bonheur de votre vie dépend de la qualité de vos pensées.",
			"de":    "Das Glück deines Lebens hängt von der Beschaffenheit deiner Gedanken ab.",
			"it":    "La felicità della tua vita dipende dalla qualità dei tuoi pensieri.",
			"ja":    "人生の幸福は、思考の質にかかっている。",
			"zh":    "生活的幸福取决于思想的品质。",
			"ko":    "삶의 행복은 생각의 질에 달려 있다.",
			"hi":    "आपके जीवन की ख़ुशी आपके विचारों की गुणवत्ता पर निर्भर करती है।",
			"pl":    "Szczęście twojego życia zależy od jakości twoich myśli.",
			"tr":    "Hayatının mutluluğu, düşüncelerinin niteliğine bağlıdır.",
			"uk":    "Щастя твого життя залежить від якості твоїх думок.",
			"sv":    "Ditt livs lycka beror på kvaliteten på dina tankar.",
			"nl":    "Het geluk van je leven hangt af van de kwaliteit van je gedachten.",
			"nb":    "Lykken i livet ditt avhenger av kvaliteten på tankene dine.",
			"da":    "Lykken i dit liv afhænger af kvaliteten af dine tanker.",
			"fi":    "Elämäsi onnellisuus riippuu ajatustesi laadusta.",
		},
	},
	{
		ID:       "mindset-12",
		Author:   ptr("William James"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.",
			"en-GB": "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.",
			"pt-PT": "A maior descoberta da minha geração é que um ser humano pode alterar a sua vida alterando as suas atitudes.",
			"pt-BR": "A maior descoberta da minha geração é que o ser humano pode alterar sua vida alterando suas atitudes.",
			"es":    "El mayor descubrimiento de mi generación es que un ser humano puede alterar su vida alterando sus actitudes.",
			"fr":    "La plus grande découverte de ma génération est qu'un être humain peut modifier sa vie en modifiant ses attitudes.",
			"de":    "Die größte Entdeckung meiner Generation ist, dass ein Mensch sein Leben ändern kann, indem er seine Einstellung ändert.",
			"it":    "La più grande scoperta della mia generazione è che un essere umano può cambiare la propria vita cambiando il proprio atteggiamento.",
			"ja":    "私の世代最大の発見は、人は心の持ち方を変えることで人生を変えられるということだ。",
			"zh":    "我这一代人最伟大的发现是：人可以通过改变态度来改变人生。",
			"ko":    "우리 세대의 가장 위대한 발견은 인간이 태도를 바꿈으로써 인생을 바꿀 수 있다는 것이다.",
			"hi":    "मेरी पीढ़ी की सबसे बड़ी खोज यह है कि इंसान अपना नज़रिया बदलकर अपना जीवन बदल सकता है।",
			"pl":    "Największym odkryciem mojego pokolenia jest to, że człowiek może odmienić swoje życie, zmieniając swoje nastawienie.",
			"tr":    "Kuşağımın en büyük keşfi, insanın tutumlarını değiştirerek hayatını değiştirebileceğidir.",
			"uk":    "Найбільше відкриття мого покоління — те, що людина може змінити своє життя, змінивши своє ставлення.",
			"sv":    "Min generations största upptäckt är att en människa kan förändra sitt liv genom att förändra sin attityd.",
			"nl":    "De grootste ontdekking van mijn generatie is dat een mens zijn leven kan veranderen door zijn houding te veranderen.",
			"nb":    "Min generasjons største oppdagelse er at et menneske kan forandre livet sitt ved å forandre holdningene sine.",
			"da":    "Min generations største opdagelse er, at et menneske kan forandre sit liv ved at ændre sin indstilling.",
			"fi":    "Sukupolveni suurin löytö on, että ihminen voi muuttaa elämänsä muuttamalla asennettaan.",
		},
	},
	{
		ID:       "mindset-13",
		Author:   ptr("Wayne Dyer"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "You cannot be lonely if you like the person you're alone with.",
			"en-GB": "You cannot be lonely if you like the person you're alone with.",
			"pt-PT": "Não podes sentir-te sozinho se gostares da pessoa com quem estás sozinho.",
			"pt-BR": "Você não pode se sentir sozinho se gostar da pessoa com quem está sozinho.",
			"es":    "No puedes estar solo si te gusta la persona con la que estás solo.",
			"fr":    "Vous ne pouvez pas être seul si vous aimez la personne avec qui vous êtes seul.",
			"de":    "Du kannst nicht einsam sein, wenn du den Menschen magst, mit dem du allein bist.",
			"it":    "Non puoi sentirti solo se ti piace la persona con cui sei da solo.",
			"ja":    "ひとりでいる相手が好きなら、孤独になりようがない。",
			"zh":    "如果你喜欢独处时陪着你的那个人，你就不会孤独。",
			"ko":    "혼자 있을 때 함께 있는 그 사람이 마음에 든다면, 결코 외로울 수 없다.",
			"hi":    "अगर आपको वह इंसान पसंद है जिसके साथ आप अकेले हैं, तो आप अकेलापन महसूस नहीं कर सकते।",
			"pl":    "Nie możesz być samotny, jeśli lubisz osobę, z którą jesteś sam.",
			"tr":    "Yalnız kaldığın kişiyi seviyorsan, yalnız olamazsın.",
			"uk":    "Ти не можеш бути самотнім, якщо тобі подобається людина, з якою ти наодинці.",
			"sv":    "Du kan inte vara ensam om du tycker om personen du är ensam med.",
			"nl":    "Je kunt niet eenzaam zijn als je de persoon met wie je alleen bent graag mag.",
			"nb":    "Du kan ikke være ensom hvis du liker personen du er alene med.",
			"da":    "Du kan ikke være ensom, hvis du kan lide den person, du er alene med.",
			"fi":    "Et voi olla yksinäinen, jos pidät siitä ihmisestä, jonka kanssa olet yksin.",
		},
	},
	{
		ID:       "mindset-14",
		Author:   ptr("James Allen"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "As a man thinketh in his heart, so is he.",
			"en-GB": "As a man thinketh in his heart, so is he.",
			"pt-PT": "Tal como o homem pensa no seu coração, assim ele é.",
			"pt-BR": "Assim como o homem pensa em seu coração, ele é.",
			"es":    "Como un hombre piensa en su corazón, así es él.",
			"fr":    "Tel un homme pense en son cœur, tel il est.",
			"de":    "Wie ein Mensch in seinem Herzen denkt, so ist er.",
			"it":    "Come un uomo pensa nel suo cuore, così egli è.",
			"ja":    "人は心の中で思うとおりの者となる。",
			"zh":    "人心中怎样思量，他为人就是怎样。",
			"ko":    "사람은 마음속으로 생각하는 그대로의 존재다.",
			"hi":    "मनुष्य जैसा अपने हृदय में सोचता है, वैसा ही वह होता है।",
			"pl":    "Jak człowiek myśli w sercu swoim, takim jest.",
			"tr":    "İnsan yüreğinde nasıl düşünürse öyledir.",
			"uk":    "Якою людина є у думках свого серця, такою вона і є.",
			"sv":    "Såsom en människa tänker i sitt hjärta, sådan är hon.",
			"nl":    "Zoals een mens denkt in zijn hart, zo is hij.",
			"nb":    "Som et menneske tenker i sitt hjerte, slik er det.",
			"da":    "Som et menneske tænker i sit hjerte, sådan er det.",
			"fi":    "Millainen ihminen on sydämensä ajatuksissa, sellainen hän on.",
		},
	},
	{
		ID:       "mindset-15",
		Author:   ptr("Winston Churchill"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Attitude is a little thing that makes a big difference.",
			"en-GB": "Attitude is a little thing that makes a big difference.",
			"pt-PT": "A atitude é uma pequena coisa que faz uma grande diferença.",
			"pt-BR": "Atitude é uma pequena coisa que faz uma grande diferença.",
			"es":    "La actitud es una pequeña cosa que marca una gran diferencia.",
			"fr":    "L'attitude est une petite chose qui fait une grande différence.",
			"de":    "Die Einstellung ist eine kleine Sache, die einen großen Unterschied macht.",
			"it":    "L'atteggiamento è una piccola cosa che fa una grande differenza.",
			"ja":    "心構えは小さなものだが、大きな違いを生む。",
			"zh":    "态度是小事，却能带来大不同。",
			"ko":    "태도는 작은 것이지만 큰 차이를 만든다.",
			"hi":    "रवैया एक छोटी चीज़ है जो बड़ा फ़र्क़ डालती है।",
			"pl":    "Nastawienie to drobiazg, który robi wielką różnicę.",
			"tr":    "Tutum, büyük fark yaratan küçük bir şeydir.",
			"uk":    "Ставлення — дрібниця, яка робить велику різницю.",
			"sv":    "Attityd är en liten sak som gör stor skillnad.",
			"nl":    "Houding is een klein ding dat een groot verschil maakt.",
			"nb":    "Holdning er en liten ting som utgjør en stor forskjell.",
			"da":    "Indstilling er en lille ting, der gør en stor forskel.",
			"fi":    "Asenne on pieni asia, joka tekee suuren eron.",
		},
	},
	{
		ID:       "mindset-16",
		Author:   ptr("Epictetus"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "It's not what happens to you, but how you react to it that matters.",
			"en-GB": "It's not what happens to you, but how you react to it that matters.",
			"pt-PT": "Não é o que te acontece, mas como reages a isso que importa.",
			"pt-BR": "Não é o que acontece com você, mas como você reage a isso que importa.",
			"es":    "No es lo que te sucede, sino cómo reaccionas ante ello lo que importa.",
			"fr":    "Ce n'est pas ce qui vous arrive, mais la façon dont vous y réagissez qui compte.",
			"de":    "Es kommt nicht darauf an, was dir widerfährt, sondern wie du darauf reagierst.",
			"it":    "Non è ciò che ti accade che conta, ma come reagisci.",
			"ja":    "大事なのは何が起こるかではなく、それにどう応じるかである。",
			"zh":    "重要的不是发生在你身上的事，而是你如何应对。",
			"ko":    "중요한 것은 당신에게 일어나는 일이 아니라, 그것에 어떻게 반응하는가이다.",
			"hi":    "मायने यह नहीं रखता कि आपके साथ क्या होता है, बल्कि यह कि आप उस पर कैसी प्रतिक्रिया देते हैं।",
			"pl":    "Liczy się nie to, co ci się przydarza, lecz to, jak na to reagujesz.",
			"tr":    "Önemli olan başına ne geldiği değil, ona nasıl tepki verdiğindir.",
			"uk":    "Важливо не те, що з тобою стається, а те, як ти на це реагуєш.",
			"sv":    "Det är inte vad som händer dig som räknas, utan hur du reagerar på det.",
			"nl":    "Het gaat er niet om wat je overkomt, maar hoe je erop reageert.",
			"nb":    "Det er ikke det som skjer med deg som teller, men hvordan du reagerer på det.",
			"da":    "Det afgørende er ikke, hvad der sker dig, men hvordan du reagerer på det.",
			"fi":    "Ratkaisevaa ei ole se, mitä sinulle tapahtuu, vaan miten siihen reagoit.",
		},
	},
	{
		ID:       "mindset-17",
		Author:   ptr("Anait Nin"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "We don't see things as they are, we see them as we are.",
			"en-GB": "We don't see things as they are, we see them as we are.",
			"pt-PT": "Não vemos as coisas como elas são, vemos as coisas como nós somos.",
			"pt-BR": "Não vemos as coisas como elas são, vemos as coisas como nós somos.",
			"es":    "No vemos las cosas como son, las vemos como somos.",
			"fr":    "Nous ne voyons pas les choses telles qu'elles sont, nous les voyons tels que nous sommes.",
			"de":    "Wir sehen die Dinge nicht, wie sie sind. Wir sehen sie so, wie wir sind.",
			"it":    "Non vediamo le cose come sono, le vediamo come siamo noi.",
			"ja":    "私たちは物事をあるがままに見ているのではない。自分のあり方を通して見ているのだ。",
			"zh":    "我们看到的不是事物的本相，而是我们自己的模样。",
			"ko":    "우리는 사물을 있는 그대로 보지 않는다. 우리 자신의 모습대로 본다.",
			"hi":    "हम चीज़ों को वैसा नहीं देखते जैसी वे हैं, हम उन्हें वैसा देखते हैं जैसे हम हैं।",
			"pl":    "Nie widzimy rzeczy takimi, jakie są. Widzimy je takimi, jacy sami jesteśmy.",
			"tr":    "Şeyleri oldukları gibi değil, kendimiz gibi görürüz.",
			"uk":    "Ми бачимо речі не такими, якими вони є, а такими, якими є ми самі.",
			"sv":    "Vi ser inte tingen som de är, vi ser dem som vi är.",
			"nl":    "We zien de dingen niet zoals ze zijn, we zien ze zoals wij zijn.",
			"nb":    "Vi ser ikke tingene som de er, vi ser dem som vi er.",
			"da":    "Vi ser ikke tingene, som de er, vi ser dem, som vi er.",
			"fi":    "Emme näe asioita sellaisina kuin ne ovat, vaan sellaisina kuin me olemme.",
		},
	},
	{
		ID:       "mindset-18",
		Author:   ptr("Victor Frankl"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.",
			"en-GB": "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.",
			"pt-PT": "Entre o estímulo e a resposta há um espaço. Nesse espaço reside o nosso poder de escolher a nossa resposta. Na nossa resposta reside o nosso crescimento e a nossa liberdade.",
			"pt-BR": "Entre o estímulo e a resposta existe um espaço. Nesse espaço está o nosso poder de escolher nossa resposta. Em nossa resposta reside nosso crescimento e nossa liberdade.",
			"es":    "Entre el estímulo y la respuesta hay un espacio. En ese espacio reside nuestro poder para elegir nuestra respuesta. En nuestra respuesta reside nuestro crecimiento y nuestra libertad.",
			"fr":    "Entre le stimulus et la réponse, il y a un espace. Dans cet espace se trouve notre pouvoir de choisir notre réponse. Dans notre réponse résident notre croissance et notre liberté.",
			"de":    "Zwischen Reiz und Reaktion liegt ein Raum. In diesem Raum liegt unsere Macht, unsere Reaktion zu wählen. In unserer Reaktion liegen unser Wachstum und unsere Freiheit.",
			"it":    "Tra lo stimolo e la risposta c'è uno spazio. In quello spazio risiede il nostro potere di scegliere la risposta. Nella nostra risposta risiedono la nostra crescita e la nostra libertà.",
			"ja":    "刺激と反応の間には空間がある。その空間にこそ、反応を選ぶ私たちの力がある。そしてその反応の中に、私たちの成長と自由がある。",
			"zh":    "在刺激与回应之间存在一个空间。在那个空间里，我们拥有选择回应的力量。我们的成长与自由就蕴含在回应之中。",
			"ko":    "자극과 반응 사이에는 공간이 있다. 그 공간에 반응을 선택할 수 있는 우리의 힘이 있다. 그리고 그 반응 속에 우리의 성장과 자유가 있다.",
			"hi":    "उद्दीपन और प्रतिक्रिया के बीच एक जगह होती है। उस जगह में हमारी प्रतिक्रिया चुनने की शक्ति है। हमारी प्रतिक्रिया में ही हमारा विकास और हमारी स्वतंत्रता निहित है।",
			"pl":    "Między bodźcem a reakcją jest przestrzeń. W tej przestrzeni tkwi nasza moc wyboru reakcji. W naszej reakcji leży nasz rozwój i nasza wolność.",
			"tr":    "Uyaran ile tepki arasında bir boşluk vardır. O boşlukta tepkimizi seçme gücümüz yatar. Tepkimizde ise büyümemiz ve özgürlüğümüz saklıdır.",
			"uk":    "Між подразником і реакцією є простір. У цьому просторі — наша сила обирати відповідь. У нашій відповіді — наше зростання і наша свобода.",
			"sv":    "Mellan stimulus och respons finns ett mellanrum. I det mellanrummet ligger vår makt att välja vår respons. I vår respons ligger vår växt och vår frihet.",
			"nl":    "Tussen prikkel en reactie zit een ruimte. In die ruimte ligt onze kracht om onze reactie te kiezen. In onze reactie liggen onze groei en onze vrijheid.",
			"nb":    "Mellom stimulus og respons finnes et rom. I det rommet ligger vår makt til å velge vår respons. I vår respons ligger vår vekst og vår frihet.",
			"da":    "Mellem stimulus og respons er der et rum. I det rum ligger vores magt til at vælge vores respons. I vores respons ligger vores vækst og vores frihed.",
			"fi":    "Ärsykkeen ja reaktion välissä on tila. Siinä tilassa on voimamme valita reaktiomme. Reaktiossamme on kasvumme ja vapautemme.",
		},
	},
	{
		ID:       "mindset-19",
		Author:   ptr("Zig Ziglar"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Your attitude, not your aptitude, will determine your altitude.",
			"en-GB": "Your attitude, not your aptitude, will determine your altitude.",
			"pt-PT": "A tua atitude, e não a tua aptidão, determinará a tua altitude.",
			"pt-BR": "Sua atitude, e não sua aptidão, determinará sua altitude.",
			"es":    "Tu actitud, no tu aptitud, determinará tu altitud.",
			"fr":    "C'est votre attitude, et non votre aptitude, qui déterminera votre altitude.",
			"de":    "Deine Einstellung, nicht deine Begabung, bestimmt deine Flughöhe.",
			"it":    "Il tuo atteggiamento, non la tua attitudine, determinerà la tua altitudine.",
			"ja":    "高く飛べるかを決めるのは、才能ではなく心構えである。",
			"zh":    "决定你人生高度的，不是你的才能，而是你的态度。",
			"ko":    "당신의 높이를 결정하는 것은 재능이 아니라 태도다.",
			"hi":    "आपकी ऊँचाई आपका रवैया तय करेगा, आपकी योग्यता नहीं।",
			"pl":    "To twoje nastawienie, a nie uzdolnienia, wyznaczy twój pułap.",
			"tr":    "Yüksekliğini yeteneğin değil, tutumun belirler.",
			"uk":    "Твоє ставлення, а не здібності, визначить твою висоту.",
			"sv":    "Din attityd, inte din begåvning, avgör din höjd.",
			"nl":    "Je houding, niet je aanleg, bepaalt hoe hoog je komt.",
			"nb":    "Holdningen din, ikke evnene dine, avgjør hvor høyt du når.",
			"da":    "Din indstilling, ikke dine evner, afgør, hvor højt du når.",
			"fi":    "Asenteesi, ei lahjakkuutesi, määrää korkeutesi.",
		},
	},
	{
		ID:       "mindset-20",
		Author:   ptr("Lou Holtz"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
			"en-GB": "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
			"pt-PT": "Capacidade é o que és capaz de fazer. Motivação determina o que fazes. Atitude determina quão bem o fazes.",
			"pt-BR": "Habilidade é o que você é capaz de fazer. Motivação determina o que você faz. Atitude determina quão bem você o faz.",
			"es":    "La capacidad es lo que eres capaz de hacer. La motivación determina lo que haces. La actitud determina qué tan bien lo haces.",
			"fr":    "La capacité est ce que vous êtes capable de faire. La motivation détermine ce que vous faites. L'attitude détermine la qualité de votre travail.",
			"de":    "Fähigkeit ist das, was du tun kannst. Motivation bestimmt, was du tust. Einstellung bestimmt, wie gut du es tust.",
			"it":    "L'abilità è ciò che sei capace di fare. La motivazione determina ciò che fai. L'atteggiamento determina quanto bene lo fai.",
			"ja":    "能力とは、何ができるかである。モチベーションは、何をするかを決める。心構えは、それをどれだけうまくやるかを決める。",
			"zh":    "能力决定你能做什么，动机决定你做什么，态度决定你做得多好。",
			"ko":    "능력은 할 수 있는 일을 말한다. 동기는 무엇을 할지 결정한다. 태도는 그 일을 얼마나 잘할지 결정한다.",
			"hi":    "योग्यता वह है जो आप कर सकते हैं। प्रेरणा तय करती है कि आप क्या करते हैं। रवैया तय करता है कि आप उसे कितनी अच्छी तरह करते हैं।",
			"pl":    "Zdolności to to, co potrafisz zrobić. Motywacja decyduje o tym, co robisz. Nastawienie decyduje o tym, jak dobrze to robisz.",
			"tr":    "Yetenek, yapabildiğindir. Motivasyon, ne yapacağını belirler. Tutum, onu ne kadar iyi yapacağını belirler.",
			"uk":    "Здібності — це те, що ти можеш робити. Мотивація визначає, що ти робиш. Ставлення визначає, наскільки добре ти це робиш.",
			"sv":    "Förmåga är vad du kan göra. Motivation avgör vad du gör. Attityd avgör hur bra du gör det.",
			"nl":    "Vermogen is wat je kunt doen. Motivatie bepaalt wat je doet. Houding bepaalt hoe goed je het doet.",
			"nb":    "Evne er hva du er i stand til å gjøre. Motivasjon avgjør hva du gjør. Holdning avgjør hvor godt du gjør det.",
			"da":    "Evne er, hvad du kan gøre. Motivation afgør, hvad du gør. Indstilling afgør, hvor godt du gør det.",
			"fi":    "Kyky on sitä, mitä pystyt tekemään. Motivaatio määrää, mitä teet. Asenne määrää, kuinka hyvin sen teet.",
		},
	},
	{
		ID:       "mindset-21",
		Author:   ptr("Napoleon Hill"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Whatever the mind can conceive and believe, it can achieve.",
			"en-GB": "Whatever the mind can conceive and believe, it can achieve.",
			"pt-PT": "Tudo o que a mente consegue conceber e acreditar, consegue alcançar.",
			"pt-BR": "Tudo o que a mente pode conceber e acreditar, ela pode realizar.",
			"es":    "Todo lo que la mente puede concebir y creer, lo puede lograr.",
			"fr":    "Tout ce que l'esprit peut concevoir et croire, il peut le réaliser.",
			"de":    "Was der Geist sich vorstellen und woran er glauben kann, das kann er auch erreichen.",
			"it":    "Qualunque cosa la mente possa concepire e credere, può realizzarla.",
			"ja":    "心が思い描き、信じられることは、必ず実現できる。",
			"zh":    "凡是心灵能构想并相信的，皆能实现。",
			"ko":    "마음이 상상하고 믿을 수 있는 것은 무엇이든 이룰 수 있다.",
			"hi":    "मन जो भी सोच सकता है और जिस पर विश्वास कर सकता है, उसे वह हासिल कर सकता है।",
			"pl":    "Cokolwiek umysł potrafi wymyślić i w co potrafi uwierzyć, to potrafi osiągnąć.",
			"tr":    "Zihin neyi tasarlayıp neye inanabilirse, onu başarabilir.",
			"uk":    "Усе, що розум може уявити й у що може повірити, він може здійснити.",
			"sv":    "Vad sinnet kan föreställa sig och tro på kan det uppnå.",
			"nl":    "Wat de geest kan bedenken en geloven, kan hij bereiken.",
			"nb":    "Det sinnet kan unnfange og tro på, kan det oppnå.",
			"da":    "Hvad sindet kan forestille sig og tro på, kan det opnå.",
			"fi":    "Minkä mieli voi käsittää ja mihin se voi uskoa, sen se voi saavuttaa.",
		},
	},
	{
		ID:       "mindset-22",
		Author:   ptr("John Milton"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
			"en-GB": "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
			"pt-PT": "A mente é o seu próprio lugar, e em si mesma pode fazer de um inferno um céu, de um céu um inferno.",
			"pt-BR": "A mente é seu próprio lugar e, em si mesma, pode fazer do inferno um céu, e do céu um inferno.",
			"es":    "La mente es su propio lugar, y en sí misma puede hacer un cielo del infierno, un infierno del cielo.",
			"fr":    "L'esprit est sa propre demeure, et peut en soi faire un ciel de l'enfer, un enfer du ciel.",
			"de":    "Der Geist ist sein eigener Ort und kann in sich selbst den Himmel zur Hölle und die Hölle zum Himmel machen.",
			"it":    "La mente è un luogo a sé, e in sé può fare del paradiso un inferno e dell'inferno un paradiso.",
			"ja":    "心はそれ自体がひとつの世界であり、地獄を天国に変え、天国を地獄に変えることができる。",
			"zh":    "心灵自成一方天地，可以把地狱变成天堂，也可以把天堂变成地狱。",
			"ko":    "마음은 그 자체로 하나의 세계이며, 지옥을 천국으로도, 천국을 지옥으로도 만들 수 있다.",
			"hi":    "मन अपनी ही एक दुनिया है, और वह नरक को स्वर्ग और स्वर्ग को नरक बना सकता है।",
			"pl":    "Umysł jest swoim własnym miejscem i sam w sobie może uczynić niebo z piekła, a piekło z nieba.",
			"tr":    "Zihin kendi başına bir yerdir; cehennemi cennete, cenneti cehenneme çevirebilir.",
			"uk":    "Розум — це власний світ, і сам у собі він може зробити з пекла рай, а з раю пекло.",
			"sv":    "Sinnet är sin egen plats och kan i sig självt göra ett himmelrike av helvetet, ett helvete av himmelriket.",
			"nl":    "De geest is zijn eigen plek en kan in zichzelf van de hel een hemel maken, en van de hemel een hel.",
			"nb":    "Sinnet er sitt eget sted, og kan i seg selv gjøre en himmel av helvete, et helvete av himmelen.",
			"da":    "Sindet er sit eget sted og kan i sig selv gøre et himmerige af helvede, et helvede af himmerige.",
			"fi":    "Mieli on oma maailmansa, ja se voi itsessään tehdä helvetistä taivaan ja taivaasta helvetin.",
		},
	},
	{
		ID:       "mindset-23",
		Author:   ptr("Eckhart Tolle"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The primary cause of unhappiness is never the situation but your thoughts about it.",
			"en-GB": "The primary cause of unhappiness is never the situation but your thoughts about it.",
			"pt-PT": "A causa primária da infelicidade nunca é a situação, mas os teus pensamentos sobre ela.",
			"pt-BR": "A causa primária da infelicidade nunca é a situação, mas os seus pensamentos sobre ela.",
			"es":    "La causa principal de la infelicidad nunca es la situación, sino tus pensamientos al respecto.",
			"fr":    "La cause première du malheur n'est jamais la situation, mais vos pensées à son sujet.",
			"de":    "Die Hauptursache des Unglücklichseins ist nie die Situation selbst, sondern deine Gedanken darüber.",
			"it":    "La causa principale dell'infelicità non è mai la situazione, ma i tuoi pensieri su di essa.",
			"ja":    "不幸の第一の原因は、決して状況そのものではなく、状況についてのあなたの思考である。",
			"zh":    "不快乐的根源从来不是处境本身，而是你对处境的想法。",
			"ko":    "불행의 근본 원인은 결코 상황 자체가 아니라, 그 상황에 대한 당신의 생각이다.",
			"hi":    "दुख का मुख्य कारण कभी परिस्थिति नहीं होती, बल्कि उसके बारे में आपके विचार होते हैं।",
			"pl":    "Główną przyczyną nieszczęścia nigdy nie jest sytuacja, lecz twoje myśli na jej temat.",
			"tr":    "Mutsuzluğun asıl nedeni asla durumun kendisi değil, o durum hakkındaki düşüncelerindir.",
			"uk":    "Головна причина нещастя — ніколи не сама ситуація, а твої думки про неї.",
			"sv":    "Den främsta orsaken till olycka är aldrig situationen utan dina tankar om den.",
			"nl":    "De belangrijkste oorzaak van ongeluk is nooit de situatie, maar je gedachten erover.",
			"nb":    "Den viktigste årsaken til ulykkelighet er aldri situasjonen, men tankene dine om den.",
			"da":    "Den primære årsag til ulykke er aldrig situationen, men dine tanker om den.",
			"fi":    "Onnettomuuden ensisijainen syy ei koskaan ole tilanne, vaan ajatuksesi siitä.",
		},
	},
	{
		ID:       "mindset-24",
		Author:   ptr("William Hazlitt"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "A consistent man believes in destiny, a capricious man in chance.",
			"en-GB": "A consistent man believes in destiny, a capricious man in chance.",
			"pt-PT": "Um homem consistente acredita no destino, um homem caprichoso no acaso.",
			"pt-BR": "Um homem consistente acredita no destino, um homem caprichoso no acaso.",
			"es":    "Un hombre coherente cree en el destino, un hombre caprichoso en el azar.",
			"fr":    "Un homme conséquent croit au destin, un homme capricieux au hasard.",
			"de":    "Ein beständiger Mensch glaubt an das Schicksal, ein launischer an den Zufall.",
			"it":    "L'uomo costante crede nel destino, quello capriccioso nel caso.",
			"ja":    "一貫した人は運命を信じ、気まぐれな人は偶然を信じる。",
			"zh":    "坚定的人相信命运，反复无常的人相信运气。",
			"ko":    "한결같은 사람은 운명을 믿고, 변덕스러운 사람은 우연을 믿는다.",
			"hi":    "स्थिर व्यक्ति नियति में विश्वास करता है, चंचल व्यक्ति संयोग में।",
			"pl":    "Człowiek stały wierzy w przeznaczenie, kapryśny — w przypadek.",
			"tr":    "Tutarlı insan kadere inanır, kaprisli insan tesadüfe.",
			"uk":    "Послідовна людина вірить у долю, примхлива — у випадок.",
			"sv":    "En beständig människa tror på ödet, en nyckfull på slumpen.",
			"nl":    "Een standvastig mens gelooft in het lot, een grillig mens in het toeval.",
			"nb":    "Et bestandig menneske tror på skjebnen, et lunefullt på tilfeldigheten.",
			"da":    "Et bestandigt menneske tror på skæbnen, et lunefuldt på tilfældet.",
			"fi":    "Johdonmukainen ihminen uskoo kohtaloon, oikukas sattumaan.",
		},
	},
	{
		ID:       "mindset-25",
		Author:   ptr("Albert Schweitzer"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
			"en-GB": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
			"pt-PT": "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se amares o que fazes, serás bem-sucedido.",
			"pt-BR": "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que faz, terá sucesso.",
			"es":    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.",
			"fr":    "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez.",
			"de":    "Erfolg ist nicht der Schlüssel zum Glück. Glück ist der Schlüssel zum Erfolg. Wenn du liebst, was du tust, wirst du erfolgreich sein.",
			"it":    "Il successo non è la chiave della felicità. La felicità è la chiave del successo. Se ami ciò che fai, avrai successo.",
			"ja":    "成功は幸福の鍵ではない。幸福が成功の鍵である。自分のしていることを愛していれば、成功できる。",
			"zh":    "成功不是幸福的钥匙，幸福才是成功的钥匙。如果你热爱自己所做的事，你就会成功。",
			"ko":    "성공이 행복의 열쇠가 아니라, 행복이 성공의 열쇠다. 하는 일을 사랑한다면 성공할 것이다.",
			"hi":    "सफलता ख़ुशी की कुंजी नहीं है। ख़ुशी सफलता की कुंजी है। अगर आप अपने काम से प्यार करते हैं, तो आप सफल होंगे।",
			"pl":    "Sukces nie jest kluczem do szczęścia. To szczęście jest kluczem do sukcesu. Jeśli kochasz to, co robisz, osiągniesz sukces.",
			"tr":    "Başarı mutluluğun anahtarı değildir. Mutluluk başarının anahtarıdır. Yaptığın işi seviyorsan başarılı olursun.",
			"uk":    "Успіх — не ключ до щастя. Щастя — ключ до успіху. Якщо любиш те, що робиш, ти досягнеш успіху.",
			"sv":    "Framgång är inte nyckeln till lycka. Lycka är nyckeln till framgång. Om du älskar det du gör kommer du att lyckas.",
			"nl":    "Succes is niet de sleutel tot geluk. Geluk is de sleutel tot succes. Als je houdt van wat je doet, zul je slagen.",
			"nb":    "Suksess er ikke nøkkelen til lykke. Lykke er nøkkelen til suksess. Elsker du det du gjør, vil du lykkes.",
			"da":    "Succes er ikke nøglen til lykke. Lykke er nøglen til succes. Hvis du elsker det, du laver, vil du få succes.",
			"fi":    "Menestys ei ole onnen avain. Onni on menestyksen avain. Jos rakastat sitä mitä teet, menestyt.",
		},
	},
	{
		ID:       "mindset-26",
		Author:   ptr("Jean-Paul Sartre"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Freedom is what you do with what's been done to you.",
			"en-GB": "Freedom is what you do with what's been done to you.",
			"pt-PT": "Liberdade é o que fazes com o que te fizeram.",
			"pt-BR": "Liberdade é o que você faz com o que fizeram a você.",
			"es":    "La libertad es lo que haces con lo que te han hecho.",
			"fr":    "La liberté est ce que vous faites de ce qu'on vous a fait.",
			"de":    "Freiheit ist das, was du aus dem machst, was man dir angetan hat.",
			"it":    "La libertà è ciò che fai con quello che ti è stato fatto.",
			"ja":    "自由とは、自分がされたことをどう生かすかである。",
			"zh":    "自由，就是你如何面对别人加诸于你的一切。",
			"ko":    "자유란 당신에게 가해진 일로 당신이 무엇을 하느냐이다.",
			"hi":    "स्वतंत्रता वह है जो आप उसके साथ करते हैं, जो आपके साथ किया गया है।",
			"pl":    "Wolność to to, co robisz z tym, co ci uczyniono.",
			"tr":    "Özgürlük, sana yapılanlarla senin ne yaptığındır.",
			"uk":    "Свобода — це те, що ти робиш із тим, що зробили з тобою.",
			"sv":    "Frihet är vad du gör med det som har gjorts mot dig.",
			"nl":    "Vrijheid is wat je doet met wat je is aangedaan.",
			"nb":    "Frihet er hva du gjør med det som er blitt gjort mot deg.",
			"da":    "Frihed er, hvad du gør med det, der er blevet gjort mod dig.",
			"fi":    "Vapaus on sitä, mitä teet sillä, mitä sinulle on tehty.",
		},
	},
	{
		ID:       "mindset-27",
		Author:   ptr("William Shakespeare"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "There is nothing either good or bad, but thinking makes it so.",
			"en-GB": "There is nothing either good or bad, but thinking makes it so.",
			"pt-PT": "Não há nada bom nem mau, mas o pensamento torna-o assim.",
			"pt-BR": "Nada é bom ou mau, mas o pensamento o torna assim.",
			"es":    "Nada es bueno ni malo, pero el pensamiento lo hace así.",
			"fr":    "Rien n'est bon ou mauvais en soi, c'est la pensée qui le rend tel.",
			"de":    "Nichts ist an sich gut oder schlecht; das Denken macht es erst dazu.",
			"it":    "Non c'è nulla di buono o di cattivo, è il pensiero che lo rende tale.",
			"ja":    "物事に良いも悪いもない。考え方がそれを決めるのだ。",
			"zh":    "事无好坏，思想使然。",
			"ko":    "본래 좋고 나쁜 것은 없다. 생각이 그렇게 만들 뿐이다.",
			"hi":    "कोई चीज़ अपने आप में अच्छी या बुरी नहीं होती, सोच उसे वैसा बना देती है।",
			"pl":    "Nic nie jest samo w sobie dobre ani złe — to myślenie czyni je takim.",
			"tr":    "Hiçbir şey kendi başına iyi ya da kötü değildir; onu öyle yapan düşüncedir.",
			"uk":    "Немає нічого ані доброго, ані поганого — таким його робить наше мислення.",
			"sv":    "Ingenting är i sig gott eller ont, men tanken gör det så.",
			"nl":    "Niets is op zichzelf goed of slecht; het denken maakt het zo.",
			"nb":    "Ingenting er i seg selv godt eller ondt, men tanken gjør det slik.",
			"da":    "Intet er i sig selv godt eller ondt, men tanken gør det sådan.",
			"fi":    "Mikään ei ole itsessään hyvää tai pahaa; ajattelu tekee sen sellaiseksi.",
		},
	},
	{
		ID:       "mindset-28",
		Author:   ptr("Charles Glassman"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Believing in yourself is not for you; it’s so that others can have a reason to believe in you.",
			"en-GB": "Believing in yourself is not for you; it’s so that others can have a reason to believe in you.",
			"pt-PT": "Acreditar em ti próprio não é para ti; é para que os outros possam ter uma razão para acreditar em ti.",
			"pt-BR": "Acreditar em si mesmo não é para você; é para que os outros tenham um motivo para acreditar em você.",
			"es":    "Creer en ti mismo no es para ti; es para que los demás tengan una razón para creer en ti.",
			"fr":    "Croire en soi n'est pas pour soi ; c'est pour que les autres aient une raison de croire en vous.",
			"de":    "An dich selbst zu glauben ist nicht für dich; es ist dafür da, dass andere einen Grund haben, an dich zu glauben.",
			"it":    "Credere in te stesso non è per te; è perché gli altri abbiano una ragione per credere in te.",
			"ja":    "自分を信じることは、自分のためではない。他の人があなたを信じる理由を持てるようにするためだ。",
			"zh":    "相信自己不是为了你自己，而是让别人有理由相信你。",
			"ko":    "자신을 믿는 것은 자신을 위해서가 아니다. 다른 사람들이 당신을 믿을 이유를 갖게 하기 위해서다.",
			"hi":    "ख़ुद पर विश्वास करना आपके लिए नहीं है; यह इसलिए है ताकि दूसरों के पास आप पर विश्वास करने की एक वजह हो।",
			"pl":    "Wiara w siebie nie jest dla ciebie; jest po to, by inni mieli powód, żeby w ciebie uwierzyć.",
			"tr":    "Kendine inanmak senin için değildir; başkalarının sana inanmak için bir nedeni olsun diyedir.",
			"uk":    "Віра в себе — не для тебе; вона для того, щоб інші мали причину повірити в тебе.",
			"sv":    "Att tro på dig själv är inte för din skull; det är för att andra ska ha en anledning att tro på dig.",
			"nl":    "In jezelf geloven is niet voor jou; het is zodat anderen een reden hebben om in jou te geloven.",
			"nb":    "Å tro på deg selv er ikke for din skyld; det er for at andre skal ha en grunn til å tro på deg.",
			"da":    "At tro på dig selv er ikke for din skyld; det er, for at andre kan have en grund til at tro på dig.",
			"fi":    "Itseensä uskominen ei ole sinua varten; se on sitä varten, että muilla on syy uskoa sinuun.",
		},
	},
	{
		ID:       "mindset-29",
		Author:   ptr("Unknown"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
			"en-GB": "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
			"pt-PT": "A tua mente é uma coisa poderosa. Quando a encheres com pensamentos positivos, a tua vida começará a mudar.",
			"pt-BR": "Sua mente é poderosa. Quando você a preenche com pensamentos positivos, sua vida começa a mudar.",
			"es":    "Tu mente es algo poderoso. Cuando la llenas de pensamientos positivos, tu vida empezará a cambiar.",
			"fr":    "Votre esprit est une chose puissante. Quand vous le remplissez de pensées positives, votre vie commencera à changer.",
			"de":    "Dein Geist ist ein mächtiges Werkzeug. Wenn du ihn mit positiven Gedanken füllst, beginnt dein Leben sich zu verändern.",
			"it":    "La tua mente è una cosa potente. Quando la riempi di pensieri positivi, la tua vita comincerà a cambiare.",
			"ja":    "心は強力な力を持っている。前向きな思考で満たせば、人生は変わり始める。",
			"zh":    "你的头脑拥有强大的力量。当你用积极的思想填满它，你的生活就会开始改变。",
			"ko":    "당신의 마음은 강력한 힘을 지녔다. 긍정적인 생각으로 채우면 삶이 달라지기 시작한다.",
			"hi":    "आपका मन एक शक्तिशाली चीज़ है। जब आप इसे सकारात्मक विचारों से भरते हैं, तो आपका जीवन बदलने लगता है।",
			"pl":    "Twój umysł to potężne narzędzie. Gdy wypełnisz go pozytywnymi myślami, twoje życie zacznie się zmieniać.",
			"tr":    "Zihnin güçlü bir şeydir. Onu olumlu düşüncelerle doldurduğunda hayatın değişmeye başlar.",
			"uk":    "Твій розум — могутня сила. Коли наповниш його позитивними думками, життя почне змінюватися.",
			"sv":    "Ditt sinne är mäktigt. När du fyller det med positiva tankar börjar ditt liv att förändras.",
			"nl":    "Je geest is iets krachtigs. Als je hem vult met positieve gedachten, zal je leven beginnen te veranderen.",
			"nb":    "Sinnet ditt er mektig. Når du fyller det med positive tanker, begynner livet ditt å endre seg.",
			"da":    "Dit sind er noget mægtigt. Når du fylder det med positive tanker, begynder dit liv at forandre sig.",
			"fi":    "Mielesi on voimakas. Kun täytät sen myönteisillä ajatuksilla, elämäsi alkaa muuttua.",
		},
	},
	{
		ID:       "mindset-30",
		Author:   ptr("Robert Collier"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Success is the sum of small efforts, repeated day in and day out.",
			"en-GB": "Success is the sum of small efforts, repeated day in and day out.",
			"pt-PT": "O sucesso é a soma de pequenos esforços, repetidos dia após dia.",
			"pt-BR": "O sucesso é a soma de pequenos esforços, repetidos dia após dia.",
			"es":    "El éxito es la suma de pequeños esfuerzos, repetidos día tras día.",
			"fr":    "Le succès est la somme de petits efforts, répétés jour après jour.",
			"de":    "Erfolg ist die Summe kleiner Anstrengungen, Tag für Tag wiederholt.",
			"it":    "Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.",
			"ja":    "成功とは、日々繰り返される小さな努力の積み重ねである。",
			"zh":    "成功是日复一日重复的小小努力的总和。",
			"ko":    "성공은 매일매일 반복되는 작은 노력들의 합이다.",
			"hi":    "सफलता छोटे-छोटे प्रयासों का योग है, जो दिन-प्रतिदिन दोहराए जाते हैं।",
			"pl":    "Sukces to suma małych wysiłków powtarzanych dzień po dniu.",
			"tr":    "Başarı, her gün tekrarlanan küçük çabaların toplamıdır.",
			"uk":    "Успіх — це сума малих зусиль, повторюваних день у день.",
			"sv":    "Framgång är summan av små ansträngningar som upprepas dag efter dag.",
			"nl":    "Succes is de som van kleine inspanningen, dag in dag uit herhaald.",
			"nb":    "Suksess er summen av små anstrengelser, gjentatt dag etter dag.",
			"da":    "Succes er summen af små anstrengelser gentaget dag efter dag.",
			"fi":    "Menestys on pienten ponnistelujen summa, päivästä toiseen toistettuna.",
		},
	},
	{
		ID:       "mindset-31",
		Author:   ptr("Buddha"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The mind is everything. What you think you become.",
			"en-GB": "The mind is everything. What you think you become.",
			"pt-PT": "A mente é tudo. O que pensas, tu tornas-te.",
			"pt-BR": "A mente é tudo. O que você pensa, você se torna.",
			"es":    "La mente lo es todo. En lo que piensas te conviertes.",
			"fr":    "L'esprit est tout. Ce que vous pensez, vous le devenez.",
			"de":    "Der Geist ist alles. Was du denkst, das wirst du.",
			"it":    "La mente è tutto. Ciò che pensi, diventi.",
			"ja":    "心がすべてである。思った通りの人間になる。",
			"zh":    "心即一切。你想什么，就会成为什么。",
			"ko":    "마음이 전부다. 생각하는 대로 이루어진다.",
			"hi":    "मन ही सब कुछ है। जो सोचते हो, वही बन जाते हो।",
			"pl":    "Umysł jest wszystkim. Stajesz się tym, o czym myślisz.",
			"tr":    "Zihin her şeydir. Ne düşünürsen o olursun.",
			"uk":    "Розум — це все. Ким себе мислиш, тим і стаєш.",
			"sv":    "Sinnet är allt. Vad du tänker blir du.",
			"nl":    "De geest is alles. Wat je denkt, word je.",
			"nb":    "Sinnet er alt. Det du tenker, blir du.",
			"da":    "Sindet er alt. Hvad du tænker, bliver du.",
			"fi":    "Mieli on kaikki. Siitä mitä ajattelet, tulet.",
		},
	},
	{
		ID:       "mindset-32",
		Author:   ptr("Henry Ford"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Whether you think you can or you think you can't, you're right.",
			"en-GB": "Whether you think you can or you think you can't, you're right.",
			"pt-PT": "Quer penses que podes ou que não podes, estás certo.",
			"pt-BR": "Se você pensa que pode ou que não pode, você está certo.",
			"es":    "Tanto si piensas que puedes como si piensas que no puedes, estás en lo cierto.",
			"fr":    "Que vous pensiez pouvoir ou ne pas pouvoir, vous avez raison.",
			"de":    "Ob du denkst, du kannst es, oder du kannst es nicht: Du wirst auf jeden Fall recht behalten.",
			"it":    "Che tu creda di farcela o di non farcela, avrai comunque ragione.",
			"ja":    "できると思うにせよ、できないと思うにせよ、あなたは正しい。",
			"zh":    "无论你认为自己行还是不行，你都是对的。",
			"ko":    "할 수 있다고 생각하든 할 수 없다고 생각하든, 당신 생각이 옳다.",
			"hi":    "चाहे आप सोचें कि आप कर सकते हैं, या सोचें कि नहीं कर सकते—दोनों ही सूरत में आप सही हैं।",
			"pl":    "Niezależnie od tego, czy myślisz, że potrafisz, czy że nie potrafisz — masz rację.",
			"tr":    "Yapabileceğini de düşünsen, yapamayacağını da düşünsen haklısın.",
			"uk":    "Думаєш, що зможеш, чи думаєш, що ні, — у будь-якому разі ти маєш рацію.",
			"sv":    "Vare sig du tror att du kan eller att du inte kan, har du rätt.",
			"nl":    "Of je nu denkt dat je het kunt of dat je het niet kunt, je hebt gelijk.",
			"nb":    "Enten du tror du kan eller tror du ikke kan, har du rett.",
			"da":    "Uanset om du tror, du kan, eller du tror, du ikke kan, har du ret.",
			"fi":    "Ajattelitpa että pystyt tai että et pysty — olet oikeassa.",
		},
	},
	{
		ID:       "mindset-33",
		Author:   ptr("Theodore Roosevelt"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Believe you can and you're halfway there.",
			"en-GB": "Believe you can and you're halfway there.",
			"pt-PT": "Acredita que podes e estás a meio caminho.",
			"pt-BR": "Acredite que você pode e você já está no meio do caminho.",
			"es":    "Cree que puedes y estarás a mitad de camino.",
			"fr":    "Croyez que vous le pouvez et vous êtes à mi-chemin.",
			"de":    "Glaube, dass du es kannst, und du bist schon halb am Ziel.",
			"it":    "Credi di potercela fare e sei già a metà strada.",
			"ja":    "できると信じれば、もう半分は達成したようなものだ。",
			"zh":    "相信自己能行，你就已经成功了一半。",
			"ko":    "할 수 있다고 믿으면 이미 절반은 이룬 것이다.",
			"hi":    "विश्वास करो कि तुम कर सकते हो, और तुम आधा रास्ता पार कर चुके हो।",
			"pl":    "Uwierz, że potrafisz, a jesteś już w połowie drogi.",
			"tr":    "Yapabileceğine inan, yolun yarısını gitmişsin demektir.",
			"uk":    "Повір, що зможеш, — і ти вже на півдорозі.",
			"sv":    "Tro att du kan, så är du redan halvvägs.",
			"nl":    "Geloof dat je het kunt en je bent al halverwege.",
			"nb":    "Tro at du kan, så er du allerede halvveis.",
			"da":    "Tro på, at du kan, så er du allerede halvvejs.",
			"fi":    "Usko että pystyt, niin olet jo puolivälissä.",
		},
	},
	{
		ID:       "mindset-34",
		Author:   ptr("Zig Ziglar"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Your attitude, not your aptitude, will determine your altitude.",
			"en-GB": "Your attitude, not your aptitude, will determine your altitude.",
			"pt-PT": "A tua atitude, e não a tua aptidão, determinará a tua altitude.",
			"pt-BR": "Sua atitude, não sua aptidão, determinará sua altitude.",
			"es":    "Tu actitud, no tu aptitud, determinará tu altitud.",
			"fr":    "Votre attitude, et non votre aptitude, déterminera votre altitude.",
			"de":    "Deine Einstellung, nicht deine Begabung, bestimmt deine Flughöhe.",
			"it":    "Il tuo atteggiamento, non la tua attitudine, determinerà la tua altitudine.",
			"ja":    "高く飛べるかを決めるのは、才能ではなく心構えである。",
			"zh":    "决定你人生高度的，不是你的才能，而是你的态度。",
			"ko":    "당신의 높이를 결정하는 것은 재능이 아니라 태도다.",
			"hi":    "आपकी ऊँचाई आपका रवैया तय करेगा, आपकी योग्यता नहीं।",
			"pl":    "To twoje nastawienie, a nie uzdolnienia, wyznaczy twój pułap.",
			"tr":    "Yüksekliğini yeteneğin değil, tutumun belirler.",
			"uk":    "Твоє ставлення, а не здібності, визначить твою висоту.",
			"sv":    "Din attityd, inte din begåvning, avgör din höjd.",
			"nl":    "Je houding, niet je aanleg, bepaalt hoe hoog je komt.",
			"nb":    "Holdningen din, ikke evnene dine, avgjør hvor høyt du når.",
			"da":    "Din indstilling, ikke dine evner, afgør, hvor højt du når.",
			"fi":    "Asenteesi, ei lahjakkuutesi, määrää korkeutesi.",
		},
	},
	{
		ID:       "mindset-35",
		Author:   ptr("Norman Vincent Peale"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Change your thoughts and you change your world.",
			"en-GB": "Change your thoughts and you change your world.",
			"pt-PT": "Muda os teus pensamentos e mudas o teu mundo.",
			"pt-BR": "Mude seus pensamentos e você mudará seu mundo.",
			"es":    "Cambia tus pensamientos y cambiarás tu mundo.",
			"fr":    "Changez vos pensées et vous changerez votre monde.",
			"de":    "Ändere deine Gedanken, und du änderst deine Welt.",
			"it":    "Cambia i tuoi pensieri e cambierai il tuo mondo.",
			"ja":    "考えを変えれば、世界が変わる。",
			"zh":    "改变你的思想，就能改变你的世界。",
			"ko":    "생각을 바꾸면 세상이 바뀐다.",
			"hi":    "अपने विचार बदलो और तुम्हारी दुनिया बदल जाएगी।",
			"pl":    "Zmień swoje myśli, a zmienisz swój świat.",
			"tr":    "Düşüncelerini değiştir, dünyan değişsin.",
			"uk":    "Зміни свої думки — і зміниш свій світ.",
			"sv":    "Förändra dina tankar så förändrar du din värld.",
			"nl":    "Verander je gedachten en je verandert je wereld.",
			"nb":    "Endre tankene dine, og du endrer verden din.",
			"da":    "Skift dine tanker, og du forandrer din verden.",
			"fi":    "Muuta ajatuksesi, niin muutat maailmasi.",
		},
	},
	{
		ID:       "mindset-36",
		Author:   ptr("Aristotle"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Happiness depends upon ourselves.",
			"en-GB": "Happiness depends upon ourselves.",
			"pt-PT": "A felicidade depende de nós mesmos.",
			"pt-BR": "A felicidade depende de nós mesmos.",
			"es":    "La felicidad depende de nosotros mismos.",
			"fr":    "Le bonheur dépend de nous-mêmes.",
			"de":    "Glück hängt von uns selbst ab.",
			"it":    "La felicità dipende da noi stessi.",
			"ja":    "幸福は自分自身にかかっている。",
			"zh":    "幸福取决于我们自己。",
			"ko":    "행복은 우리 자신에게 달려 있다.",
			"hi":    "ख़ुशी हम पर ही निर्भर करती है।",
			"pl":    "Szczęście zależy od nas samych.",
			"tr":    "Mutluluk bize bağlıdır.",
			"uk":    "Щастя залежить від нас самих.",
			"sv":    "Lyckan beror på oss själva.",
			"nl":    "Geluk hangt van onszelf af.",
			"nb":    "Lykken avhenger av oss selv.",
			"da":    "Lykken afhænger af os selv.",
			"fi":    "Onnellisuus riippuu meistä itsestämme.",
		},
	},
	{
		ID:       "mindset-37",
		Author:   ptr("Franklin D. Roosevelt"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The only limit to our realization of tomorrow will be our doubts of today.",
			"en-GB": "The only limit to our realization of tomorrow will be our doubts of today.",
			"pt-PT": "O único limite para a nossa realização de amanhã serão as nossas dúvidas de hoje.",
			"pt-BR": "O único limite para a nossa realização de amanhã serão as nossas dúvidas de hoje.",
			"es":    "El único límite para nuestra realización del mañana serán nuestras dudas de hoy.",
			"fr":    "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui.",
			"de":    "Die einzige Grenze für die Verwirklichung unseres Morgen sind unsere Zweifel von heute.",
			"it":    "L'unico limite alla realizzazione del nostro domani saranno i nostri dubbi di oggi.",
			"ja":    "明日の実現を阻む唯一の限界は、今日の私たちの疑いである。",
			"zh":    "实现明天理想的唯一障碍，是我们今天的疑虑。",
			"ko":    "내일의 실현을 가로막는 유일한 한계는 오늘 우리가 품는 의심이다.",
			"hi":    "हमारे कल की प्राप्ति की एकमात्र सीमा आज के हमारे संदेह होंगे।",
			"pl":    "Jedynym ograniczeniem dla naszego jutra będą nasze dzisiejsze wątpliwości.",
			"tr":    "Yarınımızı gerçekleştirmenin tek engeli, bugünkü şüphelerimiz olacaktır.",
			"uk":    "Єдина межа для здійснення нашого завтра — наші сьогоднішні сумніви.",
			"sv":    "Den enda gränsen för vårt förverkligande av morgondagen är våra tvivel i dag.",
			"nl":    "De enige grens aan de verwezenlijking van morgen zijn onze twijfels van vandaag.",
			"nb":    "Den eneste grensen for virkeliggjøringen av morgendagen er tvilen vår i dag.",
			"da":    "Den eneste grænse for virkeliggørelsen af vores i morgen er vores tvivl i dag.",
			"fi":    "Ainoa raja huomisemme toteutumiselle ovat tämän päivän epäilyksemme.",
		},
	},
	{
		ID:       "mindset-38",
		Author:   ptr("Confucius"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Everything has beauty, but not everyone sees it.",
			"en-GB": "Everything has beauty, but not everyone sees it.",
			"pt-PT": "Tudo tem beleza, mas nem todos a veem.",
			"pt-BR": "Tudo tem beleza, mas nem todos a veem.",
			"es":    "Todo tiene belleza, pero no todo el mundo la ve.",
			"fr":    "Tout a sa beauté, mais tout le monde ne la voit pas.",
			"de":    "Alles hat Schönheit, aber nicht jeder sieht sie.",
			"it":    "Ogni cosa ha la sua bellezza, ma non tutti la vedono.",
			"ja":    "すべてのものに美しさはあるが、誰もがそれを見られるわけではない。",
			"zh":    "万物皆有美，但不是人人都能看见。",
			"ko":    "모든 것에는 아름다움이 있지만, 모두가 그것을 보는 것은 아니다.",
			"hi":    "हर चीज़ में सौंदर्य है, पर हर कोई उसे देख नहीं पाता।",
			"pl":    "Wszystko ma w sobie piękno, ale nie każdy je dostrzega.",
			"tr":    "Her şeyde güzellik vardır ama herkes onu göremez.",
			"uk":    "Усе має красу, але не кожен її бачить.",
			"sv":    "Allt har skönhet, men alla ser den inte.",
			"nl":    "Alles heeft schoonheid, maar niet iedereen ziet haar.",
			"nb":    "Alt har skjønnhet, men ikke alle ser den.",
			"da":    "Alt har skønhed, men ikke alle ser den.",
			"fi":    "Kaikessa on kauneutta, mutta kaikki eivät näe sitä.",
		},
	},
	{
		ID:       "mindset-39",
		Author:   ptr("William James"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "The greatest discovery of any generation is that a human can alter his life by altering his attitude.",
			"en-GB": "The greatest discovery of any generation is that a human can alter his life by altering his attitude.",
			"pt-PT": "A maior descoberta de qualquer geração é que um ser humano pode alterar a sua vida alterando a sua atitude.",
			"pt-BR": "A maior descoberta de qualquer geração é que um ser humano pode alterar sua vida alterando sua atitude.",
			"es":    "El mayor descubrimiento de cualquier generación es que un ser humano puede alterar su vida alterando su actitud.",
			"fr":    "La plus grande découverte de toute génération est qu'um être humain peut modifier sa vie en modifiant son attitude.",
			"de":    "Die größte Entdeckung jeder Generation ist, dass ein Mensch sein Leben ändern kann, indem er seine Einstellung ändert.",
			"it":    "La più grande scoperta di ogni generazione è che un essere umano può cambiare la propria vita cambiando il proprio atteggiamento.",
			"ja":    "あらゆる世代の最大の発見は、人は心の持ち方を変えることで人生を変えられるということだ。",
			"zh":    "每一代人最伟大的发现是：人可以通过改变态度来改变人生。",
			"ko":    "어느 세대든 가장 위대한 발견은 인간이 태도를 바꿈으로써 인생을 바꿀 수 있다는 것이다.",
			"hi":    "हर पीढ़ी की सबसे बड़ी खोज यह है कि इंसान अपना नज़रिया बदलकर अपना जीवन बदल सकता है।",
			"pl":    "Największym odkryciem każdego pokolenia jest to, że człowiek może odmienić swoje życie, zmieniając swoje nastawienie.",
			"tr":    "Her kuşağın en büyük keşfi, insanın tutumunu değiştirerek hayatını değiştirebileceğidir.",
			"uk":    "Найбільше відкриття будь-якого покоління — те, що людина може змінити своє життя, змінивши своє ставлення.",
			"sv":    "Varje generations största upptäckt är att en människa kan förändra sitt liv genom att förändra sin attityd.",
			"nl":    "De grootste ontdekking van elke generatie is dat een mens zijn leven kan veranderen door zijn houding te veranderen.",
			"nb":    "Enhver generasjons største oppdagelse er at et menneske kan forandre livet sitt ved å forandre holdningen sin.",
			"da":    "Enhver generations største opdagelse er, at et menneske kan forandre sit liv ved at ændre sin indstilling.",
			"fi":    "Jokaisen sukupolven suurin löytö on, että ihminen voi muuttaa elämänsä muuttamalla asennettaan.",
		},
	},
	{
		ID:       "mindset-40",
		Author:   ptr("Robert Louis Stevenson"),
		Category: "mindset",
		Translations: map[string]string{
			"en-US": "Don't judge each day by the harvest you reap but by the seeds that you plant.",
			"en-GB": "Don't judge each day by the harvest you reap but by the seeds that you plant.",
			"pt-PT": "Não julgues cada dia pela colheita que fazes, mas pelas sementes que plantas.",
			"pt-BR": "Não julgue cada dia pela colheita que você colhe, mas pelas sementes que você planta.",
			"es":    "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.",
			"fr":    "Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous semez.",
			"de":    "Beurteile den Tag nicht nach der Ernte, die du einfährst, sondern nach den Samen, die du säst.",
			"it":    "Non giudicare ogni giorno dal raccolto che ottieni, ma dai semi che pianti.",
			"ja":    "一日を刈り取った収穫で判断するな。蒔いた種で判断せよ。",
			"zh":    "评判一天，不要看你收获了什么，而要看你播下了什么种子。",
			"ko":    "하루를 거둔 수확이 아니라 심은 씨앗으로 평가하라.",
			"hi":    "हर दिन को उस फ़सल से मत आँको जो आप काटते हैं, बल्कि उन बीजों से आँको जो आप बोते हैं।",
			"pl":    "Nie oceniaj dnia po zbiorach, które zebrałeś, lecz po ziarnach, które zasiałeś.",
			"tr":    "Her günü topladığın hasada göre değil, ektiğin tohumlara göre değerlendir.",
			"uk":    "Суди про день не за врожаєм, який зібрав, а за насінням, яке посіяв.",
			"sv":    "Döm inte dagen efter skörden du bärgar utan efter fröna du sår.",
			"nl":    "Beoordeel de dag niet naar de oogst die je binnenhaalt, maar naar de zaden die je plant.",
			"nb":    "Døm ikke dagen etter avlingen du høster, men etter frøene du sår.",
			"da":    "Døm ikke dagen på den høst, du henter, men på de frø, du sår.",
			"fi":    "Älä arvioi päivää korjaamasi sadon mukaan, vaan kylvämiesi siementen mukaan.",
		},
	},
}
