package quote

var purposeQuotes = []QuoteData{
	{
		ID:       "purpose-1",
		Author:   ptr("Mark Twain"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The two most important days in your life are the day you are born and the day you find out why.",
			"en-GB": "The two most important days in your life are the day you are born and the day you find out why.",
			"pt-PT": "Os dois dias mais importantes da tua vida são o dia em que nasceste e o dia em que descobres porquê.",
			"pt-BR": "Os dois dias mais importantes da sua vida são o dia em que você nasceu e o dia em que descobriu por quê.",
			"es":    "Los dos días más importantes de tu vida são el día en que naces y el día en que descubres por qué.",
			"fr":    "Les deux jours les plus importants de votre vie sont le jour de votre naissance et celui où vous découvrez pourquoi.",
			"de":    "Die zwei wichtigsten Tage deines Lebens sind der Tag, an dem du geboren wirst, und der Tag, an dem du herausfindest, warum.",
			"it":    "I due giorni più importanti della tua vita sono il giorno in cui nasci e il giorno in cui scopri perché.",
			"ja":    "人生で最も大切な二つの日は、生まれた日と、なぜ生まれたのかを知る日である。",
			"zh":    "人生中最重要的两天，是你出生的那天和你明白自己为何而生的那天。",
			"ko":    "인생에서 가장 중요한 두 날은 태어난 날과 그 이유를 깨닫는 날이다.",
			"hi":    "आपके जीवन के दो सबसे महत्वपूर्ण दिन हैं: जिस दिन आप जन्म लेते हैं और जिस दिन आप जान जाते हैं कि क्यों।",
			"pl":    "Dwa najważniejsze dni w twoim życiu to dzień, w którym się rodzisz, i dzień, w którym odkrywasz po co.",
			"tr":    "Hayatındaki en önemli iki gün, doğduğun gün ve nedenini keşfettiğin gündür.",
			"uk":    "Два найважливіші дні у твоєму житті — день, коли ти народився, і день, коли зрозумів навіщо.",
			"sv":    "De två viktigaste dagarna i ditt liv är dagen du föds och dagen du förstår varför.",
			"nl":    "De twee belangrijkste dagen in je leven zijn de dag dat je geboren wordt en de dag dat je ontdekt waarom.",
			"nb":    "De to viktigste dagene i livet ditt er dagen du blir født og dagen du finner ut hvorfor.",
			"da":    "De to vigtigste dage i dit liv er den dag, du bliver født, og den dag, du finder ud af hvorfor.",
			"fi":    "Elämäsi kaksi tärkeintä päivää ovat päivä, jolloin synnyt, ja päivä, jolloin ymmärrät miksi.",
		},
	},
	{
		ID:       "purpose-2",
		Author:   ptr("Oprah Winfrey"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The whole point of being alive is to evolve into the complete person you were intended to be.",
			"en-GB": "The whole point of being alive is to evolve into the complete person you were intended to be.",
			"pt-PT": "O objetivo de estarmos vivos é evoluirmos para a pessoa completa que deveríamos ser.",
			"pt-BR": "O objetivo de estarmos vivos é evoluirmos para a pessoa completa que deveríamos ser.",
			"es":    "El sentido de estar vivo es evolucionar hasta convertirte en a persona completa que estabas destinado a ser.",
			"fr":    "Le but d'être en vie est d'évoluer pour devenir la personne complète que vous étiez censé être.",
			"de":    "Der ganze Sinn des Lebens besteht darin, sich zu dem vollständigen Menschen zu entwickeln, der man sein sollte.",
			"it":    "Il senso stesso di essere vivi è evolvere nella persona completa che eri destinato a essere.",
			"ja":    "生きることの意味とは、本来なるべき完全な自分へと成長していくことにある。",
			"zh":    "活着的全部意义，在于成长为你本应成为的完整的人。",
			"ko":    "살아 있음의 온전한 의미는 본래 되어야 할 완전한 사람으로 성장하는 데 있다.",
			"hi":    "जीवित होने का पूरा अर्थ है उस संपूर्ण व्यक्ति के रूप में विकसित होना जो आपको बनना था।",
			"pl":    "Cały sens życia polega na tym, by rozwinąć się w pełną osobę, którą miałeś się stać.",
			"tr":    "Yaşamanın asıl amacı, olman gereken eksiksiz insana dönüşmektir.",
			"uk":    "Увесь сенс життя в тому, щоб стати тією цілісною людиною, якою ти мав бути.",
			"sv":    "Hela poängen med att leva är att utvecklas till den fullständiga person du var ämnad att vara.",
			"nl":    "De hele zin van het leven is uitgroeien tot de complete persoon die je bedoeld was te zijn.",
			"nb":    "Hele poenget med å leve er å utvikle seg til det hele mennesket du var ment å være.",
			"da":    "Hele meningen med at leve er at udvikle sig til det hele menneske, du var bestemt til at være.",
			"fi":    "Elämisen koko tarkoitus on kehittyä siksi kokonaiseksi ihmiseksi, joksi sinun oli määrä tulla.",
		},
	},
	{
		ID:       "purpose-3",
		Author:   ptr("Pablo Picasso"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The meaning of life is to find your gift. The purpose of life is to give it away.",
			"en-GB": "The meaning of life is to find your gift. The purpose of life is to give it away.",
			"pt-PT": "O sentido da vida é encontrar o teu dom. O propósito da vida é partilhá-lo.",
			"pt-BR": "O sentido da vida é encontrar o seu dom. O propósito da vida é compartilhá-lo.",
			"es":    "El sentido de la vida es encontrar tu don. El propósito de la vida es regalarlo.",
			"fr":    "Le sens de la vie est de trouver son don. Le but de la vie est de le donner.",
			"de":    "Der Sinn des Lebens ist, deine Gabe zu finden. Der Zweck des Lebens ist, sie zu verschenken.",
			"it":    "Il significato della vita è trovare il proprio dono. Lo scopo della vita è donarlo.",
			"ja":    "人生の意味とは、自分の才能を見つけること。人生の目的とは、それを分かち与えることである。",
			"zh":    "生命的意义在于找到你的天赋，生命的目的在于把它奉献出去。",
			"ko":    "삶의 의미는 자신의 재능을 찾는 것이고, 삶의 목적은 그것을 나누는 것이다.",
			"hi":    "जीवन का अर्थ है अपनी प्रतिभा को खोजना। जीवन का उद्देश्य है उसे बाँट देना।",
			"pl":    "Sensem życia jest odnaleźć swój dar. Celem życia jest go ofiarować.",
			"tr":    "Hayatın anlamı, yeteneğini bulmaktır. Hayatın amacı ise onu armağan etmektir.",
			"uk":    "Сенс життя — знайти свій дар. Мета життя — віддати його іншим.",
			"sv":    "Livets mening är att hitta din gåva. Livets syfte är att ge bort den.",
			"nl":    "De zin van het leven is je gave te vinden. Het doel van het leven is haar weg te geven.",
			"nb":    "Meningen med livet er å finne gaven din. Hensikten med livet er å gi den bort.",
			"da":    "Meningen med livet er at finde din gave. Formålet med livet er at give den videre.",
			"fi":    "Elämän merkitys on löytää lahjasi. Elämän tarkoitus on antaa se pois.",
		},
	},
	{
		ID:       "purpose-4",
		Author:   ptr("Frederick Buechner"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Your vocation in life is where your greatest joy meets the world's greatest need.",
			"en-GB": "Your vocation in life is where your greatest joy meets the world's greatest need.",
			"pt-PT": "A tua vocação na vida é onde a tua maior alegria encontra a maior necessidade do mundo.",
			"pt-BR": "Sua vocação na vida é onde sua maior alegria encontra a maior necessidade do mundo.",
			"es":    "Tu vocación en la vida está donde tu mayor alegría se encuentra con la mayor necesidad del mundo.",
			"fr":    "Votre vocation dans la vie se trouve là où votre plus grande joie rencontre le plus grand besoin du monde.",
			"de":    "Deine Berufung im Leben liegt dort, wo deine größte Freude auf das größte Bedürfnis der Welt trifft.",
			"it":    "La tua vocazione nella vita è dove la tua gioia più grande incontra il bisogno più grande del mondo.",
			"ja":    "人生における天職とは、あなたの最大の喜びと世界の最大の必要が出会う場所にある。",
			"zh":    "你人生的天职，在于你最大的喜悦与世界最大的需要相遇之处。",
			"ko":    "인생의 소명은 당신의 가장 큰 기쁨이 세상의 가장 큰 필요와 만나는 곳에 있다.",
			"hi":    "जीवन में आपका व्यवसाय वहीं है जहाँ आपका सबसे बड़ा आनंद दुनिया की सबसे बड़ी ज़रूरत से मिलता है।",
			"pl":    "Twoje powołanie w życiu jest tam, gdzie twoja największa radość spotyka największą potrzebę świata.",
			"tr":    "Hayattaki çağrın, en büyük sevincinin dünyanın en büyük ihtiyacıyla buluştuğu yerdedir.",
			"uk":    "Твоє покликання в житті там, де твоя найбільша радість зустрічається з найбільшою потребою світу.",
			"sv":    "Din kallelse i livet är där din största glädje möter världens största behov.",
			"nl":    "Je roeping in het leven ligt waar je grootste vreugde de grootste nood van de wereld ontmoet.",
			"nb":    "Ditt kall i livet er der din største glede møter verdens største behov.",
			"da":    "Dit kald i livet er dér, hvor din største glæde møder verdens største behov.",
			"fi":    "Kutsumuksesi elämässä on siellä, missä suurin ilosi kohtaa maailman suurimman tarpeen.",
		},
	},
	{
		ID:       "purpose-5",
		Author:   ptr("Unknown"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "He who has a why to live can bear almost any how.",
			"en-GB": "He who has a why to live can bear almost any how.",
			"pt-PT": "Aquele que tem um porquê para viver consegue suportar quase qualquer como.",
			"pt-BR": "Aquele que tem um porquê para viver pode suportar quase qualquer como.",
			"es":    "Quien tiene un porqué para vivir, puede soportar casi cualquier cómo.",
			"fr":    "Celui qui a un pourquoi pour vivre peut supporter presque n'importe quel comment.",
			"de":    "Wer ein Warum zum Leben hat, erträgt fast jedes Wie.",
			"it":    "Chi ha un perché per vivere può sopportare quasi ogni come.",
			"ja":    "生きる「なぜ」を持つ者は、ほとんどどんな「どのように」にも耐えられる。",
			"zh":    "知道为什么而活的人，几乎可以承受任何一种生活。",
			"ko":    "살아야 할 이유를 가진 사람은 그 어떤 상황도 견뎌 낼 수 있다.",
			"hi":    "जिसके पास जीने का 'क्यों' है, वह लगभग हर 'कैसे' को सह सकता है।",
			"pl":    "Ten, kto ma po co żyć, zniesie prawie każde jak.",
			"tr":    "Yaşamak için bir 'neden'i olan, hemen her 'nasıl'a katlanabilir.",
			"uk":    "Той, хто має «навіщо» жити, витримає майже будь-яке «як».",
			"sv":    "Den som har ett varför att leva för kan uthärda nästan vilket hur som helst.",
			"nl":    "Wie een waarom heeft om voor te leven, kan bijna elk hoe verdragen.",
			"nb":    "Den som har et hvorfor å leve for, kan tåle nesten ethvert hvordan.",
			"da":    "Den, der har et hvorfor at leve for, kan bære næsten ethvert hvordan.",
			"fi":    "Se, jolla on elämälleen miksi, kestää melkein minkä tahansa miten.",
		},
	},
	{
		ID:       "purpose-6",
		Author:   ptr("Robert Louis Stevenson"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "To be what we are, and to become what we are capable of becoming, is the only end of life.",
			"en-GB": "To be what we are, and to become what we are capable of becoming, is the only end of life.",
			"pt-PT": "Ser o que somos, e tornarmo-nos no que somos capazes de nos tornar, é o único fim da vida.",
			"pt-BR": "Ser o que somos e nos tornarmos o que somos capazes de nos tornar é o único fim da vida.",
			"es":    "Ser lo que somos y convertirnos en lo que somos capaces de ser, es el único fin de la vida.",
			"fr":    "Être ce que nous sommes, et devenir ce que nous sommes capables de devenir, est la seule fin de la vie.",
			"de":    "Zu sein, was wir sind, und zu werden, was zu werden wir fähig sind, ist das einzige Ziel des Lebens.",
			"it":    "Essere ciò che siamo e diventare ciò che siamo capaci di diventare è l'unico fine della vita.",
			"ja":    "自分であること、そしてなり得る自分になること。それこそが人生の唯一の目的である。",
			"zh":    "成为我们所是，并成为我们所能成为的人，是人生唯一的目的。",
			"ko":    "지금의 나로 존재하고, 될 수 있는 사람이 되는 것. 그것이 삶의 유일한 목적이다.",
			"hi":    "जो हम हैं वही होना, और जो हम बन सकते हैं वह बनना—यही जीवन का एकमात्र लक्ष्य है।",
			"pl":    "Być tym, kim jesteśmy, i stawać się tym, kim możemy się stać — oto jedyny cel życia.",
			"tr":    "Olduğumuz kişi olmak ve olabileceğimiz kişiye dönüşmek, hayatın tek amacıdır.",
			"uk":    "Бути тим, ким ми є, і стати тим, ким здатні стати, — єдина мета життя.",
			"sv":    "Att vara det vi är och bli det vi är kapabla att bli är livets enda mål.",
			"nl":    "Zijn wat we zijn en worden wat we kunnen worden, is het enige doel van het leven.",
			"nb":    "Å være det vi er, og å bli det vi er i stand til å bli, er livets eneste mål.",
			"da":    "At være det, vi er, og at blive det, vi er i stand til at blive, er livets eneste mål.",
			"fi":    "Olla mitä olemme ja tulla siksi, miksi kykenemme tulemaan, on elämän ainoa päämäärä.",
		},
	},
	{
		ID:       "purpose-7",
		Author:   ptr("Eleanor Roosevelt"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The future belongs to those who believe in the beauty of their dreams.",
			"en-GB": "The future belongs to those who believe in the beauty of their dreams.",
			"pt-PT": "O futuro pertence àqueles que acreditam na beleza dos seus sonhos.",
			"pt-BR": "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
			"es":    "El futuro pertenece a quienes creen en la belleza de sus sueños.",
			"fr":    "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.",
			"de":    "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.",
			"it":    "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.",
			"ja":    "未来は、自分の夢の美しさを信じる人のものである。",
			"zh":    "未来属于那些相信梦想之美的人。",
			"ko":    "미래는 자기 꿈의 아름다움을 믿는 사람들의 것이다.",
			"hi":    "भविष्य उनका है जो अपने सपनों की सुंदरता में विश्वास रखते हैं।",
			"pl":    "Przyszłość należy do tych, którzy wierzą w piękno swoich marzeń.",
			"tr":    "Gelecek, hayallerinin güzelliğine inananlarındır.",
			"uk":    "Майбутнє належить тим, хто вірить у красу своїх мрій.",
			"sv":    "Framtiden tillhör dem som tror på skönheten i sina drömmar.",
			"nl":    "De toekomst behoort aan wie gelooft in de schoonheid van zijn dromen.",
			"nb":    "Fremtiden tilhører dem som tror på skjønnheten i drømmene sine.",
			"da":    "Fremtiden tilhører dem, der tror på skønheden i deres drømme.",
			"fi":    "Tulevaisuus kuuluu niille, jotka uskovat unelmiensa kauneuteen.",
		},
	},
	{
		ID:       "purpose-8",
		Author:   ptr("Howard Thurman"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Don’t ask what the world needs. Ask what makes you come alive, and go do it. Because what the world needs is people who have come alive.",
			"en-GB": "Don’t ask what the world needs. Ask what makes you come alive, and go do it. Because what the world needs is people who have come alive.",
			"pt-PT": "Não perguntes o que o mundo precisa. Pergunta o que te faz sentir vivo, e vai fazê-lo. Porque o que o mundo precisa é de pessoas que se sintam vivas.",
			"pt-BR": "Não pergunte do que o mundo precisa. Pergunte o que faz você se sentir vivo e vá fazê-lo. Porque o que o mundo precisa é de pessoas que se sintam vivas.",
			"es":    "No te preguntes qué necesita el mundo. Pregúntate qué te hace sentir vivo y hazlo. Porque lo que el mundo necesita es gente que se sienta viva.",
			"fr":    "Ne vous demandez pas ce dont le monde a besoin. Demandez-vous ce qui vous fait vibrer, et faites-le. Car ce dont le monde a besoin, ce sont des gens qui vibrent.",
			"de":    "Frag nicht, was die Welt braucht. Frag, was dich lebendig macht, und tu das. Denn was die Welt braucht, sind Menschen, die lebendig geworden sind.",
			"it":    "Non chiederti di cosa ha bisogno il mondo. Chiediti cosa ti fa sentire vivo, e fallo. Perché ciò di cui il mondo ha bisogno è gente che si è sentita rinascere.",
			"ja":    "世界が何を必要としているかを問うな。何が自分を生き生きとさせるかを問い、それを行え。世界が必要としているのは、生き生きとした人間なのだから。",
			"zh":    "不要问世界需要什么。问问什么能让你焕发生机，然后去做。因为世界需要的，正是焕发生机的人。",
			"ko":    "세상이 무엇을 필요로 하는지 묻지 마라. 무엇이 당신을 살아 있게 하는지 묻고, 그것을 하라. 세상이 필요로 하는 것은 살아 있는 사람들이기 때문이다.",
			"hi":    "यह मत पूछो कि दुनिया को क्या चाहिए। यह पूछो कि तुम्हें क्या जीवंत बनाता है, और वही करो। क्योंकि दुनिया को ज़रूरत है जीवंत हो उठे लोगों की।",
			"pl":    "Nie pytaj, czego potrzebuje świat. Zapytaj, co sprawia, że czujesz się żywy, i rób to. Bo światu potrzeba ludzi, którzy poczuli, że żyją.",
			"tr":    "Dünyanın neye ihtiyacı olduğunu sorma. Seni neyin canlandırdığını sor ve onu yap. Çünkü dünyanın ihtiyacı olan şey, canlanmış insanlardır.",
			"uk":    "Не питай, чого потребує світ. Запитай, що робить тебе живим, і роби це. Бо світові потрібні люди, які ожили.",
			"sv":    "Fråga inte vad världen behöver. Fråga vad som får dig att känna dig levande, och gör det. För vad världen behöver är människor som har blivit levande.",
			"nl":    "Vraag niet wat de wereld nodig heeft. Vraag wat jou tot leven brengt, en ga dat doen. Want wat de wereld nodig heeft, zijn mensen die tot leven zijn gekomen.",
			"nb":    "Ikke spør hva verden trenger. Spør hva som gjør deg levende, og gjør det. For det verden trenger, er mennesker som har blitt levende.",
			"da":    "Spørg ikke, hvad verden har brug for. Spørg, hvad der gør dig levende, og gør det. For det, verden har brug for, er mennesker, der er blevet levende.",
			"fi":    "Älä kysy, mitä maailma tarvitsee. Kysy, mikä saa sinut elämään täydesti, ja tee sitä. Sillä maailma tarvitsee ihmisiä, jotka ovat heränneet eloon.",
		},
	},
	{
		ID:       "purpose-9",
		Author:   ptr("George Eliot"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "It is never too late to be what you might have been.",
			"en-GB": "It is never too late to be what you might have been.",
			"pt-PT": "Nunca é tarde demais para seres o que poderias ter sido.",
			"pt-BR": "Nunca é tarde demais para ser o que você poderia ter sido.",
			"es":    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
			"fr":    "Il n'est jamais trop tard pour être ce que vous auriez pu être.",
			"de":    "Es ist nie zu spät, das zu werden, was du hättest sein können.",
			"it":    "Non è mai troppo tardi per essere ciò che avresti potuto essere.",
			"ja":    "なれたはずの自分になるのに、遅すぎるということはない。",
			"zh":    "成为你本可以成为的人，永远都不算晚。",
			"ko":    "될 수 있었던 사람이 되기에 너무 늦은 때란 없다.",
			"hi":    "जो आप बन सकते थे, वह बनने के लिए कभी देर नहीं होती।",
			"pl":    "Nigdy nie jest za późno, by stać się tym, kim mogłeś być.",
			"tr":    "Olabileceğin kişi olmak için asla geç değildir.",
			"uk":    "Ніколи не пізно стати тим, ким ти міг би бути.",
			"sv":    "Det är aldrig för sent att bli den du kunde ha varit.",
			"nl":    "Het is nooit te laat om te worden wie je had kunnen zijn.",
			"nb":    "Det er aldri for sent å bli den du kunne ha vært.",
			"da":    "Det er aldrig for sent at blive den, du kunne have været.",
			"fi":    "Koskaan ei ole liian myöhäistä tulla siksi, joka olisit voinut olla.",
		},
	},
	{
		ID:       "purpose-10",
		Author:   ptr("Steve Jobs"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
			"en-GB": "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
			"pt-PT": "A única forma de fazeres um excelente trabalho é amares o que fazes. Se ainda não encontraste, continua a procurar. Não te acomodes.",
			"pt-BR": "A única maneira de fazer um excelente trabalho é amando o que você faz. Se você ainda não encontrou, continue procurando. Não se acomode.",
			"es":    "La única forma de hacer un gran trabajo es amar lo que haces. Si aún no lo has encontrado, sigue buscando. No te conformes.",
			"fr":    "Le seul moyen de faire du bon travail est d'aimer ce que vous faites. Si vous ne l'avez pas encore trouvé, continuez à chercher. Ne vous contentez pas de peu.",
			"de":    "Großartige Arbeit kann man nur leisten, wenn man liebt, was man tut. Wenn du es noch nicht gefunden hast, such weiter. Gib dich nicht zufrieden.",
			"it":    "L'unico modo per fare un ottimo lavoro è amare quello che fai. Se non l'hai ancora trovato, continua a cercare. Non accontentarti.",
			"ja":    "偉大な仕事をする唯一の方法は、自分のすることを愛することだ。まだ見つかっていないなら、探し続けよ。妥協してはいけない。",
			"zh":    "成就伟大工作的唯一途径是热爱你所做的事。如果还没找到，就继续寻找，不要将就。",
			"ko":    "위대한 일을 해내는 유일한 방법은 하는 일을 사랑하는 것이다. 아직 찾지 못했다면 계속 찾아라. 안주하지 마라.",
			"hi":    "महान काम करने का एकमात्र तरीक़ा है अपने काम से प्यार करना। अगर अभी तक नहीं मिला, तो खोजते रहो। समझौता मत करो।",
			"pl":    "Jedynym sposobem na wykonywanie wspaniałej pracy jest kochać to, co się robi. Jeśli jeszcze tego nie znalazłeś, szukaj dalej. Nie zadowalaj się byle czym.",
			"tr":    "Harika işler yapmanın tek yolu, yaptığın işi sevmektir. Henüz bulamadıysan aramaya devam et. Yetinme.",
			"uk":    "Єдиний спосіб робити велику справу — любити те, що робиш. Якщо ще не знайшов — продовжуй шукати. Не зупиняйся на меншому.",
			"sv":    "Det enda sättet att göra ett storartat arbete är att älska det du gör. Om du inte hittat det än, fortsätt leta. Nöj dig inte.",
			"nl":    "De enige manier om geweldig werk te leveren is houden van wat je doet. Heb je het nog niet gevonden, blijf zoeken. Neem geen genoegen met minder.",
			"nb":    "Den eneste måten å gjøre storartet arbeid på er å elske det du gjør. Har du ikke funnet det ennå, fortsett å lete. Ikke slå deg til ro.",
			"da":    "Den eneste måde at gøre et fremragende arbejde på er at elske det, du laver. Har du ikke fundet det endnu, så bliv ved med at lede. Slå dig ikke til tåls.",
			"fi":    "Ainoa tapa tehdä suurenmoista työtä on rakastaa sitä mitä tekee. Jos et ole vielä löytänyt sitä, jatka etsimistä. Älä tyydy vähempään.",
		},
	},
	{
		ID:       "purpose-11",
		Author:   ptr("Rumi"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Let the beauty of what you love be what you do.",
			"en-GB": "Let the beauty of what you love be what you do.",
			"pt-PT": "Deixa que a beleza do que amas seja o que fazes.",
			"pt-BR": "Deixe a beleza do que você ama ser o que você faz.",
			"es":    "Deja que la belleza de lo que amas sea lo que hagas.",
			"fr":    "Laisse la beauté de ce que tu aimes être ce que tu fais.",
			"de":    "Lass die Schönheit dessen, was du liebst, das sein, was du tust.",
			"it":    "Lascia che la bellezza di ciò che ami sia ciò che fai.",
			"ja":    "愛するものの美しさを、あなたの行いにしなさい。",
			"zh":    "让你所爱之美，成为你所做之事。",
			"ko":    "당신이 사랑하는 것의 아름다움이 곧 당신이 하는 일이 되게 하라.",
			"hi":    "जिससे तुम प्रेम करते हो, उसकी सुंदरता को ही अपना कर्म बनने दो।",
			"pl":    "Niech piękno tego, co kochasz, będzie tym, co robisz.",
			"tr":    "Sevdiğin şeyin güzelliği, yaptığın şey olsun.",
			"uk":    "Нехай краса того, що ти любиш, стане тим, що ти робиш.",
			"sv":    "Låt skönheten i det du älskar vara det du gör.",
			"nl":    "Laat de schoonheid van wat je liefhebt zijn wat je doet.",
			"nb":    "La skjønnheten i det du elsker være det du gjør.",
			"da":    "Lad skønheden i det, du elsker, være det, du gør.",
			"fi":    "Anna sen kauneuden, jota rakastat, olla se mitä teet.",
		},
	},
	{
		ID:       "purpose-12",
		Author:   ptr("Ralph Waldo Emerson"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
			"en-GB": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
			"pt-PT": "O propósito da vida não é ser feliz. É ser útil, ser honrado, ser compassivo, fazer com que faça alguma diferença o facto de teres vivido e vivido bem.",
			"pt-BR": "O propósito da vida não é ser feliz. É ser útil, honrado, compassivo, fazer com que faça alguma diferença o fato de você ter vivido e vivido bem.",
			"es":    "El propósito de la vida no es ser feliz. Es ser útil, ser honorable, ser compasivo, hacer que marque alguna diferencia haber vivido y haber vivido bien.",
			"fr":    "Le but de la vie n'est pas d'être heureux. C'est d'être utile, d'être honorable, d'être compatissant, de faire en sorte que cela ait une importance que vous ayez vécu et bien vécu.",
			"de":    "Der Zweck des Lebens ist nicht, glücklich zu sein. Er ist, nützlich zu sein, ehrenhaft zu sein, mitfühlend zu sein — dass es etwas ausmacht, dass du gelebt hast und gut gelebt hast.",
			"it":    "Lo scopo della vita non è essere felici. È essere utili, essere onorevoli, essere compassionevoli, far sì che il fatto di aver vissuto, e vissuto bene, faccia una differenza.",
			"ja":    "人生の目的は幸せになることではない。役に立つこと、誇り高くあること、思いやりを持つこと。そして、自分がよく生きたことが何かの違いを生むことである。",
			"zh":    "人生的目的不是快乐，而是有用、正直、慈悲——让你活过、并且好好活过这件事，产生一些意义。",
			"ko":    "삶의 목적은 행복해지는 것이 아니다. 쓸모 있는 사람, 명예로운 사람, 자비로운 사람이 되어, 당신이 잘 살았다는 사실이 어떤 의미를 남기게 하는 것이다.",
			"hi":    "जीवन का उद्देश्य ख़ुश रहना नहीं है। उद्देश्य है उपयोगी होना, सम्माननीय होना, करुणामय होना—ताकि आपके जीने का, और अच्छी तरह जीने का, कुछ अर्थ हो।",
			"pl":    "Celem życia nie jest bycie szczęśliwym. Jest nim bycie użytecznym, honorowym, współczującym — sprawienie, by to, że żyłeś, i żyłeś dobrze, miało jakieś znaczenie.",
			"tr":    "Hayatın amacı mutlu olmak değildir. Yararlı olmak, onurlu olmak, şefkatli olmak; yaşamış ve iyi yaşamış olmanın bir fark yaratmasıdır.",
			"uk":    "Мета життя — не бути щасливим. Мета — бути корисним, гідним, співчутливим; щоб те, що ти жив і жив добре, щось змінило.",
			"sv":    "Livets syfte är inte att vara lycklig. Det är att vara nyttig, att vara hedervärd, att vara medkännande — att det gör någon skillnad att du har levt och levt väl.",
			"nl":    "Het doel van het leven is niet gelukkig zijn. Het is nuttig zijn, eervol zijn, meelevend zijn — dat het iets uitmaakt dat je hebt geleefd en goed hebt geleefd.",
			"nb":    "Hensikten med livet er ikke å være lykkelig. Den er å være nyttig, å være hederlig, å være medfølende — at det utgjør en forskjell at du har levd, og levd godt.",
			"da":    "Formålet med livet er ikke at være lykkelig. Det er at være nyttig, at være hæderlig, at være medfølende — at det gør en forskel, at du har levet og levet godt.",
			"fi":    "Elämän tarkoitus ei ole olla onnellinen. Se on olla hyödyksi, olla kunniallinen, olla myötätuntoinen — että sillä on merkitystä, että elit ja elit hyvin.",
		},
	},
	{
		ID:       "purpose-13",
		Author:   ptr("Unknown"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Life is not about finding yourself. Life is about creating yourself.",
			"en-GB": "Life is not about finding yourself. Life is about creating yourself.",
			"pt-PT": "A vida não é encontrar-te a ti próprio. A vida é criares-te a ti próprio.",
			"pt-BR": "A vida não é encontrar a si mesmo. A vida é criar a si mesmo.",
			"es":    "La vida no consiste en encontrarse a uno mismo. La vida consiste en crearse a uno mismo.",
			"fr":    "La vie ne consiste pas à se trouver soi-même. La vie consiste à se créer soi-même.",
			"de":    "Im Leben geht es nicht darum, sich selbst zu finden. Im Leben geht es darum, sich selbst zu erschaffen.",
			"it":    "La vita non consiste nel trovare se stessi. La vita consiste nel creare se stessi.",
			"ja":    "人生とは自分を見つけることではない。人生とは自分を創ることである。",
			"zh":    "人生不在于找到自己，而在于创造自己。",
			"ko":    "인생은 자신을 찾는 것이 아니라 자신을 만들어 가는 것이다.",
			"hi":    "जीवन ख़ुद को खोजने का नाम नहीं है। जीवन ख़ुद को गढ़ने का नाम है।",
			"pl":    "Życie nie polega na odnajdywaniu siebie. Życie polega na tworzeniu siebie.",
			"tr":    "Hayat kendini bulmak değildir. Hayat kendini yaratmaktır.",
			"uk":    "Життя — це не пошук себе. Життя — це створення себе.",
			"sv":    "Livet handlar inte om att hitta sig själv. Livet handlar om att skapa sig själv.",
			"nl":    "Het leven gaat niet over jezelf vinden. Het leven gaat over jezelf creëren.",
			"nb":    "Livet handler ikke om å finne seg selv. Livet handler om å skape seg selv.",
			"da":    "Livet handler ikke om at finde sig selv. Livet handler om at skabe sig selv.",
			"fi":    "Elämässä ei ole kyse itsensä löytämisestä, vaan itsensä luomisesta.",
		},
	},
	{
		ID:       "purpose-14",
		Author:   ptr("Denis Waitley"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The greatest gifts you can give your children are the roots of responsibility and the wings of independence.",
			"en-GB": "The greatest gifts you can give your children are the roots of responsibility and the wings of independence.",
			"pt-PT": "As maiores dádivas que podes dar aos teus filhos são as raízes da responsabilidade e as asas da independência.",
			"pt-BR": "Os maiores presentes que você pode dar aos seus filhos são as raízes da responsabilidade e as asas da independência.",
			"es":    "Los mejores regalos que puedes dar a tus hijos son as raíces de la responsabilidad y las alas de la independencia.",
			"fr":    "Les plus grands cadeaux que vous puissiez offrir à vos enfants sont les racines de la responsabilité et les ailes de l'indépendance.",
			"de":    "Die größten Geschenke, die du deinen Kindern geben kannst, sind die Wurzeln der Verantwortung und die Flügel der Unabhängigkeit.",
			"it":    "I doni più grandi che puoi fare ai tuoi figli sono le radici della responsabilità e le ali dell'indipendenza.",
			"ja":    "子どもに与えられる最高の贈り物は、責任という根と自立という翼である。",
			"zh":    "你能给孩子最好的礼物，是责任的根和独立的翅膀。",
			"ko":    "자녀에게 줄 수 있는 가장 큰 선물은 책임이라는 뿌리와 독립이라는 날개다.",
			"hi":    "अपने बच्चों को आप जो सबसे बड़े उपहार दे सकते हैं, वे हैं ज़िम्मेदारी की जड़ें और स्वतंत्रता के पंख।",
			"pl":    "Największe dary, jakie możesz dać swoim dzieciom, to korzenie odpowiedzialności i skrzydła niezależności.",
			"tr":    "Çocuklarına verebileceğin en büyük armağanlar, sorumluluğun kökleri ve bağımsızlığın kanatlarıdır.",
			"uk":    "Найбільші дари, які ти можеш дати своїм дітям, — це коріння відповідальності та крила незалежності.",
			"sv":    "De största gåvor du kan ge dina barn är ansvarets rötter och självständighetens vingar.",
			"nl":    "De grootste geschenken die je je kinderen kunt geven, zijn de wortels van verantwoordelijkheid en de vleugels van onafhankelijkheid.",
			"nb":    "De største gavene du kan gi barna dine, er ansvarets røtter og selvstendighetens vinger.",
			"da":    "De største gaver, du kan give dine børn, er ansvarets rødder og uafhængighedens vinger.",
			"fi":    "Suurimmat lahjat, jotka voit antaa lapsillesi, ovat vastuun juuret ja itsenäisyyden siivet.",
		},
	},
	{
		ID:       "purpose-15",
		Author:   ptr("Leo Tolstoy"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The two most powerful warriors are patience and time.",
			"en-GB": "The two most powerful warriors are patience and time.",
			"pt-PT": "Os dois guerreiros mais poderosos são a paciência e o tempo.",
			"pt-BR": "Os dois guerreiros mais poderosos são a paciência e o tempo.",
			"es":    "Los dos guerreros más poderosos son la paciencia y el tiempo.",
			"fr":    "Les deux guerriers les plus puissants sont la patience et le temps.",
			"de":    "Die zwei mächtigsten Krieger sind Geduld und Zeit.",
			"it":    "I due guerrieri più potenti sono la pazienza e il tempo.",
			"ja":    "最も強い二人の戦士は、忍耐と時間である。",
			"zh":    "最强大的两位战士，是耐心和时间。",
			"ko":    "가장 강력한 두 전사는 인내와 시간이다.",
			"hi":    "दो सबसे शक्तिशाली योद्धा हैं धैर्य और समय।",
			"pl":    "Dwaj najpotężniejsi wojownicy to cierpliwość i czas.",
			"tr":    "En güçlü iki savaşçı sabır ve zamandır.",
			"uk":    "Два наймогутніші воїни — терпіння і час.",
			"sv":    "De två mäktigaste krigarna är tålamod och tid.",
			"nl":    "De twee machtigste krijgers zijn geduld en tijd.",
			"nb":    "De to mektigste krigerne er tålmodighet og tid.",
			"da":    "De to mægtigste krigere er tålmodighed og tid.",
			"fi":    "Kaksi mahtavinta soturia ovat kärsivällisyys ja aika.",
		},
	},
	{
		ID:       "purpose-16",
		Author:   ptr("W.H. Auden"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "We are here on earth to do good to others. What the others are here for I don't know.",
			"en-GB": "We are here on earth to do good to others. What the others are here for I don't know.",
			"pt-PT": "Estamos aqui na terra para fazer o bem aos outros. Para que é que os outros aqui estão, não sei.",
			"pt-BR": "Estamos aqui na terra para fazer o bem aos outros. Para que os outros estão aqui, eu não sei.",
			"es":    "Estamos aquí en la tierra para hacer el bien a los demás. Para qué están aquí los demás, no lo sé.",
			"fr":    "Nous sommes ici sur terre pour faire du bien aux autres. Ce pour quoi les autres sont ici, je l'ignore.",
			"de":    "Wir sind auf der Erde, um anderen Gutes zu tun. Wozu die anderen da sind, weiß ich nicht.",
			"it":    "Siamo qui sulla terra per fare del bene agli altri. Per cosa ci siano gli altri, non lo so.",
			"ja":    "私たちは他者に善を施すためにこの世にいる。他者が何のためにいるのかは、私にはわからない。",
			"zh":    "我们在世上是为了行善于人。至于别人是为了什么，我就不知道了。",
			"ko":    "우리는 다른 사람들에게 선을 베풀기 위해 이 땅에 있다. 다른 사람들이 왜 있는지는 나도 모른다.",
			"hi":    "हम इस धरती पर दूसरों का भला करने के लिए हैं। दूसरे किसलिए हैं, यह मुझे नहीं पता।",
			"pl":    "Jesteśmy na ziemi, by czynić dobro innym. Po co są inni — tego nie wiem.",
			"tr":    "Bu dünyada başkalarına iyilik etmek için varız. Başkalarının ne için var olduğunu bilmiyorum.",
			"uk":    "Ми на землі, щоб робити добро іншим. Навіщо тут інші — я не знаю.",
			"sv":    "Vi är här på jorden för att göra gott mot andra. Vad de andra är här för vet jag inte.",
			"nl":    "Wij zijn hier op aarde om goed te doen voor anderen. Waarvoor de anderen er zijn, weet ik niet.",
			"nb":    "Vi er her på jorden for å gjøre godt mot andre. Hva de andre er her for, vet jeg ikke.",
			"da":    "Vi er her på jorden for at gøre godt mod andre. Hvad de andre er her for, ved jeg ikke.",
			"fi":    "Olemme maan päällä tehdäksemme hyvää toisille. Mitä varten toiset ovat täällä, sitä en tiedä.",
		},
	},
	{
		ID:       "purpose-17",
		Author:   ptr("H. Jackson Brown Jr."),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.",
			"en-GB": "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.",
			"pt-PT": "Não digas que não tens tempo suficiente. Tens exatamente o mesmo número de horas por dia que foram dadas a Helen Keller, Pasteur, Michelangelo, Madre Teresa, Leonardo da Vinci, Thomas Jefferson e Albert Einstein.",
			"pt-BR": "Não diga que não tem tempo suficiente. Você tem exatamente o mesmo número de horas por dia que foram dadas a Helen Keller, Pasteur, Michelangelo, Madre Teresa, Leonardo da Vinci, Thomas Jefferson e Albert Einstein.",
			"es":    "No digas que no tienes suficiente tiempo. Tienes exactamente el mismo número de horas al día que les dieron a Helen Keller, Pasteur, Miguel Ángel, la Madre Teresa, Leonardo da Vinci, Thomas Jefferson y Albert Einstein.",
			"fr":    "Ne dites pas que vous n'avez pas assez de temps. Vous avez exactement le même nombre d'heures par jour que celles qui ont été données à Helen Keller, Pasteur, Michel-Ange, Mère Teresa, Léonard de Vinci, Thomas Jefferson et Albert Einstein.",
			"de":    "Sag nicht, du hättest nicht genug Zeit. Du hast genau so viele Stunden am Tag wie Helen Keller, Pasteur, Michelangelo, Mutter Teresa, Leonardo da Vinci, Thomas Jefferson und Albert Einstein.",
			"it":    "Non dire che non hai abbastanza tempo. Hai esattamente lo stesso numero di ore al giorno che è stato dato a Helen Keller, Pasteur, Michelangelo, Madre Teresa, Leonardo da Vinci, Thomas Jefferson e Albert Einstein.",
			"ja":    "時間が足りないと言ってはいけない。あなたに与えられた一日の時間は、ヘレン・ケラー、パスツール、ミケランジェロ、マザー・テレサ、レオナルド・ダ・ヴィンチ、トーマス・ジェファーソン、アインシュタインに与えられたものとまったく同じなのだから。",
			"zh":    "别说你时间不够。你每天拥有的小时数，与海伦·凯勒、巴斯德、米开朗基罗、特蕾莎修女、达·芬奇、杰斐逊和爱因斯坦完全相同。",
			"ko":    "시간이 부족하다고 말하지 마라. 당신에게 주어진 하루의 시간은 헬렌 켈러, 파스퇴르, 미켈란젤로, 마더 테레사, 레오나르도 다빈치, 토머스 제퍼슨, 알베르트 아인슈타인에게 주어진 것과 정확히 같다.",
			"hi":    "यह मत कहो कि तुम्हारे पास समय नहीं है। तुम्हारे पास दिन में उतने ही घंटे हैं जितने हेलेन केलर, पाश्चर, माइकल एंजेलो, मदर टेरेसा, लियोनार्डो दा विंची, थॉमस जेफ़रसन और अल्बर्ट आइंस्टीन को मिले थे।",
			"pl":    "Nie mów, że nie masz dość czasu. Masz dokładnie tyle samo godzin w ciągu dnia, ile dano Helen Keller, Pasteurowi, Michałowi Aniołowi, Matce Teresie, Leonardowi da Vinci, Thomasowi Jeffersonowi i Albertowi Einsteinowi.",
			"tr":    "Yeterli zamanın olmadığını söyleme. Günde, Helen Keller'a, Pasteur'e, Michelangelo'ya, Rahibe Teresa'ya, Leonardo da Vinci'ye, Thomas Jefferson'a ve Albert Einstein'a verilenle tıpatıp aynı sayıda saate sahipsin.",
			"uk":    "Не кажи, що тобі бракує часу. У тебе рівно стільки ж годин на день, скільки було в Гелен Келлер, Пастера, Мікеланджело, Матері Терези, Леонардо да Вінчі, Томаса Джефферсона й Альберта Ейнштейна.",
			"sv":    "Säg inte att du inte har tillräckligt med tid. Du har exakt lika många timmar om dygnet som Helen Keller, Pasteur, Michelangelo, Moder Teresa, Leonardo da Vinci, Thomas Jefferson och Albert Einstein fick.",
			"nl":    "Zeg niet dat je niet genoeg tijd hebt. Je hebt precies evenveel uren per dag als Helen Keller, Pasteur, Michelangelo, Moeder Teresa, Leonardo da Vinci, Thomas Jefferson en Albert Einstein kregen.",
			"nb":    "Ikke si at du ikke har nok tid. Du har nøyaktig like mange timer i døgnet som Helen Keller, Pasteur, Michelangelo, Mor Teresa, Leonardo da Vinci, Thomas Jefferson og Albert Einstein fikk.",
			"da":    "Sig ikke, at du ikke har tid nok. Du har præcis lige så mange timer i døgnet, som Helen Keller, Pasteur, Michelangelo, Moder Teresa, Leonardo da Vinci, Thomas Jefferson og Albert Einstein fik.",
			"fi":    "Älä sano, ettei sinulla ole tarpeeksi aikaa. Sinulla on päivässä täsmälleen yhtä monta tuntia kuin annettiin Helen Kellerille, Pasteurille, Michelangelolle, Äiti Teresalle, Leonardo da Vincille, Thomas Jeffersonille ja Albert Einsteinille.",
		},
	},
	{
		ID:       "purpose-18",
		Author:   ptr("John Ruskin"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The highest reward for a person's toil is not what they get for it, but what they become by it.",
			"en-GB": "The highest reward for a person's toil is not what they get for it, but what they become by it.",
			"pt-PT": "A maior recompensa para o trabalho de uma pessoa não é o que ela recebe por ele, mas o que se torna através dele.",
			"pt-BR": "A maior recompensa pelo trabalho de uma pessoa não é o que ela recebe por ele, mas o que ela se torna por meio dele.",
			"es":    "La mayor recompensa por el trabajo de una persona no es lo que obtiene por ello, sino lo que llega a ser gracias a él.",
			"fr":    "La plus haute récompense du labeur d'une personne n'est pas ce qu'elle en retire, mais ce qu'elle devient par lui.",
			"de":    "Der höchste Lohn für die Mühe eines Menschen ist nicht das, was er dafür bekommt, sondern das, was er dadurch wird.",
			"it":    "La più alta ricompensa per la fatica di una persona non è ciò che ne ricava, ma ciò che grazie ad essa diventa.",
			"ja":    "労苦への最高の報酬は、それによって得るものではなく、それによってどんな人間になるかである。",
			"zh":    "一个人辛劳的最高回报，不是他因此得到什么，而是他因此成为什么样的人。",
			"ko":    "수고에 대한 가장 큰 보상은 그로 인해 얻는 것이 아니라, 그로 인해 어떤 사람이 되는가이다.",
			"hi":    "मेहनत का सर्वोच्च पुरस्कार वह नहीं जो उससे मिलता है, बल्कि वह है जो हम उसके ज़रिए बन जाते हैं।",
			"pl":    "Najwyższą nagrodą za trud człowieka nie jest to, co za niego dostaje, lecz to, kim dzięki niemu się staje.",
			"tr":    "İnsanın emeğinin en yüksek ödülü, karşılığında aldığı şey değil, onun sayesinde dönüştüğü kişidir.",
			"uk":    "Найвища нагорода за працю людини — не те, що вона за неї отримує, а те, ким вона завдяки їй стає.",
			"sv":    "Den högsta belöningen för en människas möda är inte vad hon får för den, utan vad hon blir genom den.",
			"nl":    "De hoogste beloning voor iemands inspanning is niet wat hij ervoor krijgt, maar wat hij erdoor wordt.",
			"nb":    "Den høyeste belønningen for et menneskes strev er ikke det han får for det, men det han blir av det.",
			"da":    "Den højeste belønning for et menneskes slid er ikke det, han får for det, men det, han bliver ved det.",
			"fi":    "Korkein palkkio ihmisen vaivannäöstä ei ole se, mitä hän siitä saa, vaan se, millaiseksi hän sen kautta tulee.",
		},
	},
	{
		ID:       "purpose-19",
		Author:   ptr("Unknown"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The purpose of our lives is to be happy.",
			"en-GB": "The purpose of our lives is to be happy.",
			"pt-PT": "O propósito das nossas vidas é sermos felizes.",
			"pt-BR": "O propósito de nossas vidas é sermos felizes.",
			"es":    "El propósito de nuestras vidas es ser felices.",
			"fr":    "Le but de nos vies est d'être heureux.",
			"de":    "Der Zweck unseres Lebens ist es, glücklich zu sein.",
			"it":    "Lo scopo della nostra vita è essere felici.",
			"ja":    "私たちの人生の目的は、幸せになることである。",
			"zh":    "我们生命的目的就是快乐。",
			"ko":    "우리 삶의 목적은 행복해지는 것이다.",
			"hi":    "हमारे जीवन का उद्देश्य ख़ुश रहना है।",
			"pl":    "Celem naszego życia jest być szczęśliwym.",
			"tr":    "Hayatımızın amacı mutlu olmaktır.",
			"uk":    "Мета нашого життя — бути щасливими.",
			"sv":    "Syftet med våra liv är att vara lyckliga.",
			"nl":    "Het doel van ons leven is gelukkig zijn.",
			"nb":    "Hensikten med livene våre er å være lykkelige.",
			"da":    "Formålet med vores liv er at være lykkelige.",
			"fi":    "Elämämme tarkoitus on olla onnellinen.",
		},
	},
	{
		ID:       "purpose-20",
		Author:   ptr("Aristotle"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.",
			"en-GB": "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.",
			"pt-PT": "A felicidade é o sentido e o propósito da vida, todo o objetivo e fim da existência humana.",
			"pt-BR": "A felicidade é o sentido e o propósito da vida, todo o objetivo e fim da existência humana.",
			"es":    "La felicidad es el significado y el propósito de la vida, el objetivo y el fin último de la existencia humana.",
			"fr":    "Le bonheur est le sens et le but de la vie, l'objectif et la fin de l'existence humaine.",
			"de":    "Glück ist der Sinn und Zweck des Lebens, das ganze Ziel und Ende des menschlichen Daseins.",
			"it":    "La felicità è il significato e lo scopo della vita, l'intero fine e traguardo dell'esistenza umana.",
			"ja":    "幸福こそ人生の意味であり目的であり、人間存在の目標であり終着点である。",
			"zh":    "幸福是生命的意义与目的，是人类存在的全部目标与归宿。",
			"ko":    "행복은 삶의 의미이자 목적이며, 인간 존재의 목표이자 끝이다.",
			"hi":    "ख़ुशी ही जीवन का अर्थ और उद्देश्य है, मानव अस्तित्व का संपूर्ण लक्ष्य और अंत।",
			"pl":    "Szczęście jest sensem i celem życia, całym dążeniem i kresem ludzkiego istnienia.",
			"tr":    "Mutluluk, hayatın anlamı ve amacı, insan varoluşunun bütün gayesi ve sonudur.",
			"uk":    "Щастя — це сенс і мета життя, уся ціль і вершина людського існування.",
			"sv":    "Lycka är livets mening och syfte, hela målet och slutet för människans existens.",
			"nl":    "Geluk is de zin en het doel van het leven, het hele streven en einddoel van het menselijk bestaan.",
			"nb":    "Lykke er meningen og hensikten med livet, hele målet og enden for menneskets eksistens.",
			"da":    "Lykke er meningen og formålet med livet, hele målet og enden for menneskets tilværelse.",
			"fi":    "Onnellisuus on elämän merkitys ja tarkoitus, ihmisen olemassaolon koko päämäärä ja täyttymys.",
		},
	},
	{
		ID:       "purpose-21",
		Author:   ptr("Albert Einstein"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "If you want to live a happy life, tie it to a goal, not to people or things.",
			"en-GB": "If you want to live a happy life, tie it to a goal, not to people or things.",
			"pt-PT": "Se queres viver uma vida feliz, amarra-a a um objetivo, não a pessoas ou coisas.",
			"pt-BR": "Se você quer viver uma vida feliz, amarre-a a um objetivo, não a pessoas ou coisas.",
			"es":    "Si quieres vivir una vida feliz, átala a una meta, no a personas ni a cosas.",
			"fr":    "Si vous voulez mener une vie heureuse, liez-la à un objectif, pas à des personnes ou à des choses.",
			"de":    "Wenn du ein glückliches Leben führen willst, binde es an ein Ziel, nicht an Menschen oder Dinge.",
			"it":    "Se vuoi vivere una vita felice, legala a un obiettivo, non a persone o cose.",
			"ja":    "幸せな人生を送りたければ、それを人や物ではなく、目標に結びつけなさい。",
			"zh":    "想过幸福的生活，就把它系在目标上，而不是系在人或物上。",
			"ko":    "행복한 삶을 살고 싶다면 삶을 사람이나 사물이 아니라 목표에 묶어라.",
			"hi":    "अगर सुखी जीवन जीना चाहते हो, तो उसे किसी लक्ष्य से जोड़ो, लोगों या चीज़ों से नहीं।",
			"pl":    "Jeśli chcesz żyć szczęśliwie, zwiąż swoje życie z celem, a nie z ludźmi czy rzeczami.",
			"tr":    "Mutlu bir hayat yaşamak istiyorsan, onu insanlara ya da nesnelere değil, bir amaca bağla.",
			"uk":    "Якщо хочеш жити щасливо, прив'яжи життя до мети, а не до людей чи речей.",
			"sv":    "Om du vill leva ett lyckligt liv, knyt det till ett mål, inte till människor eller ting.",
			"nl":    "Als je een gelukkig leven wilt leiden, verbind het dan aan een doel, niet aan mensen of dingen.",
			"nb":    "Vil du leve et lykkelig liv, knytt det til et mål, ikke til mennesker eller ting.",
			"da":    "Vil du leve et lykkeligt liv, så knyt det til et mål, ikke til mennesker eller ting.",
			"fi":    "Jos haluat elää onnellisen elämän, sido se tavoitteeseen, älä ihmisiin tai esineisiin.",
		},
	},
	{
		ID:       "purpose-22",
		Author:   ptr("Maya Angelou"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
			"en-GB": "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
			"pt-PT": "A minha missão na vida não é meramente sobreviver, mas prosperar; e fazê-lo com alguma paixão, alguma compaixão, algum humor e algum estilo.",
			"pt-BR": "Minha missão na vida não é apenas sobreviver, mas prosperar; e fazê-lo com alguma paixão, alguma compaixão, algum humor e algum estilo.",
			"es":    "Mi misión en la vida no es simplemente sobrevivir, sino prosperar; y hacerlo con algo de pasión, algo de compasión, algo de humor y algo de estilo.",
			"fr":    "Ma mission dans la vie n'est pas seulement de survivre, mais de prospérer ; et de le faire avec passion, compassion, humour et style.",
			"de":    "Meine Mission im Leben ist nicht bloß zu überleben, sondern aufzublühen — und zwar mit etwas Leidenschaft, etwas Mitgefühl, etwas Humor und etwas Stil.",
			"it":    "La mia missione nella vita non è semplicemente sopravvivere, ma prosperare; e farlo con passione, compassione, umorismo e stile.",
			"ja":    "私の人生の使命は、ただ生き延びることではなく、豊かに生きること。しかも情熱と、思いやりと、ユーモアと、スタイルをもって。",
			"zh":    "我人生的使命不只是生存，而是绽放；并且要带着热情、慈悲、幽默和风度去绽放。",
			"ko":    "내 삶의 사명은 단지 생존하는 것이 아니라 번성하는 것이다. 그것도 약간의 열정과 연민과 유머와 품격을 갖고서.",
			"hi":    "मेरे जीवन का ध्येय केवल जीवित रहना नहीं, बल्कि फलना-फूलना है; और वह भी कुछ जुनून, कुछ करुणा, कुछ हास्य और कुछ अंदाज़ के साथ।",
			"pl":    "Moją misją w życiu nie jest jedynie przetrwać, lecz rozkwitać — i to z odrobiną pasji, współczucia, humoru i stylu.",
			"tr":    "Hayattaki görevim yalnızca hayatta kalmak değil, serpilip gelişmek; bunu da biraz tutkuyla, biraz şefkatle, biraz mizahla ve biraz tarzla yapmak.",
			"uk":    "Моя місія в житті — не просто вижити, а розквітнути; і зробити це з пристрастю, співчуттям, гумором і стилем.",
			"sv":    "Min mission i livet är inte bara att överleva utan att blomstra — och att göra det med lite passion, lite medkänsla, lite humor och lite stil.",
			"nl":    "Mijn missie in het leven is niet louter overleven, maar floreren; en dat met wat passie, wat mededogen, wat humor en wat stijl.",
			"nb":    "Mitt oppdrag i livet er ikke bare å overleve, men å blomstre — og å gjøre det med litt lidenskap, litt medfølelse, litt humor og litt stil.",
			"da":    "Min mission i livet er ikke blot at overleve, men at trives — og at gøre det med lidt passion, lidt medfølelse, lidt humor og lidt stil.",
			"fi":    "Elämäntehtäväni ei ole vain selviytyä, vaan kukoistaa — ja tehdä se intohimolla, myötätunnolla, huumorilla ja tyylillä.",
		},
	},
	{
		ID:       "purpose-23",
		Author:   ptr("Helen Keller"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Many persons have a wrong idea of what constitutes true happiness. It is not attained through self-gratification but through fidelity to a worthy purpose.",
			"en-GB": "Many persons have a wrong idea of what constitutes true happiness. It is not attained through self-gratification but through fidelity to a worthy purpose.",
			"pt-PT": "Muitas pessoas têm uma ideia errada do que constitui a verdadeira felicidade. Não é alcançada através da autogratificação, mas através da fidelidade a um propósito digno.",
			"pt-BR": "Muitas pessoas têm uma ideia errada do que constitui a verdadeira felicidade. Ela não é alcançada através da autogratificação, mas através da fidelidade a um propósito digno.",
			"es":    "Muchas personas tienen una idea errónea de lo que constituye la verdadera felicidad. No se alcanza mediante la autogratificación, sino mediante la fidelidad a un propósito digno.",
			"fr":    "Beaucoup de personnes ont une idée fausse de ce qui constitue le vrai bonheur. Il n'est pas atteint par l'autosatisfaction mais par la fidélité à un but digne.",
			"de":    "Viele Menschen haben eine falsche Vorstellung davon, was wahres Glück ausmacht. Es wird nicht durch Selbstbefriedigung erreicht, sondern durch Treue zu einem würdigen Ziel.",
			"it":    "Molte persone hanno un'idea sbagliata di cosa costituisca la vera felicità. Non si raggiunge attraverso l'autogratificazione, ma attraverso la fedeltà a uno scopo degno.",
			"ja":    "多くの人は、真の幸福が何であるかを誤解している。それは自己満足によってではなく、価値ある目的への献身によって得られるものである。",
			"zh":    "许多人对真正的幸福有错误的理解。幸福不是通过自我满足获得的，而是通过忠于一个有价值的目标获得的。",
			"ko":    "많은 사람이 진정한 행복이 무엇인지 잘못 알고 있다. 행복은 자기만족이 아니라 가치 있는 목적에 대한 충실함을 통해 얻어진다.",
			"hi":    "बहुत से लोगों की सच्ची ख़ुशी के बारे में धारणा ग़लत है। यह आत्म-तुष्टि से नहीं, बल्कि किसी योग्य उद्देश्य के प्रति निष्ठा से प्राप्त होती है।",
			"pl":    "Wielu ludzi ma błędne pojęcie o tym, czym jest prawdziwe szczęście. Nie osiąga się go przez dogadzanie sobie, lecz przez wierność godnemu celowi.",
			"tr":    "Birçok insan gerçek mutluluğun ne olduğu konusunda yanılır. Mutluluğa kendini hoşnut ederek değil, değerli bir amaca bağlı kalarak ulaşılır.",
			"uk":    "Багато людей хибно уявляють, що таке справжнє щастя. Воно досягається не самозадоволенням, а вірністю гідній меті.",
			"sv":    "Många har en felaktig uppfattning om vad sann lycka är. Den nås inte genom självtillfredsställelse utan genom trohet mot ett värdigt syfte.",
			"nl":    "Veel mensen hebben een verkeerd idee van wat waar geluk inhoudt. Het wordt niet bereikt door zelfbevrediging, maar door trouw aan een waardig doel.",
			"nb":    "Mange mennesker har en feil oppfatning av hva sann lykke er. Den oppnås ikke gjennom selvtilfredsstillelse, men gjennom troskap mot et verdig formål.",
			"da":    "Mange mennesker har en forkert forestilling om, hvad sand lykke er. Den opnås ikke gennem selvtilfredsstillelse, men gennem troskab mod et værdigt formål.",
			"fi":    "Monilla on väärä käsitys siitä, mitä todellinen onnellisuus on. Sitä ei saavuteta itsensä hemmottelulla, vaan uskollisuudella arvokkaalle päämäärälle.",
		},
	},
	{
		ID:       "purpose-24",
		Author:   ptr("Viktor Frankl"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "What man actually needs is not a tensionless state but rather the striving and struggling for a worthwhile goal, a freely chosen task.",
			"en-GB": "What man actually needs is not a tensionless state but rather the striving and struggling for a worthwhile goal, a freely chosen task.",
			"pt-PT": "O que o homem realmente precisa não é de um estado sem tensões, mas sim do esforço e da luta por um objetivo que valha a pena, uma tarefa escolhida livremente.",
			"pt-BR": "O que o homem realmente precisa não é de um estado sem tensão, mas sim de esforçar-se e lutar por um objetivo que valha a pena, uma tarefa escolhida livremente.",
			"es":    "Lo que el hombre realmente necesita no es un estado sin tensiones, sino más bien el esfuerzo y la lucha por una meta que valga la pena, una tarea elegida libremente.",
			"fr":    "Ce dont l'homme a réellement besoin, ce n'est pas d'un état sans tension, mais plutôt de l'effort et de la lutte pour un but valable, une tâche librement choisie.",
			"de":    "Was der Mensch wirklich braucht, ist kein spannungsloser Zustand, sondern das Streben und Ringen um ein lohnendes Ziel, eine frei gewählte Aufgabe.",
			"it":    "Ciò di cui l'uomo ha davvero bisogno non è uno stato senza tensioni, ma lo sforzo e la lotta per una meta che valga la pena, un compito liberamente scelto.",
			"ja":    "人間が本当に必要としているのは、緊張のない状態ではなく、価値ある目標、自ら選んだ課題のために努力し奮闘することである。",
			"zh":    "人真正需要的不是没有张力的状态，而是为一个值得的目标、一项自由选择的任务而奋斗和努力。",
			"ko":    "인간에게 정말 필요한 것은 긴장 없는 상태가 아니라, 가치 있는 목표, 스스로 선택한 과업을 향해 애쓰고 분투하는 것이다.",
			"hi":    "मनुष्य को वास्तव में तनावमुक्त अवस्था की नहीं, बल्कि किसी सार्थक लक्ष्य, किसी स्वेच्छा से चुने कार्य के लिए प्रयास और संघर्ष की आवश्यकता है।",
			"pl":    "Tym, czego człowiek naprawdę potrzebuje, nie jest stan wolny od napięcia, lecz dążenie i zmaganie się o wartościowy cel, dobrowolnie wybrane zadanie.",
			"tr":    "İnsanın gerçekten ihtiyaç duyduğu şey gerilimsiz bir durum değil, değerli bir hedef, özgürce seçilmiş bir görev uğruna çabalamak ve mücadele etmektir.",
			"uk":    "Людині насправді потрібен не стан без напруги, а прагнення і боротьба за гідну мету, вільно обране завдання.",
			"sv":    "Vad människan verkligen behöver är inte ett spänningslöst tillstånd utan strävan och kampen för ett meningsfullt mål, en fritt vald uppgift.",
			"nl":    "Wat de mens werkelijk nodig heeft, is geen spanningsloze toestand, maar het streven en worstelen naar een waardevol doel, een vrij gekozen taak.",
			"nb":    "Det mennesket egentlig trenger, er ikke en spenningsløs tilstand, men strevet og kampen for et verdifullt mål, en fritt valgt oppgave.",
			"da":    "Hvad mennesket egentlig har brug for, er ikke en spændingsløs tilstand, men stræben og kamp for et værdifuldt mål, en frit valgt opgave.",
			"fi":    "Ihminen ei todella tarvitse jännitteetöntä tilaa, vaan ponnistelua ja kamppailua arvokkaan päämäärän, vapaasti valitun tehtävän puolesta.",
		},
	},
	{
		ID:       "purpose-25",
		Author:   ptr("Mahatma Gandhi"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The best way to find yourself is to lose yourself in the service of others.",
			"en-GB": "The best way to find yourself is to lose yourself in the service of others.",
			"pt-PT": "A melhor maneira de te encontrares é perderes-te ao serviço dos outros.",
			"pt-BR": "A melhor maneira de encontrar a si mesmo é se perder no serviço aos outros.",
			"es":    "La mejor manera de encontrarte a ti mismo es perderte en el servicio a los demás.",
			"fr":    "Le meilleur moyen de se trouver est de se perdre au service des autres.",
			"de":    "Der beste Weg, sich selbst zu finden, ist, sich im Dienst an anderen zu verlieren.",
			"it":    "Il modo migliore per trovare te stesso è perderti nel servizio agli altri.",
			"ja":    "自分自身を見つける最善の方法は、他者への奉仕に没頭することである。",
			"zh":    "找到自我的最好方式，是在服务他人中忘却自我。",
			"ko":    "자신을 찾는 가장 좋은 방법은 타인을 섬기는 일에 자신을 잊는 것이다.",
			"hi":    "स्वयं को पाने का सबसे अच्छा तरीक़ा है दूसरों की सेवा में स्वयं को खो देना।",
			"pl":    "Najlepszym sposobem na odnalezienie siebie jest zatracenie się w służbie innym.",
			"tr":    "Kendini bulmanın en iyi yolu, kendini başkalarına hizmette kaybetmektir.",
			"uk":    "Найкращий спосіб знайти себе — загубити себе у служінні іншим.",
			"sv":    "Det bästa sättet att hitta sig själv är att förlora sig själv i tjänandet av andra.",
			"nl":    "De beste manier om jezelf te vinden, is jezelf te verliezen in dienst aan anderen.",
			"nb":    "Den beste måten å finne seg selv på er å miste seg selv i tjeneste for andre.",
			"da":    "Den bedste måde at finde sig selv på er at miste sig selv i tjeneste for andre.",
			"fi":    "Paras tapa löytää itsensä on kadottaa itsensä toisten palvelemiseen.",
		},
	},
	{
		ID:       "purpose-26",
		Author:   ptr("Confucius"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Wherever you go, go with all your heart.",
			"en-GB": "Wherever you go, go with all your heart.",
			"pt-PT": "Onde quer que vás, vai com todo o teu coração.",
			"pt-BR": "Aonde quer que você vá, vá com todo o seu coração.",
			"es":    "Vayas donde vayas, ve con todo tu corazón.",
			"fr":    "Où que vous alliez, allez-y avec tout votre cœur.",
			"de":    "Wohin du auch gehst, geh mit deinem ganzen Herzen.",
			"it":    "Ovunque tu vada, vacci con tutto il tuo cuore.",
			"ja":    "どこへ行くにも、心を尽くして行きなさい。",
			"zh":    "无论去哪里，都要全心全意地去。",
			"ko":    "어디를 가든 온 마음을 다해 가라.",
			"hi":    "जहाँ भी जाओ, पूरे दिल से जाओ।",
			"pl":    "Dokądkolwiek idziesz, idź całym sercem.",
			"tr":    "Nereye gidersen git, bütün kalbinle git.",
			"uk":    "Куди б ти не йшов, іди туди всім серцем.",
			"sv":    "Vart du än går, gå med hela ditt hjärta.",
			"nl":    "Waar je ook heen gaat, ga met heel je hart.",
			"nb":    "Hvor du enn går, gå med hele ditt hjerte.",
			"da":    "Hvor du end går hen, så gå med hele dit hjerte.",
			"fi":    "Minne ikinä menetkin, mene koko sydämelläsi.",
		},
	},
	{
		ID:       "purpose-27",
		Author:   ptr("Marianne Williamson"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.",
			"en-GB": "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.",
			"pt-PT": "O nosso medo mais profundo não é o de sermos inadequados. O nosso medo mais profundo é o de sermos poderosos além de toda a medida.",
			"pt-BR": "Nosso medo mais profundo não é sermos inadequados. Nosso medo mais profundo é que somos poderosos além da medida.",
			"es":    "Nuestro miedo más profundo no es que seamos inadecuados. Nuestro miedo más profundo es que somos poderosos más allá de toda medida.",
			"fr":    "Notre peur la plus profonde n'est pas d'être inapte. Notre peur la plus profonde est d'être puissant au-delà de toute mesure.",
			"de":    "Unsere tiefste Angst ist nicht, dass wir unzulänglich sind. Unsere tiefste Angst ist, dass wir über alle Maßen mächtig sind.",
			"it":    "La nostra paura più profonda non è di essere inadeguati. La nostra paura più profonda è di essere potenti oltre ogni misura.",
			"ja":    "私たちの最も深い恐れは、自分が不十分であることではない。最も深い恐れは、自分が計り知れないほど強い力を持っていることである。",
			"zh":    "我们最深的恐惧不是自己不够好，而是自己拥有超乎想象的力量。",
			"ko":    "우리의 가장 깊은 두려움은 우리가 부족하다는 것이 아니다. 우리의 가장 깊은 두려움은 우리가 측량할 수 없을 만큼 강하다는 것이다.",
			"hi":    "हमारा सबसे गहरा डर यह नहीं कि हम अपर्याप्त हैं। हमारा सबसे गहरा डर यह है कि हम असीम रूप से शक्तिशाली हैं।",
			"pl":    "Naszym najgłębszym lękiem nie jest to, że jesteśmy niewystarczający. Naszym najgłębszym lękiem jest to, że jesteśmy potężni ponad miarę.",
			"tr":    "En derin korkumuz yetersiz olmamız değildir. En derin korkumuz, ölçülemeyecek kadar güçlü olmamızdır.",
			"uk":    "Наш найглибший страх — не те, що ми недостатньо хороші. Наш найглибший страх — що ми могутні понад міру.",
			"sv":    "Vår djupaste rädsla är inte att vi är otillräckliga. Vår djupaste rädsla är att vi är kraftfulla bortom alla mått.",
			"nl":    "Onze diepste angst is niet dat we tekortschieten. Onze diepste angst is dat we mateloos krachtig zijn.",
			"nb":    "Vår dypeste frykt er ikke at vi er utilstrekkelige. Vår dypeste frykt er at vi er mektige uten mål.",
			"da":    "Vores dybeste frygt er ikke, at vi er utilstrækkelige. Vores dybeste frygt er, at vi er mægtige ud over alle grænser.",
			"fi":    "Syvin pelkomme ei ole se, että olemme riittämättömiä. Syvin pelkomme on, että olemme mittaamattoman voimakkaita.",
		},
	},
	{
		ID:       "purpose-28",
		Author:   ptr("Unknown"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Your purpose in life is to find your purpose and give your whole heart and soul to it.",
			"en-GB": "Your purpose in life is to find your purpose and give your whole heart and soul to it.",
			"pt-PT": "O teu propósito na vida é encontrares o teu propósito e dares-lhe todo o teu coração e alma.",
			"pt-BR": "Seu propósito na vida é encontrar seu propósito e dedicar todo o seu coração e alma a ele.",
			"es":    "Tu propósito en la vida es encontrar tu propósito y dedicarle todo tu corazón y alma.",
			"fr":    "Votre but dans la vie est de trouver votre but et d'y consacrer tout votre cœur et toute votre âme.",
			"de":    "Dein Lebenszweck ist es, deinen Zweck zu finden und ihm dein ganzes Herz und deine ganze Seele zu widmen.",
			"it":    "Il tuo scopo nella vita è trovare il tuo scopo e dedicargli tutto il cuore e l'anima.",
			"ja":    "人生の目的とは、自分の目的を見つけ、それに心と魂のすべてを捧げることである。",
			"zh":    "你人生的目的，是找到你的使命，并全心全意地投入其中。",
			"ko":    "인생의 목적은 자신의 목적을 찾아 온 마음과 영혼을 다해 그것에 헌신하는 것이다.",
			"hi":    "जीवन में आपका उद्देश्य है अपना उद्देश्य खोजना और उसमें अपना पूरा दिल और आत्मा लगा देना।",
			"pl":    "Twoim celem w życiu jest odnaleźć swój cel i oddać mu całe serce i duszę.",
			"tr":    "Hayattaki amacın, amacını bulmak ve ona bütün kalbini ve ruhunu vermektir.",
			"uk":    "Мета твого життя — знайти своє покликання і віддати йому все серце й душу.",
			"sv":    "Ditt syfte i livet är att hitta ditt syfte och ge det hela ditt hjärta och din själ.",
			"nl":    "Je doel in het leven is je doel te vinden en er je hele hart en ziel aan te geven.",
			"nb":    "Ditt formål i livet er å finne ditt formål og gi det hele ditt hjerte og din sjel.",
			"da":    "Dit formål i livet er at finde dit formål og give det hele dit hjerte og din sjæl.",
			"fi":    "Elämäsi tarkoitus on löytää tarkoituksesi ja antaa sille koko sydämesi ja sielusi.",
		},
	},
	{
		ID:       "purpose-29",
		Author:   ptr("Winston Churchill"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "We make a living by what we get, but we make a life by what we give.",
			"en-GB": "We make a living by what we get, but we make a life by what we give.",
			"pt-PT": "Ganhamos a vida com o que recebemos, mas construímos uma vida com o que damos.",
			"pt-BR": "Ganhamos a vida com o que recebemos, mas fazemos uma vida com o que damos.",
			"es":    "Nos ganamos la vida con lo que recibimos, pero hacemos una vida con lo que damos.",
			"fr":    "On gagne sa vie avec ce que l'on reçoit, mais on construit sa vie avec ce que l'on donne.",
			"de":    "Von dem, was wir bekommen, können wir leben. Was wir geben, macht das Leben aus.",
			"it":    "Ci guadagniamo da vivere con ciò che riceviamo, ma diamo senso alla vita con ciò che doniamo.",
			"ja":    "私たちは得るもので生計を立て、与えるもので人生を築く。",
			"zh":    "我们靠获得的东西谋生，靠给予的东西创造人生。",
			"ko":    "우리는 얻는 것으로 생계를 꾸리고, 주는 것으로 인생을 만든다.",
			"hi":    "जो हमें मिलता है उससे हम जीविका चलाते हैं, लेकिन जो हम देते हैं उससे हम जीवन बनाते हैं।",
			"pl":    "Z tego, co dostajemy, żyjemy. To, co dajemy, tworzy nasze życie.",
			"tr":    "Aldıklarımızla geçimimizi sağlarız, verdiklerimizle ise bir hayat kurarız.",
			"uk":    "Тим, що отримуємо, ми заробляємо на життя, а тим, що віддаємо, творимо життя.",
			"sv":    "Vi försörjer oss på det vi får, men vi skapar ett liv genom det vi ger.",
			"nl":    "We verdienen de kost met wat we krijgen, maar we maken een leven met wat we geven.",
			"nb":    "Vi lever av det vi får, men vi skaper et liv av det vi gir.",
			"da":    "Vi tjener til livet ved det, vi får, men vi skaber et liv ved det, vi giver.",
			"fi":    "Elantomme saamme siitä, mitä saamme, mutta elämän rakennamme siitä, mitä annamme.",
		},
	},
	{
		ID:       "purpose-30",
		Author:   ptr("Unknown"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Don't just exist, live.",
			"en-GB": "Don't just exist, live.",
			"pt-PT": "Não te limites a existir, vive.",
			"pt-BR": "Não apenas exista, viva.",
			"es":    "No solo existas, vive.",
			"fr":    "Ne vous contentez pas d'exister, vivez.",
			"de":    "Existiere nicht nur, lebe.",
			"it":    "Non limitarti a esistere, vivi.",
			"ja":    "ただ存在するな、生きよ。",
			"zh":    "不要只是存在，要活出生命。",
			"ko":    "그저 존재하지 말고, 살아라.",
			"hi":    "सिर्फ़ मौजूद मत रहो, जियो।",
			"pl":    "Nie tylko istniej — żyj.",
			"tr":    "Sadece var olma, yaşa.",
			"uk":    "Не просто існуй — живи.",
			"sv":    "Existera inte bara, lev.",
			"nl":    "Besta niet alleen, leef.",
			"nb":    "Ikke bare eksister, lev.",
			"da":    "Nøjes ikke med at eksistere, lev.",
			"fi":    "Älä vain ole olemassa, elä.",
		},
	},
	{
		ID:       "purpose-31",
		Author:   ptr("Mark Twain"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The two most important days in your life are the day you are born and the day you find out why.",
			"en-GB": "The two most important days in your life are the day you are born and the day you find out why.",
			"pt-PT": "Os dois dias mais importantes da tua vida são o dia em que nasceste e o dia em que descobres porquê.",
			"pt-BR": "Os dois dias mais importantes da sua vida são o dia em que você nasceu e o dia em que descobriu por quê.",
			"es":    "Los dos días más importantes de tu vida son el día en que naces y el día en que descubres por qué.",
			"fr":    "Les deux jours les plus importants de votre vie sont le jour de votre naissance et celui où vous découvrez pourquoi.",
			"de":    "Die zwei wichtigsten Tage deines Lebens sind der Tag, an dem du geboren wirst, und der Tag, an dem du herausfindest, warum.",
			"it":    "I due giorni più importanti della tua vita sono il giorno in cui nasci e il giorno in cui scopri perché.",
			"ja":    "人生で最も大切な二つの日は、生まれた日と、なぜ生まれたのかを知る日である。",
			"zh":    "人生中最重要的两天，是你出生的那天和你明白自己为何而生的那天。",
			"ko":    "인생에서 가장 중요한 두 날은 태어난 날과 그 이유를 깨닫는 날이다.",
			"hi":    "आपके जीवन के दो सबसे महत्वपूर्ण दिन हैं: जिस दिन आप जन्म लेते हैं और जिस दिन आप जान जाते हैं कि क्यों।",
			"pl":    "Dwa najważniejsze dni w twoim życiu to dzień, w którym się rodzisz, i dzień, w którym odkrywasz po co.",
			"tr":    "Hayatındaki en önemli iki gün, doğduğun gün ve nedenini keşfettiğin gündür.",
			"uk":    "Два найважливіші дні у твоєму житті — день, коли ти народився, і день, коли зрозумів навіщо.",
			"sv":    "De två viktigaste dagarna i ditt liv är dagen du föds och dagen du förstår varför.",
			"nl":    "De twee belangrijkste dagen in je leven zijn de dag dat je geboren wordt en de dag dat je ontdekt waarom.",
			"nb":    "De to viktigste dagene i livet ditt er dagen du blir født og dagen du finner ut hvorfor.",
			"da":    "De to vigtigste dage i dit liv er den dag, du bliver født, og den dag, du finder ud af hvorfor.",
			"fi":    "Elämäsi kaksi tärkeintä päivää ovat päivä, jolloin synnyt, ja päivä, jolloin ymmärrät miksi.",
		},
	},
	{
		ID:       "purpose-32",
		Author:   ptr("Pablo Picasso"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The meaning of life is to find your gift. The purpose of life is to give it away.",
			"en-GB": "The meaning of life is to find your gift. The purpose of life is to give it away.",
			"pt-PT": "O sentido da vida é encontrar o teu dom. O propósito da vida é partilhá-lo.",
			"pt-BR": "O sentido da vida é encontrar o seu dom. O propósito da vida é compartilhá-lo.",
			"es":    "El sentido de la vida es encontrar tu don. El propósito de la vida es regalarlo.",
			"fr":    "Le sens de la vie est de trouver son don. Le but de la vie est de le donner.",
			"de":    "Der Sinn des Lebens ist, deine Gabe zu finden. Der Zweck des Lebens ist, sie zu verschenken.",
			"it":    "Il significato della vita è trovare il proprio dono. Lo scopo della vita è donarlo.",
			"ja":    "人生の意味とは、自分の才能を見つけること。人生の目的とは、それを分かち与えることである。",
			"zh":    "生命的意义在于找到你的天赋，生命的目的在于把它奉献出去。",
			"ko":    "삶의 의미는 자신의 재능을 찾는 것이고, 삶의 목적은 그것을 나누는 것이다.",
			"hi":    "जीवन का अर्थ है अपनी प्रतिभा को खोजना। जीवन का उद्देश्य है उसे बाँट देना।",
			"pl":    "Sensem życia jest odnaleźć swój dar. Celem życia jest go ofiarować.",
			"tr":    "Hayatın anlamı, yeteneğini bulmaktır. Hayatın amacı ise onu armağan etmektir.",
			"uk":    "Сенс життя — знайти свій дар. Мета життя — віддати його іншим.",
			"sv":    "Livets mening är att hitta din gåva. Livets syfte är att ge bort den.",
			"nl":    "De zin van het leven is je gave te vinden. Het doel van het leven is haar weg te geven.",
			"nb":    "Meningen med livet er å finne gaven din. Hensikten med livet er å gi den bort.",
			"da":    "Meningen med livet er at finde din gave. Formålet med livet er at give den videre.",
			"fi":    "Elämän merkitys on löytää lahjasi. Elämän tarkoitus on antaa se pois.",
		},
	},
	{
		ID:       "purpose-33",
		Author:   ptr("John F. Kennedy"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Efforts and courage are not enough without purpose and direction.",
			"en-GB": "Efforts and courage are not enough without purpose and direction.",
			"pt-PT": "Esforço e coragem não são suficientes sem propósito e direção.",
			"pt-BR": "Esforço e coragem não são suficientes sem propósito e direção.",
			"es":    "Los esfuerzos y el valor no son suficientes sin un propósito y una dirección.",
			"fr":    "Les efforts et le courage ne suffisent pas sans but et sans direction.",
			"de":    "Anstrengung und Mut genügen nicht ohne Ziel und Richtung.",
			"it":    "Gli sforzi e il coraggio non bastano senza uno scopo e una direzione.",
			"ja":    "目的と方向がなければ、努力も勇気も十分ではない。",
			"zh":    "没有目标和方向，努力和勇气是不够的。",
			"ko":    "목적과 방향이 없다면 노력과 용기만으로는 충분하지 않다.",
			"hi":    "उद्देश्य और दिशा के बिना प्रयास और साहस पर्याप्त नहीं हैं।",
			"pl":    "Wysiłek i odwaga nie wystarczą bez celu i kierunku.",
			"tr":    "Amaç ve yön olmadan çaba ve cesaret yeterli değildir.",
			"uk":    "Зусилля й сміливість — ніщо без мети та напряму.",
			"sv":    "Ansträngning och mod räcker inte utan syfte och riktning.",
			"nl":    "Inspanning en moed zijn niet genoeg zonder doel en richting.",
			"nb":    "Innsats og mot er ikke nok uten formål og retning.",
			"da":    "Indsats og mod er ikke nok uden formål og retning.",
			"fi":    "Ponnistelu ja rohkeus eivät riitä ilman päämäärää ja suuntaa.",
		},
	},
	{
		ID:       "purpose-34",
		Author:   ptr("Friedrich Nietzsche"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "He who has a why to live can bear almost any how.",
			"en-GB": "He who has a why to live can bear almost any how.",
			"pt-PT": "Aquele que tem um porquê para viver pode suportar quase qualquer como.",
			"pt-BR": "Aquele que tem um porquê para viver pode suportar quase qualquer como.",
			"es":    "Quien tiene un porqué para vivir, puede soportar casi cualquier cómo.",
			"fr":    "Celui qui a un pourquoi pour vivre peut supporter presque n'importe quel comment.",
			"de":    "Wer ein Warum zum Leben hat, erträgt fast jedes Wie.",
			"it":    "Chi ha un perché per vivere può sopportare quasi ogni come.",
			"ja":    "生きる「なぜ」を持つ者は、ほとんどどんな「どのように」にも耐えられる。",
			"zh":    "知道为什么而活的人，几乎可以承受任何一种生活。",
			"ko":    "살아야 할 이유를 가진 사람은 그 어떤 상황도 견뎌 낼 수 있다.",
			"hi":    "जिसके पास जीने का 'क्यों' है, वह लगभग हर 'कैसे' को सह सकता है।",
			"pl":    "Ten, kto ma po co żyć, zniesie prawie każde jak.",
			"tr":    "Yaşamak için bir 'neden'i olan, hemen her 'nasıl'a katlanabilir.",
			"uk":    "Той, хто має «навіщо» жити, витримає майже будь-яке «як».",
			"sv":    "Den som har ett varför att leva för kan uthärda nästan vilket hur som helst.",
			"nl":    "Wie een waarom heeft om voor te leven, kan bijna elk hoe verdragen.",
			"nb":    "Den som har et hvorfor å leve for, kan tåle nesten ethvert hvordan.",
			"da":    "Den, der har et hvorfor at leve for, kan bære næsten ethvert hvordan.",
			"fi":    "Se, jolla on elämälleen miksi, kestää melkein minkä tahansa miten.",
		},
	},
	{
		ID:       "purpose-35",
		Author:   ptr("Abraham Maslow"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "What humans can be, they must be.",
			"en-GB": "What humans can be, they must be.",
			"pt-PT": "O que os seres humanos podem ser, devem ser.",
			"pt-BR": "O que os seres humanos podem ser, devem ser.",
			"es":    "Lo que los humanos pueden ser, deben serlo.",
			"fr":    "Ce que les humains peuvent être, ils doivent l'être.",
			"de":    "Was der Mensch sein kann, das muss er sein.",
			"it":    "Ciò che gli esseri umani possono essere, devono esserlo.",
			"ja":    "人はなり得るものに、ならなければならない。",
			"zh":    "人能成为什么，就必须成为什么。",
			"ko":    "인간은 될 수 있는 존재가 되어야만 한다.",
			"hi":    "मनुष्य जो बन सकता है, उसे वह बनना ही चाहिए।",
			"pl":    "Czym człowiek może być, tym być musi.",
			"tr":    "İnsan ne olabiliyorsa, o olmalıdır.",
			"uk":    "Ким людина може бути, тим вона мусить бути.",
			"sv":    "Vad människan kan vara, det måste hon vara.",
			"nl":    "Wat mensen kunnen zijn, moeten ze zijn.",
			"nb":    "Det mennesket kan være, må det være.",
			"da":    "Hvad mennesket kan være, må det være.",
			"fi":    "Se, mitä ihminen voi olla, hänen täytyy olla.",
		},
	},
	{
		ID:       "purpose-36",
		Author:   ptr("Michel de Montaigne"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The soul which has no fixed purpose in life is lost; to be everywhere, is to be nowhere.",
			"en-GB": "The soul which has no fixed purpose in life is lost; to be everywhere, is to be nowhere.",
			"pt-PT": "A alma que não tem um propósito fixo na vida está perdida; estar em todo o lado é estar em lado nenhum.",
			"pt-BR": "A alma que não tem um propósito fixo na vida está perdida; estar em todo lugar é estar em lugar nenhum.",
			"es":    "El alma que no tiene un propósito fijo en la vida está perdida; estar en todas partes es no estar en ninguna.",
			"fr":    "L'âme qui n'a pas de but fixe dans la vie est perdue ; être partout, c'est n'être nulle part.",
			"de":    "Die Seele, die kein festes Ziel im Leben hat, ist verloren. Überall zu sein heißt, nirgends zu sein.",
			"it":    "L'anima che non ha uno scopo fisso nella vita è perduta; essere ovunque è essere in nessun luogo.",
			"ja":    "人生に定まった目的を持たない魂は迷子である。あらゆる場所にいることは、どこにもいないことだ。",
			"zh":    "生命中没有固定目标的灵魂是迷失的；无处不在，就是无处存在。",
			"ko":    "삶에 확고한 목적이 없는 영혼은 길을 잃는다. 어디에나 있다는 것은 어디에도 없다는 것이다.",
			"hi":    "जिस आत्मा का जीवन में कोई निश्चित उद्देश्य नहीं, वह भटकी हुई है; हर जगह होना, कहीं भी न होना है।",
			"pl":    "Dusza, która nie ma stałego celu w życiu, jest zgubiona; być wszędzie to być nigdzie.",
			"tr":    "Hayatta sabit bir amacı olmayan ruh kayıptır; her yerde olmak, hiçbir yerde olmamaktır.",
			"uk":    "Душа, що не має твердої мети в житті, — загублена; бути всюди означає не бути ніде.",
			"sv":    "Den själ som inte har något fast mål i livet är förlorad; att vara överallt är att vara ingenstans.",
			"nl":    "De ziel die geen vast doel in het leven heeft, is verloren; overal zijn is nergens zijn.",
			"nb":    "Den sjel som ikke har noe fast mål i livet, er fortapt; å være overalt er å være ingensteds.",
			"da":    "Den sjæl, der ikke har noget fast mål i livet, er fortabt; at være alle vegne er at være ingen steder.",
			"fi":    "Sielu, jolla ei ole elämässä kiinteää päämäärää, on eksyksissä; olla kaikkialla on olla ei-missään.",
		},
	},
	{
		ID:       "purpose-37",
		Author:   ptr("T.D. Jakes"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "If you can't figure out your purpose, figure out your passion. For your passion will lead you right into your purpose.",
			"en-GB": "If you can't figure out your purpose, figure out your passion. For your passion will lead you right into your purpose.",
			"pt-PT": "Se não consegues descobrir o teu propósito, descobre a tua paixão. Porque a tua paixão levar-te-á diretamente ao teu propósito.",
			"pt-BR": "Se você não consegue descobrir o seu propósito, descubra a sua paixão. Pois a sua paixão o levará direto ao seu propósito.",
			"es":    "Si no puedes descubrir tu propósito, descubre tu pasión. Porque tu pasión te llevará directamente a tu propósito.",
			"fr":    "Si vous ne trouvez pas votre but, cherchez votre passion. Car votre passion vous mènera droit à votre but.",
			"de":    "Wenn du deinen Zweck nicht findest, finde deine Leidenschaft. Denn deine Leidenschaft führt dich geradewegs zu deinem Zweck.",
			"it":    "Se non riesci a capire il tuo scopo, scopri la tua passione. Perché la tua passione ti condurrà dritto al tuo scopo.",
			"ja":    "目的が見つからないなら、情熱を見つけよ。情熱は、あなたをまっすぐ目的へと導いてくれる。",
			"zh":    "如果找不到你的使命，就先找到你的热爱。因为热爱会把你直接引向使命。",
			"ko":    "목적을 찾지 못하겠다면 열정을 찾아라. 열정이 당신을 곧장 목적으로 이끌 것이다.",
			"hi":    "अगर अपना उद्देश्य नहीं समझ पा रहे, तो अपना जुनून खोजो। क्योंकि तुम्हारा जुनून तुम्हें सीधे तुम्हारे उद्देश्य तक ले जाएगा।",
			"pl":    "Jeśli nie potrafisz odkryć swojego celu, odkryj swoją pasję. Bo pasja zaprowadzi cię prosto do celu.",
			"tr":    "Amacını bulamıyorsan tutkunu bul. Çünkü tutkun seni doğruca amacına götürecektir.",
			"uk":    "Якщо не можеш зрозуміти своє призначення, знайди свою пристрасть. Бо пристрасть приведе тебе просто до призначення.",
			"sv":    "Om du inte kan lista ut ditt syfte, ta reda på din passion. För din passion leder dig rakt till ditt syfte.",
			"nl":    "Als je je doel niet kunt vinden, vind dan je passie. Want je passie leidt je recht naar je doel.",
			"nb":    "Klarer du ikke å finne formålet ditt, finn lidenskapen din. For lidenskapen din vil lede deg rett til formålet ditt.",
			"da":    "Kan du ikke finde dit formål, så find din passion. For din passion vil føre dig lige til dit formål.",
			"fi":    "Jos et löydä tarkoitustasi, löydä intohimosi. Sillä intohimosi johdattaa sinut suoraan tarkoitukseesi.",
		},
	},
	{
		ID:       "purpose-38",
		Author:   ptr("Thomas Carlyle"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "The person without a purpose is like a ship without a rudder.",
			"en-GB": "The person without a purpose is like a ship without a rudder.",
			"pt-PT": "A pessoa sem um propósito é como um navio sem leme.",
			"pt-BR": "A pessoa sem um propósito é como um navio sem leme.",
			"es":    "La persona sin propósito es como un barco sin timón.",
			"fr":    "La personne sans but est comme un navire sans gouvernail.",
			"de":    "Ein Mensch ohne Ziel ist wie ein Schiff ohne Ruder.",
			"it":    "Una persona senza uno scopo è come una nave senza timone.",
			"ja":    "目的のない人は、舵のない船のようなものだ。",
			"zh":    "没有目标的人，就像没有舵的船。",
			"ko":    "목적 없는 사람은 키 없는 배와 같다.",
			"hi":    "उद्देश्यहीन व्यक्ति बिना पतवार के जहाज़ जैसा है।",
			"pl":    "Człowiek bez celu jest jak statek bez steru.",
			"tr":    "Amaçsız insan, dümensiz gemi gibidir.",
			"uk":    "Людина без мети — як корабель без керма.",
			"sv":    "En människa utan mål är som ett skepp utan roder.",
			"nl":    "Een mens zonder doel is als een schip zonder roer.",
			"nb":    "Et menneske uten mål er som et skip uten ror.",
			"da":    "Et menneske uden formål er som et skib uden ror.",
			"fi":    "Ihminen ilman päämäärää on kuin laiva ilman peräsintä.",
		},
	},
	{
		ID:       "purpose-39",
		Author:   ptr("John D. Rockefeller"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "Singularity of purpose is one of the chief essentials for success in life, no matter what may be one's aim.",
			"en-GB": "Singularity of purpose is one of the chief essentials for success in life, no matter what may be one's aim.",
			"pt-PT": "A singularidade de propósito é um dos principais essenciais para o sucesso na vida, não importa qual seja o objetivo de cada um.",
			"pt-BR": "A singularidade de propósito é um dos principais essenciais para o sucesso na vida, não importa qual seja o objetivo de cada um.",
			"es":    "La singularidad de propósito es uno de los principales elementos esenciales para el éxito en la vida, sea cual sea el objetivo de cada uno.",
			"fr":    "La singularité d'objectif est l'un des principaux éléments essentiels du succès dans la vie, quel que soit l'objectif visé.",
			"de":    "Zielstrebigkeit ist eine der wichtigsten Voraussetzungen für Erfolg im Leben, ganz gleich, was das Ziel sein mag.",
			"it":    "L'unicità di intenti è uno dei requisiti essenziali per il successo nella vita, qualunque sia il proprio obiettivo.",
			"ja":    "目的をひとつに定めることは、何を目指すにせよ、人生の成功に欠かせない要素のひとつである。",
			"zh":    "目标专一是人生成功的首要条件之一，无论目标是什么。",
			"ko":    "목적의 단일함은 목표가 무엇이든 인생의 성공에 가장 중요한 요소 중 하나다.",
			"hi":    "लक्ष्य की एकाग्रता जीवन में सफलता की प्रमुख अनिवार्यताओं में से एक है, चाहे उद्देश्य कुछ भी हो।",
			"pl":    "Jedność celu jest jednym z głównych warunków sukcesu w życiu, niezależnie od tego, do czego się dąży.",
			"tr":    "Amaç birliği, hedef ne olursa olsun, hayatta başarının başlıca koşullarından biridir.",
			"uk":    "Цілеспрямованість — одна з головних умов успіху в житті, хоч би якою була мета.",
			"sv":    "Målmedvetenhet är en av de viktigaste förutsättningarna för framgång i livet, oavsett vad ens mål må vara.",
			"nl":    "Eenheid van doel is een van de belangrijkste voorwaarden voor succes in het leven, wat je doel ook mag zijn.",
			"nb":    "Målrettethet er en av de viktigste forutsetningene for suksess i livet, uansett hva målet måtte være.",
			"da":    "Målrettethed er en af de vigtigste forudsætninger for succes i livet, uanset hvad ens mål måtte være.",
			"fi":    "Päämäärän yhtenäisyys on yksi elämän menestyksen tärkeimmistä edellytyksistä, olipa tavoite mikä tahansa.",
		},
	},
	{
		ID:       "purpose-40",
		Author:   ptr("Og Mandino"),
		Category: "purpose",
		Translations: map[string]string{
			"en-US": "I am here for a purpose and that purpose is to grow into a mountain, not to shrink to a grain of sand.",
			"en-GB": "I am here for a purpose and that purpose is to grow into a mountain, not to shrink to a grain of sand.",
			"pt-PT": "Estou aqui por um propósito e esse propósito é crescer até ser uma montanha, não encolher até ser um grão de areia.",
			"pt-BR": "Estou aqui por um propósito e esse propósito é crescer até ser uma montanha, não encolher até ser um grão de areia.",
			"es":    "Estoy aquí por un propósito y ese propósito es crecer hasta convertirme en una montaña, no encogerme hasta ser un grano de arena.",
			"fr":    "Je suis ici dans un but précis et ce but est de devenir une montagne, pas de rétrécir jusqu'à devenir un grain de sable.",
			"de":    "Ich bin aus einem Grund hier, und dieser Grund ist, zu einem Berg zu wachsen, nicht zu einem Sandkorn zu schrumpfen.",
			"it":    "Sono qui per uno scopo, e quello scopo è crescere fino a diventare una montagna, non rimpicciolirmi fino a un granello di sabbia.",
			"ja":    "私には存在する目的がある。それは山へと成長することであり、砂粒へと縮むことではない。",
			"zh":    "我来到这里是有使命的，那就是长成一座高山，而不是缩成一粒沙。",
			"ko":    "나는 목적이 있어 여기에 있다. 그 목적은 산으로 자라나는 것이지, 모래알로 움츠러드는 것이 아니다.",
			"hi":    "मैं यहाँ एक उद्देश्य के लिए हूँ, और वह उद्देश्य है पहाड़ बनना, रेत के कण में सिमट जाना नहीं।",
			"pl":    "Jestem tu w jakimś celu, a tym celem jest wyrosnąć na górę, a nie skurczyć się do ziarnka piasku.",
			"tr":    "Buradayım çünkü bir amacım var; o amaç bir dağa dönüşmek, bir kum tanesine küçülmek değil.",
			"uk":    "Я тут заради мети, і ця мета — вирости в гору, а не змаліти до піщинки.",
			"sv":    "Jag är här av en anledning, och den anledningen är att växa till ett berg, inte att krympa till ett sandkorn.",
			"nl":    "Ik ben hier met een doel, en dat doel is uitgroeien tot een berg, niet krimpen tot een zandkorrel.",
			"nb":    "Jeg er her av en grunn, og den grunnen er å vokse til et fjell, ikke å krympe til et sandkorn.",
			"da":    "Jeg er her med et formål, og det formål er at vokse til et bjerg, ikke at skrumpe til et sandkorn.",
			"fi":    "Olen täällä tarkoitusta varten, ja se tarkoitus on kasvaa vuoreksi, ei kutistua hiekanjyväksi.",
		},
	},
}
